### ISSUE TITLE
Can't apply threshold templates

### ISSUE THREAD

**Issue by florianbeer** [Cacti/plugin_thold#1]
I have set up a new Cacti installation from the "development" branch (Cacti/cacti@430472de6088ef13cc34cddbee1f7300fa8791c3) and cloned the latest version of this plugin (20207bb96eea97a96f17ffbd96ec28b20f0529b3) into my plugins directory.

After setting up a few threshold templates I wasn't able to apply them to my SNMP devices. On the confirmation screen ("Click 'Continute' to apply all appropriate Thresholds to these Device(s)."), clicking on Continue gives me an error 500 on the server side, with PHP reporting the following:

```
PHP Notice:  Undefined variable: config in /var/www/cacti/plugins/thold/setup.php on line 356
PHP Fatal error:  Call to undefined function autocreate() in /var/www/cacti/plugins/thold/setup.php on line 362
```

**Comment by cigamit** [comment]
this should be resolved now.  please note, you must first update the cacti repo, then re-install thold, or create the new table structure, and register new hooks manually.  if you don't know how to do either, simply uninstall, and then re-install the thold plugin.  there are two new options, first to specifiy which thold templates to use at the device template, and a new thold setting for autocreate, which will create tholds automatically when you save a device.  it will only autocreate tholds associated with the devices device template though.

**Comment by florianbeer** [comment]
Thank you very much, I will test this as soon as time permits.

**Comment by cigamit** [comment]
please provide feedback.

**Comment by florianbeer** [comment]
Sorry for the delay, I was busy with other projects.  
I have now disabled and uninstalled thold from Cacti's Plugin Management, then deleted the source directory and installed a new clone of the master branch into /var/www/cacti/plugins/thold

After installing and activating it again from Cacti's Console I get the following error when trying to associate thresholds with devices:

```
CMDPHP: ERROR: SQL Cell Failed!, Error:1054, SQL:"SELECT count(*) FROM thold_data LEFT JOIN user_auth_perms ON ((thold_data.graph_id=user_auth_perms.item_id AND user_auth_perms.type=1 AND user_auth_perms.user_id= 1) OR (thold_data.host_id=user_auth_perms.item_id AND user_auth_perms.type=3 AND user_auth_perms.user_id= 1) OR (thold_data.graph_template=user_auth_perms.item_id AND user_auth_perms.type=4 AND user_auth_perms.user_id= 1)) where ((user_auth_perms.type != 1 OR user_auth_perms.type is null) AND ((user_auth_perms.type != 3) OR (user_auth_perms.type is null)) AND ((user_auth_perms.type != 4) OR (user_auth_perms.type is null)))"
Cacti[11785]: CMDPHP: ERROR: SQL Cell Failed!, Error: Unknown column 'thold_data.graph_id' in 'on clause'
```

```
Cacti[9571]: CMDPHP: ERROR: SQL Assoc Failed!, Error:1064, SQL:"SELECT id, data_template_id   FROM data_local   WHERE host_id = ?   AND data_template_id IN ()"
Cacti[9571]: CMDPHP: ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
```

It seems I don't have all necessary database fields, is there a way to re-create thold's DB schema?

**Comment by cigamit** [comment]
You must have another plugin installed.  Can you provide the plugins that you have installed and their sources as this query is neither in the github version of Cacti or thold.

**Comment by florianbeer** [comment]
```
ls /var/www/cacti/plugins
index.php  intropage  settings  thold
```

Maybe these are leftovers from old thold versions? I migrated my old cacti installation.

**Comment by cigamit** [comment]
Well, I found that I forgot one commit.  That second message should be gone now.

**Comment by florianbeer** [comment]
Which still leaves the first one. I've updated Cacti to the latest commit and re-installed thold.
I am now getting device up status but still can't apply threshold templates.

Sorry for the hassle, is there anything more I could provide you with to get behind this problem?

**Comment by cigamit** [comment]
run the following command from the 'plugins' directory:

grep -r "user_auth_perms" *

let me know where it is showing up.  it is not in the thold directory.  maybe it's the maintenance plugin or some other plugin.

**Comment by florianbeer** [comment]
Ah, good thinking. Turns out it is in the intropage plugin. (`intropage/include/functions.php`)
I'll try and disable this plugin and see where it takes me.

Thanks!

**Comment by florianbeer** [comment]
No more errors :+1:
And I could successfully create a threshold (cpu_user) for one device manually.

So maybe my thought process about creating threshold templates or applying them is wrong?
Here's what I've done:
* Go to Threshold Templates and click "Add"
* Choose Data Template "ucd/net CPU Usage - User"
* Choose Data Source "cpu_user"
* Click "Create"
* Choose Warning and Alert "High Threshold"
* Choose Warning and Alert "Notification List"
* Click "Create"
* Go to "Devices"
* Select all
* Choose Action "Apply Thresholds"
* Click "Go"
* Click "Continue"

Result: No erros, but no new thresholds created.

**Comment by florianbeer** [comment]
I'm so sorry. I've got it now. I needed to associate the threshold template with the device template first and then re-apply it to all devices. Everything is working now. Thanks for your kind help!
