### ISSUE TITLE
Error Creating thold

### ISSUE THREAD

**Issue by majlsfiles** [Cacti/plugin_thold#100]
I have cacti 1.1.12 installed and thold 1.0.3.

I have been unable to create a thold on a graph. I checked the log and saw this error:

2017/07/15 21:00:58 - ERROR PHP NOTICE in  Plugin 'thold': Undefined index: local_graph_id in file: /usr/local/share/cacti/plugins/thold/thold_functions.php  on line: 3208
2017/07/15 21:00:58 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 64 save_thold)(/plugins/thold/thold_functions.php: 3208 CactiErrorHandler)(/lib/functions.php: 4392 cacti_debug_backtrace)
[Sat Jul 15 21:00:58.828978 2017] [php7:notice] [pid 74359:tid 34592790784] [client] PHP Notice:  Undefined index: local_graph_id in /usr/local/share/cacti/plugins/thold/thold_functions.php on line 3208, referer: http://localhost/plugins/thold/thold.php
2017/07/15 21:00:58 - ERROR PHP NOTICE in  Plugin 'thold': Undefined index: graph_template_id in file: /usr/local/share/cacti/plugins/thold/thold_functions.php  on line: 3209
2017/07/15 21:00:58 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 64 save_thold)(/plugins/thold/thold_functions.php: 3209 CactiErrorHandler)(/lib/functions.php: 4392 cacti_debug_backtrace)
[Sat Jul 15 21:00:58.829231 2017] [php7:notice] [pid 74359:tid 34592790784] [client] PHP Notice:  Undefined index: graph_template_id in /usr/local/share/cacti/plugins/thold/thold_functions.php on line 3209, referer: http://localhost/plugins/thold/thold.php

Can you please help me resolve this issue.

**Comment by cigamit** [comment]
This is an upgrade error.  We don't officially support upgrades in the new install, but several people have been able to upgrade their databases manually.
