### ISSUE TITLE
thold have not value.

### ISSUE THREAD

**Issue by itsjoke** [Cacti/plugin_thold#102]
Hello

I create a traffic thold but there have not value .
![image](https://user-images.githubusercontent.com/11266502/28510248-ddac4daa-7079-11e7-948f-bbf3d2e7fddb.png)
please help me ,My system info,Centos 7,php71 ,mysql 5.6
Thanks

**Comment by cigamit** [comment]
This is likely due to thold not being enabled.  Since this is more of a support issue, I will close this.
