### ISSUE TITLE
Error when creating several tholds from the same data source

### ISSUE THREAD

**Issue by TIKA0902** [Cacti/plugin_thold#103]
817/5000
Hello everyone,

the automatic creation of thresholds via assigned "Apply Thresholds" works with me only partially. The thresholds are created correctly as long as the data sources have only one measured value or only one measured value is used. I have created several thresholds using the same data-template (example advanced-ping: "avg" and "loss" or interface errors / discards: "discards_in" and "errors_out"). In these cases only one threshold is generated, presumably the last template created (the highest ID). Unfortunately, the Web form does not display the IDs. For other forms (graph, device ..) is the case. Has anyone observed this misconduct? In the current issues I find nothing.

Best regards!
Many Thanks!

**Comment by TIKA0902** [comment]
As a supplement: I use Ubuntu 16.04LTS / Cacti 1.1.15 / Thold 1.0.3

**Comment by cigamit** [comment]
Are you auto-creating based upon thold templates that have already been created?

**Comment by ikorzha** [comment]
Tika0992, I highly suggest you grab the latest thold from github, Cigamit has applied a patch created by forum member that resolved this problem,  I have confirmed the fix is fully functional.
If it resolves your issue close this case.

**Comment by TIKA0902** [comment]
I have updated to Cacti 1.1.21 / Thold 1.0.3. The error no longer occurs. Looks good. Thank you all!
