### ISSUE TITLE
SQL query with wrong field

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_thold#104]
I have some error on the latest thold plugins (1.0.3, running on cacti 1.1.16)
07/31/2017 09:47:34 AM - CMDPHP: Poller[0] ERROR: SQL Assoc Failed!, Error:'1054', SQL:"SELECT data_id, rra_id, lastread, cdef 
FROM thold_data WHERE thold_enabled='on' AND tcheck=1"

And i can't trace it to the origin of it, but I find some error on setup.php

On the setup.php, function thold_rrd_graph_graph_options ($g)
Line 264 to 267
The query use the field data_id on the table thold_data
Data_id was renamed data_template_rrd_id a while ago

Same line 273 and 275

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
