### ISSUE TITLE
Thold plugin "incorrect" center allignment of tholds in Console->Tholds

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#107]
In the latest thold 1.0.3 I have observed an incorrect center alignment of tholds "name" in Console->Tholds
![allignment](https://user-images.githubusercontent.com/11211789/29999120-5dfac554-900a-11e7-9406-511c07249f6d.gif)

Under Thold TAB alignment is correct:
![allignment-correct](https://user-images.githubusercontent.com/11211789/29999126-98252abc-900a-11e7-9932-dd15646aac65.gif)

**Comment by cigamit** [comment]
This will be fixed in Cacti 1.1.21.  If you want to grab things early from the development branch, it'll be lib/html_utility.php.
