### ISSUE TITLE
Lots of errors after code cleanup in thold_functions.php

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#108]
Please see below. Also can we also finish issue #99 based on the last update.
Thank you in advance, ready to test at moment's notice...

2017/09/03 08:53:39 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold_process.php: 207 thold_check_threshold)(/plugins/thold/thold_functions.php: 1721 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 371 execute)(CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace)
2017/09/03 08:53:39 - ERROR PHP WARNING: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in file: /var/www/html/lib/database.php on line: 371
2017/09/03 08:53:39 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold_process.php: 207 thold_check_threshold)(/plugins/thold/thold_functions.php: 1721 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 371 execute)(CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace)
2017/09/03 08:53:39 - ERROR PHP WARNING: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in file: /var/www/html/lib/database.php on line: 371
2017/09/03 08:53:39 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold_process.php: 207 thold_check_threshold)(/plugins/thold/thold_functions.php: 1721 db_fetch_assoc)(/lib/database.php: 345 db_fetch_assoc_prepared)(/lib/database.php: 371 execute)(CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace)

**Comment by cigamit** [comment]
Okay, just committed this fix.
