### ISSUE TITLE
THOLD ERROR: RPN Expression is invalid! after the latest GITHUB update

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#109]
I'm sorry... but after update to the latest thold github, THOLD ERROR: RPN Expression is invalid errors are back.
![thold-rpn-error](https://user-images.githubusercontent.com/11211789/30030775-d3dbca68-915c-11e7-8e96-b4a87a05d7db.gif)

**Comment by cigamit** [comment]
I just did another commit.  I'm not certain if you simply did not update all the files, or if there is a bug in the settings processing.  Note, that you must update thold_functions.php, includes/settings.php, and includes/polling.php.

**Comment by ikorzha** [comment]
When  I updated I have updated the entire thold folder not copied individual files.
After your latest commit update rev 579, 8min ago same issue:
![latest-commit](https://user-images.githubusercontent.com/11211789/30032076-e66e64e2-9161-11e7-8891-d485e25006d1.gif)


![thold-rpn-error-new](https://user-images.githubusercontent.com/11211789/30031735-b4fdfbd0-9160-11e7-8112-c6150815b248.gif)

**Comment by cigamit** [comment]
I just dropped in something new.  Need the log to check the instrumentation

**Comment by ikorzha** [comment]
Latest log as requested:
![latest-log](https://user-images.githubusercontent.com/11211789/30089053-3eb35466-9278-11e7-8d4d-a287e0c045ec.gif)

**Comment by ikorzha** [comment]
As requested updated log from the time full latest github thold applied. I have uploaded portion of the log file this time as per your request,

[cacti.txt](https://github.com/Cacti/plugin_thold/files/1279508/cacti.txt)

**Comment by ikorzha** [comment]
Last updated log for today:
Latesst patch did introduced a small issue...
ERROR PHP NOTICE in  Plugin 'thold': Undefined variable: operation in file: /var/www/html/plugins/thold/thold_functions.php  on line: 205
Log attached:
[cacti.txt](https://github.com/Cacti/plugin_thold/files/1279569/cacti.txt)

**Comment by cigamit** [comment]
Yea, time for a break.  Just want to see what it will come back with.  Undefined variable fixed.

**Comment by ikorzha** [comment]
Here is an updated log based on last commit 583. There still a different error on 205, complete log attached.

ERROR PHP NOTICE in  Plugin 'thold': Array to string conversion in file: /var/www/html/plugins/thold/thold_functions.php  on line: 205

[cacti.txt](https://github.com/Cacti/plugin_thold/files/1280918/cacti.txt)

**Comment by cigamit** [comment]
This should be resolved.  I was only initializing the setting for non-thold daemon operation.  The new setting is not initialized for both daemon and non-daemon settings.  Sorry about all the confusion.  I was pretty whipped last night.

**Comment by ikorzha** [comment]
Thank you so much for dedicated work, there are no more errors in the log. I think this is the final resolution to this issue.

If you don't mind I would like to shift your attention when you have time to new thold daemon that doesn't work properly.
My brother who is a light php developer did fix it up I would like to incorporate his changes to current thold Github and may be you can see what else can be done to further improve its performance, as it looks to be not on par with default thold poller...

**Comment by cigamit** [comment]
Please either open a pull request with the diff, or create an issue and upload the changes to that issue.

**Comment by ikorzha** [comment]
Thank you for understanding. I have opened an issue #112 to request you to reconcile thold daemon performance improvements into a current branch.
