### ISSUE TITLE
Send SMS or exec script

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_thold#113]
Hello. What about this https://forums.cacti.net/viewtopic.php?f=17&t=52285 Enhancement.

I think this Enhancement must on `Notification Lists`.

if you do not mind, I'll try to help with pull request

**Comment by cigamit** [comment]
Go for it Alex.  The command execution is a good idea too.  Make sure we can use replacement tags inside the scripts.

**Comment by cigamit** [comment]
Alex, try to bring parts of this in as well.  https://github.com/Cacti/plugin_thold/issues/82

**Comment by pautiina** [comment]
Ok, I think it's a big work and I weel need you help :)
If I do, something is not right, do not swear severely

**Comment by cigamit** [comment]
I'm working on remote poller support for thold daemon and thold in general.  It's mostly backend work, and not web facing.  Just keep that in mind when working on the pull request.  I'll commit it likely all at the same time.

**Comment by cigamit** [comment]
Pretty sure 1.0.4 is ready.  So, you should be okay to start.  Working with the release manager to get some things tagged/released this weekend.

**Comment by pautiina** [comment]
OK, thanks for information. On next week I wheel try start project for Enhancement

**Comment by cigamit** [comment]
I should dig up my old code.  I had written multiple alert types (email, sms, snmp trap, script execution) and alert escalation into thold over 8 years ago but I never finished it.

**Comment by pautiina** [comment]
That would be great :)

**Comment by TheWitness** [comment]
Marking this one closed as we do currently have command execution in Thold.
