### ISSUE TITLE
Integration to Cacti GUI 1.1.23 not working correctly

### ISSUE THREAD

**Issue by sangdrax8** [Cacti/plugin_thold#114]
I have just installed a new Cacti Version 1.1.23, and thold 1.0.4.  Many of the links from the Cacti web interface are broken.  Some examples of where it breaks:

Management->Thresholds: (http://X.X.X.X/plugins/thold/thold.php)  If I refresh my browser, I will get a broken page.  If I click the "graphs" tab from the top after going to this page, I will end up with an incorrect redirection (http://X.X.X.X/plugins/thold/graph_view.php) which clearly doesn't exist.  It should have just sent me to /graph_view.php.

Using the Thold tab at the top of the screen (http://X.X.X.X/plugins/thold/thold_graph.php) results in what appears to be missing the main cacti CSS or something.  I get a page similar to Management->Thresholds but it is missing most of the buttons or the cacti web gui

I can't add thold alerts by clicking the provided icon next to graphs, I end up with just a broken website.

I just installed this setup, and I think almost everything is default. I don't have much configured, so could there be some additial settings I am missing?

**Comment by cigamit** [comment]
Please download the last update prior to the release of 1.0.4 (aka 1.0.3).  1.0.4 is under some pretty heavy development at the moment.  So, don't use it.

We apologize that we have not cut tags on develop.  Our Release Manager is a pretty busy man, and only is able to allocate time on the weekends to this effort, and he has a lot on his plate, and it's stacking up by the day.

Also, if you installed in the standard /var/www/html/cacti, you need to set your $url_path = '/cacti/';  that might be the largest portion of your problem.

**Comment by sangdrax8** [comment]
Thank you, going to 1.0.3 and setting my url_path fixed it.  It was actually defaulted to /cacti/, and my install required it to just be /.  Looks great now!
