### ISSUE TITLE
Re-Written Thold daemon processes a fraction of tholds every min.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#115]
Cigamit and Browniebraun let me first apologize for being a "pain" first of all..
I been traveling all day and only tonight had a chance to analyze results of latest thold daemon performance.
I let the data do the talking.  I have exported the entire  thold_data table into excel (I only deleted thold name column for privacy).  The table contains a column called "lasttime" (AG column in excel) when was the last time thold processed.
The results are shocking. 80% of tholds never get processed.
[thold_data.xlsx](https://github.com/Cacti/plugin_thold/files/1308064/thold_data.xlsx)

Looks at the log screenshot at 9:31PM  I switched from standard thold poller to daemon. And after that about 80% of tholds never get processed.

![latest-thold](https://user-images.githubusercontent.com/11211789/30508625-660146b0-9a69-11e7-9764-9a76ae48e94e.gif)

Pretty much what is in "InProcess" Never get processed, and it appears every min daemon starts from scratch.
Please assist in solving this major issue.

Also I am not a developer but this "lasttime" column present a great opportunity to get an accurate count of what has been processed in each poller run in that specific minute and report it in cacti log.

**Comment by cigamit** [comment]
I'm not sure what is going on then.  From my perspective, the daemon logic is right.   Browniebraun is going to have to look at this one.  If you restart the daemon, these guys should be handled.  Make sure the daemon is NOT running on other data collectors.

**Comment by ikorzha** [comment]
Cigamit, thank you very much for your latest patch, I did have 1 daemon running on one of the pollers that I stopped after your guidance.
Daemon is restarted, results are much improved.
It is still not 100% consistent every min but now at least everything gets processed once every 3min..  I have judge it by looking at thold_data table "lasttime" 
In case you wonder here is what the latest log result is much improved:
![current](https://user-images.githubusercontent.com/11211789/30527134-44ed42a4-9bf3-11e7-9c21-5e4f23a6f00c.jpeg)

**Comment by ikorzha** [comment]
I'm going to close this issue,  Browniebraun if you want to work further on this issue, I would be delighted.. Just push a thold update and I will be there...

In a mean time I will work with my brother who is a developer also to see if I can bring consistency to daemon reporting and thold executions.  If I come up with any improvements I will do a pull request.
