### ISSUE TITLE
ERROR: illegal string offset

### ISSUE THREAD

**Issue by marino-mrc** [Cacti/plugin_thold#117]
Hi, I'm using thold plugin (version 1.0.3) with cacti 1.1.19 in a centos 7 box and I have on error:

ERROR PHP WARNING in  Plugin 'thold': Illegal string offset 'X-Mailer' in file: /usr/share/cacti/plugins/thold/thold_functions.php  on line: 3518
2017/09/19 10:37:27 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 720 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 thold_poller_bottom)(/plugins/thold/includes/polling.php: 36 thold_update_host_status)(/plugins/thold/includes/polling.php: 418 thold_mail)(/plugins/thold/thold_functions.php: 3518 CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace)

It seems that the problem was solved reading this -> https://github.com/Cacti/plugin_thold/issues/73

Please, how can I solve the issue?
Thank you

**Comment by cigamit** [comment]
Found another issue.  Should be better now.
