### ISSUE TITLE
cacti 1.1.24 and thold 1.0.4 

### ISSUE THREAD

**Issue by Initarts** [Cacti/plugin_thold#119]
Already installed  cacti 1.1.24 and thold 1.0.4 ,Test send mail function properly！ But thold can't work。
![image](https://user-images.githubusercontent.com/8800508/30734807-552e2808-9faf-11e7-947c-deac653ca6cc.png)

Thold settings 
![image](https://user-images.githubusercontent.com/8800508/30734892-9e51ed1c-9faf-11e7-8c64-28e889e9e522.png)

![image](https://user-images.githubusercontent.com/8800508/30734905-ab8eaf92-9faf-11e7-989d-2019eb63df2e.png)

![image](https://user-images.githubusercontent.com/8800508/30735277-f9c1c8d8-9fb0-11e7-9853-dc59d009a333.png)
![image](https://user-images.githubusercontent.com/8800508/30735301-11365a1a-9fb1-11e7-8c1a-943ed6c3dec9.png)
The general setting is this, but it won't call the police。

**Comment by cigamit** [comment]
Can you please check the thold log for notification breaches?  Also, we would love to see your Chinese translation ;).  I know that I've asked before.  I would love to see those screen shots in 100% Chinese.

**Comment by Initarts** [comment]
I don't see any wrong information here. My English is not good. If I can, I can do my best to help you translate English into chinese. For Chinese friends to use。



512326601@qq.com
 
From: Jimmy Conner
Date: 2017-09-23 21:48
To: Cacti/plugin_thold
CC: Initarts; Author
Subject: Re: [Cacti/plugin_thold] cacti 1.1.24 and thold 1.0.4 (#119)
Can you please check the thold log for notification breaches? Also, we would love to see your Chinese translation ;). I know that I've asked before. I would love to see those screen shots in 100% Chinese.

**Comment by cigamit** [comment]
When you are on the thold tab, you can click the 'log' icon.  That's what we are looking for are breaches that resulted in an email.

**Comment by cigamit** [comment]
No response.
