### ISSUE TITLE
cacti 1.1.25 and thold 1.0.4

### ISSUE THREAD

**Issue by iz1999** [Cacti/plugin_thold#124]
Hello,

For some reason I dont see "thold" tab after enabling of the plugin.  Any help/advice would be appreciated!

Thanks 
Igor

![image](https://user-images.githubusercontent.com/32509952/31168239-edfdaf6a-a8f4-11e7-8573-69e5b12a043e.png)

![image](https://user-images.githubusercontent.com/32509952/31168260-fe6bc3be-a8f4-11e7-9035-6a83ad476285.png)

![image](https://user-images.githubusercontent.com/32509952/31168271-081279e4-a8f5-11e7-9116-6fe398c066cd.png)

**Comment by cigamit** [comment]
Refresh the page with F5, also check to see that the plugin is actually enabled under Plugin Management.

**Comment by ikorzha** [comment]
From your first screenshot, thold is not enabled yet, just installed  click on green checkmark and then press F5 to refresh the page
When thold enabled it looks like this:
![enable](https://user-images.githubusercontent.com/11211789/31502949-5e9816e6-af3c-11e7-8bf7-e511d5ed2794.jpg)

Close the case once you all set and done :)
