### ISSUE TITLE
Issue about toggle threshold vrules on

### ISSUE THREAD

**Issue by ghost** [Cacti/plugin_thold#125]
Hi,
Attempting to toggle threshold vrules on but below errors are happened :
![catch](https://user-images.githubusercontent.com/32619710/31319582-d8ff3d8a-ac1a-11e7-9ecf-0c5be4204d6a.jpg)
Cacti Ver: 1.1.25
Thold Ver: 1.0.4

**Comment by cigamit** [comment]
Yea, it's a known issue.  Sorry too much ground to cover and not nearly enough time to cover it all and do the day job at the same time.

**Comment by cigamit** [comment]
Resolved, thanks for your patience.
