### ISSUE TITLE
thold sql optimization

### ISSUE THREAD

**Issue by rgt0078** [Cacti/plugin_thold#126]
Hello,

I have a MySQL database behind a firewall, hence the number of SQL requests from thold could be optimized...

By adding more data to be retrieved in includes/polling.php (thold_check_all_thresholds function)
$sql_query = "SELECT td.*, dtr.data_source_name, **h.hostname, h.description, h.notes, h.snmp_engine_id**
		FROM thold_data AS td
		LEFT JOIN data_template_rrd AS dtr
		ON dtr.id=td.data_template_rrd_id
		**LEFT JOIN host as h
		ON td.host_id = h.id**
		WHERE td.thold_enabled='on' AND td.tcheck=1 **AND h.status=3**";

-> there is no need anymore to check status and read information in thold_functions.php (thold_check_threshold function)...
This simple trick reduces thold executions by several seconds on my environment...

Moreover, it seems the following request is useless... 
/*pull the cached name, if not present, it means that the graph hasn't polled yet */
$t = db_fetch_assoc('SELECT id, name, name_cache
		FROM data_template_data
		WHERE local_data_id = ' . $thold_data['local_data_id'] . '
		ORDER BY id
		LIMIT 1');

**Comment by cigamit** [comment]
Can you please do this in the form of a pull request?

**Comment by cigamit** [comment]
Resolved in the pull request.  Thanks!
