### ISSUE TITLE
PHP ERROR Warning on thold_functions.php - Illegal string offset 'User-Agent' and 'X-Mailer'

### ISSUE THREAD

**Issue by chtay** [Cacti/plugin_thold#130]
This maybe the same/similar error message with #73.
System running on cacti v1.1.26 and later on, replaced to v1.1.27 and it still shows the following error message.
PHP version = 7.1.10
Thold version = 1.0.4

**_Message seen on log:_**
2017/11/06 14:57:30 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 603 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 thold_poller_bottom)(/plugins/thold/includes/polling.php: 41 thold_update_host_status)(/plugins/thold/includes/polling.php: 627 thold_mail)(/plugins/thold/thold_functions.php: 3825 CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)

2017/11/06 14:57:30 - ERROR PHP WARNING in Plugin 'thold': Illegal string offset 'User-Agent' in file: /Somewhere/cacti/plugins/thold/thold_functions.php on line: 3825

and

2017/11/06 14:57:30 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 603 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 thold_poller_bottom)(/plugins/thold/includes/polling.php: 41 thold_update_host_status)(/plugins/thold/includes/polling.php: 627 thold_mail)(/plugins/thold/thold_functions.php: 3824 CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)

2017/11/06 14:57:30 - ERROR PHP WARNING in Plugin 'thold': Illegal string offset 'X-Mailer' in file: /vol/Web_Apps/cacti/plugins/thold/thold_functions.php on line: 3824 

**_Finding:_**
In thold plugin, the file "thold_functions.php", on line 3750:
function thold_mail($to_email, $from_email, $subject, $message, $filename, **$headers = ''**) {

If I not wrong, the **$headers** will be an empty string, if function is called without that parameter is provided.
But when come to line: 3824 and 3825:
    $headers['X-Mailer']   = 'Cacti-Thold-v' . $version;
    $headers['User-Agent'] = 'Cacti-Thold-v' . $version;
That may cause problem because the PHP still assume it is a string and thus, with the above 2 lines, the PHP will complain error.

Since the $headers is expect to be an array for the rest of that function (thold_mail), think it is best to replace it with this instead.
So in line 3750, replaced it with this instead:
function thold_mail($to_email, $from_email, $subject, $message, $filename, **$headers = array()**) {

I tried on my system, and so far no more showing the above error message.

**Comment by cigamit** [comment]
Resolved, thanks!
