### ISSUE TITLE
User with tholds view only permission able to enable/disable Tholds.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#131]
I have encountered the following issue with a user with Thold view permission only.
User able to disable and enable any Thold at will I believe it is a wrong logic for view only user.  Please address it.
Here are relevant screenshots:
![view-tholds](https://user-images.githubusercontent.com/11211789/32690605-4e306734-c6c7-11e7-93f4-a518e83eda7e.jpeg)
I am able to disable a thold as view only user.
![view-tholds-disable](https://user-images.githubusercontent.com/11211789/32690607-4f6b33a4-c6c7-11e7-9a18-2f402d364873.jpeg)

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting!

**Comment by ikorzha** [comment]
Cigamit, can we please re-open this issue.  I believe there is a new issue stemming from this fix.
When I navigate to console, Management Thresholds choose a threshold to delete and press GO, threshold doesn't get deleted.

**Comment by cigamit** [comment]
Hmm, I take away these permissions, and I still get a Thresholds page, but it's blank.  Which means I don't have permission.  I should start with a new install to test this.

**Comment by cigamit** [comment]
The thing I just mentioned looks like a cacti bug.  Have to report it.  I was able to remove the tholds just fine after that change.  Must be something else.  What version of Cacti?

**Comment by cigamit** [comment]
By the way, this first issue, how often does it happen.  I'll need to see the Data Template(s) screen shots and a screen shot of the Graph here.

**Comment by ikorzha** [comment]
I am running Cacti 1.1.28... And you are right it it unable to delete tholds from certain templates only not from all.  Issue occurs every time "undeletable template encountered on a device." In order to delete these tholds, I must delete entere device from Cacti to clean them..

I see the problem with Cisco Environmental Template:
![unable-to-delete](https://user-images.githubusercontent.com/11211789/36461564-36c818f2-168c-11e8-87e0-313951805f15.jpg)
This template is publicly available, if you need it for testing I can locate it on the web. Or export from my server.

**Comment by cigamit** [comment]
Bring up your browsers debug navigator, goto the console, and then try to delete the threshold.  See if there are any errors in the console.  Also, please review the cacti log right away afterwards and past screen shot's of the errors.

**Comment by ikorzha** [comment]
I did bring browser debug I do not see any errors, also in Cacti Log no errors too. Please advise how to proceed forward with regards to this issue.

**Comment by cigamit** [comment]
That's odd, put the thold.php file into debug and see what's going on.  Post the log output.  Just thold.php, not all of Cacti.

**Comment by netniV** [comment]
If you are using the latest thold, try updating again as there have been some fixes.  It may be related.
