### ISSUE TITLE
Undefined index: loss in file: /var/www/html/plugins/thold/thold_process.php on line: 225 

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#132]
Hi I occasionally run into php error in my Cacti log file...

**2017/11/12  18:44:46 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold_process.php: 225  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/12 18:44:46 - ERROR PHP NOTICE in   Plugin 'thold': Undefined index: loss in file:  /var/www/html/plugins/thold/thold_process.php  on line: 225
2017/11/12 18:44:46 - CMDPHP PHP ERROR NOTICE  Backtrace: (/plugins/thold/thold_process.php: 225  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/12 18:44:46 - ERROR PHP NOTICE in   Plugin 'thold': Undefined index: avg in file:  /var/www/html/plugins/thold/thold_process.php  on line: 225**

![undefined-index](https://user-images.githubusercontent.com/11211789/32704836-2ede05c6-c7da-11e7-8782-8e24022f9598.jpeg)

**Comment by cigamit** [comment]
Can you please upload your thold_process.php file?  I don't seen to get this line.

**Comment by ikorzha** [comment]
Cigamit, thank you for looking into it, here attached is the requested file.
FYI I have also identified another bug, that stemmed from fix of https://github.com/Cacti/plugin_thold/issues/131, tholds are now no longer can be deleted... I will open a separate issue on it,

[thold_process.php.txt](https://github.com/Cacti/plugin_thold/files/1742674/thold_process.php.txt)

**Comment by cigamit** [comment]
Okay, I've created a workaround.  I'm not certain why these indexes are not  being set properly.  Maybe it's an unreliable data source?

**Comment by ikorzha** [comment]
I believe there are "unreliable data sources".  So I track the issue to Advanced Ping Template 1.3 Avg and Loss..
I believe when template returns 0 data these tholds errors are being thrown, I lived with it for long time,,, Will test your fix now and will close the case later, Thank you.

**Comment by ikorzha** [comment]
I have tested new fix, problem still occurring msg has changed to "Undefined variable: current_time" please see below:

2018/02/20  22:59:32 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold_process.php: 225  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
--
2018/02/20 22:59:32 - ERROR PHP NOTICE in   Plugin 'thold': Undefined variable: current_time in file:  /var/www/html/plugins/thold/thold_process.php  on line: 225
2018/02/20 22:59:32 - CMDPHP PHP ERROR NOTICE  Backtrace: (/plugins/thold/thold_process.php: 225  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2018/02/20 22:59:32 - ERROR PHP NOTICE in   Plugin 'thold': Undefined variable: current_time in file:  /var/www/html/plugins/thold/thold_process.php  on line: 225

**Comment by cigamit** [comment]
Yea, that was my bad.  Time to turn in.  It's fixed now.

**Comment by cigamit** [comment]
Should be resolved now.  If not, just commit on the closed thicket and I can re-open.

**Comment by ikorzha** [comment]
Thank you Cigamit I tested the fix yesterday. No more errors in the log...

**Comment by cigamit** [comment]
Good to know.
