### ISSUE TITLE
Ability to change the subject for the threshold alert message

### ISSUE THREAD

**Issue by AH1983** [Cacti/plugin_thold#135]
Hi all,

ive just struggeling on changing the subject for the threshold alert message.
For the down device subject you can easy change it, but for the threshold alert´s its currently not forseen.

Maybe its not a big deal to change this also for threshold alert´s.

Kind Regards,
Andreas

**Comment by TheWitness** [comment]
@AH1983, give me a few examples...

**Comment by TheWitness** [comment]
This is implemented now for Thold 2.0
