### ISSUE TITLE
Up/Down History

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#139]
I may be missing something here, but the THold plugin appears to log when a device breaches its status.  It also records the current device status.  What I can't seem to find is a history of up/down status for a particular device.

**Comment by cigamit** [comment]
Use the monitor plugin for this.  It tracks the reboot and event timestamps.

**Comment by netniV** [comment]
Yes, but that's not what I want.  I want to know when a threshold was triggered from a historic point of view.  A device doesn't have to be down for a threshold to be breached and if you are not using the monitor plugin, it should be available via thold.

**Comment by rcsmota** [comment]
Hi;

Like @netniV I miss a list of history of up/down device. On monitor I can see the last status but not find a list showing all times the device up an donw.
I have some devices on remote sites that down and up several times and a list of status up and down its a good thing.

Thanks.

**Comment by netniV** [comment]
@rcsmota, I agree and I can now make this change that shows the history of alert status from Montior.  Similar to the Logs table of the THold plugin.  The one thing I'm toying with is whether having two separate logs is really worth it or it should be combined into one since Monitor relies on THold anyway.
