### ISSUE TITLE
Timeout/logout

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#14]
Getting this error in apache error log when my session times out and attempts to display logout.php:

[Tue Sep 20 11:56:17.646728 2016] [:error] [pid 14055] [client 192.168.11.140:49855] script '/var/www/html/cacti/plugins/thold/logout.php' not found or unable to stat, referer: http://192.168.11.15/cacti/plugins/thold/thold.php?action=add

**Comment by cigamit** [comment]
oh, that is interesting.  more of a cacti issue.

**Comment by cigamit** [comment]
Resolved here https://github.com/Cacti/cacti/commit/99f9f522f9e1166b3a7fd00966726e93e4a163de

**Comment by smiles1969** [comment]
This appears to be fixed now thank you.
