### ISSUE TITLE
Baseline Deviation Moving Average

### ISSUE THREAD

**Issue by rhenzon** [Cacti/plugin_thold#140]
Hi, is there a way to make the baseline deviation a moving average every 5mins? Because I noticed that if I set the time range to 30 mins, the baseline up/down only gets updated every 30 mins.  What we are tying to achieve is calculate the past 30mins baseline deviation and update the value every 5 mins.

**Comment by cigamit** [comment]
That sounds like a bug.  Marking it as such.

**Comment by TheWitness** [comment]
Switching to 1.6 milestone.

**Comment by TheWitness** [comment]
Okay, took a better part of my career, but finished.
