### ISSUE TITLE
cacti 1.1.30 division by zero when removing threshold

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_thold#141]
After upgrading from cacti 1.1.28, When I try to delete a threshold I got this error:
2018/01/08 10:24:59 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold.php: 126 list_tholds)(/plugins/thold/thold.php: 665 thold_format_number)(/plugins/thold/thold_functions.php: 2493 number_format_i18n)(/include/global_languages.php: 590 CactiErrorHandler)(/lib/functions.php: 4429 cacti_debug_backtrace)
2018/01/08 10:24:59 - ERROR PHP WARNING: Division by zero in file: /usr/share/cacti-1/include/global_languages.php on line: 590
2018/01/08 10:24:44 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold_graph.php: 56 tholds)(/plugins/thold/thold_graph.php: 429 thold_format_number)(/plugins/thold/thold_functions.php: 2493 number_format_i18n)(/include/global_languages.php: 590 CactiErrorHandler)(/lib/functions.php: 4429 cacti_debug_backtrace)
2018/01/08 10:24:44 - ERROR PHP WARNING: Division by zero in file: /usr/share/cacti-1/include/global_languages.php on line: 590

**Comment by netniV** [comment]
This appears to occur due to a graph template not being available or having a ZERO value when the following query is run:
```
  $baseu = db_fetch_cell_prepared('SELECT base_value
                                FROM graph_templates_graph
                                WHERE local_graph_id = ?',
                                array($row['local_graph_id']));
```

**Comment by cigamit** [comment]
Okay, there is a better way to handle this one...  Fixing.

**Comment by cigamit** [comment]
Should be resolved now.  We should be blocking Graph Template deletes when there are tholds that use them.
