### ISSUE TITLE
when two data source have same field name. Thold would created unexpectedly

### ISSUE THREAD

**Issue by horizonlin** [Cacti/plugin_thold#142]
![20180110_5](https://user-images.githubusercontent.com/26472990/34758545-ea898f42-f611-11e7-9628-d135f6797e6f.jpg)

![20180110_4](https://user-images.githubusercontent.com/26472990/34758541-e3445244-f611-11e7-8228-e7dba85ef09f.jpg)
![20180110_3](https://user-images.githubusercontent.com/26472990/34758537-dd79a5b2-f611-11e7-84bd-ea8d730c30ac.jpg)

**Comment by netniV** [comment]
I think you are saying that the thold entries are showing a duplicated [<text>] at the end of the title?  Can you clarify if this is correct?

**Comment by cigamit** [comment]
Good catch.  Resolved.
