### ISSUE TITLE
unexpectedly cycle in autocreate function and message show incorrect

### ISSUE THREAD

**Issue by horizonlin** [Cacti/plugin_thold#143]
Is this will be better.
function autocreate($host_id) {
	$created = 0;
	$message = '';

	$rralist = db_fetch_assoc_prepared('SELECT tt.*,dl.id as local_data_id,dtr.id as data_template_rrd_id
		FROM thold_template AS tt
		INNER JOIN plugin_thold_host_template AS ptht	ON tt.id=ptht.thold_template_id
		INNER JOIN data_local AS dl ON dl.data_template_id = tt.data_template_id 
		INNER JOIN data_template_rrd AS dtr ON dl.id = dtr.local_data_id and tt.data_source_name = dtr.data_source_name
		INNER JOIN `host` AS h ON h.id = dl.host_id and h.host_template_id = ptht.host_template_id
		WHERE  dl.host_id = ? ;',
		array($host_id));
		
	if (!sizeof($rralist)) {
		$_SESSION['thold_message'] = '<font size=-2>' . __('No Thresholds Templates associated with the Host\'s Template.', 'thold') . '</font>';
		return 0;
	}

	foreach ($rralist as $row) {
		$local_data_id      = $row['local_data_id'];
		$data_template_id   = $row['data_template_id'];

		$existing = db_fetch_row_prepared('SELECT td.id
			FROM thold_data AS td
			INNER JOIN data_template_rrd AS dtr
			ON dtr.id=td.data_template_rrd_id
			WHERE td.local_data_id = ?
			AND td.data_template_id = ?
			AND td.thold_template_id = ?
			AND td.thold_type = ?
			AND dtr.data_source_name = ?',
			array($local_data_id, $data_template_id, $row['id'], $row['thold_type'], $row['data_source_name']));
			
		if (!sizeof($existing)) {
			$data_template_rrd_id = db_fetch_cell_prepared('SELECT id
				FROM data_template_rrd
				WHERE local_data_id = ?
				AND data_source_name = ?
				AND data_template_id = ? 
				ORDER BY id LIMIT 1', array($local_data_id, $row['data_source_name'], $row['data_template_id']));

			$graph  = db_fetch_row_prepared('SELECT local_graph_id, graph_template_id
				FROM graph_templates_item
				WHERE task_item_id = ?
				AND local_graph_id > 0
				LIMIT 1', array($data_template_rrd_id));
			
			if (sizeof($graph)) {
				
				$data_source_name = $row['data_source_name'];

				$desc = db_fetch_cell_prepared('SELECT name_cache FROM data_template_data WHERE local_data_id = ? LIMIT 1', array($local_data_id));

				$insert                         = array();
				$insert['id']                   = 0;
				$insert['name']                 = $desc . ' [' . $data_source_name . ']';
				$insert['local_data_id']        = $local_data_id;
				$insert['data_template_rrd_id'] = $data_template_rrd_id;
				$insert['local_graph_id']       = $graph['local_graph_id'];
				$insert['graph_template_id']    = $graph['graph_template_id'];
				$insert['data_template_id']     = $data_template_id;

				$insert['thold_hi']             = $row['thold_hi'];
				$insert['thold_low']            = $row['thold_low'];
				$insert['thold_fail_trigger']   = $row['thold_fail_trigger'];

				$insert['time_hi']              = $row['time_hi'];
				$insert['time_low']             = $row['time_low'];
				$insert['time_fail_trigger']    = $row['time_fail_trigger'];
				$insert['time_fail_length']     = $row['time_fail_length'];

				$insert['thold_warning_hi']           = $row['thold_warning_hi'];
				$insert['thold_warning_low']          = $row['thold_warning_low'];
				$insert['thold_warning_fail_trigger'] = $row['thold_warning_fail_trigger'];
				$insert['thold_warning_fail_count']   = $row['thold_warning_fail_count'];

				$insert['time_warning_hi']            = $row['time_warning_hi'];
				$insert['time_warning_low']           = $row['time_warning_low'];
				$insert['time_warning_fail_trigger']  = $row['time_warning_fail_trigger'];
				$insert['time_warning_fail_length']   = $row['time_warning_fail_length'];

				$insert['thold_alert']          = 0;
				$insert['thold_enabled']        = $row['thold_enabled'];
				$insert['thold_type']           = $row['thold_type'];

				$insert['bl_ref_time_range']    = $row['bl_ref_time_range'];
				$insert['bl_pct_down']          = $row['bl_pct_down'];
				$insert['bl_pct_up']            = $row['bl_pct_up'];
				$insert['bl_fail_trigger']      = $row['bl_fail_trigger'];
				$insert['bl_fail_count']        = $row['bl_fail_count'];
				$insert['bl_alert']             = $row['bl_alert'];

				$insert['repeat_alert']         = $row['repeat_alert'];
				$insert['notify_default']       = $row['notify_default'];
				$insert['notify_extra']         = $row['notify_extra'];
				$insert['notify_warning_extra'] = $row['notify_warning_extra'];
				$insert['notify_warning']       = $row['notify_warning'];
				$insert['notify_alert']         = $row['notify_alert'];

				$insert['host_id']              = $host_id;

				$insert['notes']                = $row['notes'];

				$insert['cdef']                 = $row['cdef'];
				$insert['percent_ds']           = $row['percent_ds'];
				$insert['expression']           = $row['expression'];
				$insert['thold_template_id']    = $row['id'];
				$insert['template_enabled']     = 'on';

				$id = sql_save($insert, 'thold_data');

				if ($id) {
					$graph_name = get_graph_title($graph['local_graph_id']);

					thold_template_update_threshold($id, $insert['thold_template_id']);
					plugin_thold_log_changes($id, 'auto_created', $insert['name']);

					$message .= __('Created threshold for the Graph \'<i>%s</i>\' using the Data Source \'<i>%s</i>\'', $graph_name, $data_source_name, 'thold')  . "<br>";
					$created++;
				}
			}
		}
			
		
	}
	$_SESSION['thold_message'] = "<font size=-2>$message</font>";

	return $created;
}

**Comment by netniV** [comment]
I'm not sure why you've pasted an entire function from thold here.... is this related to #142 ? If so, you should have included a response on there.

**Comment by horizonlin** [comment]
#142 is an issue that I don't create a thold template to the host template . A unexpectedly thold be created using auto-create thresholds. It occur when two data source template has  same field name.

But this issue show wrong message after creating tholds, I find that execute unexpectedly cycle .
Because of the code below will replace $data_template_rrd_id  to 0 when $data_template_rrd_id is empty
$graph  = db_fetch_row_prepared('SELECT local_graph_id, graph_template_id 
						FROM graph_templates_item 
						WHERE task_item_id = ? 
						AND local_graph_id > 0 
						LIMIT 1', array($data_template_rrd_id));

**Comment by cigamit** [comment]
I would like to see a diff from the currently committed work.  Rather a pull request would be better @horizonlin

**Comment by cigamit** [comment]
I think that this is resolved.  Closing.  Please test with the latest code.  If you find that it is still broken, then please add a comment, we can re-open.
