### ISSUE TITLE
Unexpected threshold breach due to very high value

### ISSUE THREAD

**Issue by Poslik** [Cacti/plugin_thold#144]
Hello, we were facing a very strange situation, where the threshold is breached due to very high value, but the breach value is not present in rrd  and not visible in graph.

For examle the Alert message:

> An Alert has been issued that requires your attention. 

> Device: X (x.x.x.x)
> URL: Link to Graph in Cacti
> Message: ALERT: X - Traffic - * [traffic_out] went above threshold of 54000000000 with **1.6523099930385E+15**

![image](https://user-images.githubusercontent.com/35453993/34941578-a0cc6668-f9f4-11e7-8243-4151e0665ae6.png)

I discovered the problem in thold_functions.php in condition 

> }elseif ($thold_data['rrd_maximum'] == 0 && $currentval > 4.25E+9) {

which is resolved like 
> }elseif (|query_ifSpeed| == 0 && 4264205114.9701 > 4.25E+9) {

and like true. Yes, condition "|query_ifSpeed|" == 0 is really true.

The variable $thold_data['rrd_maximum'] is filled from select (thold_functions.php line 671):
`SELECT thold_data.id, thold_data.local_graph_id, thold_data.percent_ds, thold_data.expression, thold_data.data_type, thold_data.cdef, thold_data.local_data_id, thold_data.data_template_rrd_id, thold_data.lastread, UNIX_TIMESTAMP(thold_data.lasttime) AS lasttime, thold_data.oldvalue, data_template_rrd.data_source_name as name, data_template_rrd.data_source_type_id, data_template_data.rrd_step, data_template_rrd.rrd_maximum FROM thold_data LEFT JOIN data_template_rrd ON data_template_rrd.id = thold_data.data_template_rrd_id LEFT JOIN data_template_data ON data_template_data.local_data_id=thold_data.local_data_id limit 100;`

where I have sometimes "|query_ifSpeed|" parameter and sometimes number parameter (depends on Data Source configuration).

The final current value is then calculated like:
> $currentval = $item[$thold_data['name']] / $polling_interval;
or
> $currentval = 62168163488073217(this is the lastTrafficOutCounterValue) / 300

$currentval= 2.0653874912981E+14 * 8 = **1.6523099930385E+15**

Anyway, it would be better to change == on === and resolve the data type of variable too.
> }elseif ($thold_data['rrd_maximum'] === 0 && $currentval > 4.25E+9) {

**Comment by cigamit** [comment]
I see, there is a better solution for this.  Let me pull some logic from Cacti.

**Comment by cigamit** [comment]
This issue should be resolved now.  I just had to pull the |query_ifSpeed| code over from the main Cacti code.  Please close if you are satisfied.

**Comment by cigamit** [comment]
Resolution was here: https://github.com/Cacti/plugin_thold/commit/5d19718a3b37d99dfe1c57e3235e0dbdafefeb22

**Comment by Poslik** [comment]
Thank you, Cigamit.
