### ISSUE TITLE
Thold turning itself off

### ISSUE THREAD

**Issue by reileao** [Cacti/plugin_thold#145]
Hi all

Someone else with thold plugin problem which turn off alone?
I use only thold plugin in my cacti 1.1.30 and the same it turn off alone after some hours later

While it's running, the thresholds are sent by e-mail with successful, but out of the blue the some hours later the plugin turn off

Regards

**Comment by netniV** [comment]
I don't believe that THOLD turns it self off.  However, the plugin will be turned off by Cacti if an unexpected error occurs.  Can you check through your log files for any errors?

**Comment by reileao** [comment]
I believe too, but I had tried the thold 1.0.3 and 1.0.4 and the some error happend.
The other plugins runs ok only plugin thold turned off
I'm used to running only thold plugin without other settings, I'm used to use it for receive devices lost connections errors.
I got the log error:

01/15/2018 17:01:06 - SYSTEM STATS: Time:4.3627 Method:spine Processes:1 Threads:1 Hosts:9 HostsPerProcess:9 DataSources:0 RRDsProcessed:0
01/15/2018 17:01:06 - ERROR PHP ERROR in  Plugin 'thold': Uncaught Error: Call to undefined function cacti_snmp_get() in /var/www/html/plugins/thold/includes/polling.php:303
Stack trace:
#0 /var/www/html/plugins/thold/includes/polling.php(36): thold_update_host_status()
#1 /var/www/html/lib/plugins.php(170): thold_poller_bottom(Array)
#2 /var/www/html/lib/plugins.php(73): api_plugin_run_plugin_hook('poller_bottom', 'thold', 'thold_poller_bo...', Array)
#3 /var/www/html/poller.php(603): api_plugin_hook('poller_bottom')
#4 {main}
  thrown in file: /var/www/html/plugins/thold/includes/polling.php on line: 303
01/15/2018 17:01:06 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4472 cacti_debug_backtrace)
01/15/2018 17:01:06 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'

Hug

**Comment by netniV** [comment]
Does cacti live directly in the /var/www/html/ folder?

**Comment by reileao** [comment]
Yes everything in the /var/www/html/

**Comment by netniV** [comment]
Which version of THOLD generated that error? v1.0.4 doesn't have anything at the line reported.  It's a `}` which can't generate the error in question.

**Comment by reileao** [comment]
Now I'm using v1.0.3 because v1.0.4 runs the same error and I tried v1.0.3 for to see if it happen too

**Comment by cigamit** [comment]
Yea, likely a config issue.  Should be working now.

**Comment by reileao** [comment]
What version of Cacti do you use or advise for me?

**Comment by netniV** [comment]
Download the source for the plugin, and replace your existing files.  You should not need to update cacti's code.

**Comment by reileao** [comment]
Ok, I'll put again the version 1.0.4 and try it more once time if it doenst work I'll try on debian

**Comment by netniV** [comment]
You will need to re-download 1.0.4 from the develop branch as it has been updated on this website.

**Comment by reileao** [comment]
Nice man, I put on the plugin again. I'll monitoring if it going to turn off

**Comment by reileao** [comment]
Hello buddy
Until now the plugin runs a lot of fine, it havent stoped again =]
Thanks a lot for help!
