### ISSUE TITLE
Releases of thold

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#146]
It would be useful to have the same tagging done for thold as for the base cacti system.

To that end, on my forked repo, I created tags for v1.0.0 through v1.0.3.  At the moment, I'm assuming that v1.0.4 is a work in progress:

```
git tag -a v1.0.0 ce4aefe2e6dbcfbf8875d911adb5c152ab921717~1 -m v1.0.0
git tag -a v1.0.1 247b5ef8a10a9de683dcaad6f2f29bed730336a1~1 -m v1.0.1
git tag -a v1.0.2 574dca0ed9a093f61ae2fb6f3c63cc92a65d3d1c~1 -m v1.0.2
git tag -a v1.0.3 f9577a9f0a5348cf3935560678a9068fb1fe1fc5~1 -m v1.0.3
```

**Comment by cigamit** [comment]
I have asked @ronytomen to look at this ticket this morning if he has time.

**Comment by cigamit** [comment]
We were supposed to get these plugins tagged months ago.

**Comment by netniV** [comment]
I know they are only plugins, but they should probably all have the same release methods as the base code.

**Comment by netniV** [comment]
I have now tagged THold with these releases.
