### ISSUE TITLE
Make baseline deviation work with negative values

### ISSUE THREAD

**Issue by rchen14b** [Cacti/plugin_thold#147]
Hey Guys,

We have a thold template to measure a radio signal which is negative value. And it using baseline deviation method, when signal drop 60% it will trigger alert.
 
![image](https://user-images.githubusercontent.com/13096569/35159156-e875191c-fcfe-11e7-9d41-59bd1a5f4e81.png)

Right after I added this threshold, it will trigger the alert, even the signal never changed. 
Alert Message: RSSI [siklu_rsl] went below calculated baseline threshold 14.0928888888 with -35

**Comment by acarls99** [comment]
Try replacing $ref_value_min with abs( $ref_value_min) and $ref_value_max with abs( $ref_value_max) in thold_functions.php.  https://github.com/Cacti/plugin_thold/blob/f32ac92ce3cea154d25395ddd6af14a403757250/thold_functions.php#L3278

```
/*              if ($thold_data['bl_pct_down'] != '') {
                        $blt_low  = $ref_value_min - ($ref_value_min * $thold_data['bl_pct_down'] / 100);
                }

                if ($thold_data['bl_pct_up'] != '') {
                        $blt_high = $ref_value_max + ($ref_value_max * $thold_data['bl_pct_up'] / 100);
                }
*/

                if ($thold_data['bl_pct_down'] != '') {
                        $blt_low  = $ref_value_min - (abs($ref_value_min) * $thold_data['bl_pct_down'] / 100);
                }

                if ($thold_data['bl_pct_up'] != '') {
                        $blt_high = $ref_value_max + (abs($ref_value_max) * $thold_data['bl_pct_up'] / 100);
                }

```

**Comment by netniV** [comment]
I'm not sure that would make a difference.  From what I am interpreting, this would suggest that either your ref_value_min is already negative, or your bl_pct_down is greater than 100.

**Comment by acarls99** [comment]
His baseline reference looks to be -35 a value causing the thresholds to be reversed without the abs().

**Comment by netniV** [comment]
I'd have to check further whether the last_value displayed in the email is the deviation value or actual value.

**Comment by acarls99** [comment]
See https://forums.cacti.net/viewtopic.php?f=17&t=40501

**Comment by netniV** [comment]
Thanks for the link, I'll look into it a bit more tomorrow.

**Comment by netniV** [comment]
OK, so I did a spreadsheet to prove the calculations and it confirmed what the code is doing vs what is expected.  We should be absoluting the value to create the deviation.

[Threshold Baseline Deviation Calculations (2018-03-31).xlsx](https://github.com/Cacti/plugin_thold/files/1865250/Threshold.Baseline.Deviation.Calculations.2018-03-31.xlsx)

This is now patched in the latest develop branch.

**Comment by rchen14b** [comment]
@netniV Thanks so much for your help, I will test it our this Monday.

**Comment by rchen14b** [comment]
@netniV 
Hey man, 
I just updated our thold to latest version of thold. Still having the issue. It looks like the thold_function.php hasn't been updated? I also tried abs() solution, with the -50 value baseline, it still giving me the positive alert value.

**Comment by acarls99** [comment]
It corrected similar issue on my server.  It may take a while to recalculate the baseline thresholds.

**Comment by rchen14b** [comment]
@acarls99 @netniV 
 $blt_low  = '';
                $blt_high = '';

                if ($thold_data['bl_pct_down'] != '') {
                        **$blt_low  = $ref_value_min - (abs($ref_value_min) * $thold_data['bl_pct_down'] / 100);**
                }

                if ($thold_data['bl_pct_up'] != '') {
                        **$blt_high = $ref_value_max + (abs($ref_value_max) * $thold_data['bl_pct_up'] / 100);**
                }

Is that the only place you fixed? 

For example, is I have -40 value and want it alert me if value drop 20% down, for the formula above:
blt_low = -40 - (abs(-40) * 20/100) = -40-8 = - 48 , which make sense to me. But my actual alert value is 32 even after use the above formula. Any idea?

**Comment by netniV** [comment]
Pretty much.  The only other thing I did was to set the failed value for high first, the low to keep it consistent with other alert methods (time/value) since they report high first.  So unless your value deviates about that too..

**Comment by rchen14b** [comment]
@netniV  
Can you please share how you set the failed value for high first? So, when have one template with negative value, it works fine. If I add a second template also have negative value, it will then have the positive alert value.

**Comment by netniV** [comment]
Sorry, to be clear, in any threshold you have a high and low warning/alert.  Thresholds based on deviation were checking for values lower than the low threshold, then those higher than the high threshold.  I've inverted that to make it consistent with the Time and Value based Threshold types.  Effectively, it should change nothing.

**Comment by rchen14b** [comment]
@netniV 
Thanks for the reply. I think it still having some weird issue. 
The first baseline low template I added which has negative RSSI value work fine and calculate right value. 
But second baseline template I added which also has negative RSSI value will be triggered right after I added with a positive alert value. (-42, 40%, triggered baseline threshold 24.8 with -42 )

Any thought?

**Comment by rchen14b** [comment]
@netniV 
If I have a value -42 and set to baseline low 40%, even with the none abs version formula, it should be:
blt_low = -42 - (-42*(40/100)) = -25.2 

I don't understand how the positive alert value come from, any thought?

**Comment by netniV** [comment]
Can you try turning the thold debugging option on?  This will give more information in the logs as to how the values are calculated etc.

**Comment by rchen14b** [comment]
@netniV I have tried removed all template and readded it, works fine so far.
