### ISSUE TITLE
thold.sql

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#15]
Is it possible to include/maintain a running thold.sql for the current database structure? I know the setup creates the structure, but don't want to lose existing configured thresholds if I uninstall/reinstall the plugin.

**Comment by cigamit** [comment]
sure, I can upload one into the 'extras' folder

**Comment by cigamit** [comment]
Resolved here: https://github.com/Cacti/plugin_thold/commit/2204ee9f26c638ce318e36060f337ee4f881673b 

I am seeing some more odd thold behavior.  So there will be some more fixes coming soon.  They are just annoyances, like clicking on things and not seeing what you are supposed to see under Threshold Management.
