### ISSUE TITLE
Create Node dependencies for up/down messages

### ISSUE THREAD

**Issue by g1augusto** [Cacti/plugin_thold#151]
Hi,

I would like to request a dependency check (like a dependency tree) when a notification has to be sent about a device uptime:

Normally some devices a dependant to others and while is good to keep the up/down log for them if the root device is down there is no need to alert sometimes ALSO about the others.

Example:

Root device : Server switch
Child device : Servers 

Thanks for giving it a thought.

**Comment by netniV** [comment]
I already raised this as a thing for the base Cacti rather than plugins purely because it's not just notifications that should only occur in such a fashion.  There' no point even querying some devices if the parent device is unavailable.

https://github.com/Cacti/cacti/issues/1330

**Comment by netniV** [comment]
As we have the based request open I'm going to close this one.
