### ISSUE TITLE
Thold upgrade support missing some table changes

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_thold#152]
I have this log error with latest cacti/thold develop branch:

Log1:
2018/02/20 08:45:05 - DBCALL ERROR: SQL Assoc Failed!, Error: Table 'cacti.plugin_thold_host_failed' doesn't exist in engine
2018/02/20 08:45:05 - DBCALL ERROR: SQL Assoc Failed!, Error:1932, SQL:'SELECT *   FROM plugin_thold_host_failed'

Log2:
2018/02/20 09:10:03 - SYSTEM THOLD STATS: Time:0.0171 Tholds:0 TotalDevices:6 DownDevices:0 NewDownDevices:0
2018/02/20 09:10:03 - CMDPHP SQL Backtrace: (/poller.php: 723  api_plugin_hook)(/lib/plugins.php: 73  api_plugin_run_plugin_hook)(/lib/plugins.php: 170  thold_poller_bottom)(/plugins/thold/includes/polling.php: 41  thold_update_host_status)(/plugins/thold/includes/polling.php: 761  db_execute)(/lib/database.php: 135  db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
2018/02/20 09:10:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.plugin_thold_host_failed' doesn't exist in engine
2018/02/20 09:10:03 - DBCALL ERROR: A DB Exec Failed!, Error:1932, SQL:'TRUNCATE plugin_thold_host_failed'
2018/02/20 09:10:03 - CMDPHP SQL Backtrace: (/poller.php: 723  api_plugin_hook)(/lib/plugins.php: 73  api_plugin_run_plugin_hook)(/lib/plugins.php: 170  thold_poller_bottom)(/plugins/thold/includes/polling.php: 41  thold_update_host_status)(/plugins/thold/includes/polling.php: 502  db_fetch_assoc)(/lib/database.php: 360  db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
2018/02/20 09:10:03 - DBCALL ERROR: SQL Assoc Failed!, Error: Table 'cacti.plugin_thold_host_failed' doesn't exist in engine
2018/02/20 09:10:03 - DBCALL ERROR: SQL Assoc Failed!, Error:1932, SQL:'SELECT *   FROM plugin_thold_host_failed'

**Comment by netniV** [comment]
It would appear that the create/upgrade code isn't working properly.  You can find the table structure within the extras/thold.sql file.

My copy of cacti db does not have this table either.

**Comment by cigamit** [comment]
This plugin needs a dusting and cleaning.

**Comment by cigamit** [comment]
Plus there are too many open issues.  After 1.1.36, we should table Cacti work for a bit and close out some of these thold issues.  There are a few feature requests that need addressing too.

**Comment by anarkia1976** [comment]
Thanks a lot as always for support.

**Comment by netniV** [comment]
You said that about automation too (which is an integrated plugin) ;-)

**Comment by cigamit** [comment]
So much to do, so little time.

**Comment by anarkia1976** [comment]
I have dropped sql table and now no problem so far. thanks a lot guys.

**Comment by netniV** [comment]
Dropped? Or Created?

**Comment by anarkia1976** [comment]
dropped and re-created.

**Comment by netniV** [comment]
@cigamit This still needs fixing even though the issue is closed.  @anarkia1976 fixed his problem, but the underlying issue of the _failed table missing still exists for other users.

**Comment by cigamit** [comment]
Reopening @ @netniV's request.

**Comment by netniV** [comment]
I've looked over the code and that table should be created during a new install or when upgrading from a version before 0.4.7.  So I'm reversing my decision to reopen this as it would appear to be a one off issue with a specific database and no one else appears to have had this.
