### ISSUE TITLE
Threshold Template "Operator Notes" Variable Not Properly Recognized.

### ISSUE THREAD

**Issue by chris-technicate** [Cacti/plugin_thold#153]
We use "Operator Notes" in each thold template.

Under Settings > Thresholds > Threshold Alert Message:
```
An Alert has been issued that requires your immediate attention:
<br>Device Notes:<DEVICENOTE>
<br>Threshold Notes:<NOTES>
<br><GRAPH>
```

Under Settings > Thresholds > Threshold Warning Message:
```
A warning has been issued that requires your attention:
<br>Device Notes:<DEVICENOTE>
<br>Threshold Notes:<NOTES>
<br><GRAPH>
```

After much troubleshooting I realize that is it NOT pulling the Threshold Template Operator Notes.

Recreate behavior by creating a device, add some notes, create a thold template, add some operator notes, and trigger the threshold.

In my example I created a graph on a device with a template and intentionally triggered. 
My device notes: "TEST NOTES IN DEVICE"
My thold template operator notes: "TEST NOTES IN THOLD TEMPLATE"

Email looks like this:
```
An Alert has been issued that requires your immediate attention:
Device Notes:TEST NOTES IN DEVICE
Threshold Notes:TEST NOTES IN DEVICE
Graph Image.png
```
It is quite important for us to be able to forward the operator notes as those contain the instructions, warnings, or other info to resolve that specific type of alert/warning.

Please help.

**Comment by cigamit** [comment]
This should be resolved now.  Before this change the &lt;NOTES&gt; tag was being replaced by the Device notes.  Now there is a new tag &lt;DNOTES&gt; for Device Notes and &lt;NOTES&gt; for Operator Notes.  Sorry for the confusion.

**Comment by cigamit** [comment]
Resolution was here https://github.com/Cacti/plugin_thold/commit/c581fbe7a1b26a69da1fd25c3ad441f74cf9eae0

**Comment by chris-technicate** [comment]
You sir are a rockstar!
Updated, tested and confirmed.

**Comment by chris-technicate** [comment]
Actually, I just noticed a potential issue. In my operator notes:

```
The average load of <CURRENTVALUE> Amps blah blah blah
```

The email:
```
The average load of Amps blah blah blah
```

Am I not allowed to use the descriptors?

**Comment by netniV** [comment]
It shouldn't be too hard to take the notes and apply the formatting to it, but there's a potential for a recursive loop.  So I think if it was to occur, it would have to be limited to static values and not fields that could be dynamically updated by an operator to cause an endless cascade (or maybe set a cascade limit)

**Comment by chris-technicate** [comment]
If a big deal I can modify my operator notes, but if a big and simple fix I would like to use them.

**Comment by cigamit** [comment]
Okay, last commit will allow Operator Notes to include tags as that can be embedded in the email body.
