### ISSUE TITLE
Threshold Template not propagating "Operator Notes"

### ISSUE THREAD

**Issue by chris-technicate** [Cacti/plugin_thold#157]
As referenced in a previous issue - we make heavy use of both templates and operator notes.

When updating operator notes on the template it does not propagate to the individual thresholds. 

Steps to recreate:
Change a template value, such as "High Threshold"
Head to Management > Thresholds, check all thresholds, in the action menu select "Propagate Template"
All applicable thresholds (which have propagation enabled) are now updated.

Follow the same steps with operator notes in the template, no changes are applied.

**Comment by cigamit** [comment]
Resolved now.
