### ISSUE TITLE
RPN Expressions not handling replacement of ifSpeed and ifHighSpeed' correctly

### ISSUE THREAD

**Issue by rojasneva** [Cacti/plugin_thold#160]
If I have a graph 0001 of device 0099 with a local_data_id 0050 and graph_template_id 2 and I create an aggregated graph which contains graph 0001, then a new graph_id is created 0111 with an item local_data_id 0050 but graph_template_id 0

When I apply the function 'Apply thresholds' to my device 0099, then a new threshold is created with my local_data_id (0050), but the local_graph_id used is 0111 instead of the original 0001 and the graph_template_id used is 0 instead of the original 2. Apparently this creates a conflict when evaluating the RPN expression because the field '|QUERY_IFHIGHSPEED|' could not be evaluated. I am sure my interface has a valid value and my poller information is updated.
I've corrected this problem editing all sql queries of the plugin to add the following condition graph_template_id>0

Long time Cacti user, first time open source contributor.

**Comment by netniV** [comment]
I'm not sure that was the right thing to do but I'm not an expert on this plugin.  The real question is what is bring in QUERY_IFHIGHSPEED as a field and where is it failing to evaluate.

Did you modify based on todays source? If so, there is an open pull request that I made which fixes more issues.  If not, then it would probably need to be reviewed again anyway.  If you make use of git for your source control you could submit a pull request / diff file which would help.

**Comment by rojasneva** [comment]
What I think is happening is that the plugin is trying to get the |QUERY_IFHIGHSPEED| based on the local_graph_id of the aggregated graph and this graph has no oids related to it. Everything I described could be seen in the the thold_data table.
I'll submit a pull request.

**Comment by cigamit** [comment]
This basically says create the threshold based upon the non-aggregated graph.  I guess I'm okay with this, though I'm sure people will make some remarks as to how they would rather see the breach on them.

I've got some big plans for thold.  Never enough time though.

**Comment by cigamit** [comment]
Should be resolved now if you update thold_functions.php.

**Comment by rojasneva** [comment]
The problem is not the replacement of ifSpeed with ifHighSpeed, the problem is that the threshold is created using the local_graph_id of the aggregated graph and as it cannot find any OID relationships associated with it, it fails.

**Comment by TheWitness** [comment]
@rojasneva, can you please provide the rrdtool graph syntax for this specific aggregate graph?  I just want to make sure that I have it right.

**Comment by TheWitness** [comment]
Also, please describe how you were able to create a threshold from an aggregate graph?

**Comment by rojasneva** [comment]
Sorry @TheWitness, I no longer use Cacti. But from my OP:
1. Create a graph for the device.
2. Create an aggregated graph using the graph just created and an arbitrary second graph.
3. Go to the device and run the 'Apply thresholds' function.
