### ISSUE TITLE
Plugins: Uninstall should come with a verification

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#164]
Uninstalling a plugin is very dangerous because it wipes all configuration data for a plugin if the plugin is written correctly.  Therefore, when uninstalling I think we should go to another page which shows a warning about this and requests a validation (either by typing the plugin name or a verification code).

This is to prevent issues when people are upgrading plugins and are new to the system not realising you shouldn't uninstall only disable (if at all).

**Comment by cigamit** [comment]
Yea, I saw the conversation.  Using jQuery dialog, this should be easy.  Ticket belongs in Cacti section though.

**Comment by netniV** [comment]
oops correct, I'll recreate.  Just been in thold all morning lol
