### ISSUE TITLE
Separate default filter value for status

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#167]
Status should have a separate default value depending on whether you are using the management tools, or the Threshold tab.  For the tab, you may wish to set the default to only show triggerred or breached items by default so you are just working with the problematic items.

However, if you set the default to be triggered or breached, this also affects the management tools on the console tab.  Which can instantly make you feel like you just lost all the thold data you built up, especially if you have nothing in breach at that time.

**Comment by cigamit** [comment]
I like the save button approach as is in the graphs page.  How about you?  It will save all the filter values that are currently set at the user level.

**Comment by netniV** [comment]
The should still be two separate defaults for the filters though.  I thought they did already save anywhere but they shouldn't cross contaminate as they are two different types of operation.  

Also, I have a minor issue with the graph filters in that if you want to have two tabs open with different trees, you settings from one tab directly affect the other (I can understand why though to reload them if a URL doesn't sett them) but that's why it's not normally recommended.
