### ISSUE TITLE
Suggested names does not work if no substitute variable used

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#168]
Not sure if this is a thold bug or cacti one but gonna assume thold for now.

if you create a threshold template such as 'Unix - Ping Host [ping]' which is the 'Unix - Ping Host' Data Template and ping field, you will then be able to create thresholds against your devices.  This usually puts the interface name into the suggested name and all works well.

If you take away any replacement strings, then you just end up with the field name.  Additionally, because the field name is in the template, it's also being applied at the threshold level too. And it doesn't even need to be a valid name!!

With substitute variable:
![screen shot 2018-02-24 at 19 31 05](https://user-images.githubusercontent.com/9052188/36634358-393b813e-199b-11e8-966e-3715d16b0e26.png)

Without substitute variable:
![screen shot 2018-02-24 at 19 12 51](https://user-images.githubusercontent.com/9052188/36634357-3797b762-199b-11e8-89f1-cf3f625c82f8.png)

**Comment by netniV** [comment]
I think there are three things that need fixing here:

- Remove duplication of field name
- Either 
   - Fix suggested name to display the original template name
   - Fix template name to always require a substitute variable
- Check any fieldname usage would be valid
   _Admittedly this may be harder than it sounds_

**Comment by cigamit** [comment]
Yea, the way it's doing it is crap.  Should just let the user pick what to name the damn thing.

**Comment by netniV** [comment]
Partial patch:
```diff
diff --git a/thold_functions.php b/thold_functions.php
index c1983af..79c78d0 100644
--- a/thold_functions.php
+++ b/thold_functions.php
@@ -2856,20 +2856,23 @@ function thold_format_name($template, $local_graph_id, $local_data_id, $data_sou
                LIMIT 1',
                array($local_data_id));

-       if (isset($template['name']) && strpos($template['name'], '|') !== false) {
+       $host_id = 0;
+       $snmp_query_id = 0;
+       $snmp_index = 0;
+       $template_name = isset($template['name']) ? $template['name'] : $desc;
+       if (strpos($template_name, '|') !== false) {
                $gl = db_fetch_row_prepared('SELECT *
                        FROM graph_local
                        WHERE id = ?',
                        array($local_graph_id));

                if (sizeof($gl)) {
-                       $name = expand_title($gl['host_id'], $gl['snmp_query_id'], $gl['snmp_index'], $template['name']);
-               } else {
-                       $name = $desc . ' [' . $data_source_name . ']';
+                       $host_id = $gl['host_id'];
+                       $snmp_query_id = $gl['snmp_query_id'];
+                       $snmp_index = $gl['snmp_index'];
                }
-       } else {
-               $name = $desc . ' [' . $data_source_name . ']';
        }
+       $name = expand_title($host_id, $snmp_query_id, $snmp_index, $template_name);

        return $name;
 }
```

**Comment by netniV** [comment]
Resolved.
