### ISSUE TITLE
 Plugin 'thold': Undefined variable: text in thold_functions.php  on line: 2759

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#169]
Guys with latest Thold commit I am getting undefined variables in the Log file when email alarm is generated, please see below log:

2018/02/24  22:54:55 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold_process.php: 280  thold_check_threshold)(/plugins/thold/thold_functions.php: 1929  get_thold_alert_text)(/plugins/thold/thold_functions.php: 2814  thold_replace_threshold_tags)(/plugins/thold/thold_functions.php: 2766  CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)
--
2018/02/24 22:54:55 - ERROR PHP NOTICE in   Plugin 'thold': Undefined variable: thold_types in file:  /var/www/html/plugins/thold/thold_functions.php  on line: 2766
2018/02/24 22:54:55 - CMDPHP PHP ERROR NOTICE  Backtrace: (/plugins/thold/thold_process.php: 280  thold_check_threshold)(/plugins/thold/thold_functions.php: 1929  get_thold_alert_text)(/plugins/thold/thold_functions.php: 2814  thold_replace_threshold_tags)(/plugins/thold/thold_functions.php: 2759  CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)
2018/02/24 22:54:55 - ERROR PHP NOTICE in   Plugin 'thold': Undefined variable: text in file:  /var/www/html/plugins/thold/thold_functions.php  on line: 2759

**Comment by cigamit** [comment]
Should be solved now.  Sorry about that one.

**Comment by ikorzha** [comment]
Thank you so much for a fast fix, applied it testing now, Will reopen if anything....
