### ISSUE TITLE
THOLD device up down notification

### ISSUE THREAD

**Issue by chathurag** [Cacti/plugin_thold#172]
\<DATE\>not printed in sent email if the device rebooted

**Comment by chathurag** [comment]
<DATE> is not working any more for up or down notifications

**Comment by chathurag** [comment]
"<DATE>"

**Comment by netniV** [comment]
When you say not printed, do you mean it needs adding to the template or that it is not replaced when the email is sent?

**Comment by chathurag** [comment]
We have used the above option to get Device up or down notification sent to email. But when we use \<DATE\> in the message to be sent, as the device get rebooted Current time stamp is not sent with the message.

**Comment by netniV** [comment]
If I remember rightly, reboot notifcations are actually sent by the plugin Monitor?  Do you have that installed?

**Comment by chathurag** [comment]
My concern is when device is rebooted THOLD should be sending device down notification, when device comes up THOLD should send device up notification and Monitor should also send a device rebooti notification if configured. But in the device down notification and device up notification when we include \<DATE\> email is sent with blank space.

**Comment by netniV** [comment]
That is done at https://github.com/Cacti/plugin_thold/blob/18ea534d6aa247c297c5b97306e3fd9dff3b1bf3/thold_functions.php#L2790

My only thought is that the format isn't right for the date command or just isn't defined.  If it's the latter, we can put a check in and force a default format which is better than no format.

**Comment by chathurag** [comment]
It only sends a space in email. not the current timestamp

**Comment by netniV** [comment]
Then one of two things isn't happening on your system, either the date field is not within the $text field, or the CACTI_DATE_TIME_FORMAT is not defined.  Do you have any undefined constant warnings?  Can you put any debug statements in before that line to check both $text and CACTI_DATE_TIME_FORMAT ?

Something like:
```php
$tempOutput = 'Format: ';
$tempOutput .= CACTI_DATE_TIME_FORMAT;
$tempOutput .= " Text:\n";
$tempOutput .= $text;
file_put_contents('/tmp/thold.log',"$temp\n\n",FILE_APPEND);
```
Then check the thold.log file where you should see a block starting with 'Format:' and finishing with a blank line to separate the blocks.  That is so that it's easier to distinguish between them as $text can be multi-line.

**Comment by netniV** [comment]
Have you managed to try tracking down the reason @chathurag ?

**Comment by chathurag** [comment]
when device does down (power or connectivty) the \<DATE\> is is not used.

PLease find the config and recieved message.

\<DESCRIPTION\> (\<HOSTNAME\>) is DOWN at \<DATE\>

Device (x.x.x.x) is DOWN at <=> date is missing

**Comment by netniV** [comment]
I'm still waiting on the information to be able to verify this, as per my above comments.  There is not much further I can do as I can't see a reason for it without the additional debug information.

**Comment by Saat1994** [comment]
hi i get this issue.. need help .. already config smtp but not get the alert
