### ISSUE TITLE
Thold not polling interface UP/Down state. 

### ISSUE THREAD

**Issue by jagmeetbhinder** [Cacti/plugin_thold#176]
I have configured interface operation status graphs to my Cacti Installation. Graphs are reporting correct UP/Down status however THOLD is not sending interface alerts.

I noticed empty value under Threshold page. I have 162 threshold configured.

**Comment by netniV** [comment]
Are there any errors in the logs?

**Comment by netniV** [comment]
What type of thresholds are these? Time-based?

**Comment by jagmeetbhinder** [comment]
No issues in the logs. These are interface operational status. yes these are time based.
Graphs are reporting correct number (1 and 2) however threshold are not triggering.

**Comment by netniV** [comment]
Are all other Thresholds working?  Is the Threshold enabled?  What values are you seeing when you debug the datasource in question and what settings do you have for the Threshold?

**Comment by jagmeetbhinder** [comment]
Thanks for quick response. much appreciated.

here is the log entry. 
- SYSTEM THOLD DAEMON STATS: TotalTime:0.000 MaxRuntime:0.000 Processed:0 InProcess:1620 TotalDevices:237 DownDevices:0 NewDownDevices:0 MaxProcesses:20 Completed:0 Running:0 Broken:0  

Attached are the settings. 
[Threshold template.docx](https://github.com/Cacti/plugin_thold/files/1865926/Threshold.template.docx)

**Comment by jagmeetbhinder** [comment]
Yes all other threshold are working device up/down alerts are fine.

**Comment by jagmeetbhinder** [comment]
Issue is resolved by upgrading the thold to latest version. Thanks for looking into this issue.

SYSTEM THOLD DAEMON STATS: TotalTime:0.512 MaxRuntime:0.119 Processed:162 InProcess:0 TotalDevices:237 DownDevices:0 NewDownDevices:0 MaxProcesses:20 Completed:12 Running:0 Broken:0
