### ISSUE TITLE
Increase size for RPN expressions

### ISSUE THREAD

**Issue by nanonettr** [Cacti/plugin_thold#177]
I have a very long rpn expression (462 chars). I manually modified tables.
Could you increase thold_data, expression and thold_template, expression further, like 512 chars?

ref: https://github.com/Cacti/plugin_thold/issues/61

**Comment by netniV** [comment]
I have added this ready for the next release.  As you've already modified your own tables, I'll wait for more changes to come before making a new release.

Committed change: https://github.com/Cacti/plugin_thold/commit/f32ac92ce3cea154d25395ddd6af14a403757250

**Comment by nanonettr** [comment]
thanks
