### ISSUE TITLE
Graph template not found if first data source in rrd not used

### ISSUE THREAD

**Issue by nanonettr** [Cacti/plugin_thold#178]
Hello,
I had a problem while defining a new threshold.
There were 8 sources in data template and some of them; including first one; was not used in graph template.

When i assign the threshold template to graph, i found the following error in clog;
`ERROR PHP NOTICE in Plugin 'thold': Undefined index: graph_template_id in file: /usr/local/share/cacti/plugins/thold/thold_webapi.php on line: 83`

Because of graph_template_id is empty i had problems like enabling/disabling propagation, deleting threshold.

As a workaround i edited /usr/local/share/cacti/plugins/thold/thold_webapi.php;
```
        if (count($existing) == 0 && count($template)) {
                if ($local_graph_id) {
                        // $rrdlookup = db_fetch_cell("SELECT id FROM data_template_rrd WHERE local_data_id=$local_data_id ORDER BY id LIMIT 1");
                        // $grapharr  = db_fetch_row("SELECT graph_template_id FROM graph_templates_item WHERE task_item_id=$rrdlookup AND local_graph_id = $local_graph_id");
                        $grapharr  = db_fetch_row("SELECT graph_template_id FROM graph_templates_item WHERE local_graph_id = $local_graph_id LIMIT 1");

                        $desc = db_fetch_cell_prepared('SELECT name_cache FROM data_template_data WHERE local_data_id = ? LIMIT 1', array($local_data_id));
```

I did not create a patch because i do not know if this workaround create other problems.

**Comment by netniV** [comment]
Which version of thold are you using?

**Comment by nanonettr** [comment]
thold version 1.0.4

**Comment by TheWitness** [comment]
This is resolved in the latest develop.  Keeping open for a time.
