### ISSUE TITLE
support U value

### ISSUE THREAD

**Issue by nanonettr** [Cacti/plugin_thold#179]
One of my datasources returns "U" for Unknown/Undefined value. Current thlod 1.0.4 does not support this and throws error.

```
2018/04/01 23:55:04 - THOLD ERROR: RPN Expression is invalid! THold:'Server - CPU Status [CPUIdle]', Value:'212.14333333333', Expression:'|ds:CPUIdle|,|ds:CPUWait|,+,|ds:CPUGuest|,UN,0,|ds:CPUGuest|,IF,|ds:CPUGuestNice|,UN,0,|ds:CPUGuestNice|,IF,+,|ds:CPUSteal|,UN,0,|ds:CPUSteal|,IF,+,|ds:CPUIdle|,|ds:CPUWait|,+,+,|ds:CPUNice|,|ds:CPUGuestNice|,UN,0,|ds:CPUGuestNice|,IF,-,+,|ds:CPUSystem|,|ds:CPUIRQ|,+,|ds:CPUIRQSoft|,+,+,|ds:CPUUser|,|ds:CPUGuest|,UN,0,|ds:CPUGuest|,IF,-,+,/,100,*', Processed:'118187161,1552289,+,U,UN,0,U,IF,U,UN,0,U,IF,+,U,UN,0,U,IF,+,118187161,1552289,+,+,9420,U,UN,0,U,IF,-,+,6473268,839522,+,1383394,+,+,45099548,U,UN,0,U,IF,-,+,/,100,*'
2018/04/01 23:55:04 - THOLD WARNING: Unsupported Field 'U'
```

I added supoort for U, and going to create a request.

**Comment by netniV** [comment]
As a standard RPN expression, I don't think U is normally in there.  A datasource only tends to return U when it was unable to get the data, but that isn't normally stored in the cacti RRD's.  Are you saying you actually end up with U in the data file?

**Comment by nanonettr** [comment]
My SNMP query returns error on old liux kernels.
```
snmpwalk -c public -v 2c 192.168.1.175 .1.3.6.1.4.1.2021.11.64
iso.3.6.1.4.1.2021.11.64 = No Such Object available on this agent at this OID
```

on cactis datasource debug page;
DS:CPUSteal:COUNTER:600:0:U
and info page;
CPUSteal	COUNTER	600	0	NaN	U	NaN	3

![screenshot_20180402_012215](https://user-images.githubusercontent.com/2301231/38178118-95a804c0-3614-11e8-94d4-9e1b4f6b8bae.png)

**Comment by netniV** [comment]
That would really suggest a problem with the population of the data source.  As a numeric datasource you should never see U but instead NaN. At least that was my understanding of things.

**Comment by netniV** [comment]
If you debug the graph in question around time you received no data, you should see output similar to the following.  Is that what you saw?

![screen shot 2018-04-02 at 00 04 49](https://user-images.githubusercontent.com/9052188/38178372-8c6f66e2-3609-11e8-9f34-558716028779.png)

**Comment by nanonettr** [comment]
yes.

![screenshot_20180402_021255](https://user-images.githubusercontent.com/2301231/38178439-a9d1518e-361b-11e8-9ba9-ebc01283f772.png)

**Comment by nanonettr** [comment]
i made some tests and the issue is not the U value as i guessed before.

this issue is invalid. closing.
