### ISSUE TITLE
UP/DOWN notification should be a threshold rule type

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#183]
Up and down notifications should really be part of Threshold not the core cacti.  If these were a rule type, they would also be logged in the Threshold breach logs.

**Comment by TheWitness** [comment]
This is already partially implemented in thold.  I guess this falls more along the lines of what we had planned for the next gen thold.

**Comment by TheWitness** [comment]
I'm going to close this as by the time we have all the outstanding feature implemented we will have done this multiple times over.
