### ISSUE TITLE
data source value wrong if data source name is in mixed case

### ISSUE THREAD

**Issue by nanonettr** [Cacti/plugin_thold#184]
my datasource name is in mixed case. thold can not find its value and defaults to first value in template.

i traced it and problem is the array_search function; it is case sensitive.
cause of the problem is in **get_current_value** function on line;
`$idx = array_search($data_template_rrd_id, $result['data_source_names']);`

i changed it to resolve the problem;
`$idx=array_search($data_template_rrd_id, array_map('strtolower', $result['data_source_names']));`

some debug information from clog;
> 2018/04/07 18:35:13 - CMDPHP stack[0]: 2041324
> 2018/04/07 18:35:13 - CMDPHP expression: 2041324,0,+
> 2018/04/07 18:35:13 - CMDPHP return(round(value, 4)): 2041324
> 2018/04/07 18:35:13 - CMDPHP result[values][idxTEST][0]: 2041324
> **2018/04/07 18:35:13 - CMDPHP idx: result[values][][0]: 573638.93333
> 2018/04/07 18:35:13 - CMDPHP idx:**
> 2018/04/07 18:35:13 - CMDPHP idxTEST: result[values][4][0]: 2041324
> 2018/04/07 18:35:13 - CMDPHP idxTEST: 4
> 2018/04/07 18:35:13 - CMDPHP result[values][7][1]: 0
> 2018/04/07 18:35:13 - CMDPHP result[values][7][0]: 2041324
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][7]): 0,1
> 2018/04/07 18:35:13 - CMDPHP result[values][6][0]: 0
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][6]): 0
> 2018/04/07 18:35:13 - CMDPHP result[values][5][0]: 0
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][5]): 0
> 2018/04/07 18:35:13 - CMDPHP result[values][4][0]: 2041324
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][4]): 0
> 2018/04/07 18:35:13 - CMDPHP result[values][3][0]: 354997.70667
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][3]): 0
> 2018/04/07 18:35:13 - CMDPHP result[values][2][0]: 354997.70667
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][2]): 0
> 2018/04/07 18:35:13 - CMDPHP result[values][1][0]: 77481.066667
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][1]): 0
> 2018/04/07 18:35:13 - CMDPHP result[values][0][0]: 573638.93333
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values][0]): 0
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[values]): 0,1,2,3,4,5,6,7
> 2018/04/07 18:35:13 - CMDPHP result[timestamp][end_time]: 1523115300
> 2018/04/07 18:35:13 - CMDPHP result[timestamp][start_time]: 1523115000
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[timestamp]): start_time,end_time
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][7]: nth_percentile_maximum
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][6]: nanoSwapTotal
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][5]: nanoSwapFree
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][4]: nanoMemoryTotal
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][3]: nanoMemoryFree
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][2]: nanoVirtualFree
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][1]: nanoMemoryBuffer
> 2018/04/07 18:35:13 - CMDPHP result[data_source_names][0]: nanoMemoryCache
> 2018/04/07 18:35:13 - CMDPHP array_keys(result[data_source_names]): 0,1,2,3,4,5,6,7
> 2018/04/07 18:35:13 - CMDPHP array_keys(result): data_source_names,timestamp,values
> 2018/04/07 18:35:13 - CMDPHP data_template_rrd_id: nanomemorytotal
> 2018/04/07 18:35:13 - CMDPHP local_data_id: 1202
> 2018/04/07 18:35:13 - CMDPHP call: get_current_value()
> 2018/04/07 18:35:13 - CMDPHP sizeof(thold_item): FALSE
> 2018/04/07 18:35:13 - CMDPHP thold[expression]: |ds:nanoMemoryTotal|,0,+
> 

ps: possibly related to https://github.com/Cacti/plugin_thold/issues/74

**Comment by TheWitness** [comment]
Can you please test with the latest develop?  Note the following commit log for the scope of the changes:  https://github.com/Cacti/plugin_thold/commit/0ad5286c970b90dbaac68a74ba910665853e2e71
