### ISSUE TITLE
Baseline deviation with exact changes

### ISSUE THREAD

**Issue by nanonettr** [Cacti/plugin_thold#185]
Hi,

I am monitoring pings and want to set thresholds for ping changes.
But some devices pings are between 1-50 ms and other devices are 80-130 ms. I do not want to get an alert if change is smaller than 50ms.

In current version (1.0.4), i have to create a different threshold for every device.

If there is an option to calculate exact difference instead of percentage, i can use a single template.

Could you add an option for this?

**Comment by TheWitness** [comment]
Switching to 1.6 milestone.  Not enough time.

**Comment by TheWitness** [comment]
Took several years, but fixed.
