### ISSUE TITLE
THOLD ERROR: Sending Email Failed. Error was SMTP connect() failed.

### ISSUE THREAD

**Issue by maguayver** [Cacti/plugin_thold#186]
Guys, good night.
I configured Cacti 1.1.37 to send mail in the settings tab - mail / reporting / dns and /thresholds but it gives an error and does not send the email notifying that the host is offline or when it came back online.
I already consulted PHPMailer but I do not know where to configure it.
Can someone help me?
My Settings:

Mail Services SMTP
Ping Mail Server Yes
From Email Address myemail@gmail.com
From Name Cacti Server Monitor
Word Wrap 120
SMTP Hostname smtp.gmail.com
SMTP Port 465
SMTP Username myemail
SMTP Password ****
SMTP Security  SSL
SMTP Timeout  10

Thank you.

**Comment by netniV** [comment]
This should be opened on the main cacti repository really since this is to do with the core mailer setup.  I have test program which may help you see the results of the issue I can post here tonight.
