### ISSUE TITLE
Standalone Thresholds created do not read graph data due to threshold daemon not running

### ISSUE THREAD

**Issue by g1augusto** [Cacti/plugin_thold#187]
Hi Everyone,

I have noticed and I think reported already that thold plugin is not reading any data from the graph it should refer to,

I set up some standalone thresholds and the **current** column is always null, no data is read from the graphs, is this only my problem or is this a bug?

![image](https://user-images.githubusercontent.com/26431888/38896516-3644e954-4293-11e8-8fc8-8d7b1cfc947f.png)

**Comment by netniV** [comment]
I won't be able to get to this tonight.  But I will get you some SQL to debug why it believes there is no current value.

**Comment by g1augusto** [comment]
It seems that it happens only when the **Enable Threshold daemon** option is enabled, I tried without it on my test cacti and it's reading data

![image](https://user-images.githubusercontent.com/26431888/38898748-35d25f08-4296-11e8-9510-b785951b3709.png)

**Comment by netniV** [comment]
OK, good to know as that will help narrow down were to look.

**Comment by g1augusto** [comment]
Thanks, 

would be good if the operator notes would be sent in the alerting email too.

I will open a new issue in case you need, but I think I already opened that some time ago.

Good night!

**Comment by netniV** [comment]
I believe that @chris-technicate had already raised that as an issue and had it fixed.

**Comment by g1augusto** [comment]
Just to let you know that I tried again with version 1.0.6 on CACTI 1.1.38 with BOOST active and the dedicated daemon it does not read values from data sources, disabling the daemons works regularly.

**Comment by netniV** [comment]
Yeah I found that the daemon does not seem to be working.  There will be a reason but I haven't had time to investigate why.  It may even be that the daemon expects to be manually put in a cron task.

**Comment by TheWitness** [comment]
The Daemon needs to be either a respawn type systemd process not so much cron.  There is a thold_daemon.service file included in the thold directory, though looking at it, there are some updates that need to be made.  For example, it's not a ReSpawn type and it's set to "simple" and not forking.

**Comment by TheWitness** [comment]
Okay, I have resolved this by adding documentation in the README.md.  In addition, you will be notified by Cacti if you have elected to use the daemon and not enabled it.

I left the systemd documentation brief in that someone who uses Cacti should already know how to install a simple systemd script.  I also added the Restart=always, RestartSec=0, and changed the type to 'forking'.
