### ISSUE TITLE
Automation doesn't create all tholds

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#189]
My version 1.1.37
I have Device template with Interface errors tholds (error in, error out, discard in, discard out):
![cacti_problem_1](https://user-images.githubusercontent.com/26485719/39427792-5ede7f78-4c85-11e8-9094-6c8767316a29.png)

Thold definition:
![cacti_problem_1 5](https://user-images.githubusercontent.com/26485719/39427798-62d63f94-4c85-11e8-9c71-b3fe7e247171.png)

Automations works well (discovery device, add, create graphs), but if I do "Apply threshold" on switch, only one thold is created (errors in, missing errors out and both discards)
![cacti_problem_3](https://user-images.githubusercontent.com/26485719/39427800-66936dbe-4c85-11e8-901c-0552a15d8187.png)

**Comment by anarkia1976** [comment]
Can you try to update to 1.1.38, a lot of bug is fixed ... Personally tested.

**Comment by xmacan** [comment]
Update  to 1.1.38 and thold_plugin to 1.0.4 solved my problem. Thank you
