### ISSUE TITLE
Threshold created but can not get the last value 

### ISSUE THREAD

**Issue by hel2o** [Cacti/plugin_thold#19]
![default](https://cloud.githubusercontent.com/assets/14226648/21253810/3ae8450e-c39c-11e6-9eab-9188f28614f8.png)
![default](https://cloud.githubusercontent.com/assets/14226648/21257094/03a1e2f2-c3b1-11e6-83d6-c80d6e1200ea.png)
why thold dont run

**Comment by cigamit** [comment]
Are you sure this is not some other issue?  What do your http error logs contain?  Are there any messages in your cacti log?

**Comment by hel2o** [comment]
The reason is that i chose Enable Threshold Daemon !!!!

**Comment by cigamit** [comment]
So, did this resolve itself once you started the daemon?

**Comment by hel2o** [comment]
yes，
