### ISSUE TITLE
Threshold templates

### ISSUE THREAD

**Issue by rcsmota** [Cacti/plugin_thold#191]
Hi;
When I try create a template direct of graph like this
![image](https://user-images.githubusercontent.com/31240306/40053003-97b5497c-5837-11e8-81c9-d864234e8b09.png)

Its is just ignored and create a standalone threshold.

**Comment by netniV** [comment]
Can you give me the exact steps you are doing so I can reproduce?

**Comment by rcsmota** [comment]
Hi @netniV ;

Sure

In graph tab

![image](https://user-images.githubusercontent.com/31240306/40100972-d136a2a8-58dd-11e8-8478-1b29d85eef59.png)

In some graph click in Create New Threshold (Blank page with red signal)

![image](https://user-images.githubusercontent.com/31240306/40101034-0084ebb4-58de-11e8-8460-40a817ace8ba.png)

Select create a Threshold template

![image](https://user-images.githubusercontent.com/31240306/40101087-32776cfa-58de-11e8-8df8-e7c0a0768549.png)

Select Data source and create

![image](https://user-images.githubusercontent.com/31240306/40101307-f6255a68-58de-11e8-99cc-a62263cc4464.png)

instead of creating a template it creates a threshold for selected graph.

![image](https://user-images.githubusercontent.com/31240306/40101382-2bbe18f4-58df-11e8-98f1-7697c20b8db8.png)

Thanks

**Comment by rcsmota** [comment]
Hi @netniV 

Another detail, I'm using the last version 1.0.5 but in another environment I have a 1.0.3 and it work fine.

**Comment by netniV** [comment]
I believe that this is related to #199 where it is actually associated but does not display the association properly, and as I'm about to submit the fix for that I'm going to close this.
