### ISSUE TITLE
thold and monitor 

### ISSUE THREAD

**Issue by Initarts** [Cacti/plugin_thold#194]
[cacti.docx](https://github.com/Cacti/plugin_thold/files/2042236/cacti.docx)
![thold-2](https://user-images.githubusercontent.com/8800508/40582068-96269e12-619c-11e8-93ff-cffae90427fc.jpg)
![cdef](https://user-images.githubusercontent.com/8800508/40582069-96726752-619c-11e8-8520-8082473cbb3d.jpg)
![thold-1](https://user-images.githubusercontent.com/8800508/40582070-96b729fa-619c-11e8-80ce-c37e7073206a.jpg)

Now the problem is that the monitor interface can send a normal alarm mail, the report interface can also send mail, and then thold traffic monitoring here does not work, testing a number of versions of the cacti, thold are the latest version, every time here can not go, it is impossible to achieve traffic alarm function, demand the help of the author help

**Comment by cigamit** [comment]
Are these datasources updated outside of Cacti?  Thold pulls the information during the polling cycle.  We would need a lot more information before we could diagnose the issue.
