### ISSUE TITLE
Thresholds not created by device. Cant create with creation wizard either.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#196]
(Thold 1.0.5) If I go to Devices and select a network switch with many interface status graphs and select apply thresholds nothing happens (checked with thold debug enabled and I never see a job). If I go to the individual graph and select create threshold, it will be created correctly. Also when I try to use the threshold management/creation wizard I cannot select the required devices because the device list drop down only shows the top 30 devices.

**Comment by netniV** [comment]
Do you have any Threshold templates setup? If not, it won't be able to apply them automatically.

**Comment by jdcoats** [comment]
yes I have a template for interface status. I can create the thold from the graph by selecting the temple.

**Comment by jdcoats** [comment]
I can create the thresholds in bulk using the graph management page

**Comment by netniV** [comment]
What version of Cacti are you using?

**Comment by jdcoats** [comment]
1.1.38

**Comment by jdcoats** [comment]
btw the part about the device list drop down only shows the top 30 devices exists on the create graphs page too. So its cacti specific and not the plugin.

**Comment by netniV** [comment]
Sorry, didn't see that separate issue, but the device drop is actually an autocomplete drop down, so as you type the name of the device you are after, you will slowly filter the results to the one you want.  This was done in 1.1 to allow the UI to be responsive (and is configurable via the settings).

**Comment by jdcoats** [comment]
Ah! I've been enlightened! That does work :) Thanks, but the automation of template creation still doesn't seem to work as expected. I don't guess its a deal breaker since the "old" way of creating them from the graphs page does still work.

**Comment by netniV** [comment]
So, it seems that people can easily get confused between which graph and which data source is being used.  I did this myself during a load of testing tonight.  If your device has a template, the threshold template can be associated to it.  If you don't actually have the graph that is linked to the data source the threshold template uses, nothing will be created.

**Comment by jdcoats** [comment]
Confused seems to be an understatement to me. If I can go to graphs and create thresholds  for x using template y then why wouldn’t  going to tholds and creating them do the same thing?

Sent from my iPhone X

On Aug 21, 2018, at 9:10 PM, Mark Brugnoli-Vinten <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION! This email came from outside Tallahassee Memorial HealthCare. Exercise extra caution clicking links and opening attachments from any and all senders.


________________________________

So, it seems that people can easily get confused between which graph and which data source is being used. I did this myself during a load of testing tonight. If your device has a template, the threshold template can be associated to it. If you don't actually have the graph that is linked to the data source the threshold template uses, nothing will be created.

**Comment by netniV** [comment]
Because the names displayed on Templates are actually data source names, not graph names.

**Comment by netniV** [comment]
Is this still an issue?  If so, can you just let me know what I should be looking at as I'm not really clear whether anything is outstanding?

**Comment by jdcoats** [comment]
I'm still having trouble understanding this because It does not appear to work the way previous versions did. I "think" that I could go to devices, select the specific devices that I wanted to apply thresholds to and the thresholds would be created. This is not the case for me anymore. I can however go to graphs and select the graphs and create the thresholds.

**Comment by netniV** [comment]
OK, sorry, my misunderstanding on that.  Yes, you should be able to select a device and apply thresholds but only if that device is part of a template that has thresholds in it.

**Comment by jdcoats** [comment]
Thanks, please close this issue, I was missing the part about associating the device template to the threshold template.

Dan
