### ISSUE TITLE
No graphs after enabling Thold

### ISSUE THREAD

**Issue by dhavalsoni88** [Cacti/plugin_thold#2]
I am currently using Cacti 1.0.0 (from git). After enabling this plugin I am getting below errors from cacti.log and also rrdtool is unable to generate graphs. In other words after enabling Thold we are not able to generate graphs and getting below logs in cacti.log.
I am using php: 7.0, cacti: 1.0.0, DB: MariaDB 5.5.47. Apache:2.4.
Can you help me to sort this issue out?

06/08/2016 06:55:02 AM - CMDPHP SQL Backtrace: (/graph_json.php: 143 rrdtool_function_graph)(/lib/rrd.php: 2005 api_plugin_hook_function)(/lib/plugins.php: 114 thold_rrd_graph_graph_options)(/plugins/thold/setup.php: 346 db_fetch_assoc)(/lib/database.php: 296 db_fetch_assoc_prepared)(/lib/database.php: 335 cacti_debug_backtrace)
06/08/2016 06:55:02 AM - CMDPHP ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND type = 0 and time > 1465363499 and time < 1465365301' at line 1
06/08/2016 06:55:02 AM - CMDPHP ERROR: SQL Assoc Failed!, Error:1064, SQL:"SELECT time, status FROM plugin_thold_log WHERE local_graph_id = AND type = 0 and time > 1465363499 and time < 1465365301"

**Comment by cigamit** [comment]
https://github.com/Cacti/plugin_thold/commit/37e4eafc100383993b2a84f1212ad37faa60b4f8
I added this, but its just a bandaid really, need to figure out why graph_json isn't passing the graph id.

**Comment by dhavalsoni88** [comment]
Thanks "cigamit", I'll try to update my plugin with 37e4eaf, and will keep you updated.

**Comment by dhavalsoni88** [comment]
Sorry cigamit, even after updating plugin to 37e4eaf, it have same issue, no graphs are generating after enabling newer version of thold plugin.

getting below logs:

06/09/2016 10:33:30 AM - CMDPHP SQL Backtrace: (/plugins/thold/notify_lists.php: 61 edit)(/plugins/thold/notify_lists.php: 623 tholds)(/plugins/thold/notify_lists.php: 917 get_allowed_thresholds)(/plugins/thold/thold_functions.php: 948 db_fetch_cell)(/lib/database.php: 182 db_fetch_cell_prepared)(/lib/database.php: 227 cacti_debug_backtrace)
06/09/2016 10:33:30 AM - CMDPHP ERROR: SQL Cell Failed!, Error: Column 'notify_warning' in where clause is ambiguous
06/09/2016 10:33:30 AM - CMDPHP ERROR: SQL Cell Failed!, Error:1052, SQL:"SELECT COUNT(*) FROM ( SELECT uap0.user_id AS user0, uap1.user_id AS user1, uap2.user_id AS user2 FROM thold_data AS td INNER JOIN graph_local AS gl ON gl.id=td.local_graph_id LEFT JOIN graph_templates AS gt ON gt.id=gl.graph_template_id LEFT JOIN host AS h ON h.id=gl.host_id LEFT JOIN thold_template AS tt ON tt.id=td.thold_template_id LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1) LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3) LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4) WHERE (notify_warning=1 OR notify_alert=1) HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ) AS rower"
06/09/2016 10:33:30 AM - CMDPHP SQL Backtrace: (/plugins/thold/notify_lists.php: 61 edit)(/plugins/thold/notify_lists.php: 623 tholds)(/plugins/thold/notify_lists.php: 917 get_allowed_thresholds)(/plugins/thold/thold_functions.php: 931 db_fetch_assoc)(/lib/database.php: 296 db_fetch_assoc_prepared)(/lib/database.php: 335 cacti_debug_backtrace)
06/09/2016 10:33:30 AM - CMDPHP ERROR: SQL Assoc Failed!, Error: Column 'notify_warning' in where clause is ambiguous
06/09/2016 10:33:30 AM - CMDPHP ERROR: SQL Assoc Failed!, Error:1052, SQL:"SELECT td.*, tt.name AS template_name, uap0.user_id AS user0, uap1.user_id AS user1, uap2.user_id AS user2 FROM thold_data AS td INNER JOIN graph_local AS gl ON gl.id=td.local_graph_id LEFT JOIN graph_templates AS gt ON gt.id=gl.graph_template_id LEFT JOIN host AS h ON h.id=gl.host_id LEFT JOIN thold_template AS tt ON tt.id=td.thold_template_id LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1) LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3) LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4) WHERE (notify_warning=1 OR notify_alert=1) HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ORDER BY thold_alert DESC LIMIT 0, 30"

**Comment by cigamit** [comment]
the errors above are not related to graphing stopping.  latest notify_lists.php solves the sql error.

**Comment by dhavalsoni88** [comment]
I will try to use new plugin and keep you updated.

**Comment by dhavalsoni88** [comment]
No, its still not graphing

**Comment by dhavalsoni88** [comment]
Any update on this?

**Comment by cigamit** [comment]
please update php.ini, and set the following variable error_log=/tmp/php_errors.log.  restart apache, and let your web server run, and then upload the php_errors.log.  it is likely your plugin causing this issue.

**Comment by dhavalsoni88** [comment]
Thanks for your update. here is my current php.ini


[php.zip](https://github.com/Cacti/plugin_thold/files/310800/php.zip)

**Comment by cigamit** [comment]
you did not do what was asked of you.  please read again.

**Comment by dhavalsoni88** [comment]
I have done what you've asked to me to do:
1. Set the variable "error_log=/tmp/php_errors.log" in php.ini
2. Restarted the apache
I've sent you the updated 'php.ini' to you.

its stared graphing even after enabling thold plugin however, I am attaching the php_error.log file with this comment.

[php_errors.zip](https://github.com/Cacti/plugin_thold/files/313607/php_errors.zip)

**Comment by cigamit** [comment]
by reviewing the error_log, it's clear that the nwmon plugin is the root of your problems.  I'll go ahead and close this.
