### ISSUE TITLE
[Core 1.2.0] Save message shown as successfully when failed

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#200]
![image](https://user-images.githubusercontent.com/9052188/44392116-59955080-a529-11e8-89f0-f2f51b2ad222.png)

Steps to reproduce:
1. Create empty threshold
2. Set alert duration to 1 minute
3. Save the form

Changed settings are wiped out  Weirdly, you CAN set the warning duration without values.

**Comment by netniV** [comment]
I suspect that this may be down to the message type being used.  'thold_message' is a generic message type, but if it's a warning/error, it should have the 'error' type set, so may need 'thold_message' for general issues and 'thold_error' for problematic issues.

**Comment by TheWitness** [comment]
This is resolved in the development branch now.  Note, Cacti 1.2 will be required to update.
