### ISSUE TITLE
thold 1.0.3 PHP ERROR WARNING Backtrace

### ISSUE THREAD

**Issue by ISekan** [Cacti/plugin_thold#202]
22-Aug-2018 10:22:20 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 723 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 thold_poller_bottom)(/plugins/thold/includes/polling.php: 35 thold_check_all_thresholds)(/plugins/thold/includes/polling.php: 251 thold_check_threshold)(/plugins/thold/thold_functions.php: 1685 thold_mail)(/plugins/thold/thold_functions.php: 3546 CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
22-Aug-2018 10:22:20 - ERROR PHP WARNING in Plugin 'thold': Illegal string offset 'User-Agent' in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 3546
22-Aug-2018 10:22:20 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 723 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 thold_poller_bottom)(/plugins/thold/includes/polling.php: 35 thold_check_all_thresholds)(/plugins/thold/includes/polling.php: 251 thold_check_threshold)(/plugins/thold/thold_functions.php: 1685 thold_mail)(/plugins/thold/thold_functions.php: 3545 CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
22-Aug-2018 10:22:20 - ERROR PHP WARNING in Plugin 'thold': Illegal string offset 'X-Mailer' in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 3545

**Comment by netniV** [comment]
Try downloading the latest development version

**Comment by ISekan** [comment]
How I can save my old Thresholds settings?

**Comment by netniV** [comment]
By not uninstalling the old version.  Just copy over the top.

**Comment by ISekan** [comment]
does plugin need to stop or just replace files in thold dir?

**Comment by netniV** [comment]
Just replaced

**Comment by ISekan** [comment]
what does thold/extras/upgrade.php ?

**Comment by ghost** [comment]
I can't install Thold in my cacti

**Comment by ISekan** [comment]
## Installation

To install the plugin, simply copy the plugin_thold directory to Cacti's plugins directory and rename it to simply 'thold'.  Once this is complete, goto Cacti's Plugin Management section, and Install and Enable the plugin.  Once this is complete, you can grant users permission to view and create Thresholds.

Once you have installed thold, you should verify that Email support is functioning in Cacti by going to Cacti's Console and under Configuration select Settings, and from there the 'Mail/Reporting/DNS'.  From there, you can test your mail settings to validate that users will receive notifications via email.

After you have completed that, you should goto the 'Thresholds' Settings tab, and become familiar with its settings.  From there, you can provide overall control of thold, and set defaults for things like Email bodies, weekend exemptions, alert log retention, logging, etc.

As with much of Cacti, settings should be documented in line with the actual setting.  If you find that any of these settings are ambiguous, please create a pull request with your proposed changes.

**Comment by ghost** [comment]
I did it with PUTTY. I copied it into the Plugins Directory and renamed it

**Comment by ghost** [comment]
root@cacti:/opt/cacti/plugins# wget https://github.com/Cacti/plugin_thold.git
--2018-08-22 10:57:57--  https://github.com/Cacti/plugin_thold.git
Auflösen des Hostnamen »github.com (github.com)«... 192.30.253.112, 192.30.253.113
Verbindungsaufbau zu github.com (github.com)|192.30.253.112|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 301 Moved Permanently
Platz: https://github.com/Cacti/plugin_thold [folge]
--2018-08-22 10:57:57--  https://github.com/Cacti/plugin_thold
Wiederverwendung der bestehenden Verbindung zu github.com:443.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: nicht spezifiziert [text/html]
In »»plugin_thold.git«« speichern.

plugin_thold.git                                                [     <=>                                                                                                                                 ] 123,67K   147KB/s    in 0,8s

2018-08-22 10:57:58 (147 KB/s) - »plugin_thold.git« gespeichert [126635]

root@cacti:/opt/cacti/plugins# mv plugin_thold.git Thold.git
root@cacti:/opt/cacti/plugins# ls
index.php  Thold.git
root@cacti:/opt/cacti/plugins# tar -zvxf Thold.git

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
root@cacti:/opt/cacti/plugins# ls

**Comment by netniV** [comment]
The .git is if you want to use the `git` command to install/update.  To do that:

1. Install using
   1. `cd <cacti_dir>/plugins`
   2. `git clone https://github.com/cacti/plugin_<name> <name>`
2. Update using
   1. `cd <cacti_dir>/plugins/<name>`
   2. `git pull`

For source-based installation, refer to the download of source button which will create an archive of the source on GitHub or use the Releases section.  I've created a new release [v1.0.5](https://github.com/Cacti/plugin_thold/releases/tag/1.0.5) to make life easier for you as there have been a few changes.

1. Download the archive of your choice
2. Extract then use `cp -R <extract_folder>/* <cacti_dir/plugins/thold/`

**Comment by ghost** [comment]
Know my Plugin Directory is not correct

**Comment by netniV** [comment]
My comments above got parsed so I've made them code blocks to be properly readable.  `<name>` in this plugin's case is `thold` so just replace `<name>` with that.  The same logic does apply to other plugins though too.

**Comment by ghost** [comment]
THX everything works

**Comment by netniV** [comment]
I'm reopening this as confusingly @ferialjober jumped onto @Izmenoff's issue.  In future, unless it's the exact same issue you are having @ferialjober please create your own issue for better tracking 👍

**Comment by ghost** [comment]
ohh sryy ;)

**Comment by ISekan** [comment]
Use WinSCP for place files there is you need
https://winscp.net/eng/download.php

**Comment by netniV** [comment]
Are you still having an issue @Izmenoff ? If not go ahead an close this issue.

**Comment by ISekan** [comment]
**netniV**, tanks. 
I have updated.
![image](https://user-images.githubusercontent.com/17400240/44506481-47ddb580-a6af-11e8-8b40-bd8ef8482e93.png)

**Comment by netniV** [comment]
Could you do it once more? I've just re-release the code
