### ISSUE TITLE
Cacti Weathermap --> Plugin does not include an INFO file

### ISSUE THREAD

**Issue by ghost** [Cacti/plugin_thold#203]
Cacti Weathermap --> Plugin does not include an INFO file

**Comment by netniV** [comment]
This is not the place for Weathermaps, nor is Weathermaps written by The Cacti Group, it's actually written by Howard (Howie) Jones.  However, I as I am going to close this I will give you one bit of advice, Weathermaps < 1.0 does not support Cacti >= 1.0.
