### ISSUE TITLE
Errors when attempting to save a threshold

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#207]
When I attempt to save an edited thold, no matter what the change is, I get permission denied see msg below:
![capture](https://user-images.githubusercontent.com/11211789/45438205-8cdc8280-b684-11e8-9b21-2843d75d5500.PNG)

I am running the latest 1.06 Thold svn and Cacti Version 1.1.38
Please assist as it is a critical issue.

The following errors appear in log file:

2018/09/12  12:01:19 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold.php: 64  save_thold)(/plugins/thold/thold_functions.php: 3661  CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
--
2018/09/12 12:01:19 - ERROR PHP NOTICE in  Plugin 'thold': Undefined  index: graph_template_id in file:  /var/www/html/plugins/thold/thold_functions.php  on line: 3661
2018/09/12 12:01:19 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold.php: 64  save_thold)(/plugins/thold/thold_functions.php: 3660  CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2018/09/12 12:01:19 - ERROR PHP NOTICE in  Plugin 'thold': Undefined  index: local_graph_id in file:  /var/www/html/plugins/thold/thold_functions.php  on line: 3660

**Comment by netniV** [comment]
I'm sure it's not THold SVN as we moved to GIT a long time ago ;-)

However, this would suggest the that local_data_id the thold is being based on does not exist.  Is this for one particular THold or all of them?

**Comment by netniV** [comment]
Additionally, the permission denied part comes from thold verifying that the current user actually has permissions to access to the graph via it's thold_user_auth_threshold() function.

**Comment by ikorzha** [comment]
netniV, thank you for your response. I meant to say I have the latest Git 1.06 installed...
To answer your question the user is admin with all of the permissions for all graphs and plugins (unrestricted).
The issue is with particular type of threshold that is based on Cisco IP SLA. 
Normal tholds for traffic in/out do not have this problem I can make changes to it and save it.
Can you help please, for your reference, screenshot of the thold with graph is below:

![thold](https://user-images.githubusercontent.com/11211789/45491164-016ff980-b737-11e8-8ca7-124dc7dde085.PNG)

**Comment by netniV** [comment]
OK, so I suspect that this is a known issue of a multi-data source and thold not utilising the right one.  However, as I have never had a database with the issue and been able to narrow it down, it's not something that I believe has been fixed yet.  

Would it be possible for you to send me a dump of your database to diagnose to netniv@cacti.net ?  It would be treated with confidence and removed once the issue is resolved.

**Comment by ikorzha** [comment]
netniV, database is definitely confidential. What concerns me is a size of it.  2.5GB definitively not an email material.  I was able to compress it with rar to 85 meg.
Is there a private ftp or sftp I can upload it for you?
If you can reply YES I will email you for IP and credential to use.

Also I do have other scalability problems related to thold plugin due to me having 38000 tholds, I would love working with u better this product going forward if possible.

**Comment by netniV** [comment]
Hmm, that is too large for email transfer.  Send me an email to netniv@cacti.net and I'll send you a link where you can upload it to.  Once i've downloaded it, I will remove it from there.

**Comment by ikorzha** [comment]
Cacti DB has been delivered.
Thank you for looking into it in advance.

**Comment by netniV** [comment]
OK, I will be downloading that shortly. I'm currently in transit.

**Comment by ikorzha** [comment]
Thank you for looking into it.
Problem description is simple

From Cacti console -> Thesholds-> in seach field I type CPSC ISR-4431 and then click to edit.
All you have to do to replicate the problem is: remove checkmark on"Template Propagation Enabled"

And attempt to save changes..
It will result in deny msg and counter that can't be closed only via page refresh and errors in the cacti log.

Please let me know if you were able to replicate the problem.  I have sent the rrd file you have requested via email.

**Comment by netniV** [comment]
So, this has really helped because I can now see there is a problem with the save facility.  At each stage I added some extra recording/reporting (a couple of lines) and it showed the error:

```
THOLD Failed to find linked graph template item '162888' on threshold '67292'
```

It should have been looking for a data_template_rrd with id 162897 as this is what is stored in the data_template_rrd_id field for the thold_data record.  The local data ID from the threshold is 35056

```sql
SELECT id, data_template_id
                FROM data_template_rrd
                WHERE local_data_id = 35056
                ORDER BY id

+--------+------------------+
| id     | data_template_id |
+--------+------------------+
| 162888 |              106 |
| 162889 |              106 |
| 162890 |              106 |
| 162891 |              106 |
| 162892 |              106 |
| 162893 |              106 |
| 162894 |              106 |
| 162895 |              106 |
| 162896 |              106 |
| 162897 |              106 |
| 162898 |              106 |
| 162899 |              106 |
| 162900 |              106 |
| 162901 |              106 |
| 162902 |              106 |
| 162903 |              106 |
| 162904 |              106 |
| 162905 |              106 |
| 162906 |              106 |
| 162907 |              106 |
| 162908 |              106 |
| 162909 |              106 |
| 162910 |              106 |
| 162911 |              106 |
| 162912 |              106 |
| 162913 |              106 |
| 162914 |              106 |
| 162915 |              106 |
| 162916 |              106 |
| 162917 |              106 |
| 162918 |              106 |
+--------+------------------+
```

This is completely wrong because it means it's just using the first RRD created for the data source.  I think the simple fix is to make it use the data_template_rrd_id from the threshold but this will need to be tested so it'll be a couple of days before I release a fix.

**Comment by ikorzha** [comment]
Great thank you, I will be looking forward to test it out too.

**Comment by netniV** [comment]
@ikorzha I haven't forgotten about you, just the QA on the 1.2 beta is taking longer than expected as we keep finding little things.

**Comment by ikorzha** [comment]
I am patiently waiting and tracking your progress on 1.2 in Git :)

**Comment by netniV** [comment]
I feel stalked ;-)

**Comment by ikorzha** [comment]
When it comes to Cacti project I am a religious follower. Been on Cacti scene since 2009...
So what you feeling has grounds to it..

**Comment by netniV** [comment]
haha.  Well the good news is, I have a working fix.  Need to remove some 1.2 specific changes to be able to publish it so that will be over the next day or so when I restore your DB back to 1.1.38 and test against that.

**Comment by TheWitness** [comment]
I've been a happy stalker since 2002 ;)  Now, back to stalking. +1:

**Comment by ikorzha** [comment]
TheWitness I prefer the times when you were active in Cacti development and its plugins.  It was a sad times when you disappeared from a scene and just went to stalking :-1: 
We still remember you and wish for u to come back..
netniV, I will be looking forward for a fix to test once u publish it on Git.

**Comment by netniV** [comment]
OK, so the development branch should be able to handle both 1.2 and 1.1 correctly.

**Comment by ikorzha** [comment]
netniV, thank you for an excellent fix. I have fully tested it works all around, there log errors too.
I have 2 other bugs related to thold, that I will open a separate issue on.
Great job thank you so much.
