### ISSUE TITLE
[1.1.38] Thold and CPU / MySQL performance

### ISSUE THREAD

**Issue by g1augusto** [Cacti/plugin_thold#208]
Hi,

I would like to inquire about **THOLD** and the impact on CPU and MySQL (MariaDB)

This is the current amount of thresholds I have (it's going to grow...) and I can see that at each polling cycle it gives quite some numbers to **mysql** and **php** processes since I added them

```
19/Sep/2018 13:25:27 - SYSTEM THOLD STATS: Time:7.4472 Tholds:8107 TotalDevices:1360 DownDevices:8 NewDownDevices:0
```
- mysql can get up to 140%
- multiple php can get each 25 - 30 % 

![image](https://user-images.githubusercontent.com/26431888/45756401-0e9e5400-bc21-11e8-825d-0a03a488e7cc.png)

my hardware is the following : 

qty | Part Number | Description |  
-- | -- | -- | --
  |   |   |  
1 | 755258-B21 | HPE ProLiant DL360 Gen9 8SFF Configure-to-order Server |  
1 | 755258-B21 B19 | HP ProLiant DL360 Gen9 8SFF Europe-Multilingual Localization Configure-to-order Server |  
1 | 818172-L21 | HPE DL360 Gen9 Intel Xeon E5-2620v4 (2.1GHz/8-core/20MB/85W) FIO Processor Kit |  
1 | 818172-B21 | HPE DL360 Gen9 Intel Xeon E5-2620v4 (2.1GHz/8-core/20MB/85W) Processor Kit |  
1 | 818172-B21 0D1 | Factory Integrated |  
4 | 805347-B21 | HP 8GB (1x8GB) Single Rank x8 DDR4-2400 CAS-17-17-17 Registered Memory Kit |  
4 | 805347-B21 0D1 | Factory Integrated |  
2 | 873359-B21 | HPE 400GB SAS 12G Mixed Use SFF (2.5in) SC 3yr Wty Digitally Signed Firmware SSD |  
2 | 873359-B21 0D1 | Factory Integrated |  
1 | 749974-B21 | HP Smart Array P440ar/2GB FBWC 12Gb 2-ports Int FIO SAS Controller |  
2 | 720478-B21 | HPE 500W Flex Slot Platinum Hot Plug Power Supply Kit |  
2 | 720478-B21 0D1 | Factory Integrated |  
1 | BD505A | HPE iLO Advanced including 3yr 24x7 Tech Support and Updates 1-server LTU |  
1 | BD505A 0D1 | Factory Integrated |  
1 | 734811-B21 | HPE 1U Cable Management Arm for Rail Kit |  
1 | 734811-B21 0D1 | Factory Integrated |  
1 | 734807-B21 | HP 1U Small Form Factor Easy Install Rail Kit |  
1 | 734807-B21 0D1 | Factory Integrated

I could lower a bit  the impact by changing the _**thold_data**_ table to **MEMORY** , I would like to know two things:
- What is the impact on the overall processing of the server on adding thresholds ?
- changing the **thold_data** table to memory is advised (considering I have lots of RAM) ?
- Is this something that eventually can be fixed using **thold daemon** ? if so can it be fixed as currently seems to not work (#187)

**Comment by netniV** [comment]
You can't have the data table as memory since it holds not only the data but the definition.  On the stats front, I could check it out if you want to send me the above kit for say, the next 10 years? ;-)

Joking aside, I want to review thold but that's not going to happen until 1.2 is out the door... (almost there just keep finding QA issues!)

**Comment by netniV** [comment]
Oh and I think thold_daemon does work as long as you've scheduled it separately.  I don't think it's a poller run daemon (again not really looked in depth to see why as I had that same issue!)

**Comment by g1augusto** [comment]
OK,

So I should be fine adding more thresholds? 

I am going to revert the table as InnoDB, I noticed in the meanwhile that it has the data definitions (in the future can it be split so to keep fresh polled data in memory and save the SSDs?)

about the deamon...how to run it? would it improve something ?

**Comment by netniV** [comment]
I guess the value could be held in memory, but it wouldn't survive a server reboot so there would be a double query on the first run to get the last value (based on the RRD update)

**Comment by g1augusto** [comment]
well it wouldn't be too bad, after all this is for alerting and historical is already in the RRD file.

I think it's an instant value...if you agree: anytime you can, no rush really

I am still thinking about the pool of thresholds I am creating, I will be looking at 10000+ thresholds, mostly it's interfaces errors inbound and errors outbound...I may drop one of them as I feel it may put too much load on the system.

I think you don't have an estimation for the "maximum" number of thresholds, right ?

**Comment by netniV** [comment]
That, as ever, depends on the system in question ;-)

**Comment by g1augusto** [comment]
I am seeing some strange outputs...

`19/Sep/2018 15:38:09 - SYSTEM THOLD STATS: Time:464.6532 Tholds:10702 TotalDevices:1360 DownDevices:12 NewDownDevices:0`

**Comment by g1augusto** [comment]
then it lowered in elapsed time, and also number of thresholds is different...is this expected? how it works?


`19/Sep/2018 15:40:25 - SYSTEM THOLD STATS: Time:7.6318 Tholds:10084 TotalDevices:1360 DownDevices:12 NewDownDevices:0`


`19/Sep/2018 15:45:24 - SYSTEM THOLD STATS: Time:7.7134 Tholds:10536 TotalDevices:1360 DownDevices:12 NewDownDevices:0`

**Comment by netniV** [comment]
tbh, as I said above, I'm not totally convinced by the current code so I need to check through it.  I would personally, without reviewing the code, expect the number of thresholds to be constant unless there are scheduling options to exclude one.  It may also depend on the polling cycle of the data source (since it's the data source that controls what thold sees).

**Comment by TheWitness** [comment]
Using the thold daemon will enhance performance and async salability.  Some rather large companies are using it to scale their thold deployment.
