### ISSUE TITLE
[1.1.38] Thold and automation discovery

### ISSUE THREAD

**Issue by g1augusto** [Cacti/plugin_thold#209]
Hi,

when a threshold template is added to a device template, running a network discovery does not trigger the thresholds to be created for existing interface graphs. 

These can only be created by the devices menu and selecting the drop-down option "Apply thresholds"

**Comment by netniV** [comment]
That would appear to be correct.  There should probably be a toggle box that says, "Always Apply Threshold Template" but there isn't at the moment.   To be honest, I would rather see advancements in the threshold creation such that it can filter which interface thresholds get created.  I don't think that exists at the moment so any interface would end up having a threshold which is pointless on things like loop back addresses.  Or maybe I just setup my system wrong?

**Comment by g1augusto** [comment]
I thought you delegated filtering to the automation graph creation.

Make sense to have an additional filter for thresholds but it could be an option or to create filter based on the automation graph creation itself why not an entry in there? so to get more granular on the automation filter itself

**Comment by TheWitness** [comment]
This issue is resolved now.  Make certain that:

* thold autocreate is enabled
* the device template includes the threshold
* make certain your graph rules account for interface graphs

You will have to upgrade to Cacti 1.2 to apply these fixes.
