### ISSUE TITLE
Disabled Thresholds appear in breach/trigger filters

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#210]
I have an the following visual bug issue, If alarm has been triggered and gets disabled, it is still showing in triggered or breached alarms "as disabled".
I believe this is incorrect behavior. If alarm is disabled it should not be showing in triggered & breached even if it was disabled in triggered state.

![image](https://user-images.githubusercontent.com/11211789/45829028-faf9f880-bcc7-11e8-9d5a-2b43cafd26a2.png)

**Comment by netniV** [comment]
Can you separate the site issue out, thanks.  I’ll resolve these two shortly.

**Comment by ikorzha** [comment]
Absolutely, Issue #211 created for filtering issue.

**Comment by netniV** [comment]
OK, I'll buy that disabled shouldn't be in triggered.  If a status filter for disabled exists, it makes sense it should only appear in that.

**Comment by netniV** [comment]
OK, this should now be resolved.

**Comment by ikorzha** [comment]
Issue #210 is fixed partially. You have fixed it in thold.php that is responsible for console>thresholds views.
However same problem exist still in thold_graph.php that responsible for views in "Thold" tab
Please see screenshot below:
![image](https://user-images.githubusercontent.com/11211789/45838660-44eed880-bce0-11e8-8424-5ec98d5b8836.png)

**Comment by netniV** [comment]
Well, you know, get half a story, get half a fix ;-)

Looks good in my version, you sure you had the latest version? *(cough)* ;-)

**Comment by ikorzha** [comment]
Thank you so much! Great work.... I am positive I can find more issues for you to resolve :)
