### ISSUE TITLE
Site filtering does not work without another filter selected

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#211]
Site filtering doesn't work in Console->Thold-> When status "all" is selected.

if status other than all is selected it does work.

![45829253-87a4b680-bcc8-11e8-822c-03a26a8ec7ce](https://user-images.githubusercontent.com/11211789/45834384-f5ef7600-bcd4-11e8-80c7-732053e9c67a.png)

**Comment by netniV** [comment]
So, this should be the easiest to fix but ... the code looks right so I'm going to have to do some testing.

**Comment by netniV** [comment]
So I thought you might be lying to me so I picked a breached threshold, went to the device, found the site, and then filtered on that sitee and thresholds appeared.  Then I remembered, I was seing breached ones, so at least I know that works and changed it to all but then I got nothing.....

So I logged at clog and there's an SQL error which I have now resolved.

**Comment by ikorzha** [comment]
Validated thank you works!
