### ISSUE TITLE
DBCALL ERROR: A DB Exec Failed!, Error:1062, SQL:'INSERT INTO plugin_thold_daemon_processes (poller_id, pid) VALUES(?, ?)'

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#212]
Hi I am not sure if this is a bug or DB performance tuning issue.
I have a large install base of 38,000 tholds, with Cacti polling time every minute.
Occasionally on my Cacti Log (once every 20-30min) I see the following error msgs:
I am looking at Cacti team guidance, is this a bug or something else.
About Environment: 
Cacti 1.1.38
Latest Thold.
5 Cacti Pollers.

I also from time to time have erratic "Master poller" behavior (like poller over run, than shows 2 system stats within 1minute, 1 with high poller time...

![image](https://user-images.githubusercontent.com/11211789/45953110-18d0a180-bfd7-11e8-85df-f3119492bda4.png)

2018/09/24  08:28:08 - CMDPHP SQL Backtrace: (/poller.php: 545  process_poller_output)(/lib/poller.php: 521  process_poller_output)(/lib/poller.php: 521  process_poller_output)(/lib/poller.php: 510  api_plugin_hook_function)(/lib/plugins.php: 113  api_plugin_run_plugin_hook_function)(/lib/plugins.php: 214  thold_poller_output)(/plugins/thold/includes/polling.php: 316  db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
--
2018/09/24 08:28:08 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '1-1537792088.4353' for key 'PRIMARY'
2018/09/24 08:28:08 - DBCALL ERROR: A DB Exec Failed!, Error:1062,  SQL:'INSERT INTO plugin_thold_daemon_processes      (poller_id, pid)       VALUES(?, ?)'

![image](https://user-images.githubusercontent.com/11211789/45952659-b4f9a900-bfd5-11e8-9f02-42c5144be61f.png)

**Comment by netniV** [comment]
This sounds like you've ended up with two pollers running at the same time.  However, the strange thing is that it's using the same PID which more looks like a unix time stamp but with microseconds...

**Comment by ikorzha** [comment]
I honestly believe that in this case thold is a victim.  If I disable weathermap plugin and run without for 30min, I do not get a single poller overrun....
And my maps all run within 25sec, so they are definately not over running the poll cycle.
One thing I am still running weathermap 1.0.0dev 1 year old edition, that was Howie preliminary version for Cacti 1.x before he started to undertake a major re-design.
I am not sure if his current Git development is usable to test what is your opinion?

Look at this screen shot:
What a difference with weathermap enable vs disable:

![image](https://user-images.githubusercontent.com/11211789/45954776-e70e0980-bfdb-11e8-9b88-138634e77962.png)

I am going to close the issue after your comments.

**Comment by netniV** [comment]
I would post this to Howie's repo.  I've worked with him for some time and I'm sure he'll have an opinion on this.  As for as his current dev state, things work from a runtime point of view. The editor also works.  But adding new maps, defining groups, etc.  that is all work that needs to be done.
