### ISSUE TITLE
how can i get thold_mail attachment png path ?

### ISSUE THREAD

**Issue by pan781023** [Cacti/plugin_thold#213]
i went to add line notify and append png file , but i can't get png full path to append ,what can i do ?

**Comment by netniV** [comment]
If I remember rightly, the image is generated and automatically attached to the email.  It is not saved.

**Comment by pan781023** [comment]
How do I save the attached file?

**Comment by netniV** [comment]
Right click, save.

**Comment by pan781023** [comment]
In thold_functions.php  how can i download attached file ?

thanks .

**Comment by pan781023** [comment]
I find it !  I can get attached file to /tmp and delete after use

$savepath .=  '/tmp/' . $attachments[0]['filename'] ;
file_put_contents($savepath, $attachments[0][attachment]);

if(file_exists((string)$savepath)){
 unlink((string)$savepath);
}

**Comment by netniV** [comment]
You would be removing the file you just created with that basic code.  The file_put_contents should come afterwards.
