### ISSUE TITLE
Plugin 'thold': A  non-numeric value encountered in file: thold_functions.php  on line: 629

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#214]
I have upgraded my installation to PHP 7.2 and now occasionaly getting the following error msg in the log..

2018/09/25  13:13:16 - CMDPHP PHP ERROR WARNING Backtrace:  (/plugins/thold/thold_process.php: 194  thold_get_currentval)(/plugins/thold/thold_functions.php: 629  CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
--
2018/09/25 13:13:16 - ERROR PHP WARNING in  Plugin 'thold': A  non-numeric value encountered in file:  /var/www/html/plugins/thold/thold_functions.php  on line: 629

![image](https://user-images.githubusercontent.com/11211789/46034988-f79fac00-c0cf-11e8-90e8-672794edd129.png)

**Comment by netniV** [comment]
What version of thold? Line 629 in the latest version is a curly brace `}`

**Comment by ikorzha** [comment]
I am on the latest thold git. Are you looking at the file thold_functions.php:
If so you should see the line below:
![image](https://user-images.githubusercontent.com/11211789/46040407-3a688080-c0de-11e8-9d5f-d15b989cb99f.png)

**Comment by netniV** [comment]
Try adding this to the line after:

```php
cacti_log($currentval . ' = ' . $item[$thold_data['name']] . ' - ' .$thold_data['oldvalue']);
```

I suspect that the value may well be a 'U'

**Comment by ikorzha** [comment]
I have added the line I will report the re-occurrence once it happens with additional info.

**Comment by ikorzha** [comment]
netniV, I had to remove a temporary log patch as it created 100Meg of Cacti non-error log in 45min.
Can you amend your logging to only capture the value of error transaction?

**Comment by netniV** [comment]
Not really.  You'd have to write a whole bunch of code to have . set_error_handler() and then pump out the detail though that detail wouldn't be available in the error handler so you'd have to set a global variable then come back and report if that variable was set.

**Comment by ikorzha** [comment]
netniV, this issue is a low paypoint. There are way more pressing issues, since troubleshooting it too hard with your permission I will close this case for now until better times.
