### ISSUE TITLE
reapply suggested name script

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/plugin_thold#215]
do we have any CLI script to do reapply suggested name for the thresholds?.. i have around 35000 threshold graphs... i am really struggling to do reapply suggested name for the 35000 graphs..

**Comment by netniV** [comment]
You can do it from the template with the latest version of Thresholds.  Not sure if the script might timeout though with that many at once.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/46418214-3e6e5100-c723-11e8-8420-69a4d4632890.png)
