### ISSUE TITLE
How thold configures alarms for custom merged Graph traffic？

### ISSUE THREAD

**Issue by garywu520** [Cacti/plugin_thold#217]
After cacti merges the traffic graphs, can you use the threshold to monitor the total traffic of the merged graphs to alert?
For example, if the interface traffic of the two interfaces is 100MB, use the threshold configuration threshold of 100MB to monitor the Graph and reach 100MB for email alarm.

Currently, traffic consolidation and email alerts have been configured and are working properly.
My doubt is that thold can't now configure alarms for custom Graph traffic.

If so, what should I do? Thank you!

**Comment by cigamit** [comment]
Currently, you can not monitor Aggregate Graphs with Thold, as we require data back from the poller to check against.  As these individual portions of the graphs may be polled at different polling periods, it makes things difficult to say the least to combine them for checking.
So at this time, this is not something we are looking at doing unless we change how Aggregates work.
