### ISSUE TITLE
Minor "alerted" thold readability problem via console->tholds->triggered

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#218]
I have a minor alerted thold readability problem via console->tholds->triggered in the "modern theme"
As per legend it should be black on red, instead of green on red that is very hard to read.
Anything can be on this front:?
![image](https://user-images.githubusercontent.com/11211789/47092933-10ded880-d1f6-11e8-9b97-275c61c2c8d5.png)

**Comment by netniV** [comment]
The reason for this is because the name is a link.  The default style for a link is green.  Thold should be overriding this but I'm not sure to what.

**Comment by TheWitness** [comment]
This is resolved in the latest develop.  Keeping open for a time.
