### ISSUE TITLE
Cannot add threshold in Cacti, no "add" button available. 

### ISSUE THREAD

**Issue by don1406** [Cacti/plugin_thold#222]
I have installed the plugin "Thold", but i can't add anything. I don't have the add button.
In my older Cacti i also have installed the plugin "Thold". In my older Cacti there is also no "add" button, but when i type ....../plugins/thold/add_graph.php, it seems to work, but not on the new Cacti.
My new Cacti is on version 1.1.38 (latest stable version).
Older Cacti is on version 0.8.

![cacti no add button](https://user-images.githubusercontent.com/34776452/48353065-c9c9f300-e68e-11e8-9482-ba411f200b25.PNG)

**Comment by netniV** [comment]
You add thresholds via the + button top right of Console->Thresholds. You can also add them using either automation, or by associating a threshold to a device template and then resyncing the template with the auto create option in settings turned on.
