### ISSUE TITLE
Thold plugin, i get no notification..

### ISSUE THREAD

**Issue by don1406** [Cacti/plugin_thold#223]
Hi,

I have a problem (again) with my Thold plugin on Cacti 1.1.38.
If a host is going down, i get no e-mail notification hoever "Dead Device Notifications" is turned on.

I only get a e-mail if the host is returned from down state.
Is there a possibility to get an e-mail notification, the moment that a host is down..

Thanks

**Comment by netniV** [comment]
Please ensure that you have the latest version of thold.

**Comment by don1406** [comment]
Yes i have. Version 1.0.4. 
I have installed the plugin 2 days ago. From the docs.cacti.net site.

**Comment by netniV** [comment]
Try using the latest release on here.  I think the cacti site is a version or two behind.

**Comment by don1406** [comment]
i had, i'm sorry, the link on the cacti site was the link to the github. I have now installed the "addon" Monitor. Let's see of this is working. i keep you posted!

**Comment by don1406** [comment]
It is working fine now with the plugin/addon monitor.
