### ISSUE TITLE
cli_thresholds.php dont work.

### ISSUE THREAD

**Issue by tabyr** [Cacti/plugin_thold#226]
Hello.
Cacti 1.1.38
thold 1.0.6
When use like `php cli_thresholds_my.php --thold-template=2 --graph-ids='1 2 3'` nothing happend.
Is it working? Or broken?

**Comment by cigamit** [comment]
I assume you meant _cli_thresholds.php_ instead of _cli_thresholds_my.php_
Have you tried it with the debug flag?

**Comment by tabyr** [comment]
Yep. soz. _my.php just copy if file with error and debug flags.
And with this flags no error and anything else.

**Comment by cigamit** [comment]
Did you copy the file into the cli directory of your base cacti, or are you attempting to run it from the thold directory?  Its needs to be in the cli directory.  You also most likely have php errors disabled, so its not displaying all the errors it should be.

**Comment by tabyr** [comment]
Okay try original file in thold directory with enable debug. And nothing!
Try urself.

**Comment by cigamit** [comment]
Yes, it seems we only added the functions to deal with --auto and not individual graphs even though the options are there. Most likely since we don't have an easy function for that yet.  We will add it to the list of future things to fix.

**Comment by tabyr** [comment]
Ok, thx, Waiting for fix.

**Comment by TheWitness** [comment]
This issue has been addressed in the following commit.  Please read the commit log for important information: https://github.com/Cacti/plugin_thold/commit/0ad5286c970b90dbaac68a74ba910665853e2e71

**Comment by tabyr** [comment]
Hello again.
New update of plugin requires cacti 1.2.0.
When be update cacti to stable 1.2.0 ?
