### ISSUE TITLE
Thold Action=Edit and Save button

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_thold#23]
After clicking save button something in not working correctly.

> 2016-12-28 15:48:33 - DBCALL ERROR: SQL Assoc Failed!, Error:1054, SQL:"SELECT td.*, tt.name AS template_name, uap0.user_id AS user0, uap1.user_id AS user1, uap2.user_id AS user2 FROM thold_data AS td INNER JOIN graph_local AS gl ON gl.id=td.local_graph_id LEFT JOIN graph_templates AS gt ON gt.id=gl.graph_template_id LEFT JOIN host AS h ON h.id=gl.host_id LEFT JOIN thold_template AS tt ON tt.id=td.thold_template_id LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1) LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3) LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4) WHERE (thold_data.thold_enabled='on') HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ORDER BY thold_alert DESC LIMIT 0, 500"
> 2016-12-28 15:48:33 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column 'thold_data.thold_enabled' in 'where clause'
> 2016-12-28 15:48:33 - DBCALL ERROR: SQL Cell Failed!, Error:1054, SQL:"SELECT COUNT(*) FROM ( SELECT uap0.user_id AS user0, uap1.user_id AS user1, uap2.user_id AS user2 FROM thold_data AS td INNER JOIN graph_local AS gl ON gl.id=td.local_graph_id LEFT JOIN graph_templates AS gt ON gt.id=gl.graph_template_id LEFT JOIN host AS h ON h.id=gl.host_id LEFT JOIN thold_template AS tt ON tt.id=td.thold_template_id LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1) LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3) LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4) WHERE (thold_data.thold_enabled='on') HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ) AS rower"
> 2016-12-28 15:48:33 - DBCALL ERROR: SQL Cell Failed!, Error: Unknown column 'thold_data.thold_enabled' in 'where clause' 

I did remove the whole tables from db and reinstall the plugin.
In DB there is a column 'thold_enabled' in 'thold_data' table so I think this querry is broken.
All the values in this table = 'on'

**Comment by cigamit** [comment]
This is a bug.  Solution is a bit complicated, but doable.
