### ISSUE TITLE
Thold not receiving alerts

### ISSUE THREAD

**Issue by chenbangkuo** [Cacti/plugin_thold#230]
Hi, I'm kind of new at cacti, so if lack any proper information please let me know :)
Cacti version : 1.1.38
Thold version : 1.0.4 ~ 1.0.6
As the title , the thold alerting function don't seems to work on my server.
I did tried to reinstall thold with any updated version i'v got, but can't seems
to fix the problem, and also got some PHP error's in the logging. 
Strange thing is the whole thing happens after i rebooted the server, at that point 
i reinstall the thold to 1.0.5 and it works find for 2 day's, but now it goes down again. 
Also tried to change threshold High/Low settings, doesn't work either. 
Could kindly point out the issue. 
Here is the screen shot's 
![2019-01-06_19h19_44](https://user-images.githubusercontent.com/36146687/50735321-3f15f800-11e8-11e9-91cf-595025b2351f.png)
![2019-01-06_19h20_47](https://user-images.githubusercontent.com/36146687/50735325-43daac00-11e8-11e9-9333-1d6f92108e10.png)

**Comment by TheWitness** [comment]
Looks more like a poller problem and not a thold problem.  Script server failures are indicative of a poller timing out.  As such, take this one up on the forums.
