### ISSUE TITLE
thold_command_execution() is sending unexpanded command line

### ISSUE THREAD

**Issue by ahouston** [Cacti/plugin_thold#232]
The exec calls in thold_command_execution() aren't using the $cmd variable.

For example:
> exec($thold_data['trigger_cmd_high'], $output, $return);

Should read:
exec($cmd, $output, $return);

I managed to get a few commits ahead on my fork, so I'm going to have to rewind a bit for a pull request, but this is the commit that fixes it:

https://github.com/ahouston/plugin_thold/commit/a7131087b474dfffc7e9d99dfa0ff9a935f3d076

**Comment by TheWitness** [comment]
Yup, right, fixed.
