### ISSUE TITLE
Problem when acknowleding a thold

### ISSUE THREAD

**Issue by hmorandell** [Cacti/plugin_thold#241]
Hi,
when I try to acknowledge a triggered thold, I get the error:

`SQL Save on table 'plugin_thold_log': Column 'graph_id' does not exist, unable to save!
`

The Column in this thold version has been renamed to "**local_graph_id**" and is not called "**graph_id**" anymore. Should I change only the column name in the function?

**Comment by TheWitness** [comment]
Try updating to the latest dev, then try again.  Also, make sure you provide the stack trace in your report that shows the file and line number.

**Comment by hmorandell** [comment]
it seems to work now, I do not get the error anymore. Just not sure how it works, as the comment I put in I seem not to find anywhere for the moment. but for now I close this issue, thanks!

**Comment by hmorandell** [comment]
OK, I reopen this issue as there is now some new errors in the logfile:

`2019/02/08 10:20:07 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'graph_id' in 'field list'`

`2019/02/08 10:20:07 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'current' cannot be null`

`2019/02/08 10:20:07 - DBCALL ERROR: SQL Save Failed for Table 'plugin_thold_log'. SQL:'INSERT INTO plugin_thold_log (`type`, `time`, `host_id`, `local_graph_id`, `threshold_id`, `threshold_value`, `current`, `status`, `description`, `id`) VALUES (99, 1549617607, 0, 0, 2695, '', NULL, 0, 'Threshold 2695 has been acknowledged. Additional Comments: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 0) ON DUPLICATE KEY UPDATE `type`=VALUES(`type`), `time`=VALUES(`time`), `host_id`=VALUES(`host_id`), `local_graph_id`=VALUES(`local_graph_id`), `threshold_id`=VALUES(`threshold_id`), `threshold_value`=VALUES(`threshold_value`), `current`=VALUES(`current`), `status`=VALUES(`status`), `description`=VALUES(`description`)'`

maybe this is useful to fix the problem. please let me know if there is any other details you might need

**Comment by cigamit** [comment]
Please see if it's still broken.

**Comment by netniV** [comment]
This may also be related to #250

**Comment by hmorandell** [comment]
OK everything seems fine now, but now I get the error when acknowleding a threshold that a column is missing in plugin_thold_log:

`SQL Save on table 'plugin_thold_log': Column 'lastread' does not exist, unable to save!`

Indeed this column does not exist:
```
MariaDB [cacti]> describe plugin_thold_log
    -> ;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int(12)      | NO   | PRI | NULL    | auto_increment |
| time            | int(24)      | NO   | MUL | NULL    |                |
| host_id         | int(10)      | NO   | MUL | NULL    |                |
| local_graph_id  | int(10)      | NO   | MUL | NULL    |                |
| threshold_id    | int(10)      | NO   | MUL | NULL    |                |
| threshold_value | varchar(64)  | NO   |     | NULL    |                |
| current         | varchar(64)  | NO   |     | NULL    |                |
| status          | int(5)       | NO   | MUL | NULL    |                |
| type            | int(5)       | NO   | MUL | NULL    |                |
| description     | varchar(255) | NO   |     | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
10 rows in set (0.00 sec)
```

I downloaded the last development version before.

**Comment by hmorandell** [comment]
and now everytime a thold is breached or triggered, there are more errors in the logfile (they haven't been there before:

```
2019/02/20 08:58:46 - CMDPHP SQL Backtrace: (/poller.php[796]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[465]:thold_check_threshold(), /plugins/thold/thold_functions.php[2295]:thold_log(), /plugins/thold/thold_functions.php[1449]:sql_save())
2019/02/20 08:58:46 - DBCALL ERROR: SQL Save on table 'plugin_thold_log': Column 'lastread' does not exist, unable to save!
2019/02/20 08:58:46 - THOLD: Threshold Breached ID: 1459 DataTemplate: Cisco - BGP Peer Statistics DataSource: bgp_peer_status Type: High / Low Enabled: on Current: 6 High: Low: 6 Trigger: 60 Warning High: Warning Low: Warning Trigger: 0 SentTo:
2019/02/20 08:58:46 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[796]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[465]:thold_check_threshold(), /plugins/thold/thold_functions.php[2295]:thold_log(), /plugins/thold/thold_functions.php[1382]:CactiErrorHandler())
2019/02/20 08:58:46 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: lastread in file: /var/www/html/plugins/thold/thold_functions.php on line: 1382
```

**Comment by netniV** [comment]
lastread is on the thold_data as far as I am aware, not the log so that's an interesting error.

**Comment by cigamit** [comment]
This is resolved now.

**Comment by hmorandell** [comment]
OK looks much better now, just that there is still one minor error logged:


```
2019/02/20 16:04:37 - CMDPHP SQL Backtrace: (/plugins/thold/thold.php[50]:do_actions(), /plugins/thold/thold.php[336]:ack_logging(), /plugins/thold/thold_functions.php[3329]:db_fetch_row_prepared(), /lib/database.php[421]:db_execute_prepared())
--
2019/02/20 16:04:37 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'graph_id' in 'field list'


```

**Comment by netniV** [comment]
I believe that was resolved as well.
