### ISSUE TITLE
Cacti hangs after installing most recent thold

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/plugin_thold#242]
I´m ussing cacti 1.2.1 and when i try to use the development version of thold cacti get stuck and got the following into the log file:

`

08-02-2019  14:55:39 - CMDPHP WARNING: Registering Realm for Plugin thold and  Filenames thold.php is ambiguous.  Using first matching Realm.  Contact  the plugin owner to resolve this issue.
--
08-02-2019 14:55:33 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
08-02-2019 14:55:33 - ERROR PHP ERROR: Maximum execution time of 299  seconds exceeded in file: C:\Apache24\htdocs\cacti\lib\database.php on  line: 235
08-02-2019 14:55:32 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:28 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:24 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:21 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:18 - CMDPHP PHP ERROR WARNING Backtrace:   (C:\Apache24\htdocs\cacti\plugins\Thold\thold_graph.php[40]:delete_old_thresholds(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[3182]:CactiErrorHandler())
08-02-2019 14:55:18 - ERROR PHP WARNING: Invalid argument supplied  for foreach() in file:  C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php  on line:  3182
08-02-2019 14:55:18 - CMDPHP SQL Backtrace:   (C:\Apache24\htdocs\cacti\plugins\Thold\thold_graph.php[40]:delete_old_thresholds(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[3175]:db_fetch_assoc(),   C:\Apache24\htdocs\cacti\lib\database.php[449]:db_fetch_assoc_prepared(),  C:\Apache24\htdocs\cacti\lib\database.php[463]:db_execute_prepared())
08-02-2019 14:55:18 - CMDPHP ERROR: A DB Row Failed!, Error: Column 'data_source_name' in where clause is ambiguous
08-02-2019 14:55:17 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:15 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:10 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:06 - CMDPHP WARNING: Registering Realm for Plugin  thold and Filenames thold.php is ambiguous.  Using first matching Realm.   Contact the plugin owner to resolve this issue.
08-02-2019 14:55:04 - CMDPHP PHP ERROR WARNING Backtrace:   (C:\Apache24\htdocs\cacti\poller.php[796]:api_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[74]:api_plugin_run_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[177]:thold_poller_bottom(),  C:\Apache24\htdocs\cacti\plugins\Thold\includes\polling.php[45]:thold_check_all_thresholds(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\polling.php[419]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:CactiErrorHandler())
08-02-2019 14:55:04 - ERROR PHP WARNING: include(): Failed opening  'C:/Apache24/htdocs/cacti/plugins/thold/includes/arrays.php' for  inclusion (include_path='.;C:\php\pear') in file:  C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php  on line:  1494

`

and this:
`

C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[1141]:plugin_thold_log_changes(),   C:\Apache24\htdocs\cacti\plugins\Thold\thold_functions.php[1494]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[85]:thold_upgrade_database(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\database.php[884]:db_add_column(),  C:\Apache24\htdocs\cacti\lib\database.php[580]:db_execute(),  C:\Apache24\htdocs\cacti\lib\database.php[188]:db_execute_prepared())
--
08-02-2019 14:54:01 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'acknowledgement'
08-02-2019 14:54:00 - CMDPHP SQL Backtrace:   (C:\Apache24\htdocs\cacti\poller.php[796]:api_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[74]:api_plugin_run_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[177]:thold_poller_bottom(),  C:\Apache24\htdocs\cacti\plugins\Thold\includes\polling.php[45]:thold_check_all_thresholds(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\polling.php[419]:include(),   C:\Apache24\htdocs\cacti\plugins\Thold\includes\arrays.php[367]:plugin_thold_upgrade(),   C:\Apache24\htdocs\cacti\plugins\Thold\setup.php[127]:plugin_thold_install(),

`

i just went back to the previous version and everything is working fine again, by the way the new version number (1.2) is not recognized in cacti, the new files are still identified as 1.0.6.

**Comment by netniV** [comment]
I believe that this is now resolved in issue #245 so try the upgrade again and it should go through this time.
