### ISSUE TITLE
Unknown column 'td.template' error generated when propagating templates

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#244]
> 2019/02/11  16:41:44 - CMDPHP SQL Backtrace:   (/plugins/thold/thold.php[50]:do_actions(),  /plugins/thold/thold.php[312]:db_fetch_row_prepared(),  /lib/database.php[422]:db_execute_prepared())
--
2019/02/11 16:41:44 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'td.template' in 'field list'
2019/02/11 16:41:44 - CMDPHP SQL Backtrace:   (/plugins/thold/thold.php[50]:do_actions(),  /plugins/thold/thold.php[312]:db_fetch_row_prepared(),  /lib/database.php[422]:db_execute_prepared())
2019/02/11 16:41:44 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'td.template' in 'field list'

**Comment by netniV** [comment]
This has now been committed to the development code.
