### ISSUE TITLE
No device available when attempting to manually add a new Threshold

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#248]
I have applied thold plugin and import some threshold template.  I try to create threshold using threshold template, but the device can not be choosen. 
![screen shot 2019-02-13 at 3 39 16 pm](https://user-images.githubusercontent.com/47589910/52695166-c0f6ff00-2fa6-11e9-8a28-7c11e99598eb.png)

**Comment by netniV** [comment]
If you go to the devices list and select that graph template, do you have any devices defined?

**Comment by yingbaiibm** [comment]
1. I have devices listed under Devices page 
2. I can create graph based on graph template Alert-Host With X Status for device such as lsf107_Summary directly.
3. So for this problem, when creating the threshold, should list all the devices. 

Devices page:
![screen shot 2019-02-14 at 10 47 21 am](https://user-images.githubusercontent.com/47589910/52759438-d91e5b00-3046-11e9-9ca1-5a96a5ee37d9.png)

**Comment by netniV** [comment]
And do you have any graphs for those devices using the template you are trying to create a threshold for?  You can use the template filter on the graph listing to verify this.

**Comment by TheWitness** [comment]
@yingbaiibm, I see your point.  Presently, the Device must be mapped to the underlying Graph Template, but this is not the desired behavior.  Let me make that correction.

**Comment by cigamit** [comment]
@TheWitness, if I read the code correctly, you should be able to pick a device unless the template happens to be associated with a Data Query.  At that point, if the device is not associated with the Data Query, then it will not show up.

**Comment by TheWitness** [comment]
Correct.  Everything is working as it should. @yingbaiibm, can you please update to the latest version and see if this message continues.

**Comment by yingbaiibm** [comment]
@TheWitness  verified the bug,  it works now.  
![screen shot 2019-02-26 at 2 58 32 pm](https://user-images.githubusercontent.com/47589910/53393552-a45fbb80-39d7-11e9-8823-d27f181a829e.png)

**Comment by netniV** [comment]
Should they be allowed to pick the device, but then have an error displayed that informs them of that situation?  It could be tricky to figure out otherwise.

**Comment by TheWitness** [comment]
@yingbaiibm, please close once you confirm that these bugs are addressed.
