### ISSUE TITLE
Wrong Error message whn saving a device, with threshold

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_thold#249]
Hi all,
same as number 2128, error message when I save a device with threshold enabled
Note, we could not process all your actions. Details are below.

Save Successful.
Created threshold for the Graph 'XXXX Te1/2/7 - Status -  ' using the Data Source 'int_status'

But every thing is working and threshold are created.
No error in cacti log
Cacti 1.2.1
Centos 7
Some plugin

**Comment by TheWitness** [comment]
This message is correct.  When you have thold auto creation enabled, and you save a device when there is no thold created, you will get that message in the message box.  Once the thold is created, you should not get it a second time however.

**Comment by netniV** [comment]
Looking above, is that the case though? He did have a threshold created.

**Comment by TheWitness** [comment]
Closing this issue as it's not really an issue.
