### ISSUE TITLE
SNMP trap support generates new Engine ID for each trap 

### ISSUE THREAD

**Issue by ronytomen** [Cacti/plugin_thold#25]
Originally submitted to the Cacti Bug system: http://bugs.cacti.net/view.php?id=2635

> Hi,
> I have started using Thold version 0.6.0 (SVM version as it's not yet released). This version has been updated by the snmpagent developer with added support for thold to generate snmp traps when an alarm is triggered.
> 
> I have configured and tested this. All work well and traps are generated (using snmp v3) however each trap has a new Engine ID generated for it. This is regardless of the source host.
> 
> A solution would enable a complete integration with Netcool alarm managers.

**Comment by browniebraun** [comment]
-implemented
If defined the device (cacti host) related SNMP Engine ID will be preferred - if not, the SNMP Engine ID being set for the related notification receivers will be taken into account.
