### ISSUE TITLE
Threshold names are not being displayed correctly

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#253]
This occurs because the name_cache in the thold_data table is not populated properly if the template it relies on has no value for suggested_name.  The UI defaults this to be '|data_source_description|' but the upgrade code sees blank and does not substitute this.

**Comment by netniV** [comment]
This has now been resolved in the development code.

**Comment by xmacan** [comment]
The same problem is in notification list, see screenshot:
![screenshot_2019-03-05 console - notification lists edit](https://user-images.githubusercontent.com/26485719/53805368-391f6780-3f4a-11e9-95e0-500d2cf7282e.png)

Notify_lists.php, line 1316. If I change $row['name_cache'] to $row['name'], it works
