### ISSUE TITLE
Log errors on creation and thols missing after polling cycle

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/plugin_thold#254]
Using the most recent dev version i get this erros in the log:

```
19/02/2019  10:26:03 - CMDPHP PHP ERROR NOTICE Backtrace:   (E:\Apache24\htdocs\cacti\plugins\thold\thold.php[135]:thold_edit(),  E:\Apache24\htdocs\cacti\plugins\thold\thold.php[1864]:draw_edit_form(),  E:\Apache24\htdocs\cacti\lib\html_form.php[55]:CactiErrorHandler())
--
19/02/2019 10:26:03 - ERROR PHP NOTICE: Undefined index: value in  file: E:\Apache24\htdocs\cacti\lib\html_form.php  on line: 55
19/02/2019 10:26:02 - CMDPHP raise_message($message_id, $message, $level);
19/02/2019 10:25:54 - CMDPHP PHP ERROR NOTICE Backtrace:   (E:\Apache24\htdocs\cacti\plugins\thold\thold.php[83]:thold_add(),  E:\Apache24\htdocs\cacti\plugins\thold\thold.php[194]:thold_wizard(),  E:\Apache24\htdocs\cacti\plugins\thold\thold_webapi.php[879]:html_start_box(),  E:\Apache24\htdocs\cacti\lib\html.php[87]:CactiErrorHandler())
19/02/2019 10:25:54 - ERROR PHP NOTICE: Undefined variable: add_text  in file: E:\Apache24\htdocs\cacti\lib\html.php  on line: 87
19/02/2019 10:25:54 - CMDPHP PHP ERROR NOTICE Backtrace:   (E:\Apache24\htdocs\cacti\plugins\thold\thold.php[83]:thold_add(),  E:\Apache24\htdocs\cacti\plugins\thold\thold.php[194]:thold_wizard(),  E:\Apache24\htdocs\cacti\plugins\thold\thold_webapi.php[879]:html_start_box(),  E:\Apache24\htdocs\cacti\lib\html.php[84]:CactiErrorHandler())
19/02/2019 10:25:54 - ERROR PHP NOTICE: Undefined variable: add_text  in file: E:\Apache24\htdocs\cacti\lib\html.php  on line: 84
19/02/2019 10:25:54 - CMDPHP PHP ERROR WARNING Backtrace:   (E:\Apache24\htdocs\cacti\plugins\thold\thold.php[83]:thold_add(),  E:\Apache24\htdocs\cacti\plugins\thold\thold.php[194]:thold_wizard(),  E:\Apache24\htdocs\cacti\plugins\thold\thold_webapi.php[879]:html_start_box(),  E:\Apache24\htdocs\cacti\lib\html.php[58]:CactiErrorHandler())
19/02/2019 10:25:54 - ERROR PHP WARNING: Missing argument 6 for  html_start_box(), called in  E:\Apache24\htdocs\cacti\plugins\thold\thold_webapi.php on line 879 and  defined in file: E:\Apache24\htdocs\cacti\lib\html.php  on line: 58
19/02/2019 10:25:49 - CMDPHP PHP ERROR NOTICE Backtrace:   (E:\Apache24\htdocs\cacti\plugins\thold\thold.php[83]:thold_add(),  E:\Apache24\htdocs\cacti\plugins\thold\thold.php[194]:thold_wizard(),  E:\Apache24\htdocs\cacti\plugins\thold\thold_webapi.php[879]:html_start_box(),  E:\Apache24\htdocs\cacti\lib\html.php[87]:CactiErrorHandler())
```
but even so the threshold shows in the list, but in the next polling cycle the threshold get erased with no futher error in the log.

**Comment by netniV** [comment]
Thresholds are not normally automatically deleted by the system.  Have you looked at the thold_data table to see if there is any data in it?

**Comment by DoubleBeast** [comment]
i search the data table and it is blank, so to discard i unistall thold with the intention of reinstalling it and it says that is incompatible because requires cacti 1.2.2 (i have 1.2.1), is normal that the plugin requires the dev version of cacti? i will try to update cacti in my test server and let you know the results.

Is there a download location of a stable realease of thold or only the dev version avaible here?

**Comment by netniV** [comment]
You have the dev version of the plugin, it can (and does in this case) require the dev version of cacti to run the plugin.  1.2.2 will hopefully be released this weekend.

**Comment by DoubleBeast** [comment]
ok, i understand, the stable version is the master branch? i ask because it looks like a year behind the dev version and the version on the cacti home is even older

**Comment by netniV** [comment]
Stable versions of plugins are actually on the releases tab

**Comment by DoubleBeast** [comment]
> 
> 
> Stable versions of plugins are actually on the releases tab

thanks, i must be blind.

**Comment by DoubleBeast** [comment]
so now i'm using the stable realease and don't get the tholds erased but i´m getting this errors:

![thold](https://user-images.githubusercontent.com/37849594/53200189-4f96fc00-35f7-11e9-98c1-262d0cb8daee.png)

the procedure i follow to get there was:
1-try to use the 1.2 realease directly but still getting the version 1.2.2 compatibility error (i'm still ussing cacti 1.2.1)
2-install thold realease 1.0.6 and create a threshold whitout error logs
3-update thold to realese 1.2 (disable thold->overwrite old files->enable thold)

after that aparently work but getting this recurrent error in the log:


21/02/2019  16:37:36 - CMDPHP PHP ERROR NOTICE Backtrace:   (E:\Apache24\htdocs\cacti\plugins\thold\thold_graph.php[55]:tholds(),  E:\Apache24\htdocs\cacti\plugins\thold\thold_graph.php[482]:CactiErrorHandler())

21/02/2019 16:37:36 - ERROR PHP NOTICE: Undefined index:  acknowledgment in file:  E:\Apache24\htdocs\cacti\plugins\thold\thold_graph.php  on line: 482

am i doing something wrong?

**Comment by netniV** [comment]
Problem you will have now is that you’ve been upgraded to the dev version and that has changed your scheme.  So, the only true cause of action is to completely uninstall thold, then install again (all on the plugins page).  Uninstalling also removes the tables, which means it wipes everything and then adds them freshly back in.

**Comment by DoubleBeast** [comment]
that was what i did in the previous comment, with a fresh install of the 1.2 version (Releases Version) i get the compatibility error, with a fresh install of 1.0.6 i get no errors and if i update from 1.06->1.2 i get the log error mentioned.

as it appears to be an isolated case it may be caused by something in my setup, i'm going back to 1.0.6 and close this issue.

Thanks for the support Mark.
