### ISSUE TITLE
When listing Thresholds, unable to sort by Data Source column

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#258]
**To Reproduce**
1. Go to thresholds page
2. Add some threshold 
3. Check sort by DSName

2019/02/27 10:54:21 - CMDPHP Filter Variable: state, Must have a default and none is set
2019/02/27 10:54:39 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'data_source' in 'order clause'
2019/02/27 10:54:39 - CMDPHP SQL Backtrace:  (/plugins/thold/thold.php[141]:list_tholds(), /plugins/thold/thold.php[622]:get_allowed_thresholds(), /plugins/thold/thold_functions.php[1233]:db_fetch_assoc(), /lib/database.php[449]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())
2019/02/27 10:54:44 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'data_source' in 'order clause'
2019/02/27 10:54:44 - CMDPHP SQL Backtrace:  (/plugins/thold/thold.php[141]:list_tholds(), /plugins/thold/thold.php[622]:get_allowed_thresholds(), /plugins/thold/thold_functions.php[1233]:db_fetch_assoc(), /lib/database.php[449]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())
2019/02/27 10:55:03 - SYSTEM STATS: Time:1.2899 Method:cmd.php Processes:1 Threads:N/A Hosts:7 HostsPerProcess:7 DataSources:52 RRDsProcessed:52
2019/02/27 10:55:03 - SYSTEM THOLD STATS: Time:0.0400 Tholds:2 TotalDevices:7 DownDevices:0 NewDownDevices:0
2019/02/27 10:55:04 - SYSTEM SYSLOG STATS:Time:0.3 Deletes:0 Incoming:0 Removes:0 XFers:29 Alerts:0 Alarms:0 Reports:0

**Expected behavior**
Sort function should work well for DSName

**Screenshots**
![screen shot 2019-02-27 at 11 02 50 am](https://user-images.githubusercontent.com/47589910/53462597-4f778000-3a7f-11e9-8993-f103e425cdf7.png)

**Comment by netniV** [comment]
This is likely related to https://github.com/Cacti/cacti/issues/2460

**Comment by netniV** [comment]
This is because the datasource is only read whilst looping through the thresholds to display.  I will be pushing a fix for this during my lunch.

**Comment by netniV** [comment]
This has now been resolved in the development code.
