### ISSUE TITLE
Custom status was not replaced correctly after creating threshold 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#259]
**To Reproduce**
1. Go to thresholds page 
2. Create a threshold for template Alert-Host with X status, change custom status to Closed-Full 
3. After creating threshold, the custom status does not changed correctly with value Closed-Full 

**Screenshots**
![screen shot 2019-02-27 at 11 13 52 am](https://user-images.githubusercontent.com/47589910/53463065-db3ddc00-3a80-11e9-95ec-fba784e0a7c1.png)
![screen shot 2019-02-27 at 11 13 23 am](https://user-images.githubusercontent.com/47589910/53463075-e133bd00-3a80-11e9-89d6-ea09df69fc44.png)

compared with cacti0.88
![screen shot 2019-02-27 at 11 15 15 am](https://user-images.githubusercontent.com/47589910/53463124-06283000-3a81-11e9-97cb-979c4c10bd09.png)

**Comment by TheWitness** [comment]
@yingbaiibm, please send me a dump of your cacti database.  Thanks.

**Comment by yingbaiibm** [comment]
@TheWitness  here is my database dump file 
cacti: 1.2.0
thold: newest development code 

[rtm_cacti.sql.zip](https://github.com/Cacti/plugin_thold/files/2913233/rtm_cacti.sql.zip)

**Comment by TheWitness** [comment]
This is now resolved.
