### ISSUE TITLE
New thold tab in a threshold can not work properly 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#260]
I am confused about this tab, this is a newly added tab compared with cacti0.88.  what does this tab mean ? creating new threshold ? any connection with the existing threshold ?  And how the three drop down list work here with below graph ? 

**To Reproduce**
1. Go to thresholds page 
2. Add a threshold 
3. Click the threshold 
4. Go to new thold n/a tab
5. Choose datasource, create button exist, click create, page becomes blank.  Error exist
2019/02/27 16:01:31 - ERROR PHP NOTICE in  Plugin 'thold': Undefined variable: name in file: /opt/IBM/cacti/plugins/thold/thold_functions.php  on line: 4188
2019/02/27 16:01:31 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold.php[87]:save_thold(), /plugins/thold/thold_functions.php[4188]:CactiErrorHandler())
2019/02/27 16:01:31 - ERROR PHP NOTICE in  Plugin 'thold': Undefined variable: name in file: /opt/IBM/cacti/plugins/thold/thold_functions.php  on line: 4189
2019/02/27 16:01:31 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold.php[87]:save_thold(), /plugins/thold/thold_functions.php[4189]:CactiErrorHandler())
2019/02/27 16:01:31 - ERROR PHP NOTICE in  Plugin 'thold': Undefined variable: data_source_info in file: /opt/IBM/cacti/plugins/thold/thold_functions.php  on line: 4197
2019/02/27 16:01:31 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold.php[87]:save_thold(), /plugins/thold/thold_functions.php[4197]:CactiErrorHandler())
2019/02/27 16:01:31 - ERROR PHP NOTICE in  Plugin 'thold': Undefined variable: data_source_info in file: /opt/IBM/cacti/plugins/thold/thold_functions.php  on line: 4198
2019/02/27 16:01:31 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/thold/thold.php[87]:save_thold(), /plugins/thold/thold_functions.php[4198]:CactiErrorHandler())

**Expected behavior**
the newly added tab could work properly 

**Screenshots**
![screen shot 2019-02-27 at 4 08 56 pm](https://user-images.githubusercontent.com/47589910/53475233-6e3f3c00-3aaa-11e9-9ef5-d15e82153bc0.png)
![screen shot 2019-02-27 at 4 09 06 pm](https://user-images.githubusercontent.com/47589910/53475240-7303f000-3aaa-11e9-9d83-f4c483e4c673.png)
![screen shot 2019-02-27 at 4 09 22 pm](https://user-images.githubusercontent.com/47589910/53475244-75fee080-3aaa-11e9-9196-efbb441a8d01.png)
![screen shot 2019-02-27 at 4 12 42 pm](https://user-images.githubusercontent.com/47589910/53475348-af375080-3aaa-11e9-9d65-2a1dbdb0812c.png)

**Comment by netniV** [comment]
The errors @TheWitness or I will look into later, for now I just wanted to let you know that the new tab is to allow you create a custom threshold specifically for this graph on the fly as if you'd go to the Threshold list, and then clicked on the plus, selected Non-Templated, selected the device, and finally selected the graph in question.

However, it does appear to be broken!

**Comment by netniV** [comment]
I believe that this could be related to #257

**Comment by TheWitness** [comment]
@yingbaiibm, you should update to the latest develop, then run the following SQL command:

`update plugin_config set version='0.4.0.1' where directory='thold';`

Then, goto the Console -> Configuration -> Plugins, to re-upgrade the plugin.  Then, see if you can re-produce this issue.  I can not in my environment.

**Comment by TheWitness** [comment]
I've marked it resolved in that I have been making many changes around the Wizard section of the code as I continue to test and optimize the code.

**Comment by yingbaiibm** [comment]
retest passed
