### ISSUE TITLE
Thold plugin auto disabled by error 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#261]
**To Reproduce**
1. Go to threshold page, create a threshold and trigger it 
2. After threshold trigged, error exist in log and thold plugin disabled automatically 

2019/02/27 16:31:25 - ERROR PHP ERROR in  Plugin 'thold': Call to undefined function get_daysfromtime() in file: /opt/IBM/cacti/plugins/thold/thold_functions.php on line: 87
2019/02/27 16:31:25 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2019/02/27 16:31:25 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2019/02/27 16:31:25 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
2019/02/27 16:31:33 - ERROR PHP ERROR in  Plugin 'thold': Call to undefined function get_daysfromtime() in file: /opt/IBM/cacti/plugins/thold/thold_functions.php on line: 87
2019/02/27 16:31:33 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2019/02/27 16:31:33 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2019/02/27 16:31:33 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
2019/02/27 16:31:38 - ERROR PHP ERROR in  Plugin 'thold': Call to undefined function get_daysfromtime() in file: /opt/IBM/cacti/plugins/thold/thold_functions.php on line: 87
2019/02/27 16:31:38 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2019/02/27 16:31:38 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2019/02/27 16:31:38 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
2019/02/27 16:32:19 - CMDPHP Filter Variable: status, Must have a default and none is set

**Comment by netniV** [comment]
You need Cacti 1.2.2. It’s in the requirements of THold INFO file

**Comment by yingbaiibm** [comment]
@netniV So cacti 1.2.2 has solved this problem and I need to use cacti 1.2.2 instead of cacti 1.2 ?

**Comment by netniV** [comment]
1.2.2 has the function that THold is using so it's less that 1.2.2 solved the problem and more than THold relies upon it.  In reality, the issue is that Cacti's core doesn't check the upgraded plugin for it's dependenc as it should automatically disable a plugin whose dependencies are not met.  I've create a feature enhancement for just that scenario.
