### ISSUE TITLE
MySQL is sorting measured values as strings not numerics on Log tab

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#262]
![screen shot 03-01-19 at 08 45 am](https://user-images.githubusercontent.com/42470924/53642046-c9824300-3bfe-11e9-8cb9-029c9bac8746.PNG)

**Comment by netniV** [comment]
This seems to be a MySQL thing as I had the same issue on https://github.com/Cacti/cacti/issues/2419

**Comment by interduo** [comment]
I don't know if You know that also here 'In State' column has broken sorting.

**Comment by netniV** [comment]
Define here?  The logs tab doesn't have an instate as far as I recall.

**Comment by interduo** [comment]
"Threshold" tab.

**Comment by interduo** [comment]
It exists in Thold tab also is it worth to make new issue?

OK - I did https://github.com/Cacti/plugin_thold/issues/272
