### ISSUE TITLE
System incorrectly reports that you do not have access to a threshold that you do have access to

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#264]
**Describe the bug**
Given a list of thresholds, when attempting group operations, the message randomly appears that you do not have access to one or more thresholds.  However, when you look at the access, you do have access it is just that the device has now been disabled.

**Expected behavior**
Whilst the device or threshold may have been disabled, group actions again the thresholds should continue to work as long as you have permission to do so.  The function `is_graph_allowed` in the Cacti core does not allow for scenarios where group operations against even disabled items may be needed.

Threshold should probably include a checkbox to filter out these types of devices.

**Plugin (please complete the following information):**
 - Version: 1.2.1
 - Source: GitHub
 - Identifer: Latest commit was 0f56891

**Additional context**
This is very likely related to [User Admin - Effective Permissions - Disabled Devices should show denied](https://github.com/cacti/cacti/issues/2464)

**Comment by TheWitness** [comment]
This should be resolved now.  Can you test with the latest develop?
