### ISSUE TITLE
Allow Device Association/Disassociation to set Thresholds Notification as well

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#268]
It is maybe only question. I have Cacti with 300 devices and 2500 tholds. Automatic creating of host and tholds works great and helps a lot. But I have problem with thold notifications. All devices has 
Threshold Up/Down Email Notification = List below and one of my 30 notification lists.
UP/DOWN notofications works great. 
But tholds  - I must "associate" under notification lists -> mylist -> Thresholds. It is a lot of work for us.  Without this, tholds are "Log only".

I have thold template with Alert and warning notification list set to none because I have (for example)  one thold for dozens of hosts and they are in 10 notification lists. I don't want have dozens templates for every notification list.

My idea - add to thold template in Warning and Alert Notification List option "Notify the same list as Threshold Up/Down Email Notification in host settings".

Is it possible? We really need notify UP/DOWN/thold to the same list.

**Comment by netniV** [comment]
You might like my plugin, [tholdlists](https://github.com/netniV/plugin_tholdlists).  It allows you to mass import notification lists and assign them to specific graphs/thresholds.  I have a client who uses this to populate the thresholds based on the graphs of a customer to a specific notification list (all lists are prefixed with "Customer - " just to make it easier too).  They use these to notify customers of excess power usage etc.

**Comment by TheWitness** [comment]
Should that be merged?

**Comment by netniV** [comment]
I haven't touched it in a while, feel free to examine it and if you think it could be usefully integrated, I have no issues with that.

**Comment by TheWitness** [comment]
So, giving some thought.  Are you trying to have the same associations with the devices as you have to the Thresholds.  If that's the case, then we can add an option to update the Thresholds associated with the Device as well.

The rub is that if these thresholds are 'templated', we will wipe out that data every time you save the Threshold Template.  Maybe that's something we should not be doing unless you expressly ask for it.

**Comment by TheWitness** [comment]
This issues is resolved.
