### ISSUE TITLE
rpn expression ignored ?

### ISSUE THREAD

**Issue by JorisFRST** [Cacti/plugin_thold#270]
**Describe the bug**
Simple rpn expression sum of 2 datasources  
|ds:scDiskStatus|,|ds:scDiskHealthy|,+
Output of thold (value) is only the value of the Data Field specified when setting up the threshold.

**To Reproduce**
Create new threshold for a graph with 2 datasources.
set to rpn, add the two datasources.

**Expected behavior**
output should be the sum

**Screenshots**

**Plugin (please complete the following information):**
 - Version: dev 1.21
 - Source: github
 - Identifier: Mar 4, 2019

**Comment by TheWitness** [comment]
@JorisFRST, are you using Data Source Statistics?  Please advise.  If not, it will attempt to gather the expression data from the RRDfile, which will be slower.  I would add some select `cacti_log()` calls around line: 836 and line: 871 of thold_functions.php.  On line 836, something like:

```php
cacti_log('dsname:' . $dsname . ', thold: ' . $thold['id']);
```

On line 871:

```php
cacti_log('dsname:' . $dsname . ', currentval:' . $expression[$key]);
```

Post what you find for the thold in question.

**Comment by TheWitness** [comment]
To get the line numbers correct, you will have to pull the latest develop version.

**Comment by TheWitness** [comment]
No feedback.

**Comment by JorisFRST** [comment]
Sorry, was busy at work, I can do it now if you still have the time.  I'll pull the latest version first to see if it's not solved already.

**Comment by JorisFRST** [comment]
Enabling Datasource Statistics fixed my issue.

**Comment by TheWitness** [comment]
Glad that resolved it for you.
