### ISSUE TITLE
Data Source link on Data Template column is ambiguous and can lead to confusion

### ISSUE THREAD

**Issue by TheWitness** [Cacti/plugin_thold#274]
**Describe the bug**
When a Data Source has more than one Graph or has no Graph at all, the Link to create a Threshold does not currently make sense.  We have tied Thresholds to Graphs now, so in those cases, the Link on the Data Source page should be removed.  In fact, I think we should remove that feature entirely.

**To Reproduce**
1. Create a Data Source with no Graph
2. Goto Data Sources page
2. Click on the Data Template link for that Data Source
3. Notice the broken Thold page

**Expected behavior**
This type of confusion should be avoided.  Recommend removing the link functionality on the Data Template column.

**Additional Context**
Maybe we make it a settings and do two things: 1) Remove the link if there is > 1 Graph, 2) Remove the link if there is no Graph.

**Comment by netniV** [comment]
Would it not be prudent to drop them into the wizard where they can select only graphs matching the data source?
