### ISSUE TITLE
When finding data sources to template, string vs array error occurs if templates are found

### ISSUE THREAD

**Issue by spikechoi** [Cacti/plugin_thold#277]
**Describe the bug**
When I created a threshold from a data source by the template. I saw the error message from the debug log, and my threshold doesn't polling as well.
**To Reproduce**
1. Go to 'data source'
2. Click on 'create Threshold from Template'
3. See error

**Expected behavior**
Create a threshold without error and functioning.

**Screenshots**
![image](https://user-images.githubusercontent.com/48840197/54846610-3d53cf00-4d17-11e9-861f-881dc5ff597f.png)
![image](https://user-images.githubusercontent.com/48840197/54846641-4cd31800-4d17-11e9-9fbd-bec3aa0a7190.png)

**Plugin (please complete the following information):**
 - Version: 1.2.1
 - Source: [github]
 - Identifer: []

**Additional context**

**Comment by netniV** [comment]
Please download the latest version again, this error should be resolved.
