### ISSUE TITLE
When creating new thresholds, created count generates errors

### ISSUE THREAD

**Issue by spikechoi** [Cacti/plugin_thold#278]
**Describe the bug**
Create threshold from database by template. Error message showed in log.

**To Reproduce**
1 Go to 'data source'
2 Click on 'create Threshold from Template'
3 See error

**Expected behavior**
Create a threshold without error and functioning.

**Screenshots**
![image](https://user-images.githubusercontent.com/48840197/54849289-c28eb200-4d1e-11e9-85dc-17b49896e9b9.png)

**Plugin (please complete the following information):**
 - Version: [ 1.2.1]
 - Source: [github]

**Comment by netniV** [comment]
Please download the latest version, this should be resolved now.
