### ISSUE TITLE
Current value does not seem to be set or update when refreshing thresholds

### ISSUE THREAD

**Issue by spikechoi** [Cacti/plugin_thold#279]
**Describe the bug**
 SYSTEM THOLD DAEMON STATS: TotalTime:0.000 MaxRuntime:0.000 Processed:0 InProcess:27 TotalDevices:1 DownDevices:0 NewDownDevices:0 MaxProcesses:1 Completed:0 Running:0 Broken:0

**To Reproduce**
Create a threshold from the template or create from data sources.

**Expected behavior**
Current value should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/48840197/54849840-63ca3800-4d20-11e9-8fe0-f8c62898ba08.png)

**Plugin (please complete the following information):**
 - Version: [1.2.1]
 - Source: [github]
 - Identifer: []

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.5.1804 (Core)
 - Browser Firefox
 - Version
php71w-mysqlnd-7.1.26-1.w7.x86_64
php71w-cli-7.1.26-1.w7.x86_64
php71w-opcache-7.1.26-1.w7.x86_64
php71w-pdo-7.1.26-1.w7.x86_64
php71w-gd-7.1.26-1.w7.x86_64
php71w-imap-7.1.26-1.w7.x86_64
php71w-snmp-7.1.26-1.w7.x86_64
php71w-ldap-7.1.26-1.w7.x86_64
php71w-xml-7.1.26-1.w7.x86_64
php71w-process-7.1.26-1.w7.x86_64
mod_php71w-7.1.26-1.w7.x86_64
php71w-common-7.1.26-1.w7.x86_64
php71w-mcrypt-7.1.26-1.w7.x86_64
php71w-mbstring-7.1.26-1.w7.x86_64
php71w-intl-7.1.26-1.w7.x86_64
MariaDB-shared-10.0.38-1.el7.centos.x86_64
MariaDB-common-10.0.38-1.el7.centos.x86_64
MariaDB-server-10.0.38-1.el7.centos.x86_64
MariaDB-devel-10.0.38-1.el7.centos.x86_64
MariaDB-client-10.0.38-1.el7.centos.x86_64
httpd-tools-2.4.6-88.el7.centos.x86_64
httpd-2.4.6-88.el7.centos.x86_64

**Additional context**

**Comment by netniV** [comment]
This is not actually a bug, but a setup issue.

I think you have the "Daemon" option enabled.  People often enable that without actually setting up it's own cron or service process to actually do the polling.  If you have a look in the thold folder there is a thold_daemon.service that is an example of a service file for systemd systems.

**Comment by spikechoi** [comment]
Hi Sir,
I disabled the Daemon, and it works now.
It’s a pleasure to be helped by you.

**Comment by netniV** [comment]
Your welcome, glad you are sorted 👍
