### ISSUE TITLE
Threshold notification URL

### ISSUE THREAD

**Issue by spikechoi** [Cacti/plugin_thold#282]
**Describe the bug**
The URL of the notification is missing the root path.
Wrong result:
http://scilmon02/graph.php?local_graph_id=3
**Screenshots**
![image](https://user-images.githubusercontent.com/48840197/54880733-3fd33780-4e83-11e9-93f9-7c0d2e47f965.png)

Expected result:
It should be 
http://scilmon02/SCIL/graph.php?local_graph_id=3

**Plugin (please complete the following information):**
 - Version: [1.2.1]
 - Source: [github]

**Additional context**

**Comment by netniV** [comment]
This Just needs $config[‘url_path’] to be added. If that is something you can do and submit as a PR that would be good otherwise we will do so later.

**Comment by spikechoi** [comment]
Adding in which files?

**Comment by spikechoi** [comment]
I got it. Thanks for the remind.

**Comment by netniV** [comment]
Oh, I thought you'd already the URL_PATH in `include/config.php`, and that the code was wrong.  So I take it you'd missed that step and once corrected your config, it is all working fine now?

**Comment by spikechoi** [comment]
Hi Teacher,
I edited thold_functions.php
thold_functions.php:    $text = str_replace('<URL>',           "<a href='" . html_escape("$httpurl/SCIL/graph.php?local_graph_id=$local_graph_id") . "'>" . __('Click here to link in the SCIL Monitoring Tool', 'thold') . "</a>", $text);

**Comment by spikechoi** [comment]
("$httpurl/SCIL/graph.php?local_graph_id=$local_graph_id")
There is missing the root path
original is
("$httpurl/graph.php?local_graph_id=$local_graph_id")

**Comment by spikechoi** [comment]
OH My GOD i realized that the HTTP should be set to http://scilmon02/SCIL, not http://scilmon02/
HAHA

**Comment by netniV** [comment]
That’s what I wondered :)
