### ISSUE TITLE
Do not show 'Threshold Create' icon on the Graphs page for Aggregates

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#283]
**To Reproduce**
1. Go to 'Management Graphs page', choose template unix-Load Average
2. Create Aggregate graph for this graph using aggregate template 
3. Go to Graph - List View page 
4. Choose the aggregate graph and click create threshold button 
5. After choose the datasource, still can not create the threshold for this graph 

**Expected behavior**
Can create threshold for aggregate graph 

**Screenshots**
![Screen Shot 2019-03-26 at 3 32 23 PM](https://user-images.githubusercontent.com/47589910/54978990-df580d80-4fdc-11e9-96e7-6d378dc892b5.png)
![Screen Shot 2019-03-26 at 3 32 48 PM](https://user-images.githubusercontent.com/47589910/54978992-e252fe00-4fdc-11e9-8ef7-cc0729019821.png)
![Screen Shot 2019-03-26 at 3 33 07 PM](https://user-images.githubusercontent.com/47589910/54978996-e54dee80-4fdc-11e9-8c9b-136db6ad2a8d.png)
![Screen Shot 2019-03-26 at 3 33 24 PM](https://user-images.githubusercontent.com/47589910/54978997-e848df00-4fdc-11e9-99b1-25b64254e7df.png)
![Screen Shot 2019-03-26 at 3 34 05 PM](https://user-images.githubusercontent.com/47589910/54979005-ed0d9300-4fdc-11e9-9b67-6f1aaa9cab5d.png)

**Plugin (please complete the following information):**
 - Version: cacti 1.2.2, thold 1.2.1 
 - OS: rhel7.3 x86_64
 - Browser FF

**Comment by TheWitness** [comment]
@yingbaiibm, thanks for opening this.  The use of an Aggregate Graph for a Threshold is currently a feature request.  We should be removing the Create icon for this graph type.

**Comment by TheWitness** [comment]
Fixed.
