### ISSUE TITLE
SQL error after save a thold 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#288]
**Describe the bug**

**To Reproduce**
1. create a thold from thold template 
2. check log 
2019/04/04 14:27:39 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php[87]:save_thold(), /plugins/thold/thold_functions.php[4340]:thold_template_update_threshold(), /plugins/thold/thold_functions.php[4901]:update_suggested_names_from_template(), /plugins/thold/thold_functions.php[5004]:thold_expand_string(), /plugins/thold/thold_functions.php[3063]:CactiErrorHandler()) 2019/04/04 14:27:39 - ERROR PHP NOTICE in Plugin 'thold': Undefined variable: thod_data in file: /opt/IBM/cacti/plugins/thold/thold_functions.php on line: 3063 

**Plugin (please complete the following information):**
cacti 1.2.3 
thold 1.2.4 
FF
rhel73 x64

**Comment by netniV** [comment]
This has now been resolved in the development code.
