### ISSUE TITLE
Threshold filter on Thold - Log tab can not work 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#289]
**To Reproduce**
1. Go to Thold - Log tab 
2. There is threshold info created by thold template  Alert - Job Pending for X Seconds
3. Change the threshold filter to Alert - Job Pending for X Seconds [pend_jobs], can not get record 

**Expected behavior**
When change the threshold filter, can get correct record 

**Screenshots**
![Screen Shot 2019-04-04 at 5 16 35 PM](https://user-images.githubusercontent.com/47589910/55544478-c72f6f00-56fd-11e9-8280-2392305dbce3.png)
![Screen Shot 2019-04-04 at 5 13 30 PM](https://user-images.githubusercontent.com/47589910/55544484-c8f93280-56fd-11e9-94ee-cc67ccb0fd41.png)

cacti 1.2.3 
thold 1.2.4 
rhel73 x64 
FF

**Comment by TheWitness** [comment]
What is curious is that the days are set to 0 days.

**Comment by TheWitness** [comment]
@yingbaiibm, can you please confirm that the template_id in the plugin_thold_log table is > 0?

**Comment by ddb4github** [comment]
Filter 'Threshold' is still not work due to diff below.
Query_SQL append 'template_id' in SQL. It should be "td.id"

```diff
--- thold/thold_graph.php    2019-04-16 23:31:58.000000000 +0800
+++ thold/thold_graph.php     2019-04-18 23:16:24.042561506 +0800
@@ -1065,7 +1065,7 @@
        } elseif (get_request_var('threshold_id') == '0') {
                $sql_where .= (strlen($sql_where) ? ' AND':'') . ' td.id IS NULL';
        } elseif (get_request_var('threshold_id') > 0) {
-               $sql_where .= (strlen($sql_where) ? ' AND':'') . ' td.thold_template_id=' . get_request_var('threshold_id');
+               $sql_where .= (strlen($sql_where) ? ' AND':'') . ' td.id=' . get_request_var('threshold_id');
        }

        if (get_request_var('status') == '-1') {

**Comment by yingbaiibm** [comment]
Passed retest, close
