### ISSUE TITLE
Feature Request: Automatic HRULE

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#29]
Auto generate HRULE lines for min/max thresholds on graphs to visually represent where the thresholds are set and/or being exceeded.

**Comment by cigamit** [comment]
Nice concept, but here is the rub:

1) More than one data source per graph
2) More than 1 threshold per data source
3) More than one logging level per threshold

The graph would get messy pretty quick.  So, what do you think the workaround would be?

**Comment by smiles1969** [comment]
Perhaps store a bool variable in a table to track whether min and max HRULE is enabled per graph and/or data source?

This would allow each threshold to be enabled or disabled depending on graph.

If by logging level you mean warning vs alert, I would make the alert HRULE solid and the warning HRULE dotted.

The HRULE should show in the legend with a color that contrasts it's data source color if it's an area type.

**Comment by cigamit** [comment]
I would say put it on the threshold.  So, add two columns to the thold_data, warning HRULE and alert HRULE checkboxes, make one orange, and the other red.  What do you think about that?  It could still get messy, but the mess would be the responsibility of the author of the thold.

**Comment by smiles1969** [comment]
Sounds good!

**Comment by smiles1969** [comment]
Below is an example of how I envision your proposal would look:

![image](https://cloud.githubusercontent.com/assets/17500126/21867746/2ec09fc8-d815-11e6-8897-a317b8646fd1.png)

And the Graph Debug would look similar to this:

![image](https://cloud.githubusercontent.com/assets/17500126/21867759/40624858-d815-11e6-99b3-8f29fff2fd4b.png)

**Comment by cigamit** [comment]
Yea, the whole concept is simple enough, it's just about getting time to execute the change.

**Comment by cigamit** [comment]
Okay, this is done now.  Give it a try.  I'm going to close, but feel free to comment.

**Comment by smiles1969** [comment]
Very cool, thanks Jimmy!

**Comment by smiles1969** [comment]
For some reason the text formatting tags are not being interpreted in the legend,  and are showing on the graph for bold and underline. Is this a setting I need to change or a bug?

Looks like this:
<u><b>Threshold Alert/Warning Values</b>                         </u>

**Comment by cigamit** [comment]
Update lib/rrd.php.  Pango markup is always on for RRDtool versions 1.3 and above.

**Comment by smiles1969** [comment]
I updated rrd.php (No change)

I was running rrdtool 1.4.8, but have now upgraded to rrdtool 1.6.999 and made sure it compiled with pangocairo. I am still seeing the tags on the legend. 

I have tried different browsers with no change.

I created new graphs from scratch and applied new thresholds, no change.

Not sure what else to try.

**Comment by smiles1969** [comment]
Nevermind, I just pulled the latest commit from cacti/cacti which includes an update to lib/rrd.php and everything is working now :)

Thanks again, this is awesome!

**Comment by cigamit** [comment]
I found a major bug, not with this but in thold.  Just fixed it.  However, for some reason, I'm not getting all my HRULES on the graph.  Still looking into it.

**Comment by smiles1969** [comment]
I noticed graphs with area stacks were not showing HRULES but I figured it was something I was doing wrong.

**Comment by cigamit** [comment]
Yea, it was operator error otherwise known as PEBKAC.  The darn thing was disabled.  Funny.

**Comment by smiles1969** [comment]
Loose nut on the keyboard?

**Comment by cigamit** [comment]
But the other bug was a dusey.  Not sure how it was missed.  There's been a lot of code refactoring.  So, spif happens.

**Comment by cigamit** [comment]
I also just made the output a bit more appealing on the thold.php page.

**Comment by smiles1969** [comment]
I see that.. Are you having any issue with area graphs, like the standard unix drive space graph showing the HRULE lines?

**Comment by smiles1969** [comment]
Oh, it's printing, but it's at 0 on the y axis.

![image](https://cloud.githubusercontent.com/assets/17500126/22128766/bcfda990-de67-11e6-8b9b-f037d3871d95.png)

**Comment by smiles1969** [comment]
Haha I need more 0's to get it to Gb

**Comment by smiles1969** [comment]
See, this is paying off already having the visual

**Comment by smiles1969** [comment]
There seems to be something off between Gig and Meg calcualtion still

![image](https://cloud.githubusercontent.com/assets/17500126/22128903/a130b08a-de68-11e6-96c4-e1dc4ac4f841.png)

**Comment by smiles1969** [comment]
I fixed the number display issue by changing the function number_format_i18n to

![image](https://cloud.githubusercontent.com/assets/17500126/22129432/8ae19206-de6b-11e6-97c3-c0befff02960.png)

But this must be independant issue from the HRULE printing at 0 on Y axis.

Graph looks better now for legend.

![image](https://cloud.githubusercontent.com/assets/17500126/22129459/c556b6c8-de6b-11e6-9a9b-ba39172c0cff.png)

**Comment by smiles1969** [comment]
Heres another graph that the Y axis is only in Mbps, and it seems to work for both HRULES and Legend display.. Only thing that seems odd is it shows 1000M for Alert and 5 G for warn:

![image](https://cloud.githubusercontent.com/assets/17500126/22130025/489eb1fe-de6f-11e6-80b6-cf71878376ca.png)

**Comment by smiles1969** [comment]
I guess the checks should be >= in number_format_i18n to avoid the above.. I have backed out my changes to this function.

**Comment by cigamit** [comment]
Yea, the number format assumes the data fed to it is an absolute number and not something like 1.2 == 1.2KBytes.  I'll make the changes shortly for >=.

**Comment by smiles1969** [comment]
I'm still trying to understand the Drive space issue between M and G

![image](https://cloud.githubusercontent.com/assets/17500126/22130444/9eb48d0a-de71-11e6-9466-c4192c344ffb.png)

![image](https://cloud.githubusercontent.com/assets/17500126/22130459/bc082fe2-de71-11e6-8a7d-4a668b0f78c6.png)

**Comment by cigamit** [comment]
Well, that's odd.  Screen shot the edit thold page.

**Comment by cigamit** [comment]
Well looking at the Graph Template, it's using the 'Multiply by 1024' CDEF to get the real value.  Which means what it's storing in the RRDfile is in KBytes.  It's a bit of a mess.  Have to think about this.  Does the thold still work if you use that CDEF? (The graph enhancement will go away, but test the CDEF anyway).

**Comment by cigamit** [comment]
I'm testing now using the cdef.  That will be what has to be done.  I'll be committing something a little later.

**Comment by cigamit** [comment]
You should be able to use the 'Multiply by 1024' cdef to that thold now, and things will be fine.

**Comment by smiles1969** [comment]
Looks Great!

![image](https://cloud.githubusercontent.com/assets/17500126/22159968/fe44d6f2-df08-11e6-904e-7a930eecfc07.png)
