### ISSUE TITLE
New Requirement: CLI to import thold template

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#292]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Provide a CLI to import single or N-in-1 thold template
Or register hook to Cacti core import interface

**Describe alternatives you've considered**
N/A,  WebUI Import is not my required

**Additional context**
N/A

**Comment by TheWitness** [comment]
This is now resolved.

**Comment by TheWitness** [comment]
New command is 

```shell
php -q cli_import.php --filename=/path/to/some/xml/file
```
