### ISSUE TITLE
[Thold][Notification List] php error, undefined selected_items in notify_lists.php

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#293]
**To Reproduce**
php error when check notification List page 
2019/04/10 15:19:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/notify_lists.php[58]:form_actions(), /plugins/thold/notify_lists.php[763]:CactiErrorHandler())
2019/04/10 15:19:41 - ERROR PHP NOTICE in Plugin 'thold': Undefined variable: selected_items in file: /opt/IBM/cacti/plugins/thold/notify_lists.php on line: 763

**Plugin (please complete the following information):**
 - Version: cacti 1.2.3  thold 1.2.4 

**Desktop (please complete the following information):**
 - OS: rhel73 x64
 - Browser: FF

**Comment by TheWitness** [comment]
Resolved.  Please retest.

**Comment by yingbaiibm** [comment]
passed retest
