### ISSUE TITLE
php error Constant STAT_NORMAL,STAT_LO,STAT_HI already defined

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#299]
**Describe the bug**
Error exist in log 

2019/04/22 16:43:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/var/www/html/cacti/settings.php[25]:unknown(), /include/auth.php[28]:unknown(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_config_insert(), /plugins/thold/includes/settings.php[83]:CactiErrorHandler())
2019/04/22 16:43:18 - ERROR PHP NOTICE in Plugin 'thold': Constant STAT_NORMAL already defined in file: /opt/IBM/cacti/plugins/thold/includes/settings.php on line: 83
2019/04/22 16:43:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/var/www/html/cacti/settings.php[25]:unknown(), /include/auth.php[28]:unknown(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_config_insert(), /plugins/thold/includes/settings.php[82]:CactiErrorHandler())
2019/04/22 16:43:18 - ERROR PHP NOTICE in Plugin 'thold': Constant STAT_LO already defined in file: /opt/IBM/cacti/plugins/thold/includes/settings.php on line: 82
2019/04/22 16:43:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/var/www/html/cacti/settings.php[25]:unknown(), /include/auth.php[28]:unknown(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_config_insert(), /plugins/thold/includes/settings.php[81]:CactiErrorHandler())
2019/04/22 16:43:18 - ERROR PHP NOTICE in Plugin 'thold': Constant STAT_HI already defined in file: /opt/IBM/cacti/plugins/thold/includes/settings.php on line: 81
2019/04/22 16:43:16 - CMDPHP PHP ERROR NOTICE Backtrace: (/var/www/html/cacti/settings.php[25]:unknown(), /include/auth.php[28]:unknown(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_config_insert(), /plugins/thold/includes/settings.php[83]:CactiErrorHandler())
2019/04/22 16:43:16 - ERROR PHP NOTICE in Plugin 'thold': Constant STAT_NORMAL already defined in file: /opt/IBM/cacti/plugins/thold/includes/settings.php on line: 83 

**Plugin (please complete the following information):**
cacti 1.2.3
thold 1.2.4

**Comment by TheWitness** [comment]
Resolved.
