### ISSUE TITLE
Install Thold ERRROR

### ISSUE THREAD

**Issue by diditonf** [Cacti/plugin_thold#3]
I getting this error when i try install thold...

**[Wed Jun 15 19:44:09.058317 2016] [:error] [pid 3437] [client 177.117.26.214:41986] PHP Fatal error:  Call to undefined function __() in /usr/share/cacti/plugins/thold/includes/settings.php on line 89, referer: http://177.130.1.245/cacti/graphs.php?action=graph_edit&id=18**

> 	$messages['thold_save'] = array(
> 		'message' => __('A template with that Data Source already exists!'),
> 		'type' => 'error'
> 	);

**Comment by cigamit** [comment]
Which version of Cacti?  The current dev version (the one in git) only works with Cacti 1.0.  You also fail to mention your distro version.  That particular function is part of the internationalization, some distros require a separate package in order to support gettext.

**Comment by cigamit** [comment]
No response.
