### ISSUE TITLE
Thold shows multiple tabs as 'selected' when first creating a thold

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#300]
**Describe the bug**
thold show two tabs as 'selected'  if  I create thold for mid of three rrd only.
Not sure why test case pass if thold is created with the first rrd.

**To Reproduce**
1. Create a thold from graph that have three rrd like "Load Average". Ensure the mid of rrds is used by created thold. 
2. Click left or right rrd(non-created-thold)
3. See error
![thold_tab_selected_error](https://user-images.githubusercontent.com/17589018/56505101-38b84b80-654d-11e9-970a-b1471eb4191c.png)

**Comment by TheWitness** [comment]
Resolved.
