### ISSUE TITLE
Thold Graph does not substitute comment for warn/alert hrule

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#301]
**Describe the bug**
Thold Graph does not substitute comment for warn/alert hrule

**To Reproduce**
1. Create a thold from graph with warn/alert hi/low
2. enable warn/alert hrule with proper color
3. Check comments area of thold graph 
![thold_hrule_line_comment_error](https://user-images.githubusercontent.com/17589018/56505694-e6782a00-654e-11e9-97cd-ba4cfad2962a.png)

**Comment by TheWitness** [comment]
Resolved.

**Comment by ddb4github** [comment]
Still.
Should also change name to name_cache at line: 487, 491, 517, 521

**Comment by TheWitness** [comment]
Thanks for pointing out.  Resolved now.
