### ISSUE TITLE
missed three hook: thold_update_hostsalarm, thold_reset_hostsalarm,  thold_delete_hostsalarm

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#303]
Required three hook: thold_update_hostsalarm, thold_reset_hostsalarm,  thold_delete_hostsalarm to reuse thold breach items in another plugin

Cacti 1.2.3
Thold 1.2.4

**Comment by yingbaiibm** [comment]
@TheWitness  we need these three hooks,  in previous thold 0.4.0.1, these are exist.

**Comment by TheWitness** [comment]
@yingbaiibm, I must have missed something.  Please send direct email relative to what was missed.

**Comment by TheWitness** [comment]
I'm going to close this as it's really not applicable to thold at the moment.  In the future, if you review the Enhancement requests, there will be a whole new level of notification going into the tool in the next several releases.
