### ISSUE TITLE
Warn Cacti Administrator if the Thold Daemon is Down

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#304]
**Is your feature request related to a problem? Please describe.**
Currently, uses can enable the option to utilise the THold Daemon but often fail to create the cron settings that need to accomodate this.  This leads to head scratching as thresholds are not alerted on, no data seems to be being picked up, etc.

**Describe the solution you'd like**
If enough polling cycles pass without the thold daemon even starting, a warning should be issued to the primary administrator and the option to use the daemon should be turned off.  This will then start the polling process using the standard inline polling methods allowing notifications to at least begin again.

**Describe alternatives you've considered**
We could just send the email notification, but with full instructions on what is required to enable the daemon.  Again, this should be repeated until the problem is resolved or the daemon option is turned off.

**Comment by TheWitness** [comment]
Okay, this is implemented.  Changed the title to inform the administrator rather than 'disable'.
