### ISSUE TITLE
DBCALL ERROR: SQL Save on table 'plugin_thold_log': Column 'local_graph_id' does not exist, unable to save!

### ISSUE THREAD

**Issue by john-d13** [Cacti/plugin_thold#306]
Recently upgrade to Cacti 1.2.3.  Installed latest version of thold.  Thresholds are being triggered successfully but unable to send email to notification list.   Here is an error in the log that may describe the issue.

05/03/2019 10:13:57 - DBCALL ERROR: SQL Save on table 'plugin_thold_log': Column 'local_graph_id' does not exist, unable to save!
--
05/03/2019 10:13:57 - MAILER ERROR:
05/03/2019 10:13:57 - THOLD: Sending email to 'john@hotmail.com'
05/03/2019 10:13:57 - THOLD: Preparing to send email

**Comment by netniV** [comment]
Do you have the stack trace that occurs just before this?  local_data_id is on the thold_data table so should always exist unless this is a save for a different table.

**Comment by TheWitness** [comment]
I would suspect that your plugin_thold_log was not properly upgraded as the schema should look as follows:

```sh
MariaDB [cacti]> desc plugin_thold_log;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int(12)      | NO   | PRI | NULL    | auto_increment |
| time            | int(24)      | NO   | MUL | NULL    |                |
| host_id         | int(10)      | NO   | MUL | NULL    |                |
| local_graph_id  | int(10)      | NO   | MUL | NULL    |                |
| threshold_id    | int(10)      | NO   | MUL | NULL    |                |
| threshold_value | varchar(64)  | NO   |     |         |                |
| current         | varchar(64)  | NO   |     |         |                |
| status          | int(5)       | NO   | MUL | NULL    |                |
| type            | int(5)       | NO   | MUL | NULL    |                |
| description     | varchar(255) | NO   |     |         |                |
+-----------------+--------------+------+-----+---------+----------------+
10 rows in set (0.00 sec)
```

What version did you upgrade from?

**Comment by TheWitness** [comment]
No feedback.

**Comment by ddb4github** [comment]
Due to https://github.com/Cacti/plugin_thold/issues/329#issuecomment-499553290
