### ISSUE TITLE
Thold should log thold device down and recovering to Cacti log for syslog forwarding

### ISSUE THREAD

**Issue by eholz1** [Cacti/plugin_thold#307]
Hello All,

I am trying to understand how the cacti log file gets written. I am using cacti-1.1.38,
and sending messages (some) to the syslog file, in my case "messages".
When a device goes down I always get the "ERROR" message in "messages".
BUT when a device comes backup I do not get the "NOTICE" message that indicates the 
device has "RECOVERED".  This message is in the cacti.log file, but so far I have been unable
to get this message in the syslog file.

Is there some sort of php mod that needs to be done to accomplish this?
Thanks for a great forum.
eholz1

**Comment by adamsla** [comment]
That is a core cacti setting.  So, there are two ways to handle that.

1) Feature in cacti that allows 'NOTICE' to forward to syslog
2) Change the message level to a 'WARNING' instead of 'NOTICE'.

I wrote this thing in the stone age, before I knew how to spell 'syslog'.

**Comment by TheWitness** [comment]
I hope you got my message.  I think that short term, the best thing to do is change the message to a WARNING message instead of NOTICE.

**Comment by TheWitness** [comment]
I think the notification on up/down are handled in the Monitor plugin presently.  Are you using the Monitor plugin?

**Comment by eholz1** [comment]
Thank you so much, I will look into this, and I am not using the monitor plug-in, I will check it out, and install, and test.
Thanks Again for replying,
eholz1

**Comment by eholz1** [comment]
Hello 'Witness'
Monitor plugin not quite work (cacti-1.1.38), php 5.3, I repalced the split() with explode() on line 33, and got around that error. but now I get an error, which disables the plugin, about call to undefined function:
function get_host_tree_array($where = "",$only_hosts = false) {
        $leafs = array();
        $branchleafs = 0;
        $tree_list = get_graph_tree_array();
not sure where that is defined. it shows get_graph_tree_array() as undefined

eholz1

**Comment by eholz1** [comment]
Just a side note, I am thinking that cacti-1.1.38 already has the UP/DOWN handled by the Threshold tab. It handles sending the email message(s) UP or DOWN, and the cacti.log file does contain a line with "NOTICE", but that never makes it to the syslog file.

**Comment by eholz1** [comment]
Hello - thanks, stone age, I will give it a shot, NOTICE to WARNING

tHANKS
EHOLZ2

**Comment by TheWitness** [comment]
I think Monitor is only compatible with 1.2+.  You must be using an old version as I don't think there is split in that one.

**Comment by cigamit** [comment]
Okay, I reviewed this and made some changes to help your logging scenario.

**Comment by cigamit** [comment]
Close if you are okay with the changes.  Host[] entries changed to Device[] per the cacti standard.

**Comment by TheWitness** [comment]
No feedback.
