### ISSUE TITLE
Plugin Thold Active 1.2.4 but not showing in cacti 1.1.19

### ISSUE THREAD

**Issue by inetactief** [Cacti/plugin_thold#308]
We have update cacti from 0.8.8b to 1.1.19 on CentOS 6 
Before on 0.8.8b we use version 0.5 Thold plugin that works very good.
 So i download a new plugin 1.2.4 and set this in the plugin /usr/share/cacti/plugins/thold/ 
On Plugin Management i install and active the plugin. That look good. But nothing happen. 
I can not find anywhere the Thold settings. I try to find the log. 

I have not deinstall 0.5 on 0.8.8b before upgrading, Is that a problem?

We use PHP 5.6.40 ( i upgrade from 5.4 to 5.6) also update the database mysql from 5.1 to 5.5.6

**Comment by TheWitness** [comment]
It's compatible with Cacti 1.2+ only.

**Comment by inetactief** [comment]
okay i use what is on the download page: https://www.cacti.net/download_cacti.php 
yum install cacti
This is the last version for me 1.1.19. Is there way to update on yum to the last version 1.2+?

**Comment by inetactief** [comment]
On 1.2.4 in the README.md there is:
NOTE: The Thold plugin that is in GitHub is ONLY compatible with Cacti 1.0.0 and above!

But i download a older version  thold-1.0.6 https://github.com/Cacti/plugin_thold/releases
Looks like that works.
