### ISSUE TITLE
thold Version 1.2 not work Cacti Version 1.1.27

### ISSUE THREAD

**Issue by fouadmfam** [Cacti/plugin_thold#313]
i have cacti v 1.1.27 i tried to install thold v1.2 on that version and after installed success and enable the plugin i could not find the settings or tab for thresholds so i tried older version of plugin thold and i got error.

Validation error for variable id with a value of plugin_thold-1.0.6. See backtrace below for more details.

(/plugins.php: 51 get_filter_request_var)(/lib/html_utility.php: 435 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

please help me to find a solution 
thank you.

**Comment by TheWitness** [comment]
Thold 1.2 requires Cacti 1.2.2.  Please upgrade if you wish to use the Thold 1.2 stream.
