### ISSUE TITLE
Can not create threshold with data qurey item required 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#317]
**To Reproduce**
1. Go to Templates - Threshold 
2. Add a threshold template for a Data Template 
![Screen Shot 2019-05-16 at 5 08 09 PM](https://user-images.githubusercontent.com/47589910/57841751-b8100680-77fd-11e9-980b-3e32e969f23c.png)

3. Go to Management - Threshold page 
4. Create a theshold based on created threshold template, require data query items and can not create threshold. 
![Screen Shot 2019-05-16 at 5 06 13 PM](https://user-images.githubusercontent.com/47589910/57841784-c5c58c00-77fd-11e9-9ba4-8ecc3551ba0e.png)

**Plugin (please complete the following information):**
 - Version: cacti 1.2.3
                  Thold 1.2.4

**Comment by TheWitness** [comment]
@yingbaiibm, this is not a bug.  Templates have no idea of what graphs have been created.  So, even for a Data Query Template, they don't know the index of the item to be selected.  Now, when creating a Threshold using the new interface, you have the opportunity to select.  I hope that is clear.

**Comment by yingbaiibm** [comment]
@TheWitness  I know that.  But since we can't create threshold in data query,  we should not let user to have the chance to get here.   I would ask, why you let me able to create a threshold template, but does not allow me to create a threshold from the created threshold template ?  

Expect behavior: 
1) Should not let user to create threshold template for none-supported data template. 
2) Hard code the threshold template drop down list with supported template, do not show the user created threshold template.

**Comment by TheWitness** [comment]
Sorry @yingbaiibm, but creating thold template for data query data sources is like the most important feature in thold. Take for example Traffic Graphs, those thold templates are what 99% of users create.   So,  it's a non-starter.

**Comment by yingbaiibm** [comment]
@TheWitness  So can we just hard code the threshold template drop down list when creating the threshold like we do before ?    Creating threshold template is fine, we just do not show them in drop down list when creating threshold.

**Comment by yingbaiibm** [comment]
![Screen Shot 2019-05-20 at 2 40 34 PM](https://user-images.githubusercontent.com/47589910/58001261-98365680-7b0d-11e9-84f0-83eb13b4bc24.png)
