### ISSUE TITLE
Thold templates is not able to be migrated due to hash is not identical between fresh install and upgrade

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#318]
**Describe the bug**
Thold templates is not able to be migrated due to hash is not identical between fresh install and upgrade

**To Reproduce**
1. Under Cacti 0.8.8c + Thold  0.4.4
    Create several thold template
    Upgrade to Cacti 1.2.3 + Thold 1.2.4
    Export thold templates as xml file for fresh install of "Cacti 1.2.3 + Thold 1.2.4" usage
2. Repeat steps above, and then import "thold template" xml file
3. Check thold templates page
    Each template is duplicated.

**Expected behavior**
non-duplicated
>>>generate hash by 'thold template name"

**Plugin (please complete the following information):**
 - Thold 1.2.4
 - github develop branch

**Comment by TheWitness** [comment]
@ddb4github, Can you please provide a dump of your 0.8.8 database, and the results of the dump of the 1.2.4 database after the issue has occurred.  Send to my normal email.

**Comment by TheWitness** [comment]
@ddb4github, I'm going to mark unverified since it appears after our conversation, that you are using a proprietary way to import the templates.  I suggest you repackage to use an official XML file for the template exports that contain the hash.

**Comment by ddb4github** [comment]
> @ddb4github, I'm going to mark unverified since it appears after our conversation, that you are using a proprietary way to import the templates. I suggest you repackage to use an official XML file for the template exports that contain the hash.

@TheWitness The major issue is about case:
Way#1 .    For official thold template XML file:

1. thold developer(me) upgrade thold from 0.4.1 to 1.2
2. during step#1,  "upgrade script" generate `hash-A` for a thold template.
3. thold developer export 'thold template' as a official template XML
4. `thold 1.2 fresh user` will use this XML as OoB thold template

Way#2:     For original thold 0.4.1 user: 
      
 * upgrade script will generate `hash-B` for a same thold template.

**Comment by cigamit** [comment]
I suggest you add a hook in the upgrade script so that the standard templates all get the same hash upon upgrade.

**Comment by TheWitness** [comment]
I believe that @cigamit is correct, is the upgrade handling the creation of the hash?  Do the default templates have a hash already.  Seems hard coding in the upgrade and the XML file is the way to go.

**Comment by TheWitness** [comment]
No feedback.
