### ISSUE TITLE
Can not show disabled device in Thold - Device Status page 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#321]
**To Reproduce**
1. Add a device and disable it 
2. Go to Thold - Device Status page 
3. Choose Status Filter as All, can not see disabled device 

**Expected behavior**
1. Can show the disabled device when choose status as All
2. Status drop down list option has the value of Disabled, this is missed compared to thold 0.4.0.1 

**Plugin (please complete the following information):**
 - Version:cacti 1.2.3 
 - thold development code of May 20.

**Comment by TheWitness** [comment]
This is a new setting in the users profile called 'Hide Disabled'.  It is not a bug.  If you disabled 'Hide Disabled', you will be able to view the Disabled Devices.

**Comment by yingbaiibm** [comment]
Thanks, get this and works fine.
