### ISSUE TITLE
Standalone thresholds based on graph with serveral DS don't work for DS after the 1st one...

### ISSUE THREAD

**Issue by diazdw** [Cacti/plugin_thold#322]
Hello,

I'm using Cacti 1.2.3 with Thold 1.2.4 (development branch, last zip).

I've created a graph (using a SNMP - Generic 2 OID graph template) based on 2 independent data sources (using SNMP - Generic OID data template), both of them feeded by SNMP OID's (not network traffic related, but custom OID's, created by extending the standard Linux SNMP agent, to monitor --count-- some financial transactions from a log file).

I've created a standalone (not template based) threshold for the second data source in that graph and added some dummy High/Low values to test the threshold.

It seems, thold is unable to read the value in that second data source (which internal name is snmp_oid_2); current value always says 0.00 (which is false) and threshold is never triggered.

No errors are shown in Cacti log file.

**Comment by TheWitness** [comment]
You should upload a screen shot.  Also, upload as screen shot of the Graph with debug turned on so we can see the RRDtool syntax.

**Comment by diazdw** [comment]
Hello,

Here are the screenshots:

![Console -} Graph Management -} (Edit)](https://user-images.githubusercontent.com/50931653/58217062-4da80c00-7cbe-11e9-932f-60bb54832a82.png)

![Thold](https://user-images.githubusercontent.com/50931653/58217068-54368380-7cbe-11e9-816f-be7ba3475cca.jpg)

**Comment by TheWitness** [comment]
I wonder if that is roundoff.  Maybe make the precision 3 digits after the decimal.

**Comment by TheWitness** [comment]
I've confirmed that the second and third data sources are working.  Right now the values are rounded to two digits.  There is a function called thold_format_number() that takes the second option as the number of decimal places to display, why don't you manually change to 4 for that page and see if it looks right.

**Comment by diazdw** [comment]
Hello,

I made the suggested changed everywhere I found that function. Unfortunately, no luck: Problem persists:

![screencapture-192-168-175-30-cacti-plugins-thold-thold-php-2019-05-23-10_09_49](https://user-images.githubusercontent.com/50931653/58270542-4a0c9780-7d47-11e9-93bb-9e4fb7eb48bc.png)

![thold_2019-05-23_101026](https://user-images.githubusercontent.com/50931653/58270547-4da01e80-7d47-11e9-9569-f56a116d1ebb.jpg)

**Comment by diazdw** [comment]
Hello,

I've confirmed this is a bug, when retrieving/saving datasource and graph data for the threshold to store them in thold_data table: Field local_data_id is saved with wrong value (always referencing the first data source added to graph) and graph_template_id is saved with 0 value. I manually changed those values to the correct ones in the table, and all failing threshold started to work as expected.

**Comment by TheWitness** [comment]
Wow, what a great catch.  Fixing now.

**Comment by TheWitness** [comment]
Fixed.
