### ISSUE TITLE
value not correct in Thold - Log page 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#324]
**To Reproduce**
1. Create a threshold for cluster available memory 
2. Trigger the threshold 
3. Go to Thold - Log page to check log info 
4. The value for Alert value and measured value incorrect. 

**Screenshots**
![Screen Shot 2019-05-24 at 2 58 50 PM](https://user-images.githubusercontent.com/47589910/58308930-6686fd80-7e35-11e9-9f75-a12951f719fd.png)
![Screen Shot 2019-05-24 at 2 59 44 PM](https://user-images.githubusercontent.com/47589910/58308933-6b4bb180-7e35-11e9-9468-9b29903adeea.png)

**Plugin (please complete the following information):**
 - Version: cacti 1.2.3 
                  Thold of May 23

**Comment by TheWitness** [comment]
Renamed a few functions to me this more clear.

**Comment by yingbaiibm** [comment]
Closed retest
