### ISSUE TITLE
In State status incorrect for threshold 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#325]
**To Reproduce**
1. Add two threshold for graph cluster - available memory  with two different datasource, mem and swp
2. Trigger two threshold
3. On threshold In state value incorrect. Always be Since Created 

**Screenshots**
![Screen Shot 2019-05-24 at 3 14 59 PM](https://user-images.githubusercontent.com/47589910/58309458-e2357a00-7e36-11e9-87d6-19f4b0c6160e.png)

**Plugin (please complete the following information):**
 - Version: cacti 1.2.3
                  Thold development code of May 23

**Comment by TheWitness** [comment]
This was caused by the "Never" alert check frequency.  "Never" has not been removed from the alert check frequency/duration.

**Comment by yingbaiibm** [comment]
closed test, never option dropped under breached duration dropdown list
