### ISSUE TITLE
php error for thold_functions.php

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#327]
php error exist

2019/05/24  14:50:12 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/thold/thold.php[135]:thold_edit(),  /plugins/thold/thold.php[1273]:thold_get_lastread_for_display(),  /plugins/thold/thold_functions.php[3565]:CactiErrorHandler())
2019/05/24 14:50:12 - ERROR PHP NOTICE in  Plugin 'thold': Undefined  index: lastread in file:  /opt/IBM/cacti/plugins/thold/thold_functions.php  on line: 3565

2019/05/24 14:50:12 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/thold/thold.php[135]:thold_edit(),  /plugins/thold/thold.php[1273]:thold_get_lastread_for_display(),  /plugins/thold/thold_functions.php[3560]:CactiErrorHandler())
2019/05/24 14:50:12 - ERROR PHP NOTICE in  Plugin 'thold': Undefined  index: data_source_name in file:  /opt/IBM/cacti/plugins/thold/thold_functions.php  on line: 3560

cacti 1.2.3
thold of May 23

**Comment by nekretnine-srbija** [comment]
Thanks for resolving it.
