### ISSUE TITLE
Non classic theme Device Selection

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#33]
There seems to be an issue with the Device selection when not using the classic theme where there are several devices missing from the list. When I try to add a new threshold from Console->Thresholds->Add, the behavior is different when I'm in a theme other than classic.

The issue appears to be in the function html_host_filter in cacti/lib/html.php.

Added some debugging to show me what is being passed to the function (get_request_var('host_id')) and the value is -1.. Given that value being passed, and following the code function, I don't see where it would actually perform a new query to look up devices unless it were classic theme.

**Comment by cigamit** [comment]
I have not tested that path in the navigation.  Going to test it now.

**Comment by cigamit** [comment]
That's Autocomplete.  Just select double click in the Device field and start typing.  You should be pleasantly surprised.  By default, the Autocomplete only shows the first 20 Devices.

**Comment by smiles1969** [comment]
It was showing 30 devices and I have more than that. It was different in classic than dark or paw

Sent from my iPhone

On Jan 16, 2017, at 7:19 PM, Jimmy Conner <notifications@github.com<mailto:notifications@github.com>> wrote:


That's Autocomplete. Just select double click in the Device field and start typing. You should be pleasantly surprised. By default, the Autocomplete only shows the first 20 Devices.

**Comment by cigamit** [comment]
Correct.  Classic is supposed to be 'old school' cacti that provides all the devices in one drop down.  Think about how long that would make the browser hesitate if you had 20k devices.  That's why we use Autocomplete.
