### ISSUE TITLE
Undefined index: local_data_id if graph title include '|input_xxxxx|'

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#332]
**Describe the bug**
Thold graph title is not updated during creating if title include '|input_xxxx|'
Then view graph will log PHP error

```log
2019/05/29 19:52:54 - ERROR PHP NOTICE: Undefined index: local_data_id in file: /var/www/html/cacti/lib/rrd.php on line: 2424
2019/05/29 19:52:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_image.php[132]:rrdtool_function_graph(), /lib/rrd.php[1347]:rrd_function_process_graph_options(), /lib/rrd.php[1151]:rrd_substitute_host_query_data(), /lib/rrd.php[2424]:CactiErrorHandler())
```

**To Reproduce**
1. Create or modify a graph template, add a valid '|input_xxxx|' into title field
2. Edit related datasource template, enable 'input field' in 'Custom Data' section
3. Create a thold from above datasource template
4. View new created graph
5. Check cacti.log

**Comment by TheWitness** [comment]
This is a Cacti issue and has been resolved here: https://github.com/Cacti/cacti/commit/756b0779c642d50b2d7296b8617d408a0c51e8d1
