### ISSUE TITLE
Undefined  index: data_source_name in file: thold_functions.php

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#334]
Create thold and found error 
2019/05/30  11:03:02 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/thold/thold.php[135]:thold_edit(),  /plugins/thold/thold.php[1286]:thold_get_column_by_cdef(),  /plugins/thold/thold_functions.php[3677]:CactiErrorHandler())
2019/05/30 11:03:02 - ERROR PHP NOTICE in  Plugin 'thold': Undefined  index: data_source_name in file:  /opt/IBM/cacti/plugins/thold/thold_functions.php  on line: 3677

Cacti 1.2.3
Thold development code of May 29

**Comment by TheWitness** [comment]
This has been resolved.

**Comment by yingbaiibm** [comment]
passed retest
