### ISSUE TITLE
Undefined index: desc in file: /opt/IBM/cacti/plugins/thold/thold_functions.php

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#335]
Found php error when check ack function 

2019/05/30 14:53:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_graph.php[64]:thold_threshold_ack(), /plugins/thold/thold_functions.php[5632]:ack_logging(), /plugins/thold/thold_functions.php[3856]:thold_log(), /plugins/thold/thold_functions.php[1485]:CactiErrorHandler())
2019/05/30 14:53:10 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: desc in file: /opt/IBM/cacti/plugins/thold/thold_functions.php on line: 1485

**Comment by TheWitness** [comment]
This is resolved now.

**Comment by yingbaiibm** [comment]
passed retest
