### ISSUE TITLE
cacti 1.2.4 and THOLD 1.2.4 check_all_thresholds error

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#336]
Hello Guys 

I am seeing the following errors come up every now and again from THOLD
Not sure if there is something on my end but everything seems to be working fine

2019/05/31  10:31:16 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[796]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:thold_poller_bottom(),  /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(),  /plugins/thold/includes/polling.php[471]:thold_check_threshold(),  /plugins/thold/thold_functions.php[2166]:thold_command_execution(),  /plugins/thold/thold_functions.php[3311]:thold_set_environ(),  /plugins/thold/thold_functions.php[3373]:putenv(), CactiErrorHandler())
--
2019/05/31 10:31:16 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[796]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:thold_poller_bottom(),  /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(),  /plugins/thold/includes/polling.php[471]:thold_check_threshold(),  /plugins/thold/thold_functions.php[2166]:thold_command_execution(),  /plugins/thold/thold_functions.php[3311]:thold_set_environ(),  /plugins/thold/thold_functions.php[3372]:putenv(), CactiErrorHandler())
2019/05/31 10:31:16 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[796]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:thold_poller_bottom(),  /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(),  /plugins/thold/includes/polling.php[471]:thold_check_threshold(),  /plugins/thold/thold_functions.php[2166]:thold_command_execution(),  /plugins/thold/thold_functions.php[3311]:thold_set_environ(),  /plugins/thold/thold_functions.php[3371]:putenv(), CactiErrorHandler())

ate | Fri, 31 May 2019 10:51:37 -0400
-- | --
Cacti Version | 1.2.4
Cacti OS | unix
RSA Fingerprint | 5f:c6:e7:c5:42:82:af:57:cb:65:cf:fb:38:d7:67:51
NET-SNMP Version | NET-SNMP version: 5.7.3
RRDtool Version Configured | 1.7.0+
RRDtool Version Found | 1.7.0
Devices | 17
Graphs | 183
Data Sources | Script/Command: 11SNMP Get: 14SNMP Query: 53Script Server: 74Total: 152

PHP 7.3.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:00:05) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.3.4, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.3.5-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by netniV** [comment]
You have given the backtrace but not the actual warning from what I can see.
