### ISSUE TITLE
THOLD truncating command

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#337]
Hello Guys 

I am seeing an issue where THOLD cuts off text from a long command 

I am sending a curl command that is 299 characters it seems that the max characters limit is  251.
can this be extended? Possibly to a user-defined limit?

**Comment by cigamit** [comment]
Hmm, the upgrade script should have created those columns as 512.  Looks like the initial table creation wasn't updated though, so fixing that via fc185f2

You may run these again and see if it helps.  

ALTER TABLE thold_data MODIFY COLUMN trigger_cmd_high varchar(512) NOT NULL default ""
ALTER TABLE thold_data MODIFY COLUMN trigger_cmd_low varchar(512) NOT NULL default ""
ALTER TABLE thold_data MODIFY COLUMN trigger_cmd_norm varchar(512) NOT NULL default ""

ALTER TABLE thold_template MODIFY COLUMN trigger_cmd_high varchar(512) NOT NULL default ""
ALTER TABLE thold_template MODIFY COLUMN trigger_cmd_low varchar(512) NOT NULL default ""
ALTER TABLE thold_template MODIFY COLUMN trigger_cmd_norm varchar(512) NOT NULL default ""

**Comment by TheWitness** [comment]
This was resolved a few days ago by @cigamit.  Must have been some upgrade issue as the command has been 512 for a while, though there has not been a tag in a while.
