### ISSUE TITLE
Feature Request - Add new text field for Alerts/Warnings

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#34]
Add a text field (Notes?) to both alerts and warnings where instructions can be added to advise the NOC/alert recipients on how to handle the incoming alert/warning. This information would be included in the email/text that is sent out.

**Comment by interduo** [comment]
per host(?) or per threshold(?)

**Comment by smiles1969** [comment]
Per alert/warning.

Sent from my iPhone

On Jan 19, 2017, at 2:24 AM, Interduo <notifications@github.com<mailto:notifications@github.com>> wrote:


per host(?) or per threshold(?)

**Comment by cigamit** [comment]
Resolved.
