### ISSUE TITLE
Call to undefined function db_fetch_cell_assoc()

### ISSUE THREAD

**Issue by diazdw** [Cacti/plugin_thold#343]
**Describe the bug**
e-mail message: Cacti disabled plugin thold due to the following error: PHP ERROR in Plugin 'thold': Call to undefined function db_fetch_cell_assoc() in file: /var/www/html/cacti/plugins/thold/thold.php on line: 1047! See the Cacti logfile for more details.

**To Reproduce**
1. I was creating a custom data template with 5 different DS, which wil be fed by a Oracle DB select (using a custom data input method).
2. I had some issued trying to create 2 different graphs using same that same data template for the same device (other data sources using that data template got kinde corrupted --some values changed-- and unable to fix them from Web UI)
3. I got the e-mail message from Cacti.

**Expected behavior**
Thold working fine and never disables automatically

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium

**Comment by TheWitness** [comment]
This issue is fixed now.  Close if you concur.

**Comment by ddb4github** [comment]
#343 should be marked duplicated with #340
