### ISSUE TITLE
Thold - A non-numeric value encountered

### ISSUE THREAD

**Issue by Arkasha18** [Cacti/plugin_thold#347]
i install clear last cacti and clear las thold.
install my old graf template (i made myself, hdd storage usage over SNMP)
I not understand what the problem .
Have data in rrd 
2019/07/14 15:23:08 - POLLER: Poller[Main Poller] CACTI2RRD: /usr/bin/rrdtool update /home/arkasha18/site/admin.ru.net/cacti_new/rra/default_home_win_hrstoragesize_256.rrd --skip-past-updates --template hrStorageUsed:hrStorageSize 1563106985:27380565:29048289
2019/07/14 15:23:06 - POLLER: Poller[Main Poller] Device[default_home_win] DS[ default_home_win - hrStorageTable - C: Label: Serial Number 3e6f2391] Graphs[ default_home_win - C: Label: Serial Number 3e6f2391] SNMP: v2: , dsname: hrStorageUsed, oid: .1.3.6.1.2.1.25.2.3.1.6.1, output: 27380565
2019/07/14 15:23:06 - POLLER: Poller[Main Poller] Device[default_home_win] DS[ default_home_win - hrStorageTable - C: Label: Serial Number 3e6f2391] Graphs[ default_home_win - C: Label: Serial Number 3e6f2391] SNMP: v2: , dsname: hrStorageSize, oid: .1.3.6.1.2.1.25.2.3.1.5.1, output: 29048289

but thold not correct read value :
2019/07/14 15:03:15 - THOLD: Threshold HI / Low check is normal HI:b,a,/,100,* LOW:b,a,/,100,* VALUE:b,a,/,100,*
2019/07/14 15:03:15 - THOLD: Checking Threshold: Name: 'hrStorageUsed', local_data_id: '256', data_template_rrd_id: '713', value: 'b,a,/,100,*'

I do not understand how debug thold data

my graf template use 2xCDEFs
cdef=CURRENT_DATA_SOURCE,|query_hrStorageAllocationUnits|,*
and second
cdef=b,a,/,100,*
when i delete second (cdef=b,a,/,100,*) all work..
but i not understand why.

if i change in graf (hrStorageSize Item # 9) "CDEF Function:Host MIB - hrStorageTable Units" all work ok, but with "CDEF Function:Make a percentage b/a" - not work

http://test.admin.ru.net/cacti_test/graph_templates_items.php?action=item_edit&id=668&graph_template_id=68
http://test.admin.ru.net/cacti_test/graph_templates.php?action=template_edit&id=68

![2](https://user-images.githubusercontent.com/1715886/61299329-878e1e00-a7e8-11e9-898d-bdff748d2e12.jpg)
![1](https://user-images.githubusercontent.com/1715886/61299330-878e1e00-a7e8-11e9-9363-699062f4f9f6.jpg)

**Comment by cigamit** [comment]
Duplicate of Issue #345.  This is a duplicate in that they both relate to CDEF handling.

**Comment by cigamit** [comment]
This should be resolved now.  Update to the develop branch and let me know if this is resolved.

**Comment by Arkasha18** [comment]
resolved
thx
