### ISSUE TITLE
Error trying to resolve Graph display values with error: Unknown RPN type: 1

### ISSUE THREAD

**Issue by hmorandell** [Cacti/plugin_thold#354]
**Describe the bug**
I updated Cacti & Spine to version 1.2.4, and updated also the Thold Plugin to version 1.3.2
Since the update of the thold plugin, I get continuos errors of this type in the logfile:

...

```
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
--
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
2019/07/23 14:22:46 - CMDPHP Unknown RPN type: 1
...
```

**To Reproduce**
I updated the thold plugin by uninstalling the old (1.2.4) version first, installed the new version and restored the thold plugin tables:
```
thold_template
thold_data 
plugin_thold_threshold_contact 
plugin_thold_template_contact
plugin_thold_log 
plugin_thold_host_template 
plugin_thold_host_failed 
plugin_thold_device_template 
plugin_thold_daemon_processes 
plugin_thold_daemon_data 
plugin_thold_contacts
```

**Plugin (please complete the following information):**
 - Version: 1.3.2
 - Source: github

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser chrome/opera

**Comment by netniV** [comment]
You should never uninstall a plugin as it removes the tables, hooks, etc and makes upgrades not happen since the plugin doesn't know that the tables were the older ones.

I would install the previous version you had, restore the tables, then copy over the upgrade, visit the plugins page, and it should upgrade itself.

**Comment by hmorandell** [comment]
You're right - I did the update the wrong way.
Anyway, I did like you suggested, but as soon as I upgrade from 1.2.4 to 1.3.2 I have the same errors again. I go back to version 1.2.4 and will stick with that version for now.

**Comment by cigamit** [comment]
These warnings are harmless, but let me know if the values displayed look correct.  Thanks!

**Comment by hmorandell** [comment]
Hi I updated know with the development branch and the error is not present in the log anymore.
Thanks!
