### ISSUE TITLE
Downtime message is only calculated when SNMP is in use

### ISSUE THREAD

**Issue by jees1234** [Cacti/plugin_thold#358]
**Describe the bug**
&lt;DOWNTIME&gt; variable ($downtimemsg) is not calculated and hence not put in Recovering Device Message. This happens only for hosts where SNMP is not enabled.

**To Reproduce**
The problem is in include/polling.php as $downtimemsg is calculated only for SNMP enabled hosts - see:

if (($host['snmp_community'] == '' && $host['snmp_username'] == '') || $host['snmp_version'] == 0) {
					// SNMP not in use
					$snmp_system = __('SNMP not in use', 'thold');
				} else {

---> $downtimemsg calculated here <---

				}

Code for $downtimemsg calculation should be put out of "if statement" in order to be executed for both SNMP and non-SNMP enabled hosts.

**Expected behavior**
&lt;DOWNTIME&gt; variable ($downtimemsg) should be calculated also for non-SNMP enabled hosts.

**Screenshots**

**Plugin (please complete the following information):**
 - Version: 1.3.2
 - Source: github
 - Identifer: e2b3aa6

**Comment by netniV** [comment]
Seems reasonable to me.
