### ISSUE TITLE
Allow <DOWNTIME> variable substitution also in UP/DOWN e-mail subject

### ISSUE THREAD

**Issue by jees1234** [Cacti/plugin_thold#359]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to make possible to put &lt;DOWNTIME&gt; also in UP/DOWN e-mail message subject not only in message body.
I use only e-mail subject for sending SMS notifications so I have configured something like this:

Down Device Subject
Host &lt;DESCRIPTION&gt; is DOWN. Previously up for &lt;DOWNTIME&gt;.

Recovering Device Subject
Host &lt;DESCRIPTION&gt; is UP. Host was down for &lt;DOWNTIME&gt;.

This should be pretty straightforward - just allow &lt;DOWNTIME&gt; substitution in include/polling.php for UP/DOWN message also for message subject:

$subject = str_replace('&lt;DOWNTIME&gt;', $downtimemsg, $subject);

I have already modified the code on my installation but it would be nice to put the code also to master branch so I don't have to modify the code everytime thold is upgraded.
Thanks.

**Comment by TheWitness** [comment]
I'm not sure this is 100% what you were asking for.  If not, open another ticket.
