### ISSUE TITLE
Threshold,take the opposite value

### ISSUE THREAD

**Issue by Initarts** [Cacti/plugin_thold#360]
![image](https://user-images.githubusercontent.com/8800508/62688194-f3843080-b9fa-11e9-8d77-b3835d824fa5.png)
As shown above, create an inflow template.

Then, when creating monitoring items according to the template, after selecting the template, it is found that the monitoring items are the opposite, the listed graphics are not created, and the created graphics should be listed

![1](https://user-images.githubusercontent.com/8800508/62688447-71483c00-b9fb-11e9-8262-35541d257888.jpg)

**Comment by netniV** [comment]
You can create a threshold if a datasource exists.  If the datasource does not get used, is irrelevant since the data comes from the source not the graph.

**Comment by TheWitness** [comment]
Yea, I see what the user means in this case.  I think this feature is a bit of a corner case.  It's likely better to add the Thold Templates to the Device Template, and then either have Automation Create the thresholds, or through Graphs New interface.  Though this is a good idea, there is no ability to generalize it right now.

**Comment by TheWitness** [comment]
So, I've given this more thought, and I would prefer you use the alternate approach to create the thresholds.  This feature was initially implemented as a corner case to create both the graph and the threshold at the same time.  In a normal Cacti world, the graph comes first, and then the thresholds follow.  So, I'm closing this for now.
