### ISSUE TITLE
Thold  1.3.2  api_plugin_run_plugin_hook_function(), 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#362]
Hey Guys 

I am seeing the below errors in the latest thold version

2019/08/23 15:30:08 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[676]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[760]:CactiErrorHandler())

Doesnt seem to be impacting anything

**Comment by netniV** [comment]
There should be another error next to this.

**Comment by bmfmancini** [comment]
Sorry yes here is the full error 

2019/08/23 15:30:08 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[760]:CactiErrorHandler())
2019/08/23 15:30:08 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 760

**Comment by netniV** [comment]
This seems to be an issue with `$item[$thold_data['name']]` not being numeric.  You could add a call to `cacti_log()` to record the output if it's `!is_numeric()`

**Comment by bmfmancini** [comment]
so would it be an issue with how the threshold is named ?

**Comment by netniV** [comment]
could be

**Comment by TheWitness** [comment]
Ohhh, this explains some more.  Have to check something...

**Comment by TheWitness** [comment]
This one is duplicate.  I already fixed it a while ago.
