### ISSUE TITLE
Multiple PHP  Errors  coming from Thold 1.3.2

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#363]
Hey Everyone

Seeing alot of errors in the log coming from thold 

No impact seen  everything seems to work fine

2019/08/23 13:26:16 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php[141]:list_tholds(), /plugins/thold/thold.php[563]:top_header(), /lib/functions.php[3229]:include_once(), /include/top_header.php[43]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:26:16 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php[141]:list_tholds(), /plugins/thold/thold.php[563]:top_header(), /lib/functions.php[3229]:include_once(), /include/top_header.php[27]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:26:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_templates.php[73]:top_header(), /lib/functions.php[3229]:include_once(), /include/top_header.php[43]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:26:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_templates.php[73]:top_header(), /lib/functions.php[3229]:include_once(), /include/top_header.php[27]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:25:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_graph.php[53]:general_header(), /lib/functions.php[3244]:include_once(), /include/top_general_header.php[49]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:25:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_graph.php[53]:general_header(), /lib/functions.php[3244]:include_once(), /include/top_general_header.php[27]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:25:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_templates.php[73]:top_header(), /lib/functions.php[3229]:include_once(), /include/top_header.php[43]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:25:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_templates.php[73]:top_header(), /lib/functions.php[3229]:include_once(), /include/top_header.php[27]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:23:38 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_graph.php[97]:general_header(), /lib/functions.php[3244]:include_once(), /include/top_general_header.php[43]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())
2019/08/23 13:23:38 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold_graph.php[97]:general_header(), /lib/functions.php[3244]:include_once(), /include/top_general_header.php[27]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())

**Comment by TheWitness** [comment]
I'm unable to reproduce this.  Can you confirm with the latest develop?
