### ISSUE TITLE
Thold 1.3.2  A non-numeric value encountered in thold_functions.php

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#364]
Hey Guys I am seeing the following error I belive this was also reported here but it was closed

https://github.com/Cacti/plugin_thold/issues/214

2019/08/26 09:05:10 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[760]:CactiErrorHandler())
2019/08/26 09:05:10 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 760
2019/08/26 09:05:07 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[760]:CactiErrorHandler())
2019/08/26 09:05:07 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php 

No impact seen at this time

**Comment by vKnmnn** [comment]
I'm having the same issue
```
18.10.2019 11:42:24 - CMDPHP PHP ERROR NOTICE Backtrace:  (/poller.php[796]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /usr/local/share/cacti/plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /usr/local/share/cacti/plugins/thold/includes/polling.php[469]:thold_check_threshold(), /usr/local/share/cacti/plugins/thold/thold_functions.php[2026]:thold_modify_values_by_cdef(), /usr/local/share/cacti/plugins/thold/thold_functions.php[3643]:thold_build_cdef(), /usr/local/share/cacti/plugins/thold/thold_functions.php[3995]:thold_rpn(), /usr/local/share/cacti/plugins/thold/thold_functions.php[4033]:CactiErrorHandler())
18.10.2019 11:42:24 - ERROR PHP NOTICE in  Plugin 'thold': A non well formed numeric value encountered in file: /usr/local/share/cacti/plugins/thold/thold_functions.php  on line: 4033

```

**Comment by vKnmnn** [comment]
I've traced this back to template php scripts that do not validate the output of `cacti_snmp_get()`
In this case it was a device with bad indexes, which didn't produce a number as output which didn't get checked.

 I will now try to add checks to the scripts i have installed to make sure there's empty output when that happens (which seems to be the preferred way, as i looked at `get_cpu_usage()` in `scripts/query_host_cpu.php`)

**Comment by netniV** [comment]
Those look like core scripts @vKnmnn, can you confirm?

**Comment by vKnmnn** [comment]
The scripts that didn't validate the output aren't core scripts. They are some version of the WLC5508 Template i found on the forums. I've uploaded a version including the checks in a [gist](https://gist.github.com/vKnmnn/718962ba237223a83daeb2f499972081)

**Comment by netniV** [comment]
OK, fair enough. Sounds like you have resolve your own issue.  If so, feel free to close this tracker.

**Comment by vKnmnn** [comment]
I would, but I merely hijacked this issue. It's your call.

**Comment by netniV** [comment]
Oh u did ha. Didn’t see that Sean had posted this as you were the only one to comment :)

**Comment by bmfmancini** [comment]
Hey Guys will the code be updated with the checks ?
I am still getting these errors every so often

**Comment by TheWitness** [comment]
@bmfmancini,

Are you using boost?  If so, this problem was likely fixed in Cacti 1.2.9.  Can you please check again?

Larry

**Comment by TheWitness** [comment]
I think this is happening when the data collector is returning unknown data or 'U'.  Doing a fix right now.

**Comment by TheWitness** [comment]
Should be fixed now.  Please confirm and close.  There has been a lot of changes.  So, either take the whole thing, or just cherrypick the changes here.
