### ISSUE TITLE
Incomplete list of device's interfaces for creating thresholds 

### ISSUE THREAD

**Issue by igorz19** [Cacti/plugin_thold#365]
**Describe the bug**
When you try to create threshold it does not show  complete list of interfaces available on the corresponding device. 

**To Reproduce**
In a threshold creating process when you select interfaces 

**Expected behavior**
List of all interfaces for the corresponding device must be available

**Comment by netniV** [comment]
You will need to give more details, including an example and if possible send a copy of your database to developers@cacti.net so we can analyse what is occurring with your specific data.

**Comment by TheWitness** [comment]
I have to give this one some thought.  When this feature was added, we could only create one Threshold per interface of a given type.  In the current Cacti, you can create unlimited numbers of thresholds per interface type.  However this function was really designed to create both the graph and the threshold simultaneously.  So, this will take more time to work through the various possible regressions.

**Comment by TheWitness** [comment]
Giving this more thought, I would prefer that we leave this one alone.  There are enough ways to create a threshold beyond this corner case.
