### ISSUE TITLE
When a value is undefined, Thresholds are no longer triggering when minimum is zero

### ISSUE THREAD

**Issue by nicolapiazzi** [Cacti/plugin_thold#366]
Previoulsly (1.0.4) i defined thlod templates to watch when a line was down
Line down have undefine value (-) into its data and in thold is represented with 0
Putting a low threshold about 0.1 the value is under this and give an alert

Now in latest version we have same values (i monitor same device and have 2 cacti in use) but it shows 0 in the device [traffic_in] or [traffic_out] but it not trigger

**Comment by TheWitness** [comment]
Interesting.  This one might be tricky to figure out.  Marking it as a bug for now.

**Comment by TheWitness** [comment]
@nicolapiazzi, coming back to this now, are you saying that the device timed out and returned a 'U', or the device is down and returned a 'U'?  I think this was intentional for catching false positives.

**Comment by TheWitness** [comment]
I switched this to an enhancement.  If you look at the change, there is a new systemwide setting to allow 'U' or 'Nan' to be treated as zero.
