### ISSUE TITLE
traffic data multiplied by 8

### ISSUE THREAD

**Issue by nicolapiazzi** [Cacti/plugin_thold#367]
this happens only using interface traffic (was correct in thold 1.0.4)
if you define a value using traffic_in or traffic_out when you watch in thold you see it multiplied by 8 and this is the value that it use to trigger

for example, if a device collect a bit value of 200 and you define a thold of 100 if is compared with 800 not 100

to reproduce simply create a thold template using traffic_in (for example 100) associate to a device and wathc into thold page, you can see value multiplied by 8

i think this is not a cdef problem because i watched all definitions in a prevous cacti version with thold 1.0.4 and are the same

**Comment by netniV** [comment]
I believe that this is related to #361, try updating to the latest develop version and let me know if that resolves things.

**Comment by nicolapiazzi** [comment]
Hi
Low Threshold 0.1 When Apply to interface display 800.00m
I deleted and recreate threshold, nothing changes
version not changed after copy new develop (1.3.2)
Do you think that thold template recreation also needed ?

**Comment by nicolapiazzi** [comment]
Also with new template problem still alive

**Comment by netniV** [comment]
Try setting the cdef on the template itself.
