### ISSUE TITLE
thold not working for Counter data source and CDEF in graph and High or Low Threshold= 0

### ISSUE THREAD

**Issue by akharuk** [Cacti/plugin_thold#371]
i have a simple data source with 2 fileds with type COUNTER. Poller read file that contain two integer. Graph applying CDEF to show data: make per 5 minutes. i created thold with High value>0. As i see from you last changed for thold and cdefs i do not need to use CDEF now in thold.
So this is what i have for thold setting:
![image](https://user-images.githubusercontent.com/31667435/65177603-ab2b4a00-da5f-11e9-932d-c946f2da6fe4.png)

this is what i see in thold list(min high\low values i see 0, not - or U):
![image](https://user-images.githubusercontent.com/31667435/65177952-710e7800-da60-11e9-8260-4dd8629f9099.png)

this is what i see once value >0 but thold not alerting
![image](https://user-images.githubusercontent.com/31667435/65178387-4670ef00-da61-11e9-8842-19ae8e85b368.png)

**Comment by akharuk** [comment]
Looks like it's some kind of new behavior for COUNTER type(not sure about other) and graphs that use CDEFs for displaying data?
i am using make per 5 minutes CDEF for graph line that multiplying current_data_source value to 300.
for some reason thold for such values do divide values(current_data_source and thold value) by 300.
This is what i did:
1) instead of zero insert very small double:1.0E-7.
![image](https://user-images.githubusercontent.com/31667435/65183782-d8322980-da6c-11e9-9f2e-de2262f2ce7c.png)
2) and this is what i have after: thold alerting
![image](https://user-images.githubusercontent.com/31667435/65183850-ff88f680-da6c-11e9-8fb4-915dd0867038.png)
looks like 1.03 was divided by 300 and this value > 1.0E-7
this is the email subject: [ErrFileCnt] went above threshold of 30 µ with 1.03

**Comment by TheWitness** [comment]
Oh, goodness.
