### ISSUE TITLE
Thold plugin execute a script each time device state changes? v2

### ISSUE THREAD

**Issue by navennn** [Cacti/plugin_thold#372]
Hi,
Can you please take another look at https://github.com/Cacti/plugin_thold/issues/82 ? I think the second part of this request was forgotten.

**Is your feature request related to a problem? Please describe.**
There is a fair description under #82 

**Describe the solution you'd like**
Can you also please make script execution possible for up/down hosts, not only for thresholds?

**Describe alternatives you've considered**
It was partially done so I haven't explored any other solutions.

**Additional context**
#82

**Comment by bmfmancini** [comment]
I made the same feature request a couple of days ago !

For me I am looking to send a curl request to our ticketing system instead
of email

**Comment by TheWitness** [comment]
Okay, this is implemented for version 1.5.  Someone please test and report back.

**Comment by bmfmancini** [comment]
Thanks Larry!
I will for sure test and let you know !

**Comment by TheWitness** [comment]
@bmfmancini, cool!

**Comment by bmfmancini** [comment]
Hey @TheWitness I was able to test the function it works!
Quick question for clarity since  the description says you cannot pass command line arguments 
how would we be able to pass the variables to a script ?

Could you make it like the other thold command execution options ?

**Comment by TheWitness** [comment]
All the variables are already in the environment of the script.  For example: device_id would be $THOLD_DEVICE_ID.  Shouldn't that be enough?

**Comment by bmfmancini** [comment]
Ok so for example I should be able to do

#!/bin/bash

Echo THOLD_DEVICE_ID

without doing anything else ?

Sorry just a bit confused here

**Comment by TheWitness** [comment]
Something more like this:

myscript.sh
```bash
#!/bin/bash
/path/to/my/ticketapi.php --create-ticket --cacti-device=$THOLD_DEVICE_ID --message="$THOLD_SUBJECT"
```

**Comment by TheWitness** [comment]
Of course, since you have to evaluate the variables, some cases might be 'close' vs. 'create'.  There might some variables missing, like something like $THOLD_ID.

**Comment by bmfmancini** [comment]
ok but without being able to use arguments how would the variable data be passed between thold and the script ?

Simple example I have tested with the command execution from the thold template 

#!/bin.bash
echo "$1" >> /var/www/html/cacti/log/cacti.log

and in thold I would execute the command 
/tmp/test.sh <THOLD_ID>

that would net me the thold_id being sent to the cacti log

in this feature without the ability to use arguments how would bash/php/python etc be able to recive the <thold_id> variable ?

**Comment by bmfmancini** [comment]
Hey @TheWitness  I have tried the following script test 

#!/bin/bash
echo THOLD_HOSTNAME >> /tmp/test.txt

I also tried $THOLD_HOSTNAME 

But I am still stuck with how you see the script enviroment being able to pull the info without allow for arguments to be passed 

Here is the output in the log

2020/09/17 15:06:04 - THOLD Device Down Command for Device[test10] Command[/var/www/html/cacti/cli/test.sh] ExitStatus[1] Output[] 

Unless I am doing something wrong here

**Comment by bmfmancini** [comment]
Some more info 

For a threshold breach you are allowed to execute a command like this 

![image](https://user-images.githubusercontent.com/13388748/93518419-c5aa3480-f8fa-11ea-928f-ecef9362c856.png)

If we can have that functionality or similar that would be awesome

**Comment by TheWitness** [comment]
Do this:

```
#!/bin/bash
env > /tmp/test.out
```

**Comment by TheWitness** [comment]
Here is what you will have in your script:

```
[root@vmhost3 tmp]# cat test.out
TOLD_DATE_RFC822=Thu, 17 Sep 20 19:02:35 -0400
TOLD_TOT_POLL=1008573
XDG_SESSION_ID=6588
TOLD_FAIL_POLL=62446
SHELL=/bin/sh
TOLD_DATE=2020/09/17 19:02:35
USER=apache
TOLD_SNMP_SYSTEM=
TOLD_DESCRIPTION=vhost03
TOLD_LAST_FAIL=2020-09-17 19:02:00
TOLD_MESSAGE=Device did not respond to SNMP, ICMP: Ping timed out
TOLD_HOST_ID=51
TOLD_CUR_TIME=5.59712
PATH=/usr/bin:/bin
_=/usr/bin/env
TOLD_SNMP_LOCATION=Unknown
PWD=/var/www/html/cacti
TOLD_DOWNTIME=1m
TOLD_UPTIME=
LANG=en_US.UTF-8
TOLD_HOSTNAME=192.168.11.203
TOLD_SNMP_CONTACT=Dads Place (North)
SHLVL=3
HOME=/usr/share/httpd
LOGNAME=apache
TOLD_DOWNUP=DOWN
TOLD_NOTES=Added by Cacti Automation
TOLD_AVG_TIME=1.24880
TOLD_TIME=1600383755
XDG_RUNTIME_DIR=/run/user/48
THOLD_SUBJECT=Device Error: vhost03 (192.168.11.203) is DOWN
RRD_DEFAULT_FONT=Queenie's.ttf
TOLD_SNMP_HOSTNAME=vhost03
TOLD_AVAILABILITY=93.80850
```

**Comment by TheWitness** [comment]
And, when the device comes back:

```
[root@vmhost3 tmp]# cat test.out
TOLD_DATE_RFC822=Thu, 17 Sep 20 19:06:34 -0400
TOLD_TOT_POLL=1008581
XDG_SESSION_ID=6592
TOLD_FAIL_POLL=62451
SHELL=/bin/sh
TOLD_DATE=2020/09/17 19:06:34
USER=apache
TOLD_SNMP_SYSTEM=Linux vhost03 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64
TOLD_DESCRIPTION=vhost03
TOLD_LAST_FAIL=2020-09-17 19:02:00
TOLD_MESSAGE=
TOLD_HOST_ID=51
TOLD_CUR_TIME=0.79549
PATH=/usr/bin:/bin
_=/usr/bin/env
TOLD_SNMP_LOCATION=Unknown
PWD=/var/www/html/cacti
TOLD_DOWNTIME=4m 34s
TOLD_UPTIME=8592
LANG=en_US.UTF-8
TOLD_HOSTNAME=192.168.11.203
TOLD_SNMP_CONTACT=Dads Place (North)
SHLVL=3
HOME=/usr/share/httpd
LOGNAME=apache
TOLD_DOWNUP=UP
TOLD_NOTES=Added by Cacti Automation
TOLD_AVG_TIME=1.24880
TOLD_UPTIMETEXT=0d 0h 1m
TOLD_TIME=1600383994
XDG_RUNTIME_DIR=/run/user/48
THOLD_SUBJECT=Device Notice: vhost03 (192.168.11.203) returned from DOWN state
RRD_DEFAULT_FONT=Queenie's.ttf
TOLD_SNMP_HOSTNAME=vhost03
TOLD_AVAILABILITY=93.80800
```

**Comment by TheWitness** [comment]
Get on those training wheels a fly @bmfmancini ;)

**Comment by bmfmancini** [comment]
Ouch!  lol thanks for the help Larry I put my training wheels back on haha
