### ISSUE TITLE
About 361

### ISSUE THREAD

**Issue by nicolapiazzi** [Cacti/plugin_thold#373]
Sorry but i think that bug 361 is not solved
I installed a fresh cacti with latest rrdtool, spine, cacti and develop thold latest al 20/09/2019
I create 2 graps, one byte and one bits and apply thlod 0.1 low
![1](https://user-images.githubusercontent.com/54310887/65341731-4b54b080-dbd1-11e9-94b4-1ca379140778.gif)
As you can see one have value in bits and other in bytes, the one in bits have thold 0.800m instead 0.100m but the template is the same
i created a cdef that multiply by 1 and applied to template, now also bits have thold 0.100m but its value is turned in bytes
![2](https://user-images.githubusercontent.com/54310887/65341955-f6fe0080-dbd1-11e9-964a-8bf076330f75.gif)

**Comment by nicolapiazzi** [comment]
Do you have a solution about this, because i made a fresh install and i found that is seems not solved, thanks

**Comment by TheWitness** [comment]
It's converting to bits from bytes more than likely.  Several people have been commenting on this.  Right now it's considered not an issue.

**Comment by TheWitness** [comment]
You have one graph that is bits/second, and the second graph is bytes per second.  That explains the difference.
