### ISSUE TITLE
Question - Variables to use when sending a command 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#376]
Hey All 

I am trying to format  a command using the variables from THOLD I am struggling to find which variables will dispay the same data as whats in the email more specifcially I want to know which interface has errors on it so far I have been able to get the hostname Ip and that there are errors but which one would show which interface the errors are on ?

**Comment by bmfmancini** [comment]
This is what I have used 

<DESCRIPTION> <HOSTNAME> <SUBJECT> <BREACHED_ITEMS> which produces
name of host IP  BDCNEXT328.corp.bdc.ca - Errors I added <CURRENTVALUE> to show the values 
I just need to find the interface now

**Comment by bmfmancini** [comment]
I have used <DESCRIPTION> <HOSTNAME> <SUBJECT>  <CURRENT_VALUE>
which  produces  the  the device name ip and errors  along with the number of errors but so far I have not been able to find the variable that will report back the interface

**Comment by TheWitness** [comment]
Here are the variable names that are set:

* THOLD_CURRENTVALUE
* THOLD_DATE
* THOLD_DATE_RFC822
* THOLD_DESCRIPTION
* THOLD_DEVICENOTE
* THOLD_DSNAME
* THOLD_DURATION
* THOLD_GRAPHID
* THOLD_HI
* THOLD_HOSTNAME
* THOLD_LOW
* THOLD_NOTES
* THOLD_THOLDTYPE
* THOLD_THRESHOLDNAME
* THOLD_TIME
* THOLD_TRIGGER
* THOLD_URL

Is that what you were looking for?

**Comment by TheWitness** [comment]
It would be nice to have that documented somewhere.

**Comment by TheWitness** [comment]
Marking this one fixed.  I updated the documentation just a little.
