### ISSUE TITLE
THOLD 1.3.2 Not executing commands all of the time 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#377]
THOLD 1.3.2 seems to not always execute commands all of the time 
It appears on some thresholds it executes while others not 

Is there a way to debug this ?

**Comment by bmfmancini** [comment]
I have tried everything that I can think of 
Cacti reports that it has called the command but it doesnt 

I have attempted to run the script as the apache user and it works fine manually
I dont get why it wont execute properly 

anyone who has an idea please let me know this is how I have my command setup

![image](https://user-images.githubusercontent.com/13388748/65729703-32df0d00-e08d-11e9-8181-2937a408eb0b.png)

the script has a echo out to a log file so I know the script has not been called

**Comment by bmfmancini** [comment]
@netniV  any ideas ?

**Comment by netniV** [comment]
Sorry, I didn't see any notifications on thold for a while.  Not sure off the top of my head but looks like you have an issue tracker open for the variables you can use, plus had one about the script anyway so I am assuming you resolved this.
