### ISSUE TITLE
THOLD not executing command 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#379]
Hey Everyone 

I am having an issue with THOLD executing a shell script 
running the script manually works  and the script  is owned by apache the log shows the command was run but I dont see it working at all 

Looking for some help on this one to see if its me or THOLD

**Comment by cigamit** [comment]
Look, magic.  It's in thold and now re-opened...

**Comment by bmfmancini** [comment]
So it looks like when I used the <GRAPH> variable caused the issue removed the variable now I am all good
