### ISSUE TITLE
Wrong the thold create from  template

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_thold#38]
When thold create from template, not all the parameters are entered into the database.
cacti.log 
```
2017-01-28 00:57:20 - ERROR PHP NOTICE in  Plugin 'thold': Undefined index: template in file: /var/www/cacti/plugins/thold/setup.php  on line: 981
2017-01-28 00:57:20 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs.php: 68 form_actions)(/graphs.php: 666 api_plugin_hook_function)(/lib/plugins.php: 104 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 205 thold_graphs_action_execute)(/plugins/thold/setup.php: 981 CactiErrorHandler)(/lib/functions.php: 4230 cacti_debug_backtrace)
```

![10](https://cloud.githubusercontent.com/assets/11805503/22390524/2fc59edc-e4f4-11e6-9cf5-3efb0dca1043.png)
![11](https://cloud.githubusercontent.com/assets/11805503/22390522/2fc21cee-e4f4-11e6-983d-5c1ad2991b8c.png)
![12](https://cloud.githubusercontent.com/assets/11805503/22390525/2fc8d75a-e4f4-11e6-89bf-737fa3ac6084.png)
![13](https://cloud.githubusercontent.com/assets/11805503/22390523/2fc2b0be-e4f4-11e6-9eea-0dc5ecb660f1.png)

**Comment by pautiina** [comment]
I run debug, aand have results:
`2017-01-30 14:07:59 - DBCALL DEVEL: SQL Exec: "INSERT INTO thold_template (`id`, `hash`, `name`, `thold_type`, `thold_hi`, `thold_low`, `thold_fail_trigger`, `time_hi`, `time_low`, `time_fail_trigger`, `time_fail_length`, `thold_warning_hi`, `thold_warning_low`, `thold_warning_fail_trigger`, `time_warning_hi`, `time_warning_low`, `time_warning_fail_trigger`, `time_warning_fail_length`, `thold_enabled`, `exempt`, `thold_hrule_warning`, `thold_hrule_alert`, `restored_alert`, `bl_ref_time_range`, `bl_pct_down`, `bl_pct_up`, `bl_fail_trigger`, `repeat_alert`, `notify_extra`, `notify_warning_extra`, `notify_warning`, `notify_alert`, `cdef`, `data_type`, `percent_ds`, `expression`) VALUES (2, '550f362f67478ddd20898a16c129ee70', 'Host MIB - Hard Drive Space [hdd_used]', 0, '95', '', 10, '', '', 1, 1, '90', '', 10, '', '', 1, 1, 'on', '', '0', '0', '', 86400, '20', '20', 2, 1, '', '', 0, 0, 0, 0, 'hdd_used', '') ON DUPLICATE KEY UPDATE `hash`=VALUES(`hash`), `name`=VALUES(`name`), `thold_type`=VALUES(`thold_type`), `thold_hi`=VALUES(`thold_hi`), `thold_low`=VALUES(`thold_low`), `thold_fail_trigger`=VALUES(`thold_fail_trigger`), `time_hi`=VALUES(`time_hi`), `time_low`=VALUES(`time_low`), `time_fail_trigger`=VALUES(`time_fail_trigger`), `time_fail_length`=VALUES(`time_fail_length`), `thold_warning_hi`=VALUES(`thold_warning_hi`), `thold_warning_low`=VALUES(`thold_warning_low`), `thold_warning_fail_trigger`=VALUES(`thold_warning_fail_trigger`), `time_warning_hi`=VALUES(`time_warning_hi`), `time_warning_low`=VALUES(`time_warning_low`), `time_warning_fail_trigger`=VALUES(`time_warning_fail_trigger`), `time_warning_fail_length`=VALUES(`time_warning_fail_length`), `thold_enabled`=VALUES(`thold_enabled`), `exempt`=VALUES(`exempt`), `thold_hrule_warning`=VALUES(`thold_hrule_warning`), `thold_hrule_alert`=VALUES(`thold_hrule_alert`), `restored_alert`=VALUES(`restored_alert`), `bl_ref_time_range`=VALUES(`bl_ref_time_range`), `bl_pct_down`=VALUES(`bl_pct_down`), `bl_pct_up`=VALUES(`bl_pct_up`), `bl_fail_trigger`=VALUES(`bl_fail_trigger`), `repeat_alert`=VALUES(`repeat_alert`), `notify_extra`=VALUES(`notify_extra`), `notify_warning_extra`=VALUES(`notify_warning_extra`), `notify_warning`=VALUES(`notify_warning`), `notify_alert`=VALUES(`notify_alert`), `cdef`=VALUES(`cdef`), `data_type`=VALUES(`data_type`), `percent_ds`=VALUES(`percent_ds`), `expression`=VALUES(`expression`)"`

Mysql have error:
`# 1054 - Unknown 'thold_hrule_warning' column in 'field list'`

**Comment by pautiina** [comment]
First I think that it is
```
$insert['name']               = $name;
$insert['host_id']            = $data_source['host_id'];
$insert['local_data_id']      = $local_data_id;
$insert['local_graph_id']     = $graph;
$insert['data_template_id']   = $data_template_id;
$insert['graph_template_id']  = $grapharr['graph_template_id'];
$insert['thold_hi']           = $template['thold_hi'];
$insert['thold_low']          = $template['thold_low'];
$insert['thold_fail_trigger'] = $template['thold_fail_trigger'];
$insert['thold_enabled']      = $template['thold_enabled'];
$insert['bl_ref_time_range']  = $template['bl_ref_time_range'];
$insert['bl_pct_down']        = $template['bl_pct_down'];
$insert['bl_pct_up']          = $template['bl_pct_up'];
$insert['bl_fail_trigger']    = $template['bl_fail_trigger'];
$insert['bl_alert']           = $template['bl_alert'];
$insert['repeat_alert']       = $template['repeat_alert'];
$insert['notify_extra']       = $template['notify_extra'];
$insert['cdef']               = $template['cdef'];
$insert['thold_template_id']  = $template['id'];
$insert['template_enabled']   = 'on';
```
should be replaced by this, then when you update the template - to data change also, if on date thold chose  `Template Propagation Enabled`
```
$insert['name']               = $name;
$insert['host_id']            = $data_source['host_id'];
$insert['local_data_id']      = $local_data_id;
$insert['local_graph_id']     = $graph;
$insert['data_template_id']   = $data_template_id;
$insert['graph_template_id']  = $grapharr['graph_template_id'];
$insert['thold_hi']           = $template['thold_hi'];
$insert['thold_low']          = $template['thold_low'];
$insert['thold_fail_trigger'] = $template['thold_fail_trigger'];
$insert['thold_warning_hi']   = $template['thold_warning_hi'];
$insert['thold_warning_low']  = $template['thold_warning_low'];
$insert['thold_warning_fail_trigger'] = $template['thold_warning_fail_trigger'];
$insert['thold_enabled']      = $template['thold_enabled'];
$insert['bl_ref_time_range']  = $template['bl_ref_time_range'];
$insert['bl_pct_down']        = $template['bl_pct_down'];
$insert['bl_pct_up']          = $template['bl_pct_up'];
$insert['bl_fail_trigger']    = $template['bl_fail_trigger'];
$insert['bl_alert']           = $template['bl_alert'];
$insert['repeat_alert']       = $template['repeat_alert'];
$insert['notify_alert']       = $template['notify_alert'];
$insert['notify_warning']       = $template['notify_warning'];
$insert['notify_extra']       = $template['notify_extra'];
$insert['notify_warning_extra'] = $template['notify_warning_extra'];
$insert['thold_hrule_alert']  = $template['thold_hrule_alert'];
$insert['thold_hrule_warning']= $template['thold_hrule_warning'];
$insert['cdef']               = $template['cdef'];
$insert['thold_template_id']  = $template['id'];
```
In my change dont work:
```
$insert['thold_hrule_alert']  = $template['thold_hrule_alert'];
$insert['thold_hrule_warning']= $template['thold_hrule_warning'];
```
i dont now why.

**Comment by pautiina** [comment]
I think that line 891 must be replace from:
`thold_template_update_threshold ($id, $insert['template']);
`
to:
`thold_template_update_threshold ($id, $insert['thold_template_id']);`

**Comment by pautiina** [comment]
I have some patch for new instalation and create Thold from template. 
In this patch just does not work just this when you update a template:
```
$insert['thold_hrule_alert']  = $template['thold_hrule_alert'];
$insert['thold_hrule_warning']= $template['thold_hrule_warning'];
```
when creating the template it works
[thold.zip](https://github.com/Cacti/plugin_thold/files/744431/thold.zip)

**Comment by cypherstream** [comment]
Unzipped creates a thold.patch file, how do you apply it?

**Comment by pautiina** [comment]
@cypherstream 
```
cd PATH_TO_CACTI/plugins
unzip thold.zip
patch -p0 < thold.patch
```

**Comment by cypherstream** [comment]
Thanks this worked.  I had to drop all existing thold tables in mysql and allow the re-installation of thold to recreate them.  I see this is not committed to the main branch yet but so far things are working so maybe after further testing it can be updated.

**Comment by cigamit** [comment]
pautiina, thanks for your detailed audit.  I found a few additional gaps, and will commit shortly.

**Comment by cigamit** [comment]
Resolved, thanks for testing!
