### ISSUE TITLE
Automation - graph rule create more graphs than expected

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#382]
**Describe the bug**
I have rule (screenshot 1). Show matching devices doesn't show my windows device. I have tried another rule and thhe result was the same. But when I create new windows device a lot of Interface errors/discards graphs is created:
2019/10/17 10:04:53 - THOLD: Threshold Auto-created by User[1] TH[9402] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:53 - THOLD: Threshold Auto-created by User[1] TH[9403] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:53 - THOLD: Threshold Auto-created by User[1] TH[9404] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:54 - THOLD: Threshold Auto-created by User[1] TH[9405] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]
2019/10/17 10:04:54 - AUTOM8 NOTE: Graph Added - Device[647], Graph[24035], DS[25325, 25325], Rule[6]
2019/10/17 10:04:54 - THOLD: Threshold Auto-created by User[1] TH[9406] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:54 - THOLD: Threshold Auto-created by User[1] TH[9407] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:54 - THOLD: Threshold Auto-created by User[1] TH[9408] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:54 - THOLD: Threshold Auto-created by User[1] TH[9409] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]
2019/10/17 10:04:54 - AUTOM8 NOTE: Graph Added - Device[647], Graph[24036], DS[25326, 25326], Rule[6]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9410] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9411] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9412] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9413] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]
2019/10/17 10:04:55 - AUTOM8 NOTE: Graph Added - Device[647], Graph[24037], DS[25327, 25327], Rule[6]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9414] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9415] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9416] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:55 - THOLD: Threshold Auto-created by User[1] TH[9417] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]
2019/10/17 10:04:55 - AUTOM8 NOTE: Graph Added - Device[647], Graph[24038], DS[25328, 25328], Rule[6]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9418] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9419] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9420] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9421] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]
2019/10/17 10:04:56 - AUTOM8 NOTE: Graph Added - Device[647], Graph[24039], DS[25329, 25329], Rule[6]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9422] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9423] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9424] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:56 - THOLD: Threshold Auto-created by User[1] TH[9425] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]
2019/10/17 10:04:57 - AUTOM8 NOTE: Graph Added - Device[647], Graph[24040], DS[25330, 25330], Rule[6]
2019/10/17 10:04:57 - THOLD: Threshold Auto-created by User[1] TH[9426] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:57 - THOLD: Threshold Auto-created by User[1] TH[9427] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:57 - THOLD: Threshold Auto-created by User[1] TH[9428] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:57 - THOLD: Threshold Auto-created by User[1] TH[9429] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]
2019/10/17 10:04:57 - AUTOM8 NOTE: Graph Added - Device[647], Graph[24041], DS[25331, 25331], Rule[6]
2019/10/17 10:04:58 - THOLD: Threshold Auto-created by User[1] TH[9430] DataTemplate[Interface - Errors/Discards] DataSource[discards_in]
2019/10/17 10:04:58 - THOLD: Threshold Auto-created by User[1] TH[9431] DataTemplate[Interface - Errors/Discards] DataSource[discards_out]
2019/10/17 10:04:58 - THOLD: Threshold Auto-created by User[1] TH[9432] DataTemplate[Interface - Errors/Discards] DataSource[errors_in]
2019/10/17 10:04:58 - THOLD: Threshold Auto-created by User[1] TH[9433] DataTemplate[Interface - Errors/Discards] DataSource[errors_out]

**Expected behavior**
This rule couldn't create any graphs for windows device.

**Screenshots**
![screen1-rule_definition](https://user-images.githubusercontent.com/26485719/66992015-60860780-f0c9-11e9-8f12-42e8d95e8ce5.png)

**Plugin (please complete the following information):**
 - Version: 1.3.2
 - Source: github
 - Identifer: github commit ref

**Desktop (please complete the following information):**
 - OS: Ubutnu 19.10
 - Browser Firefox
 - Version 69.0.2

**Additional context**

**Comment by TheWitness** [comment]
I'm not sure what the issue is here.  Can you show me your device template edit screen including the thold templates?

**Comment by TheWitness** [comment]
Any update?

**Comment by TheWitness** [comment]
@xmacan rather any update?

**Comment by xmacan** [comment]
@TheWitness - it is long time. I will try it again asap

**Comment by xmacan** [comment]
It is long time. I changed all my automatic rules. Maybe it was any problem on my side.
