### ISSUE TITLE
bandwith calulcation incorrect 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#385]
Hey Guys 

I found this today  when setting a threshold for traffic in I tried to set  a threshold for 8MBPS whihch should be 8000000 bits however when you enter this value into THOLD it comes back with 64MBPS ??

I played around a bit and found I have to enter 1000000 which comes as 8MBPS ???

![image](https://user-images.githubusercontent.com/13388748/67712284-12f77d80-f99a-11e9-904a-e54728e56524.png)

![image](https://user-images.githubusercontent.com/13388748/67712290-17239b00-f99a-11e9-83bf-94bdffcdd1c3.png)

![image](https://user-images.githubusercontent.com/13388748/67712366-36bac380-f99a-11e9-9b9f-2c6d21779fea.png)

![image](https://user-images.githubusercontent.com/13388748/67712383-40442b80-f99a-11e9-8c7e-f30952c4d4e5.png)

**Comment by DoubleBeast** [comment]
i was confused too, it appears that something changed into latest versions, the value set into the tresthold is in bytes (presume that is because it is the original value received from the datasource) but the value that the threshold shows is related to the values that the especific graphs use (in this case bits)

**Comment by bmfmancini** [comment]
I just came back to this 

Yea I guess it makes sense  from the hardware/interface perspective as it clocks in bits but the GUI portion can be confusing maybe a tweak to the labeling of the field saying something like (bits) to indicate thats the way it should be enetered

**Comment by TheWitness** [comment]
Yea, when this was done, it ended up being confusing by making you enter the 'raw' value.  I'll mark this as a feature request.  We should not be requiring you to know you are tholding on bit or bytes and what the stored unit should be anyway.

**Comment by TheWitness** [comment]
I'm just going to leave this alone for the moment.
