### ISSUE TITLE
Thresholding Stacked Graphs.

### ISSUE THREAD

**Issue by RustedKnight** [Cacti/plugin_thold#387]
The unique deployment we have would benefit from being able to alert off of stacked graphs using the combined values. Would this be a feature that would be able to be worked into the Threshold plugin? I envision it as being set up simmilar to how they handle setting up stacked graphs where you select multiple data sources and then apply a CDEF expression to them to get the output.

**Comment by TheWitness** [comment]
You should be able to use the CDEF 'Total All Data Sources' today without change.  You simply have to change the Data Manipulation to CDEF and pick that CDEF.
