### ISSUE TITLE
Discussion: thold generate graph image as mail attachment without permission checking

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#389]
**Description**
During review [Cacti#2964](https://github.com/Cacti/cacti/issues/2964) solution, I found thold plugin always generate graph image as mail attachment whenever receiver has or not permission to view that graph.

**Question**
Should we:
* Cross check or grant user graph permission for "thold->notification list"
* Or Remove thold graphs from user graph permission management interface.

**Comment by netniV** [comment]
In truth, a user should not be receiving a notification if he does not have access to the threshold, graph or data however we Store emails in the notifications list not users so I think that can’t be applied

**Comment by TheWitness** [comment]
Yea, I'm going to close this one.
