### ISSUE TITLE
Problem with clean install plugin the thold

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_thold#39]
In a clean installation, not all fields are created in the database and chasti.log have errors.
I run debug, and have results:

` 2017-01-30 14:07:59 - DBCALL DEVEL: SQL Exec: "INSERT INTO thold_template (`id`, `hash`, `name`, `thold_type`, `thold_hi`, `thold_low`, `thold_fail_trigger`, `time_hi`, `time_low`, `time_fail_trigger`, `time_fail_length`, `thold_warning_hi`, `thold_warning_low`, `thold_warning_fail_trigger`, `time_warning_hi`, `time_warning_low`, `time_warning_fail_trigger`, `time_warning_fail_length`, `thold_enabled`, `exempt`, `thold_hrule_warning`, `thold_hrule_alert`, `restored_alert`, `bl_ref_time_range`, `bl_pct_down`, `bl_pct_up`, `bl_fail_trigger`, `repeat_alert`, `notify_extra`, `notify_warning_extra`, `notify_warning`, `notify_alert`, `cdef`, `data_type`, `percent_ds`, `expression`) VALUES (2, '550f362f67478ddd20898a16c129ee70', 'Host MIB - Hard Drive Space [hdd_used]', 0, '95', '', 10, '', '', 1, 1, '90', '', 10, '', '', 1, 1, 'on', '', '0', '0', '', 86400, '20', '20', 2, 1, '', '', 0, 0, 0, 0, 'hdd_used', '') ON DUPLICATE KEY UPDATE `hash`=VALUES(`hash`), `name`=VALUES(`name`), `thold_type`=VALUES(`thold_type`), `thold_hi`=VALUES(`thold_hi`), `thold_low`=VALUES(`thold_low`), `thold_fail_trigger`=VALUES(`thold_fail_trigger`), `time_hi`=VALUES(`time_hi`), `time_low`=VALUES(`time_low`), `time_fail_trigger`=VALUES(`time_fail_trigger`), `time_fail_length`=VALUES(`time_fail_length`), `thold_warning_hi`=VALUES(`thold_warning_hi`), `thold_warning_low`=VALUES(`thold_warning_low`), `thold_warning_fail_trigger`=VALUES(`thold_warning_fail_trigger`), `time_warning_hi`=VALUES(`time_warning_hi`), `time_warning_low`=VALUES(`time_warning_low`), `time_warning_fail_trigger`=VALUES(`time_warning_fail_trigger`), `time_warning_fail_length`=VALUES(`time_warning_fail_length`), `thold_enabled`=VALUES(`thold_enabled`), `exempt`=VALUES(`exempt`), `thold_hrule_warning`=VALUES(`thold_hrule_warning`), `thold_hrule_alert`=VALUES(`thold_hrule_alert`), `restored_alert`=VALUES(`restored_alert`), `bl_ref_time_range`=VALUES(`bl_ref_time_range`), `bl_pct_down`=VALUES(`bl_pct_down`), `bl_pct_up`=VALUES(`bl_pct_up`), `bl_fail_trigger`=VALUES(`bl_fail_trigger`), `repeat_alert`=VALUES(`repeat_alert`), `notify_extra`=VALUES(`notify_extra`), `notify_warning_extra`=VALUES(`notify_warning_extra`), `notify_warning`=VALUES(`notify_warning`), `notify_alert`=VALUES(`notify_alert`), `cdef`=VALUES(`cdef`), `data_type`=VALUES(`data_type`), `percent_ds`=VALUES(`percent_ds`), `expression`=VALUES(`expression`
`
Mysql have error:
`# 1054 - Unknown 'thold_hrule_warning' column in 'field list'`

I think the line 78
`api_plugin_db_add_column ( 'thold', 'thold_data', array ( 'name' => 'data_template_id', 'type' => 'int (11)', 'NULL' => false, 'default' => 0, 'after' => 'graph_template'));`
should be replaced by:
`api_plugin_db_add_column ( 'thold', 'thold_data', array ( 'name' => 'data_template_id', 'type' => 'int (11)', 'NULL' => false, 'default' => 0, 'after' => 'graph_template_id'));`

I think that after the line 373 you need to add the following lines:
```
        $data['columns'][] = array('name' => 'thold_hrule_alert',   'type' => 'int(11)', 'unsigned' => true, 'NULL' => true);
        $data['columns'][] = array('name' => 'thold_hrule_warning', 'type' => 'int(11)', 'unsigned' => true, 'NULL' => true);
```
And after  line 436 adding:

```
        $data['columns'][] = array('name' => 'thold_hrule_alert',   'type' => 'int(11)', 'unsigned' => true, 'NULL' => true);
        $data['columns'][] = array('name' => 'thold_hrule_warning', 'type' => 'int(11)', 'unsigned' => true, 'NULL' => true);
```

**Comment by pautiina** [comment]
Patch for new instalation have in #38

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
