### ISSUE TITLE
Undefined CDEF generated with latest Core / Thold versions

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#391]
**Describe the bug**
After upgrading to the latest 1.2.7+dev and 1.3.2+dev code, there is an error constantly being recorded in the log files:

```
2019/11/27 09:31:20 - THOLD WARNING: CDEF property not implemented yet: COUNT_ALL_DS_DUPS
```

I attempting to import the Cacti_Stats.xml.gz package but that made no difference
```console
sudo -u www-data php ../../cli/import_package.php --filename=Cacti_Stats.xml.gz
```

**Comment by TheWitness** [comment]
I'm simply going to suppress this warning for now.
