### ISSUE TITLE
Make THOLD working on 1min poller w/ 5min rrd

### ISSUE THREAD

**Issue by choefing** [Cacti/plugin_thold#392]
On our Cacti 1.2.7 / Thold 1.3.2 we were in need to provide a high resolution 1 minute poller for just some of the graphs while the remaining ones stay at 5 minutes.
So cron and poller cycle in Cacti is set to 1 minute and the hosts are equally distributed (cacti setting). This in turn means that every minute a cacti and thold poller runs where a dedicated 5 minute graph datasource is polled on e.g. 1st, 6th, 11th ... run.

When you now create a treshold for a 5 minute graph with baseline deviation for 30 minutes span, it creates one with "duration 6 minutes" as 5 poller runs are done within 5 minutes and thold therefore calculates with wrong values.

![Capture](https://user-images.githubusercontent.com/26385419/70019414-6e182380-1589-11ea-84d3-7ceb418c2536.PNG)

**The feature request here would be** to NOT to take the count of poller runs into consideration but check what kind of rrd / poller cycle time for that rrd is used for the datasource in question.

Thanks for the effort so far
Chris

**Comment by netniV** [comment]
I think that is a resaonable diagnosis.  We will look into it.

**Comment by TheWitness** [comment]
This is resolved now.
