### ISSUE TITLE
THOLD shows devices that have been deleted as down 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#394]
Hello All,

I am seeing that on THOLD 1.3.2 that when you delete a device that had a status of down 
thold shows the device as down still even though it does not exist

**Comment by bmfmancini** [comment]
More info 

I have a multi poller system 
I am noticing the issue on devices that were on a remote poller and not the main poller 
I am checking the tables now

**Comment by netniV** [comment]
I will have to run some tests when I get some time together. Unfortunately, multi-pollers do require more time and effort to debug due to their interactions and ensuring everything is at the same state.

**Comment by bmfmancini** [comment]
hey, @netniV  did you ever find anything on this ?
could it be related to what @TheWitness  fixed where the deleted column was not being purged ?
I would assume Monitor should ignore that table

**Comment by TheWitness** [comment]
Resolved.
