### ISSUE TITLE
Baseline Deviation does not work (as expected)

### ISSUE THREAD

**Issue by choefing** [Cacti/plugin_thold#396]
As uploading of files did not work for me several times please find values in the answers to this.

Cacti 1.2.8 
basic installation with 1 minute default setting during installation, no remote poller, no boost
Thold 1.3.2

###  Non floating time range window
Related to #140 
If this first finding is not a bug but a feature, please skip.
As per my understanding baseline deviation should find the e.g. lowest value in time range X and calculate the threshold. After next polling cycle this time range window should shift by the time of 1 polling cycle and calculate new thold. This obviously does not happen.
As per attached files you can see that the bl_thold_valid is a static timestamp, in my case it is valid for 15 minutes. AFTER those 15 minutes a new treshold is calculated from last 15 minutes, so time window is skipping to next every 15 minutes instead of every single minute as is it should be as per my understanding.

### Non working tholds for bit/s graphs

Next thing recognized is that thold baseline deviation is NOT working for the cacti provided "in/out bit/s (64bit)" but works properly for the byte/s ones.
I created 2 thold templates, baseline deviation, 15 minutes, 50% down alert.
See attached attempts to gather relevant data.
graph id 59 is always the bit/s one and 27 is always the byte/s.

**1st - thold_bits59_bytes27_no_cdef**
- Template thold "bits" and thold "bytes" with excat same settings
- data type is set to "Exact value"

Thold Overview shows always valid entries for "Current" so bit/s is 8 times higher than byte/s value-

bytes/s-thold: behaves as expected
bit/s-thold: "freaks" out after a time with the calculation of "thold_low" which leads to very high values and always have threshold breached until the "bl_thold_valid" refreshes and "thold_low" is calculated again.

Despite I know / thought data is retrieved from DS value in poller table and not from a graph value I tried to work with CDEF --> Turn bits into bytes.

**2nd - thold_bits59_bytes27_cdef_bits_to_bytes**
- Template thold "bits" and thold "bytes" with same base settings
- data type is set to "Exact value" for byte/s and "CDEF" Turn Bits into Bytes for bit/s

Thold Overview shows valid current value for byte/s and few Tbit/s value for bit/s where between 50 and 100 mbit/s are expected.

bytes/s-thold: behaves as expected
bit/s-thold: way to high values for "oldvalue" and "lastread" but despite value for "thold_low" is wrong, the calculation does not "freak out"

Tried the other way round as well with "bytes to bits" CDEF (even worse counters and current value) for just testing reasons as well as RPN expression "|ds:traffic_in|,8,/" (same result as "bits-to-bytes" CDEF version as expected) but did not receive any useful outcome for the bit/s graph thold.
See attached for values.

**Comment by choefing** [comment]
I can provide the remaining 2 test files if needed.

**thold_bits59_bytes27_no_cdef**
`

local_graph_id | thold_low | bl_ref_time_range | bl_pct_down | bl_thold_valid | lastread | lasttime | oldvalue
-- | -- | -- | -- | -- | -- | -- | --
59 |   | 900 | 50 | 0 | NULL | 0000-00-00 00:00:00 | NULL
27 |   | 900 | 50 | 0 | NULL | 0000-00-00 00:00:00 | NULL
59 | 489.788,87 | 900 | 50 | 1576791900 | 0,00 | 2019-12-19 21:38:02 | 1.272.739.402.694.770,00
27 | 3.918.310,92 | 900 | 50 | 1576791900 | 0,00 | 2019-12-19 21:38:02 | 1.272.739.402.694.770,00
59 | 3.918.310,92 | 900 | 50 | 1576791900 | 6.817.749,34 | 2019-12-19 21:39:01 | 1.272.739.804.941.980,00
27 | 3.918.310,92 | 900 | 50 | 1576791900 | 6.817.749,34 | 2019-12-19 21:39:01 | 1.272.739.804.941.980,00
59 | 31.346.487,39 | 900 | 50 | 1576791900 | 8.173.677,37 | 2019-12-19 21:40:01 | 1.272.740.295.362.630,00
27 | 3.918.310,92 | 900 | 50 | 1576791900 | 8.173.677,37 | 2019-12-19 21:40:01 | 1.272.740.295.362.630,00
59 | 250.771.899,12 | 900 | 50 | 1.576.791.900 | 9.238.472,85 | 2019-12-19 21:41:01 | 1.272.740.849.671.000,00
27 | 3.918.310,92 | 900 | 50 | 1.576.791.900 | 9.238.472,85 | 2019-12-19 21:41:01 | 1.272.740.849.671.000,00
59 | 2.006.175.192,93 | 900 | 50 | 1576791900 | 8.955.725,67 | 2019-12-19 21:42:01 | 1.272.741.387.014.540,00
27 | 3.918.310,92 | 900 | 50 | 1576791900 | 8.955.725,67 | 2019-12-19 21:42:01 | 1.272.741.387.014.540,00
59 | 16.049.401.543,48 | 900 | 50 | 1576791900 | 8.224.669,18 | 2019-12-19 21:43:01 | 1.272.741.880.494.690,00
27 | 3.918.310,92 | 900 | 50 | 1576791900 | 8.224.669,18 | 2019-12-19 21:43:01 | 1.272.741.880.494.690,00
59 | 128.395.212.347,80 | 900 | 50 | 1576791900 | 7.498.911,25 | 2019-12-19 21:44:01 | 1.272.742.330.429.360,00
27 | 3.918.310,92 | 900 | 50 | 1576791900 | 7.498.911,25 | 2019-12-19 21:44:01 | 1.272.742.330.429.360,00
59 | 518.746,20 | 900 | 50 | 1576792800 | 7.745.861,23 | 2019-12-19 21:45:01 | 1.272.742.795.181.040,00
27 | 4.149.969,61 | 900 | 50 | 1576792800 | 7.745.861,23 | 2019-12-19 21:45:01 | 1.272.742.795.181.040,00
59 | 4.149.969,61 | 900 | 50 | 1576792800 | 8.644.358,61 | 2019-12-19 21:46:02 | 1.272.743.322.486.910,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 8.644.358,61 | 2019-12-19 21:46:02 | 1.272.743.322.486.910,00
59 | 33.199.756,90 | 900 | 50 | 1.576.792.800 | 7.716.883,28 | 2019-12-19 21:47:02 | 1.272.743.785.499.910,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 7.716.883,28 | 2019-12-19 21:47:02 | 1.272.743.785.499.910,00
59 | 33.199.756,90 | 900 | 50 | 1.576.792.800 | 6.795.539,87 | 2019-12-19 21:48:05 | 1.272.744.213.618.920,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 6.795.539,87 | 2019-12-19 21:48:05 | 1.272.744.213.618.920,00
59 | 2.124.784.441,70 | 900 | 50 | 1.576.792.800 | 8.958.623,60 | 2019-12-19 21:49:02 | 1.272.744.724.260.470,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 8.958.623,60 | 2019-12-19 21:49:02 | 1.272.744.724.260.470,00
59 | 16.998.275.533,62 | 900 | 50 | 1.576.792.800 | 8.796.742,97 | 2019-12-19 21:50:02 | 1.272.745.252.065.040,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 8.796.742,97 | 2019-12-19 21:50:02 | 1.272.745.252.065.040,00
59 | 135.986.204.268,95 | 900 | 50 | 1.576.792.800 | 8.984.645,50 | 2019-12-19 21:51:02 | 1.272.745.791.143.770,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 8.984.645,50 | 2019-12-19 21:51:02 | 1.272.745.791.143.770,00
59 | 1.087.889.634.151,60 | 900 | 50 | 1.576.792.800 | 7.079.714,03 | 2019-12-19 21:52:02 | 1.272.746.215.926.620,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 7.079.714,03 | 2019-12-19 21:52:02 | 1.272.746.215.926.620,00
59 | 1.087.889.634.151,60 | 900 | 50 | 1.576.792.800 | 7.835.716,32 | 2019-12-19 21:53:05 | 1.272.746.709.576.740,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 7.835.716,32 | 2019-12-19 21:53:05 | 1.272.746.709.576.740,00
59 | 69.624.936.585.702,00 | 900 | 50 | 1.576.792.800 | 7.710.083,41 | 2019-12-19 21:54:03 | 1.272.747.156.761.580,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 7.710.083,41 | 2019-12-19 21:54:03 | 1.272.747.156.761.580,00
59 | 556.999.492.685.616,00 | 900 | 50 | 1.576.792.800 | 7.795.878,44 | 2019-12-19 21:55:02 | 1.272.747.616.718.410,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 7.795.878,44 | 2019-12-19 21:55:02 | 1.272.747.616.718.410,00
59 | 4.455.995.941.484.920,00 | 900 | 50 | 1.576.792.800 | 7.463.009,98 | 2019-12-19 21:56:02 | 1.272.748.064.499.010,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 7.463.009,98 | 2019-12-19 21:56:02 | 1.272.748.064.499.010,00
59 | 35.647.967.531.879.400,00 | 900 | 50 | 1.576.792.800 | 8.977.745,00 | 2019-12-19 21:57:02 | 1.272.748.603.163.710,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 8.977.745,00 | 2019-12-19 21:57:02 | 1.272.748.603.163.710,00
59 | 285.183.740.255.035.000,00 | 900 | 50 | 1.576.792.800 | 10.083.371,58 | 2019-12-19 21:58:02 | 1.272.749.208.166.000,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 10.083.371,58 | 2019-12-19 21:58:02 | 1.272.749.208.166.000,00
59 | 2.281.469.922.040.280.000,00 | 900 | 50 | 1.576.792.800 | 8.069.889,77 | 2019-12-19 21:59:02 | 1.272.749.692.359.390,00
27 | 4.149.969,61 | 900 | 50 | 1.576.792.800 | 8.069.889,77 | 2019-12-19 21:59:02 | 1.272.749.692.359.390,00
59 | 512.323,15 | 900 | 50 | 1.576.793.700 | 8.147.053,62 | 2019-12-19 22:00:02 | 1.272.750.181.182.610,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 8.147.053,62 | 2019-12-19 22:00:02 | 1.272.750.181.182.610,00
59 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 9.625.303,20 | 2019-12-19 22:01:02 | 1.272.750.758.700.800,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 9.625.303,20 | 2019-12-19 22:01:02 | 1.272.750.758.700.800,00
59 | 32.788.681,44 | 900 | 50 | 1.576.793.700 | 8.042.082,53 | 2019-12-19 22:02:02 | 1.272.751.241.225.750,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 8.042.082,53 | 2019-12-19 22:02:02 | 1.272.751.241.225.750,00
59 | 262.309.451,52 | 900 | 50 | 1.576.793.700 | 8.252.633,22 | 2019-12-19 22:03:01 | 1.272.751.728.131.110,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 8.252.633,22 | 2019-12-19 22:03:01 | 1.272.751.728.131.110,00
59 | 2.098.475.612,16 | 900 | 50 | 1.576.793.700 | 9.165.806,80 | 2019-12-19 22:04:01 | 1.272.752.278.079.520,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 9.165.806,80 | 2019-12-19 22:04:01 | 1.272.752.278.079.520,00
59 | 16.787.804.897,28 | 900 | 50 | 1.576.793.700 | 8.236.932,20 | 2019-12-19 22:05:01 | 1.272.752.772.295.450,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 8.236.932,20 | 2019-12-19 22:05:01 | 1.272.752.772.295.450,00
59 | 134.302.439.178,24 | 900 | 50 | 1.576.793.700 | 12.182.782,98 | 2019-12-19 22:06:01 | 1.272.753.503.262.430,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 12.182.782,98 | 2019-12-19 22:06:01 | 1.272.753.503.262.430,00
59 | 1.074.419.513.425,90 | 900 | 50 | 1.576.793.700 | 9.446.993,57 | 2019-12-19 22:07:01 | 1.272.754.070.082.040,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 9.446.993,57 | 2019-12-19 22:07:01 | 1.272.754.070.082.040,00
59 | 8.595.356.107.407,20 | 900 | 50 | 1.576.793.700 | 8.563.025,92 | 2019-12-19 22:08:01 | 1.272.754.583.863.600,00
27 | 4.098.585,18 | 900 | 50 | 1.576.793.700 | 8.563.025,92 | 2019-12-19 22:08:01 | 1.272.754.583.863.600,00

`

**thold_bits59_bytes27_cdef_bits_to_bytes**
`

local_graph_id | thold_low | bl_ref_time_range | bl_pct_down | bl_thold_valid | lastread | lasttime | oldvalue
-- | -- | -- | -- | -- | -- | -- | --
59 | 488.848,57 | 900 | 50 | 1576795500 | 0,00 | 2019-12-19 22:31:02 | 1.590.956.827.670.300.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 0,00 | 2019-12-19 22:31:02 | 1.272.765.462.136.210,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.696.537.851.525,20 | 2019-12-19 22:32:01 | 1.590.957.332.399.900.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.843.791,58 | 2019-12-19 22:32:01 | 1.272.765.865.919.910,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.596.720.031,10 | 2019-12-19 22:33:01 | 1.590.958.032.018.700.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 9.328.250,50 | 2019-12-19 22:33:01 | 1.272.766.425.614.940,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.597.987.232,10 | 2019-12-19 22:34:01 | 1.590.958.792.339.300.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 10.137.607,65 | 2019-12-19 22:34:01 | 1.272.767.033.871.400,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.598.893.805,90 | 2019-12-19 22:35:01 | 1.590.959.336.283.500.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 7.252.590,53 | 2019-12-19 22:35:01 | 1.272.767.469.026.830,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.599.764.595,80 | 2019-12-19 22:36:01 | 1.590.959.858.757.500.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.966.319,48 | 2019-12-19 22:36:01 | 1.272.767.887.006.000,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.600.600.251,10 | 2019-12-19 22:37:01 | 1.590.960.360.150.700.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.685.241,92 | 2019-12-19 22:37:01 | 1.272.768.288.120.520,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.601.453.830,20 | 2019-12-19 22:38:01 | 1.590.960.872.298.100.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.828.633,23 | 2019-12-19 22:38:01 | 1.272.768.697.838.510,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.602.263.054,80 | 2019-12-19 22:39:01 | 1.590.961.357.832.900.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.473.796,45 | 2019-12-19 22:39:01 | 1.272.769.086.266.300,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.603.170.993,80 | 2019-12-19 22:40:01 | 1.590.961.902.596.300.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 7.263.512,05 | 2019-12-19 22:40:01 | 1.272.769.522.077.020,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.604.018.809,30 | 2019-12-19 22:41:01 | 159.096.241.128.557,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.782.523,85 | 2019-12-19 22:41:01 | 1.272.769.929.028.450,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.604.870.328,60 | 2019-12-19 22:42:01 | 159.096.292.219.716,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.812.154,53 | 2019-12-19 22:42:01 | 1.272.770.337.757.720,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.605.679.418,60 | 2019-12-19 22:43:01 | 1.590.963.407.651.100.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 6.472.719,78 | 2019-12-19 22:43:01 | 1.272.770.726.120.910,00
59 | 488.848,57 | 900 | 50 | 1576795500 | 2.651.606.724.971,30 | 2019-12-19 22:44:01 | 1.590.964.034.982.800.000.000.000.000,00
27 | 3.910.788,52 | 900 | 50 | 1576795500 | 8.364.422,17 | 2019-12-19 22:44:01 | 1.272.771.227.986.240,00
59 | 461.613,31 | 900 | 50 | 1576796400 | 2.651.607.625.076,40 | 2019-12-19 22:45:01 | 1.590.964.575.045.800.000.000.000.000,00
27 | 3.692.906,46 | 900 | 50 | 1576796400 | 7.200.840,55 | 2019-12-19 22:45:01 | 1.272.771.660.036.670,00
59 | 461.613,31 | 900 | 50 | 1576796400 | 2.608.139.666.616,30 | 2019-12-19 22:46:02 | 159.096.519.663.600.000.000.000.000,00
27 | 3.692.906,46 | 900 | 50 | 1576796400 | 8.152.001,62 | 2019-12-19 22:46:02 | 1.272.772.157.308.770,00
59 | 461.613,31 | 900 | 50 | 1576796400 | 2.651.609.572.120,30 | 2019-12-19 22:47:02 | 1.590.965.743.272.200.000.000.000.000,00
27 | 3.692.906,46 | 900 | 50 | 1576796400 | 7.288.482,73 | 2019-12-19 22:47:02 | 1.272.772.594.617.740,00
59 | 461.613,31 | 900 | 50 | 1576796400 | 2.696.552.982.835,90 | 2019-12-19 22:48:01 | 159.096.625.987.320,00
27 | 3.692.906,46 | 900 | 50 | 1576796400 | 7.004.759,64 | 2019-12-19 22:48:01 | 1.272.773.007.898.560,00
59 | 461.613,31 | 900 | 50 | 1576796400 | 2.608.142.337.394,70 | 2019-12-19 22:49:02 | 1.590.966.825.810.700.000.000.000.000,00
27 | 3.692.906,46 | 900 | 50 | 1576796400 | 7.422.131,70 | 2019-12-19 22:49:02 | 1.272.773.460.648.590,00
59 | 461.613,31 | 900 | 50 | 1576796400 | 2.651.612.349.886,20 | 2019-12-19 22:50:02 | 1.590.967.409.931.700.000.000.000.000,00
27 | 3.692.906,46 | 900 | 50 | 1576796400 | 7.788.279,38 | 2019-12-19 22:50:02 | 1.272.773.927.945.350,00

`

**Comment by TheWitness** [comment]
Switched to 1.6 milestone.  Not enough time.

**Comment by TheWitness** [comment]
This should be resolved now.  I've made some fairly large enhancements to Baseline deviation today.  Will be released in 2.0.
