### ISSUE TITLE
help to configure thold

### ISSUE THREAD

**Issue by amarnath-jena** [Cacti/plugin_thold#399]
![cactigenralinfo](https://user-images.githubusercontent.com/54077804/73921847-2649ab80-48ee-11ea-8924-20852abb670b.png)
 I have setup thold in cacti for snmp and ping devices (device uptime) as the devices goes down the alert is generated. But the issue is when i ping the device from my local machine its works. And the alerts just irritates in my inbox it sends alert even if the device is down 1 min . Help me out to configure thold for a devices in such condition if the devices stay down for 10min then send a alert for down or up whatever it may be.  I am new for Thold

Thank you

**Comment by bmfmancini** [comment]
you change the threshold to time based 
then change the trigger count to 10

**Comment by amarnath-jena** [comment]
i did the same changes but still it generates alert even if the device is working fine .

**Comment by amarnath-jena** [comment]
![Screenshot from 2020-02-07 12-26-40](https://user-images.githubusercontent.com/54077804/74007789-2d7fc080-49a5-11ea-83ad-9318f583bea7.png)

**Comment by TheWitness** [comment]
There is not enough information here.  What is your data source and if you would please upload the script.  I would have preferred you use the Monitor plugin for notification.
