### ISSUE TITLE
sql index reached; Too many keys specified; max 64 keys allowed

### ISSUE THREAD

**Issue by laterallink** [Cacti/plugin_thold#40]
Was having issues with the plugin not pulling up any of the view pages, figured it might be something to consider looking at, not sure how commenting out the below items might effect something other than some sql performance, but figured I'd report it anyhow; 

mysql> show index in thold_data;

> | thold_data |          1 | tcheck_15         |            1 | tcheck           | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
> | thold_data |          1 | graph_id_15       |            1 | graph_id         | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
> | thold_data |          1 | graph_template_14 |            1 | graph_template   | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
> +------------+------------+-------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+
64 rows in set (0.00 sec)

strace was showing the proc locked in an endless loops:

```
 write(17, "0\0\0\0\3ALTER TABLE `thold_data` ADD INDEX ( `tcheck` )", 52) = 52
 read(17, "5\0\0\1\377-\4#42000Too many keys specified; max 64 keys allowed", 16384) = 57
 
 write(17, "Q\0\0\0\3ALTER TABLE thold_data ADD COLUMN bl_thold_valid INT UNSIGNED NOT NULL DEFAULT 0", 85) = 85
 read(17, "/\0\0\1\377$\4#42S21Duplicate column name 'bl_thold_valid'", 16384) = 51
 
 write(17, "Q\0\0\0\3ALTER TABLE thold_data ADD COLUMN bl_thold_valid INT UNSIGNED NOT NULL DEFAULT 0", 85) = 85
 read(17, "/\0\0\1\377$\4#42S21Duplicate column name 'bl_thold_valid'", 16384) = 51
```

Uninstall/reinstall with the following changes to bring things back online:
Commented out in includes/database.php:

```
 #     db_execute('ALTER TABLE `thold_data` ADD INDEX ( `tcheck` )', FALSE);
 #     db_execute('ALTER TABLE `thold_data` ADD INDEX ( `graph_id` )', FALSE);
 #     db_execute('ALTER TABLE `thold_data` ADD INDEX ( `graph_template` )', FALSE);
 #     db_execute('ALTER TABLE `thold_data` ADD INDEX ( `data_template` )', FALSE);
 
 #     db_execute("ALTER TABLE thold_data REMOVE COLUMN bl_enabled", FALSE);
 #     db_execute("ALTER TABLE thold_template REMOVE COLUMN bl_enabled", FALSE);
```

Updated to modify instead of add: 
```
 db_execute('ALTER TABLE thold_data MODIFY COLUMN bl_thold_valid INT UNSIGNED NOT NULL DEFAULT 0', FALSE);
```

**Comment by cigamit** [comment]
Have you been running Cacti 1.0.0 alpha for a while?  We had a bug in db_execute() that would cause a loop.  It was corrected a while ago.  You may have to re-install thold using the latest Cacti, or dump the table and reload it after editing out all the duplicated indexes.

**Comment by cigamit** [comment]
Okay, I stand corrected.  I see the real issue here.  Thanks for reporting.  I have resolved the issue.
