### ISSUE TITLE
Slow cli_thresholds.php Performance

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#400]
Hey Guys 

I am noticing a slowdown on the cli_thresholds.php script  

I am trying to quantify this to help however to create roughly 1k Thresholds was about 20 minutes but via the cacti GUI it was about 3 minutes 

Cacti version 1.2.9 
THOLD version 1.3.2

I believe it has to do with the PHP script not spawning it appears the GUI does which explains the speed difference

**Comment by TheWitness** [comment]
Well that's odd.

**Comment by TheWitness** [comment]
Show me how you are calling the script that causes the slowdown.

**Comment by bmfmancini** [comment]
sure let me pull up the command I used

**Comment by bmfmancini** [comment]
php cli_thresholds.php --thold-template=2

That template is for a interface errors template

**Comment by TheWitness** [comment]
This should be fixed now.  Please test.

**Comment by bmfmancini** [comment]
Ok tested 

The script is a bit faster however compared to the gui its much slower 

Via CLI script 
3 Minutes to create 1158 thresholds

Via Gui
 25 Seconds
