### ISSUE TITLE
Errors occur with invalid thresholds with a bad thold type

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_thold#401]
Hello,
Once in a while I get this error:
13/02/2020 08:54:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[801]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2207]:get_thold_alert_text(), /plugins/thold/thold_functions.php[3606]:thold_replace_threshold_tags(), /plugins/thold/thold_functions.php[3540]:CactiErrorHandler())
13/02/2020 08:54:18 - ERROR PHP NOTICE in Plugin 'thold': Trying to access array offset on value of type null in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 3540

Cacti 1.2.9
thold:1.3.2

Forum: https://forums.cacti.net/viewtopic.php?f=17&t=60668
and suggestion from NetIV:
$text = str_replace('<THOLDTYPE>',     $thold_types[$thold['thold_type']], $text);

So this suggests that your threshold doesn't have a type. And it's then trying to use null (since there was no value) when accessing the array.

But I have no threshold with an empty type!

**Comment by TheWitness** [comment]
I suspect that this is symptomatic of another issue, like the thold is not even set.
