### ISSUE TITLE
Notification List changes should be allowed enmass 

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_thold#403]
**Is your feature request related to a problem? Please describe.**
At the moment, there doesn't apply to be a way to change several devices so that they are using different notification settings.  I thought this would be under Change Device Options or Change Monitoring Options but neither shows the ability to modify them.

**Describe the solution you'd like**
The ability to select the notification list mode and list itself.

**Comment by TheWitness** [comment]
This is presently performed from the Notification List 'edit' function and is supported.  So, this is really not required, just a documentation issue.
