### ISSUE TITLE
THOLD 1.3.3  Cacti 1.2.9 PHP errors 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#404]
Hello Everyone 

First off @TheWitness  the new release is great! 
I appreciate all the work you did!!

I just noticed the following new errors I haven't seen before so far in my lab testing everything works so I am sure these are minor errors 

2020/03/02 10:05:04 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[801]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2220]:thold_command_execution(), /plugins/thold/thold_functions.php[3449]:thold_set_environ(), /plugins/thold/thold_functions.php[3500]:CactiErrorHandler())

2020/03/02 10:05:04 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: status_last_error in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 3500
2020/03/02 10:05:04 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[801]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2220]:thold_command_execution(), /plugins/thold/thold_functions.php[3449]:thold_set_environ(), /plugins/thold/thold_functions.php[3499]:CactiErrorHandler())

**Comment by TheWitness** [comment]
I just pushed a change.  Let me know if you get any more errors.

**Comment by TheWitness** [comment]
Tagged to the wrong ticket.  You should see the diff now.

**Comment by bmfmancini** [comment]
Cool man !

I confirm this is working error free now!
