### ISSUE TITLE
THOLD 1.3.4 no 1 minute cycle/Trigger option

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#406]
Hello 

I notice that in 1.3.4 the 1 Minute cycle/Trigger  option is missing

![image](https://user-images.githubusercontent.com/13388748/76997227-580c5400-6929-11ea-9e5c-3ee97de8bef2.png)

Here is 1.3.2

![image](https://user-images.githubusercontent.com/13388748/76997299-7eca8a80-6929-11ea-8a46-d2553b6bfd4b.png)

**Comment by bmfmancini** [comment]
Looked deeper into this  the option is also not present in 1.3.3
@TheWitness  was this removed for a reason or is there a bug or something?

**Comment by TheWitness** [comment]
It's a bug.  Fixing in a minute or so.
