### ISSUE TITLE
THOLD  1.3.2 Showing mysql has gone away even when everything is working fine

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#408]
Hello Everyone 

After applying suggested names to a device Thold went nuts exhausted all of the system memory and is now spewing out these errors 

2020/03/25 14:30:08 - CMDPHP SQL Backtrace: (/poller.php[801]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[469]:thold_check_threshold(), /plugins/thold/thold_functions.php[2565]:thold_check_baseline(), /plugins/thold/thold_functions.php[4221]:thold_get_ref_value(), /plugins/thold/thold_functions.php[4146]:rrdtool_function_fetch(), /lib/rrd.php[899]:boost_fetch_cache_check(), /lib/boost.php[272]:boost_process_poller_output(), /lib/boost.php[632]:db_fetch_cell(), /lib/database.php[383]:db_fetch_cell_prepared(), /lib/database.php[399]:db_execute_prepared())
2020/03/25 14:30:08 - CMDPHP ERROR: A DB Cell Failed!, Error: MySQL server has gone away

The DB is up and running no issues graphs are working just fine and cacti UI is working but I am getting an errors saying the DB is not working ?? very odd

**Comment by TheWitness** [comment]
This likely has something to do with there being aborts and the MySQL server cutting off connections, or you may be flushing hosts on the server side while processes are using those connections.  This is more of a Cacti issue.  So, if the problems continue, please open a bug on the cacti forums indicating which db* function is providing those errors.
