### ISSUE TITLE
Cannot send mail due to default From mail is invalid 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#409]
**To Reproduce**
1. Add a thold and trigger it, make it send mail to user 
2. After thold trigger, can not send mail to user and log error exist 
2020/03/26 06:20:04 - THOLD ERROR: Sending Email Failed. Error was Invalid address: (From): Cacti@localhost
2020/03/26 06:20:04 - CMDPHP MAILER ERROR Backtrace: (/poller.php[801]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[474]:thold_check_threshold(), /plugins/thold/thold_functions.php[2217]:thold_mail(), /plugins/thold/thold_functions.php[5388]:mailer(), /lib/functions.php[3527]:record_mailer_error(), /lib/functions.php[3733]:cacti_debug_backtrace())
2020/03/26 06:20:04 - CMDPHP MAILER ERROR: Invalid address: (From): Cacti@localhost
2020/03/26 06:20:03 - THOLD ERROR: Sending Email Failed. Error was Invalid address: (From): Cacti@localhost 

For cacti 1.2.x, use new mailer, will check email format and the mail domain must be two part.  If not set From mail, using default From mail in thold, the error exist.

**Expected behavior**
Can send mail to user using default from mail in thold. 

**Plugin (please complete the following information):**
cacti 1.2.10
thold 1.3.4

**Desktop (please complete the following information):**
 - OS: rhel7 x64
 - Browser  FF 74

**Comment by a-lang** [comment]
I had the same issue and I found a quick solution as follows.

To verify the issue check if the table 'settings' missed the names called thold_*, the amount 
 is supposed to be more than 20, if it isn't, go to next step.

Go to Cacti Admin > Configuration > Settings > Alerting/Thold > 
 Select one of whatever you wanted and make a change to it and then SAVE it.

The DB is supposed to be updated that those missed rows in the table 'settings' were re-inserted.

That's it. Try it again the email should be working.
![cacti-fix-email](https://user-images.githubusercontent.com/11038458/77736323-08273e80-7047-11ea-8ada-6db80679281e.png)

**Comment by ddb4github** [comment]
@a-lang Yes,  Pre-Condition is that `settings_from_email` is configured.
If both of 'settings_from_email' and `thold_from_email` are not configured, Thold plugin will use default `Cacti@<server name>` or `Cacti@locahost`

Cact use PHPMailer library since Cacti 1.0,  And PHPMailer  always validate email addr format with PHP build-in ruler `FILTER_VALIDATE_EMAIL` if `FromMail` include `@`

a valid format must like `name@hostname.dormainame`, or just `name`
