### ISSUE TITLE
The newly added device In Stat value incorrect

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#411]
**To Reproduce**
1) Go to management - device page
2) Add a device
3) Go to Thold -device status page to check the newly added device info,  In State value is incorrect.

**Screenshots**
<img width="1280" alt="Screen Shot 2020-03-27 at 2 28 53 PM" src="https://user-images.githubusercontent.com/47589910/77733316-9f899300-7041-11ea-969b-b67c56fab6f3.png">

**Plugin (please complete the following information):**
cacti 1.2.10
thold 1.3.4
rhel8.2 x64
FF 74

**Comment by ddb4github** [comment]
Cacti-->host.php
```php
CAST(IF(availability_method = 0, '0',
	IF(status_event_count > 0 AND status IN (1, 2), status_event_count*$poller_interval,
	IF(UNIX_TIMESTAMP(status_rec_date) < 943916400 AND status IN (0, 3), total_polls*$poller_interval,
	IF(UNIX_TIMESTAMP(status_rec_date) > 943916400, UNIX_TIMESTAMP() - UNIX_TIMESTAMP(status_rec_date),
	IF(snmp_sysUptimeInstance>0 AND snmp_version > 0, snmp_sysUptimeInstance/100, UNIX_TIMESTAMP()
))))) AS unsigned) AS instate
```
Thold-->thold_functions.php
```php
IF(status_event_count>0, status_event_count*$poller_interval,
IF(UNIX_TIMESTAMP(status_rec_date)>943916400,UNIX_TIMESTAMP()-UNIX_TIMESTAMP(status_rec_date),
IF(snmp_sysUptimeInstance>0 AND snmp_version > 0, snmp_sysUptimeInstance,UNIX_TIMESTAMP()))) AS instate
```

**Comment by yingbaiibm** [comment]
@TheWitness  This still not work in my env with the fix

**Comment by ddb4github** [comment]
Might be Cacti Issue:
For a new created virtual device with configuration as table below,  TimeInState will be  shown as current milliseconds by UNIX_TIMESTAMP(). Both Console->Devices and Thold->Device Status
availability_method | status_event_count | status | status_rec_date | UNIX_TIMESTAMP(status_rec_date) | total_polls | snmp_sysUptimeInstance | inState
--- | :--- | :--- | :--- | :--- | :--- | :--- | :---
2 | 0 | 1 | 0000-00-00 00:00:00 | 0 | 0 | 0 | 1587890213

**Comment by netniV** [comment]
```php
CAST(IF(availability_method = 0, 

		-- No, Set to 2
		'0', 

	IF(status_event_count > 0 AND status IN (1, 2), 

		-- No, event count is 0
		status_event_count*$poller_interval,

	IF(UNIX_TIMESTAMP(status_rec_date) < 943916400 AND status IN (0, 3), 

		-- No, UT(SRD) = 0, status = 1
		total_polls*$poller_interval,

	IF(UNIX_TIMESTAMP(status_rec_date) > 943916400, 

		-- No, UT(SRD) = 0
		UNIX_TIMESTAMP() - UNIX_TIMESTAMP(status_rec_date),

	IF(snmp_sysUptimeInstance>0 AND snmp_version > 0, 

	    -- No, sysUpTime = 0
		snmp_sysUptimeInstance/100, 

-- Yes, all other options exhausted
UNIX_TIMESTAMP()
))))) AS unsigned) AS instate
```

So, based off the code and your comments, this should be using the unix timestamp as we have no idea when a previous state changed.  If you can suggest a better method, that may need also applying to the core.

**Comment by ddb4github** [comment]
0. I trigger this issue after create a virtual host, and before poller.php run
1. `total_polls` will be always greater than zero if poller.php can regularly run, and host table is updated per poller cycle
2. `last_updated` is initialized with "created time", and will be updated on time once host table is regularly updated.
3. Then `total_polls  + last_updated` combination can be trusted now.

So I think
```pascal
if <current existing contions>
....
else If total_polls > 0 //host table is updated by workable poller.php
    return total_polls*$poller_interval
else if <other condition>
....
else //host table is never updated, last_updated=<host> record created time
    UNIX_TIMESTAMP() - UNIX_TIMESTAMP(last_updated)
```

BTW,  Sometimes, `total_polls` and `availability` are reset by "Clear Statistics" action. 
If poller.php become in-workable after "Reset" acton, `UNIX_TIMESTAMP() - UNIX_TIMESTAMP(last_updated)` is still valuable that means `From previous 'reset' time to now()`

**Comment by netniV** [comment]
As long as that can be replicated between the versions using SQL and those using PHP calls, that seems good to me.  I know I battled with it in the past and managed to get it where it is now for both core and thold, previously it was a lot more unreliable.
