### ISSUE TITLE
Error while sending notify email

### ISSUE THREAD

**Issue by georgiyAK** [Cacti/plugin_thold#413]
When event triggered, i have error in logs 

CMDPHP MAILER ERROR Backtrace:  (/poller.php[801]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[35]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[251]:thold_check_threshold(), /plugins/thold/thold_functions.php[1751]:thold_mail(), /plugins/thold/thold_functions.php[3567]:mailer(), /lib/functions.php[3521]:record_mailer_error(), /lib/functions.php[3719]:cacti_debug_backtrace())
2020/04/02 16:00:06 - SNMPAGENT ERROR: Unknown event: tholdNotify (CACTI-THOLD-MIB)

**Comment by TheWitness** [comment]
What version of Cacti and thold?  Also, do you have the snmpagent enabled from Console > Configuration > Settings > Poller?

**Comment by georgiyAK** [comment]
Cacti version is 1.2.10
Thold version is  1.0.3

I try turn off and turn on snmp agent support, but there is no result.

**Comment by TheWitness** [comment]
Define "no result".  If you have snmp agent support disabled, you should not be using notification receivers or traps/informs in thold.  This bug should be addressed though.  Might be more of a thold issue.  Will have to check.

**Comment by georgiyAK** [comment]
"No result" mean - no email alerts was recivied. Now i turn snmp agent suport to "off". What options need to be configured in thold to recive emails?

**Comment by netniV** [comment]
You are likely having mailing problems due to the age of Thold that you are using versions the practically up to date cacti.  The mailer function has changed a lot and you are likely using an incompatible version of Thold.

**Comment by TheWitness** [comment]
Assuming user upgrade thold and this issue is resolved.
