### ISSUE TITLE
zero 'lastread' value incorrectly processed by thold_check_threshold()

### ISSUE THREAD

**Issue by ahouston** [Cacti/plugin_thold#417]
**Describe the bug**

I use the THOLD to alarm on interfaces where the traffic has dropped to zero as a way of detecting link failures in the network.

I noticed that some of these thresholds are no longer triggering, and went digging in the code to try figure this out.

I believe the issue is in thold_functions.php, line 2157: `if ($thold_data['lastread'] != '') {`

When the value is numeric zero, then `0 != ''` evaluates to false, meaning $breach_up and $breach_down are set to false.

I've changed this line to `if ($thold_data['lastread'] !== '') {` and the thresholds are triggering correctly now. I assume that this would apply to line 2809 too.

**To Reproduce**
1. Setup threshold on SNMP interface traffic_in with alert or warning low set to 1
2. Fail the link
3. Observe threshold not triggering

**Expected behavior**

Zero values should be valid for the purposes of comparison.

**Comment by netniV** [comment]
Since lastread in thold_data allows for nulls, I think you would need to amend that to be:

```php
$thold_data['lastread'] !== '' && thold_data['lastread'] !== false
```

Would you agree?

**Comment by netniV** [comment]
Alternatively, use is_numeric() around it? It seems to be used as a numeric string value so we can check that it is one?

**Comment by ahouston** [comment]
Agreed - I think your is_numeric() idea is the simplest and neatest solution.
