### ISSUE TITLE
Charts are no longer being tracked.

### ISSUE THREAD

**Issue by ank0l0g** [Cacti/plugin_thold#419]
Hi.

It was 1.3.2 updated to 1.4

Charts are no longer being tracked.
Depended on some value.
Removing and re-creating tracking does not produce results. The value is empty.
![err-1](https://user-images.githubusercontent.com/60463210/79433543-4d071b00-7fde-11ea-8eff-7ff11aae173c.JPG)
![err-2](https://user-images.githubusercontent.com/60463210/79433549-4ed0de80-7fde-11ea-9433-805a1a9bf445.JPG)
![err-3](https://user-images.githubusercontent.com/60463210/79433554-509aa200-7fde-11ea-8a9b-cf83121cec2c.JPG)
![err-4](https://user-images.githubusercontent.com/60463210/79433555-509aa200-7fde-11ea-9170-35b1a80aeaa7.JPG)

**Comment by TheWitness** [comment]
You comments make no sense.  Please take this up on the forums, and if a developer is able to assist you there and recommended you open a bug, then come back and open one where you have clearly stated the issue.

**Comment by TheWitness** [comment]
I think I know the issue now, are you using the thold_daemon?  Is it running, the daemon?  Do you see thold statistics coming into the log?  Is the plugin enabled?  Likely you encountered an error and thold disabled itself to prevent damaging the Cacti system.  When you find the source of that, please open a new ticket.

**Comment by ank0l0g** [comment]
The plugin Thold has been launched.
There is information in the logs about him.
![err-5](https://user-images.githubusercontent.com/60463210/80335999-07144780-8867-11ea-8b26-45d5e05ce842.JPG)
![err-6](https://user-images.githubusercontent.com/60463210/80336001-08457480-8867-11ea-957d-69e1c2f3d51e.JPG)

**Comment by TheWitness** [comment]
For now, just disable the daemon.  You system is small enough.  Then, we need to debug the daemon, but I don't have time presently.  Maybe @browniebraun can help diagnose.  He wrote it.
