### ISSUE TITLE
Charts are no longer being tracked

### ISSUE THREAD

**Issue by ank0l0g** [Cacti/plugin_thold#428]
Hi.

It was 1.3.2 updated to 1.4

Charts are no longer being tracked.
Depended on some value.
Removing and re-creating tracking does not produce results. The value is empty.
The plugin Thold has been launched.
There is information in the logs about him.

![err-5](https://user-images.githubusercontent.com/60463210/79725099-bbf3b500-82f9-11ea-8e3b-1d1ce448e479.JPG)
![err-6](https://user-images.githubusercontent.com/60463210/79725108-c0b86900-82f9-11ea-9a61-63fe27ef3112.JPG)
![err-1](https://user-images.githubusercontent.com/60463210/79725118-c44bf000-82f9-11ea-8546-087754302aa9.JPG)
![err-2](https://user-images.githubusercontent.com/60463210/79725121-c4e48680-82f9-11ea-98f9-d2dbb9960a58.JPG)
![err-3](https://user-images.githubusercontent.com/60463210/79725123-c4e48680-82f9-11ea-8cff-82b57640af64.JPG)
![err-4](https://user-images.githubusercontent.com/60463210/79725126-c57d1d00-82f9-11ea-9feb-086c5fd79f80.JPG)

**Comment by netniV** [comment]
I believe that this is a duplicate issue so I'm going to close it.
