### ISSUE TITLE
Create new threshold not creating

### ISSUE THREAD

**Issue by mattymrm** [Cacti/plugin_thold#43]
Clicking on the icon to create a threshold next to a graph, goes to the next page, select action to create a new threshold, then click continue and this just throws me back to the page of graphs I was looking at with no errors. Creating from an existing thold template is fine though.

my thold is broke anyway as the current value never updates and ive been going cross eyed for the last few weeks trying to figure out why :/

**Comment by mattymrm** [comment]
<img width="988" alt="screen shot 2017-02-07 at 01 55 22" src="https://cloud.githubusercontent.com/assets/25553853/22674685/32a9816c-ecd9-11e6-82f8-6aaf19041995.png">
<img width="1688" alt="screen shot 2017-02-07 at 01 56 13" src="https://cloud.githubusercontent.com/assets/25553853/22674684/32a8f7a6-ecd9-11e6-8154-e768d67f7e60.png">

tried uninstalling plugin, starting from scratch. Current value never updates. Doesn't matter even if I create a threshold against a standard traffic interface. As you can see its reading the current value ok.

**Comment by cigamit** [comment]
Goto Settings->Threshold and see if thresholds are disabled.  It's the first option on that page.  Also, is the Threshold Daemon enabled?  If so, disable it.

**Comment by mattymrm** [comment]
yeah it was the threshold daemon being enabled that stopped it working, thanks :) Looks like when you uninstall and re-install the plugin it doesn't clear its settings table out also.

**Comment by mattymrm** [comment]
shouldn't the daemon work? :)

Also the original issue still remains, if I click to create a new threshold not from a template it throws me back to the graph list page.

**Comment by cigamit** [comment]
Mattymrm, Can you open a fresh issue?  In there, take us through reproduction one step at a time.  Which options did you choose after clicking the icon, etc.  Once we have a full repeatable case, we can squash it.

**Comment by mattymrm** [comment]
yeah opened as issue 44. :) cheers. ill open another one for the daemon.

**Comment by browniebraun** [comment]
I've already updated the daemon to flush the tables once it starts.
