### ISSUE TITLE
ERROR PHP WARNING in  Plugin 'thold': Use of undefined constant LOG_VERBOSITY_MEDIUM

### ISSUE THREAD

**Issue by tfagart** [Cacti/plugin_thold#433]
Hello

**Describe the bug**
I can see lot's of PHP Warning while threshold are being calculated

**To Reproduce**
1. Check your logs while you've got thold

**Expected behavior**
No more error logs

**Screenshots**

**Plugin (please complete the following information):**
 - Version: 1.4
 - Source: Github

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 76.0.1

**Additional context**
I've got a little bit more than 20K thold being calculated each 5 mns. There is 54 lines of log error each 5 mns (That might be related to specific thold)

Thanks

**Comment by netniV** [comment]
That seems strange because POLLER_VERBOSITY_MEDIUM is a constant in `includes/global_constants.php`:

```console
~/sp POLLER_VERBOSITY_MEDIUM
Searching for POLLER_VERBOSITY_MEDIUM
includes/global_arrays.php:622:	POLLER_VERBOSITY_MEDIUM => __('MEDIUM - Statistics, Errors and Results'),
includes/global_constants.php:126:define('POLLER_VERBOSITY_MEDIUM', 3);
```

Do you have the stack trace for this?

**Comment by ddb4github** [comment]
```diff
diff --git a/thold_functions.php b/thold_functions.php
index 4fc41d3..60414a8 100644
--- a/thold_functions.php
+++ b/thold_functions.php
@@ -4032,7 +4032,7 @@ function thold_build_cdef($cdef, $value, $local_data_id, $data_template_rrd_id)

                        break;
                default:
-                       cacti_log('Unknown RPN type: ' . $cdef_array[$cursor]['type'], false, 'THOLD', LOG_VERBOSITY_MEDIUM);
+                       cacti_log('Unknown RPN type: ' . $cdef_array[$cursor]['type'], false, 'THOLD', POLLER_VERBOSITY_MEDIUM);

                        return($oldvalue);
```

**Comment by netniV** [comment]
> ```diff
> diff --git a/thold_functions.php b/thold_functions.php
> index 4fc41d3..60414a8 100644
> --- a/thold_functions.php
> +++ b/thold_functions.php
> @@ -4032,7 +4032,7 @@ function thold_build_cdef($cdef, $value, $local_data_id, $data_template_rrd_id)
> 
>                         break;
>                 default:
> -                       cacti_log('Unknown RPN type: ' . $cdef_array[$cursor]['type'], false, 'THOLD', LOG_VERBOSITY_MEDIUM);
> +                       cacti_log('Unknown RPN type: ' . $cdef_array[$cursor]['type'], false, 'THOLD', POLLER_VERBOSITY_MEDIUM);
> 
>                         return($oldvalue);
> ```

Good spot, must have missed that one.
