### ISSUE TITLE
Thold v1.4 plugin crash 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#437]
Hello Everyone 

I just experienced a THOLD plugin crash with the following 

This was right before the plugin was disabled 

2020/06/19 23:43:48 - ERROR PHP WARNING in Plugin 'thold': Use of undefined constant ST_NOTIFYRS - assumed 'ST_NOTIFYRS' (this will throw an Error in a future version of PHP) in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 2567
2020/06/19 23:36:18 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2020/06/19 23:36:18 - ERROR PHP ERROR in Plugin 'thold': Maximum execution time of 59 seconds exceeded in file: /var/www/html/cacti/plugins/thold/includes/polling.php on line: 473

This came up after I re-enabled 

2020/06/19 23:43:48 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'ST_NOTIFYRS' in 'field list'
2020/06/19 23:43:48 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[816]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2567]:CactiErrorHandler())
2020/06/19 23:43:48 - ERROR PHP WARNING in Plugin 'thold': Use of undefined constant ST_NOTIFYRS - assumed 'ST_NOTIFYRS' (this will throw an Error in a future version of PHP) in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 2567

**Comment by TheWitness** [comment]
What Cacti version.  Current CLI's are using a 300 seconds max execution time.  What' the data collection frequency too?

**Comment by bmfmancini** [comment]
Hey

Here is what I got

Cacti v1.2.12
Thold 1.4
Polling time 1 minute

**Comment by TheWitness** [comment]
Move to the develop version of thold and update cli_check.php to the 1.2.x branch.  If this is coming from the daemon, you should set the max_execution_time to -1.  If it's not, that would be a bug.

**Comment by bmfmancini** [comment]
Ok cool thanks for the suggestion

We don't use the daemon so it wouldn't be coming from there

**Comment by TheWitness** [comment]
The errors were caused due to thold being disabled.  Once you find the original source a better backtrace, open a new bug.
