### ISSUE TITLE
Cacti with thold problem

### ISSUE THREAD

**Issue by ghost** [Cacti/plugin_thold#438]
i installed a Cacti Version 1.2.13 with Thold: Version 1.4, after done the configure with alert email. there have a error appear like attached file. Anyone help?

CMDPHP MAILER ERROR Backtrace: (
/poller.php[823]:api_plugin_hook(),
/lib/plugins.php[74]:api_plugin_run_plugin_hook(),
/lib/plugins.php[177]:thold_poller_bottom(),
/plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(),
/plugins/thold/includes/polling.php[473]:thold_check_threshold(),
/plugins/thold/thold_functions.php[2217]:thold_mail(),
/plugins/thold/thold_functions.php[5402]:mailer(),
/lib/functions.php[3530]:record_mailer_error(),
/lib/functions.php[3731]:cacti_debug_backtrace()
)
2020-07-22 13:50:05 - CMDPHP MAILER ERROR:

**Comment by TheWitness** [comment]
There is not enough information here.

**Comment by TheWitness** [comment]
No feedback.
