### ISSUE TITLE
Thold 1.4 + cacti 1.2.14 - Classic Theme - Unable to Create Thresholds

### ISSUE THREAD

**Issue by superdare** [Cacti/plugin_thold#441]
Hello,

Fresh installation of cacti 1.2.14, everything works but not the thold plugin.
Graphs are created without errors, with 1min polling.

centos 7
php 7.3.21
10.4.14-MariaDB MariaDB Server
Apache/2.4.6
cacti 1.2.14
thold plugin 1.4

Short description:
Management / Thresholds / Add / selected Non Templated / selected Device / select a Graph and after this step I'm unable to select Data Source. The plugin is going me to the first step with no error, just like that. I tested also with thold-1.3.4 with no luck.

Even if I go to Graphs / select one device / "Create Thresold", directly from graph, and after I select a Data Source, let's say "load_5min" the plugin is going me to the first step again.

1:
![image](https://user-images.githubusercontent.com/35686030/90312010-ad18ba00-df09-11ea-8fa3-88886d288fde.png)

2:
![image](https://user-images.githubusercontent.com/35686030/90312038-da656800-df09-11ea-9aed-d97af19f87f5.png)

Thank you !

**Comment by superdare** [comment]
Well, if you use Classic Theme, Thold Plugin will not work...

**Comment by stevecox745** [comment]
I have the same issue with Thold here...

Centos 7
PhP 5.6
MariaDB 10.2
Apache 2.4.6
Cacti 1.2.14
Thold plugin 1.4
Thold daemon is *not* running, though I tried with it running, too
Cacti theme was Classic, also tried Paw, Dark, and Modern


Have uninstalled and reinstalled plugin multiple times.

Cannot create new Thresholds at all. 

I can try Management/Thresholds/ ADD, Non-templated, Select Device [All good to this point], Seclect a graph (any graph!) and screen reloads back to the beginning of Threshold Creation Wizard.
I can also go to Graphs, click on the Threshold create icon, takes me to Threshold Creation Wizard, but now shows a graph. When I select a Data Source (ANY data source), it reloads back to the start of the creation wizard just like above.

Log shows no errors, even in Debug mode.

2020/08/21 10:10:09 - SYSTEM THOLD STATS: Time:0.1261 Tholds:0 TotalDevices:32 DownDevices:0 NewDownDevices:0
2020/08/21 10:10:08 - SYSTEM STATS: Time:6.4167 Method:spine Processes:2 Threads:6 Hosts:32 HostsPerProcess:16 DataSources:47 RRDsProcessed:47 
![cacti-cap1](https://user-images.githubusercontent.com/70024237/90902123-fe0d3000-e399-11ea-9327-a5444a5d016b.PNG)

**Comment by stevecox745** [comment]
Tried command line...

[root@grvcacti thold]# php ./cli_thresholds.php --host-ids='2' --graph-ids='38'
Auto Creating Thresholds
No Threshold(s) Created.  Either they already exist, or no suitable matches found.

**Comment by stevecox745** [comment]
Uninstalled Thold 1.4 and installed Thold 1.3.4 as a test. Same problem, no different.

**Comment by stevecox745** [comment]
Some more information, after I tried doing this with a template.

If you first create a Threshold Template, then go to Management/Threshold, it will let you go through Type (Templated), then Template Select, then Graph Template, then Device... but the Data Query Item drop-down always has NO DATA in it, so you cannot go any further.

**Comment by stevecox745** [comment]
I may have found where it is breaking. When you select the device, it seems to work. But after you select the device and the page pops up the Graph selection box, the Device box goes back to no selection...  then once you select a graph it resets back to the default page.


![select](https://user-images.githubusercontent.com/70024237/91445057-9b0d1480-e843-11ea-9dca-77e6e4872c17.PNG)

**Comment by TheWitness** [comment]
Okay, this is fixed now.
