### ISSUE TITLE
PHP bug - Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#444]
2020/09/10 14:38:31 - ERROR PHP DEPRECATED in  Plugin 'thold': Array and string offset access syntax with curly braces is deprecated in file: /usr/local/share/cacti/plugins/thold/thold_webapi.php  **on line: 969**
2020/09/10 14:38:31 - CMDPHP PHP ERROR Backtrace:  (/plugins/thold/thold.php[37]:include_once(), /plugins/thold/thold.php[37]:CactiErrorHandler())

**Comment by TheWitness** [comment]
Thank @xmacan.  Thought we had gotten all these.
