### ISSUE TITLE
Threshold not triggering if CDEF is utilized

### ISSUE THREAD

**Issue by stevecox745** [Cacti/plugin_thold#446]
Centos 7
PhP 5.6
MariaDB 10.2
Apache 2.4.6
Cacti 1.2.14
Thold plugin 1.4

Not triggering if a CDEF is used on the graph element that is being monitored. 

For example, two devices. On one the CDEF is "Major Alarm"so that it shows on the graph. On the other, I have no CDEF defined. The one with no CDEF triggers (Door 1), but the one with a CDEF doesn't trigger any time I try it. Both are set to "0" as the baseline.

If I change the Gen_Run to remove the CDEF it will trigger.

![thold](https://user-images.githubusercontent.com/70024237/93230345-943c3800-f745-11ea-92a6-654282d94963.PNG)

**Plugin (please complete the following information):**
 - Version: 1.4  (with "thold_webapi" upgraded from bug fix #441
 - Source: Package + updated "thold_webapi"

**Comment by TheWitness** [comment]
What is the cdef?  Upload a screen shot of it.

**Comment by stevecox745** [comment]
It's two different CDEFs. One is "Multiply by 10", and the other is the "MAJOR ALARM" CDEF which is multiply by 25.

![image](https://user-images.githubusercontent.com/70024237/93349631-b85f4e00-f805-11ea-8492-2e8b1146f5f3.png)

![image](https://user-images.githubusercontent.com/70024237/93349680-c90fc400-f805-11ea-8a50-a7548b8e73ea.png)

**Comment by stevecox745** [comment]
I only use the CDEFs to bring the level up on the graph so that it is visible. For instance, the GenRun is multiplied by 25 to draw a visible line on a graph that is scaled 0 to 100. If I remove that CDEF, the GenRun will trigger a threshold alert. If I keep the CDEF, it will not.

**Comment by stevecox745** [comment]
Here is a better illustration. This has a CDEF of "Multiply by 15" attached to it...

Note how the Current Value is 15 (the door IS open, and generated a "1" which was multiplied by 15). But it is NOT triggering. I can put a "0" or a "1" or even a "14" in the Threshold entry for this device and it won't trigger.

However, if I remove all CDEFs, set the threshold to "0" and open the door, it triggers.


![image](https://user-images.githubusercontent.com/70024237/93380864-d17bf500-f82d-11ea-92c9-0594125dfdd2.png)

**Comment by TheWitness** [comment]
Okay, this is resolved, you due to a recent change by @cigamit you will have to run the following SQL and then goto the Thold tab to upgrade your database after you sync.

```sql
UPDATE plugin_config SET version='1.4' WHERE directory='thold';
```
