### ISSUE TITLE
Notification List is not saved when adding new device

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#449]
Add new device, choose Threshold Up/Down Email Notification and select any notification list. After save, everything is saved except notification list, UP/Down email notification will be disabled.
When select Global list, it is saved correctly.

Problem is only when adding new devices. Modification works fine.

Tested on 1.3.4 and 1.5, the same behavior

**Comment by xmacan** [comment]
Problem is in setup.php, function thold_api_device_save:
if (!isset($result[0]['disabled'])) {
        return $save;
}
... here is code for save notify list

Why this condition?

**Comment by TheWitness** [comment]
That's odd.
