### ISSUE TITLE
thold daemon not processing tholds

### ISSUE THREAD

**Issue by mattymrm** [Cacti/plugin_thold#45]
If thold daemon is enabled no thresholds get processed. If its not enabled then they work ok and get processed.

**Comment by pautiina** [comment]
May be you problem on #47 and #46

**Comment by cigamit** [comment]
Please check recent updates and provide a status.

**Comment by mattymrm** [comment]
yup still the same once the daemon box is ticked -

2017-02-20 10:00:29 - SYSTEM THOLD STATS: CPUTime:0 MaxRuntime:0 Tholds:0 TotalDevices:102 DownDevices:0 NewDownDevices:0 Processes: 0 completed, 0 running, 0 broken

**Comment by browniebraun** [comment]
The checkbox state itself does not initiate a restart of the daemon. (I will change that).
In the meanwhile go to the CLI and kill the daemon to ensure that it is a new instance.

**Comment by pautiina** [comment]
Update plugin and retest

**Comment by mattymrm** [comment]
the last update was 4 days ago, I installed the latest from GitHub two days ago.

**Comment by pautiina** [comment]
@mattymrm read carefully:
![17](https://cloud.githubusercontent.com/assets/11805503/23234948/7013c7ee-f95c-11e6-88af-473728c2f804.png)
If you have checkbox  you must manualy run thold_daemon.php

**Comment by mattymrm** [comment]
okay but it doesn't say that specifically. If thats the case thats probably why it doesn't work as I wasn't aware of that. Ill leave the dedicated daemon off.
