### ISSUE TITLE
Thold generate wrong bandwidth alert

### ISSUE THREAD

**Issue by georgej77** [Cacti/plugin_thold#450]
Hi,

I have upgraded Cacti version from 0.8.8b to 1.2.13. Then installed Threshold plugin version 1.5. It is using for monitoring bandwidth usage. After the upgrade, its generating wrong alert. Let me share my configuration. Please correct me if there is any change on it.

![image](https://user-images.githubusercontent.com/41739394/95325329-a9c4fd80-08be-11eb-8881-7d1b4add3836.png)

![image](https://user-images.githubusercontent.com/41739394/95325539-fa3c5b00-08be-11eb-9784-5d062db7c08e.png)

**Comment by TheWitness** [comment]
Is the source graph bits/second or bytes/second?  If bits/second, you will have to divide by 8 as thold in the 1.5.  It could also be an issue with the CDEF calculation.

Export the thold template and post to this bug report.

**Comment by TheWitness** [comment]
I see the cdef problem now.  For GUAGES it's fine, for COUNTERS, it's buggered.

**Comment by TheWitness** [comment]
Okay, figured it out.  Committing shortly.

**Comment by TheWitness** [comment]
Okay, this is resolved, you due to a recent change by @cigamit you will have to run the following SQL and then goto the Thold tab to upgrade your database after you sync.

```sql
UPDATE plugin_config SET version='1.4' WHERE directory='thold';
```

**Comment by georgej77** [comment]
Thanks. Now it seems to be working fine.
Thold version 1.5.1
