### ISSUE TITLE
Creating Threshold from Template Missing from Graph Page

### ISSUE THREAD

**Issue by chris-y** [Cacti/plugin_thold#451]
**Describe the bug**
Since upgrading Cacti from 1.1 to 1.2.10 and Thold to 1.4/latest HEAD it does not appear to be possible to create a threshold from a template.

**To Reproduce**
1. Go to the graph trees and locate a graph to create a threshold against
2. Click on "create threshold"
3. The screen only gives an option of creating a non-templated threshold.  Fiddling with the top option can force it to create a threshold template but this then tries to create graphs as well so doesn't allow to create a new threshold against an existing graph.

**Expected behavior**
The "create threshold" screen should give an option of selecting a threshold template for the current graph.

**Screenshots**
This is the screen which appears:
![image](https://user-images.githubusercontent.com/1818803/95968303-30b92f00-0e05-11eb-8bfe-b995fa755942.png)
It only allows to create a non-templated threshold.

**Plugin (please complete the following information):**
 - Version: 1.4/HEAD
 - Source: github
 - Identifer: efe24be

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chromium
 - Version: 85.0.564.68

**Additional context**
It's quite likely I'm doing something wrong!  I have not tried creating a new template, because it doesn't appear to allow that either without creating a graph along with it.

To clarify, I'm trying to create a threshold from an existing template which was created against that graph type.  I'm not (currently) trying to create a new template.

**Comment by chris-y** [comment]
"Auto-create thresholds" doesn't find anything to create either.
`Either No Templates or Threshold(s) Already Exists - No Thresholds were created.`

**Comment by TheWitness** [comment]
First, this is not the way to create a threshold from a Template, unless the graph does not exist.

![image](https://user-images.githubusercontent.com/1439914/97448311-e6f13e00-1906-11eb-8b7d-1dcb67b5fad1.png)

The right way is by highlighting the existing graphs and then create from Template as below.

![image](https://user-images.githubusercontent.com/1439914/97448529-1ef88100-1907-11eb-9fff-0c1328002ea5.png)

I'm pretty sure it's working just fine.

**Comment by chris-y** [comment]
I was clicking on the icon to the right of an already-created graph (recently changed to a spanner).  This is how I have been creating thresholds from templates for many years!
![image](https://user-images.githubusercontent.com/1818803/97457622-d4402e80-1931-11eb-9b56-9a28b8a0c271.png)

Your method is working fine and is arguably easier, thank you.

What is the purpose of the button next to the graph, as it no longer appears to do anything useful?

**Comment by TheWitness** [comment]
Well, that is a good point.  It was really designed for non-templated thresholds.  Let me give it some thought.  I'm trying to get 1.5 ready to go out the door today.

**Comment by TheWitness** [comment]
I'm going to make this an enhancement request.  I know technically it's kind of not in a sense.  When we added the ability to create from a threshold template options, we never expected this path to be taken.  But due to the other constraints, timing chief among them, I'm going to hold off on a 1.5 fix for this.

**Comment by tceydeliler** [comment]
[https://github.com/Cacti/plugin_thold/issues/451#issuecomment-717965313](url)
This is not work 1.2.15
Altough I have graph , when I select graph and create thold from template I get popup:
Sorry, we could not process your last action.
No Threshold(s) Created. Threshold(s) Template not found.

**Comment by anarkia1976** [comment]
I have the same problem here with latest plugin and latest cacti.

**Comment by TheWitness** [comment]
Create the Graph first, then you can create the Thold from the Graph interface from the Dropdown area.  I'm not going to be fixing this any time soon.  If you want it fixed, you will have to write a pull request.

**Comment by TheWitness** [comment]
This is resolved now.
