### ISSUE TITLE
missing column thold_template.show_units after fresh install

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#454]
Thold 1.5

Saving threshold template:
SQL Save on table 'thold_template': Column 'show_units' does not exist, unable to save!

"add column show_units" (maybe more columns in more tables) is in database update only, it is missing in setup_database

**Comment by cigamit** [comment]
Thanks for catching.  We might want to do another release after this :(

**Comment by TheWitness** [comment]
I can do it....
