### ISSUE TITLE
No data trigger

### ISSUE THREAD

**Issue by TomSoftly** [Cacti/plugin_thold#465]
I have trigger on Juniper MX80 power supply with current number wich it get back. But today power supply died, and no trigger works. How create trigger for no data?

**Comment by cigamit** [comment]
Moved to the thold repo, as Cacti doesn't do triggers.

Is the Power Supply a host in Cacti, and was it being reported as down by Cacti?

**Comment by zuka1337** [comment]
@cigamit is it possible to trigger graph NaN values ? Like the image bellow:

![image](https://user-images.githubusercontent.com/57998098/99110219-f6000d80-25e1-11eb-9d7f-594e5feb3c2e.png)

**ps:**  Would be nice, to find and fix graphs that is not working..

**Comment by TomSoftly** [comment]
> Like the image bellow:

It's my problem

**Comment by TomSoftly** [comment]
![trigger mx](https://user-images.githubusercontent.com/61692183/99141612-33fb4100-2677-11eb-96fe-9cf16f11ca19.jpg)
Now i have this trigger - 2 is normal, when value is high or low trigger will work. But need to trigger -nan value.

**Comment by TomSoftly** [comment]
So, nobody knows?

**Comment by cigamit** [comment]
Thold will not trigger is the host is down, as Cacti doesn't poll any data, so we have no data to check.  Instead you would want the monitor plugin, which will notify you if the host is down.

**Comment by TomSoftly** [comment]
The host itself is running. It has 2 power supplies. One of them is working, and the second is disconnected. Both had a graph of the working position. On the graph of the disconnected power supply, the graph stopped running and the nan position appeared. It is necessary for the trigger to work on this position.

**Comment by TheWitness** [comment]
A Nan should generally be treated as '0' in Thold.  You should review the 'lastread' value in the thold_data table for the thold.  Report back.

**Comment by zuka1337** [comment]
Hello @TheWitness,

I have some devices that report back 0 as real values (nothing wrong about it).
When a graph return NaN (Not a Number/empty)  this should be treated as NULL?
If so then you can implement what @TomSoftly is asking.

I think would be a good feature to trigger that specific graph

**Comment by jeanmarc0** [comment]
Hi,
I have the same problem (ping host down detection) and I found something funny, I set it today and don't know yet if it works (and don't want to crash my computer today ;-)), but it sounds good.
In _data type_, put _RPN expression_, in _RPN expression_, put _|ds:ping|,1,+_ and in _min value_, put _1_.
If the value is **NaN**, value will be **0**, for any other values between 0 and infinity (and beyond!), value will be at least **1**...
I'm sorry I don´t have the link of the site where I found this trick (and if I use _back_, I'll lost my post :-)).
Hope this helps,
JiM

**Comment by TheWitness** [comment]
Great solution.
