### ISSUE TITLE
Thold 1.5.2 got the PHP Error warning

### ISSUE THREAD

**Issue by Ching-Cloud** [Cacti/plugin_thold#472]
**Describe the bug**
Hi

We got the PHP ERROR WARNING on 1.5.2 when the thold was triggered. Also, we have no idea why the thold get the negative value. We 100% sure the value are positive value for our thold configuration.

The error messages and screenshot about this issue as below.
2020/11/18 14:40:22 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[802]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[522]:thold_check_threshold(), /plugins/thold/thold_functions.php[2047]:thold_modify_values_by_cdef(), /plugins/thold/thold_functions.php[3732]:thold_build_cdef(), /plugins/thold/thold_functions.php[4076]:thold_rpn(), /plugins/thold/thold_functions.php[4111]:CactiErrorHandler())
2020/11/18 14:40:22 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 4111
2020/11/18 14:40:22 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[802]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[522]:thold_check_threshold(), /plugins/thold/thold_functions.php[2047]:thold_modify_values_by_cdef(), /plugins/thold/thold_functions.php[3731]:thold_build_cdef(), /plugins/thold/thold_functions.php[4076]:thold_rpn(), /plugins/thold/thold_functions.php[4111]:CactiErrorHandler())
2020/11/18 14:40:22 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 4111
2020/11/18 14:40:22 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[802]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[522]:thold_check_threshold(), /plugins/thold/thold_functions.php[2047]:thold_modify_values_by_cdef(), /plugins/thold/thold_functions.php[3729]:thold_build_cdef(), /plugins/thold/thold_functions.php[4076]:thold_rpn(), /plugins/thold/thold_functions.php[4111]:CactiErrorHandler())
2020/11/18 14:40:22 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 4111
2020/11/18 14:40:22 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[802]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[522]:thold_check_threshold(), /plugins/thold/thold_functions.php[2047]:thold_modify_values_by_cdef(), /plugins/thold/thold_functions.php[3728]:thold_build_cdef(), /plugins/thold/thold_functions.php[4076]:thold_rpn(), /plugins/thold/thold_functions.php[4111]:CactiErrorHandler())
2020/11/18 14:40:22 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 4111
2020/11/18 14:40:22 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[802]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[522]:thold_check_threshold(), /plugins/thold/thold_functions.php[2047]:thold_modify_values_by_cdef(), /plugins/thold/thold_functions.php[3726]:thold_build_cdef(), /plugins/thold/thold_functions.php[4076]:thold_rpn(), /plugins/thold/thold_functions.php[4111]:CactiErrorHandler())
2020/11/18 14:40:22 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/html/cacti/plugins/thold/thold_functions.php on line: 4111
2020/11/18 14:40:22 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[802]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[522]:thold_check_threshold(), /plugins/thold/thold_functions.php[2047]:thold_modify_values_by_cdef(), /plugins/thold/thold_functions.php[3725]:thold_build_cdef(), /plugins/thold/thold_functions.php[4076]:thold_rpn(), /plugins/thold/thold_functions.php[4111]:CactiErrorHandler()) 

**Screenshots**
![messageImage_1606721270741](https://user-images.githubusercontent.com/29098681/100580900-ba737c00-3321-11eb-9e2b-020d0dbdfc24.jpg)

**To Reproduce**
1. Create a new threshold 
2. Edit the thold trigger
3. Waiting for the alarm

**Expected behavior**
Work fine without Error

**Plugin (please complete the following information):**
 - Version: thold 1.5.2
 - Source: github
 - Identifer: 

**Desktop (please complete the following information):**
 - OS: CentOS8.2
 - Cacti version: 1.2.9

**Comment by TheWitness** [comment]
Update to the latest develop branch.  There has been some work around this topic in the last few days.  Report back.

**Comment by Ching-Cloud** [comment]
Hi,

Thanks for your reply.
We did try to develop branch. This issue still exists. 

![messageImage_1606789459256](https://user-images.githubusercontent.com/29098681/100689724-fe1cc300-33bf-11eb-9b53-5c88145e9b0d.jpg)

![messageImage_1606789475998](https://user-images.githubusercontent.com/29098681/100689735-037a0d80-33c0-11eb-8566-02a4791eebdf.jpg)

**Comment by jckruger** [comment]
I had a similar issue and what I did was disable and uninstall the thold plugin and then remove the plugin folder completely. I then recopied the files making sure they are 755 Directory and 644 files. I re-enabled and re-installed and checked again. It seems that there is a table entry missing in the Cacti Settings table. I added a new entry called  thold_from_email and put in a correct email address and it started to work. Maybe that will fix it. It did for me.

**Comment by jckruger** [comment]
I found this bit in the \includes\database.php file
	```
$e = strtolower(db_fetch_cell("SELECT `value` FROM settings WHERE `name` = 'thold_from_email'"));
		if ($e == 'cacti@cactiusers.org') {
			db_execute("UPDATE settings SET `value`='Cacti@cacti.net' WHERE `name`='thold_from_email'");
```

**Comment by TheWitness** [comment]
> 
> 
> I found this bit in the \includes\database.php file
> ```
> $e = strtolower(db_fetch_cell("SELECT `value` FROM settings WHERE `name` = 'thold_from_email'"));
> if ($e == '[cacti@cactiusers.org](mailto:cacti@cactiusers.org)') {
> db_execute("UPDATE settings SET `value`='[Cacti@cacti.net](mailto:Cacti@cacti.net)' WHERE `name`='thold_from_email'");

That's some grimy old logic, once you've configured things correctly, that should never happen.  I think it was added early on as @cigamit was getting a bunch of emails of people who first installed thold and did not know what they were doing.  It's annoying after a time.

**Comment by TheWitness** [comment]
This is a duplicate ticket.  We are still tracing the issue.

**Comment by TheWitness** [comment]
Update to the latest thold_functions.php and let me know if these errors are cleared now.

**Comment by Ching-Cloud** [comment]
Hi,

Thanks for your reply.

We have updated the thold_functions.php and confirmed the logs. We didn't see some error message after updating the newer. But the thold list dashboard still shows the negative values. Did any solution to fix it?
![messageImage_1607313142456](https://user-images.githubusercontent.com/29098681/101307999-c1e7d780-3883-11eb-8d9c-548860a8f60a.jpg)

**Comment by rajkishore004** [comment]
i am getting following error.


2024-08-07 12:11:03 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2024-08-07 12:11:03 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024-08-07 12:11:03 - ERROR PHP ERROR in Plugin 'thold': Uncaught PDOException: There is no active transaction in /var/www/html/cacti/plugins/thold/includes/polling.php:253 Stack trace: #0 /var/www/html/cacti/plugins/thold/includes/polling.php(253): PDO->commit() #1 /var/www/html/cacti/lib/plugins.php(237): thold_poller_bottom() #2 /var/www/html/cacti/lib/plugins.php(95): api_plugin_run_plugin_hook() #3 /var/www/html/cacti/poller.php(862): api_plugin_hook() #4 {main} thrown in file: /var/www/html/cacti/plugins/thold/includes/polling.php on line: 253

**Comment by xmacan** [comment]
Please update to thold 1.8.1 (you have to cacti at least 1.2.25). 1.5.2 is very old.
