### ISSUE TITLE
Time Exemption per thold

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#473]
Thold has weekend exemption. It would be great the same function for user defined times.

Example - I have a lot of linux/unix servers which every night between 4 and 5 o'clock do rsync/backup/... operations.
I have thold for load and every night I get emails about high load. I would like to define exemption for this time. 

Maybe table of time exceptions definition  (every day from-to time, day of week from-time,..) and possibility to add at least one exceptions to any thold.

**Comment by TheWitness** [comment]
How about the maint plugin.  Note it's at the host level currently.

**Comment by cigamit** [comment]
Ya, that reminds me.  I want to completely remove the weekend exemption code from Thold and force usage of the Maint plugin for this.  Could probably add a per-thold scheduling to the maint plugin also.

**Comment by TheWitness** [comment]
Yea, great idea.

**Comment by xmacan** [comment]
Thank you, I didn't think to use maint.
