### ISSUE TITLE
Threshold rules

### ISSUE THREAD

**Issue by cactiuser1** [Cacti/plugin_thold#476]
Hello. Somebody   please tell me where in the cacti 1.2.15 threshold rules?  how do i write my threshold rules?  i tried to add autothold plugin but it doesn't work in this version.  How i can create rules for this version?  thanks

**Comment by TheWitness** [comment]
This topic is best taken up on the forums.  Please take it up there.

**Comment by TheWitness** [comment]
You have to install and enable the thold plugin, found basically where this bug was transferred to.  But in either case, forums where questions like this should start.
