### ISSUE TITLE
1.5.2 Does not show current value

### ISSUE THREAD

**Issue by tceydeliler** [Cacti/plugin_thold#479]
Hi,
Cacti 1.2.15 and thold 1.5.2 on Centos7.
I create 30 Mbps thold value 1Gbps interface for in and out traffic. But current value not shown.

1. Create thold template: 30000000 value and CDEF (turn bytes into bits) for high value. Time based and five minutes breach window
2. Go to datasource and select  thold templates and create tholds
3. Go to Thold tab
4. There is no "current value".Shows Zero
![2020-12-10_10-20](https://user-images.githubusercontent.com/10337838/101734468-5dba5300-3ad1-11eb-8857-f48f932b9983.png)
![2020-12-10_10-18](https://user-images.githubusercontent.com/10337838/101734265-0fa54f80-3ad1-11eb-8e67-e35a63bd8647.png)

Even database reads the last and previous value, web page shows nothing:
![2020-12-10_14-52](https://user-images.githubusercontent.com/10337838/101769071-7a698180-3af7-11eb-937b-0d5374029101.png)

**Plugin (please complete the following information):**
 - Version: 1.5.2
 - Source: github

 - OS: Centos 7
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by tceydeliler** [comment]
I check it detailly,
thold plugin only work with Interface bytes/sec graph.If Interface bits/sec graphs, thold cant  read current value as shown below
![Thold](https://user-images.githubusercontent.com/10337838/101900793-22974d00-3bc1-11eb-88f7-e17ea8075984.png)
By the way I reinstall cacti from github 1.2.16 and thold 1.5.2. But nothing change

**Comment by TheWitness** [comment]
My guess is that you are running the develop version and not the release version.  If you are running develop, update the thold_functions.php from there and report back.

**Comment by tceydeliler** [comment]
Hi,
Now Ok. I can see current values.
Thank you

**Comment by mosharaf07** [comment]
> 
> 
> Hi,
> Now Ok. I can see current values.
> Thank you

please explain how to resolve it. thanks

**Comment by TheWitness** [comment]
There has been a lot of discussion on this for the last two years.  I'm pretty sure it's resolved in Develop now and so I'm just going to close this one.  Open a new issue if you are still experiencing this issue after either updating to 2.0 or grabbing a fresh copy from Develop.
