### ISSUE TITLE
Thold and Thold Template missing <DATE> Tab in Help

### ISSUE THREAD

**Issue by AndyLeung2021** [Cacti/plugin_thold#482]
Background:
I installed cacti version with 1.1.19 and thold version with 1.03. I configured a threshold to send out threshold alert by SMTP email.
My issue:
If I configured below html config for threshold alert message, the time value will return a bunch of numbers but not normal time format like YYYY/MM/DD/H:M:S, how can make the output to normal time format?

**Configure:**
![image](https://user-images.githubusercontent.com/77342455/104339432-8ac7ae80-5532-11eb-8386-1234fde82d27.png)

**Output:**
for example:  **Time:** 1610441403

**Comment by TheWitness** [comment]
I've updated the tool tip help to add the `<DATE>` tag to reduce the confusion.  Thanks for raising this information.
