### ISSUE TITLE
Thold entry creates 8 times

### ISSUE THREAD

**Issue by tceydeliler** [Cacti/plugin_thold#483]
When I create an thold about Interface traffic, Thold management page show 8 same thold with same ID. So, when I try to delete one, all of them are  deleted.

1. Go to Data Source Management
2. Select a Interface traffic datasource
3. Scroll down to 'Create treshold from template'
4. Select template.
5. OK

**Expected behavior**
In Thold management page I should see only one thold. But there is 8 times

![thold](https://user-images.githubusercontent.com/10337838/104737783-c2fb0700-5755-11eb-81a4-11d875f0ba79.png)

DB shows only one record for every thold ID
![db](https://user-images.githubusercontent.com/10337838/104762002-b76b0880-5774-11eb-8c50-8504a8954b8f.png)

**Plugin (please complete the following information):**
 - Version: 1.5.2
 - Source: github
 - Identifer: ZIP

**Desktop (please complete the following information):**
 - OS: Any OS
 - Browser Chrome, Firefox

**Comment by TheWitness** [comment]
This is duplicate and resolved in the develop branch.
