### ISSUE TITLE
Thold daemon not working

### ISSUE THREAD

**Issue by browniebraun** [Cacti/plugin_thold#488]
**Describe the bug**
New processes for the daemon will be queued with every poller run, but removed before the daemon is able to pick related records in 'plugin_thold_daemon_processes' up.

Main reason is a bad clean-up SQL statement being executed in polling.php.

Line 201-204:
```
			db_execute_prepared('DELETE FROM plugin_thold_daemon_processes
				WHERE (end > 0 AND end <= ?)
				OR (start <= ? AND end = 0)',
				array($now, $now - 600));
```

New records are always having a start and end time of 0 per default.
The second term "start <= ?" will always match for new entries in this case and cause a removal before the daemon can process them.

Solution: Rewrite the SQL statement as follows:

```
db_execute_prepared('DELETE FROM plugin_thold_daemon_processes
				WHERE (end > 0 AND end <= ?)
				OR ( start > 0 AND start <= ? AND end = 0)',
				array($now, $now - 600));
```

**Comment by TheWitness** [comment]
@bmfmancini , can you review this one?

**Comment by TheWitness** [comment]
This table is not used in the latest source code.  I guess we can simply close this one.  Table likely needs to be dropped.
