### ISSUE TITLE
A non-numeric value encountered in thold_functions.php on line 3223

### ISSUE THREAD

**Issue by browniebraun** [Cacti/plugin_thold#489]
**Describe the bug**
Noticed an error message like shown written in the header of this issue record.

The issue is in `$thold_snmp_data['eventThresholdType'] = $thold_types[$thold['thold_type']] + 1;` of construct

```
	if (isset($thold_types[$thold['thold_type']])) {
		$thold_snmp_data['eventThresholdType'] = $thold_types[$thold['thold_type']] + 1;
	} else {
		$thold_snmp_data['eventThresholdType'] = 1;
	}
```

Reason: $thold_types contains the drop down menu records for the thold setup pages 

$thold_types[0] => 'High/Low'
$thold_types[1] => 'Baseline Deviation'
$thold_types[2] => 'Time Based'

The key will be stored within table thold_data, which needs to be increased by one. But the code statements tries to add 1 to the text description.

Solution:

Change:
`$thold_snmp_data['eventThresholdType'] = $thold_types[$thold['thold_type']] + 1;`
to:
`$thold_snmp_data['eventThresholdType'] = $thold['thold_type'] + 1;`

**Comment by TheWitness** [comment]
Why not a pull request @browniebraun ?

**Comment by TheWitness** [comment]
@browniebraun, you need to check my work here as the snmp agent stuff is your.

**Comment by TheWitness** [comment]
Checked the MIB file.  This is resolved.
