### ISSUE TITLE
THOLD ERROR: RPN Expression is invalid

### ISSUE THREAD

**Issue by Freestylerrr** [Cacti/plugin_thold#490]
I'm using a RPN Expression to calculate a Bandwidth in %. It's working fine in graph, but not in Thold. I'm getting this error. 

But the value it's actually not zero, see RRDTool below.

```
2021-02-18 13:27:36 - THOLD ERROR: RPN Expression is invalid! THold:'Huawei - OLT - ONT/OPL - Budesinskeho26&28 [oltrx]', Value:'-21.31', Expression:'CURRENT_DATA_SOURCE,100,*,ALL_DATA_SOURCES_NODUPS,/', Processed:'CURRENT_DATA_SOURCE,100,*,ALL_DATA_SOURCES_NODUPS,/'
--
2021-02-18 13:27:36 - THOLD ERROR: RPN value: v1 can not be "0" when the operator is "/". Stack:"-2131,0"
```

RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-30' \
--pango-markup  \
--title='Huawei - OLT - ONT/OPL - Budesinskeho26&28' \
--vertical-label='dBm' \
--base=1000 \
--height=200 \
--width=700 \
--tabwidth '30' \
--rigid \
--alt-autoscale \
--upper-limit='5' \
--lower-limit='-35' \
COMMENT:"From 2021-02-17 13\:42\:31 To 2021-02-18 13\:42\:01\c" \
COMMENT:"  \n" \
--color BACK#161616 \
--color CANVAS#060606 \
--color SHADEA#0B0B0B \
--color SHADEB#292929 \
--color GRID#545454 \
--color MGRID#6A6C6C \
--color FONT#FFFFFF \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#060606 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/huawei_-_olt_onttx_1134.rrd':'onttx':AVERAGE \
DEF:b='/var/www/html/cacti/rra/huawei_-_olt_onttx_1134.rrd':'oltrx':AVERAGE \
DEF:c='/var/www/html/cacti/rra/huawei_-_olt_onttx_1134.rrd':'ontrx':AVERAGE \
DEF:d='/var/www/html/cacti/rra/huawei_-_olt_onttx_1134.rrd':'onttvrx':AVERAGE \
HRULE:-35#DEB887FF:'OLT Minimum limit\: -35dBm\n' \
HRULE:-18#C3FDB8FF:'ONT CATV minimum limit\: -18dBm' \
HRULE:-30#81D8D0FF:'ONT Minimum limit\: -30dBm\n' \
LINE1:a#F51D30FF:'ONT Trasnsmit   '  \
GPRINT:a:MIN:'Min\:%8.2lf %s'  \
GPRINT:a:MAX:'Max\:%8.2lf %s'  \
GPRINT:a:LAST:'Current\:%8.2lf %s\n'  \
LINE1:b#FBB117FF:'OLT Receive     '  \
GPRINT:b:MIN:'Min\:%8.2lf %s'  \
GPRINT:b:MAX:'Max\:%8.2lf %s'  \
GPRINT:b:LAST:'Current\:%8.2lf %s\n'  \
LINE1:c#0000FFFF:'ONT Receive     '  \
GPRINT:c:MIN:'Min\:%8.2lf %s'  \
GPRINT:c:MAX:'Max\:%8.2lf %s'  \
GPRINT:c:LAST:'Current\:%8.2lf %s\n'  \
LINE1:d#59E817FF:'ONT CATV Receive'  \
GPRINT:d:MIN:'Min\:%8.2lf %s'  \
GPRINT:d:MAX:'Max\:%8.2lf %s'  \
GPRINT:d:LAST:'Current\:%8.2lf %s\n' 
RRDtool Command lengths = 1797 charaters.
RRDtool Says:
OK

**Comment by netniV** [comment]
So the RPN error is purely because you have a divide by zero problem occurring.  You should fix your expression to prevent a division by zero error (even if that's something as simple as putting an if clause around it and changing it to a 1)
