### ISSUE TITLE
Timestamp formats not working in the down message

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#491]
```
When sending down notifications the 3 timestamp formats in the "?" "tooltip" <DATE> <TIME> or <DATE_RFC822> are not provided in the notification.
```

Revision Jan 18 17:50 develop.zip

```
Subject : Error: <DATE> <TIME> <DESCRIPTION> (<HOSTNAME>) is DOWN
```
```
Message: Error : <DATE_RFC822> <DESCRIPTION> (<HOSTNAME>) is <DOWN/UP><br>Reason: <MESSAGE><br><br>Average system response: <AVG_TIME> ms<br>System availability: <AVAILABILITY><br>Total Checks Since Clear: <TOT_POLL><br>Total Failed Checks: <FAIL_POLL><br>Last Date Checked DOWN : <LAST_FAIL><br>Device Previously UP for: <DOWNTIME><br>NOTES: <NOTES><br>Device NOTES: <DNOTES>
```
any of the three formats are ignored or do not return results in the down message.

**Comment by jdcoats** [comment]
I'm sending the notices as txt. Interestingly enough the recovery message adheres to all of the html br's and formats the message breaks correctly, but the down message strips the br's / html as the help says it should but in this case the html stripped message does not print the timestamps.

**Comment by jdcoats** [comment]
Come on someone tell me why
```
Timestamp: <DATE_RFC822>
```
works in the UP message but not in the DOWN message :)

**Comment by jdcoats** [comment]
@TheWitness  @netniV .. This is an important one for anyone that wants timestamps printed in the alert messages. Timestamps still do not work in the Down message.

**Comment by jdcoats** [comment]
Notice the formatting and timestamp work in the UP message but not in the DOWN even though the same message format is used. Note the breaks do not work nor do the timestamps.
```
#DOWN MESSAGE:

Timestamp:  

System : MAINDC07.DOMAIN.TLD (1.1.1.1) is DOWN

Reason: Device did not respond to SNMP, ICMP: Ping timed out Current ping response: 0.41 ms Average system response: 0.66 ms System availability: 100 % Total Checks Since Clear: 1374756 Total Failed Checks: 64 Last Date Checked UP: 2021-09-27 16:46:22 Device Previously DOWN for: 2m


#UP MESSAGE:

Timestamp: Mon, 27 Sep 21 16:50:21 -0400 

System : MAINDC07.DOMAIN.TLD (1.1.1.1) is UP

Current ping response: 0.28 ms
Average system response: 0.66 ms
System availability: 100.00 %
Total Checks Since Clear: 1,374,759
Total Failed Checks: 64
Last Date Checked UP: 2021-09-27 16:46:22 Device Previously DOWN for: 3m 59s

Snmp Info:
Name - MAINDC07.DOMAIN.TLD
Location - Operations
Uptime - 0d 0h 2m (15796 ms)
System - Hardware: Intel64 Family 6 Model 79 Stepping 1 AT/AT COMPATIBLE - Software: Windows  Version 6.3 (Build 14393 Multiprocessor Free)

```

**Comment by netniV** [comment]
Sorry, @jdcoats, I just simply haven't had the time to setup a test and debug this yet.  I don't know if @TheWitness has had any better luck as he's just changed employment so will be training hard at hardly training. :)

**Comment by xmacan** [comment]
I'll take a look at it

**Comment by TheWitness** [comment]
Thanks @xmacan.  Should be pretty strait forward to review the `str_replace()` logic.

**Comment by xmacan** [comment]
@jdcoats - fixed. Please try actual develop version

**Comment by netniV** [comment]
For reference, this was fixed as part of PR #531 but the hash tag was left off the commit.

**Comment by jdcoats** [comment]
@xmacan Thank You!

**Comment by jdcoats** [comment]
resolved
