### ISSUE TITLE
[Feature Request] - Show acknowledgment status on Thresholds tab instead of log

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#497]
Currently, when you acknowledge a breached threshold the acknowledgement is only noted in the threshold log and not the main thresholds tab 

Current behaviour 

![thold_ack](https://user-images.githubusercontent.com/13388748/111873858-c6cf2380-8968-11eb-8afe-b2c94886993d.gif)

This can be confusing for the end-user as the legend at the bottom says the pink colour means the threshold has been acknowledged and even after you have acknowledged the alarm it still shows red with ack required no 

It would be nice to either have the alert change colour to the ack colour or a column that shows the alarm has been acked
Another thing I can see if one template needs an ack but not another upon breach and someone else acks the alarm it will show ack required no but no way to really tell if that's based on a template or if someone else ackd the alarm without looking at the log

The column could simply say ack by then the username of who acknowledge the alert

**Comment by TheWitness** [comment]
Yea, this makes sense.
