### ISSUE TITLE
Return button in Thold templates is broken

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#498]
In thold when you go to the thold templates section and click return instead of being returned to the list of the threshold templates you just end up at the same page due to content security policy

![thold_return](https://user-images.githubusercontent.com/13388748/111882473-3571a880-898c-11eb-8735-7dcb16adfa09.gif)

```
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“default-src”).
```

**Comment by ikorzha** [comment]
Fix tested, working. Please close.
