### ISSUE TITLE
Update the thold poller process to reduce the duration of the update

### ISSUE THREAD

**Issue by earendilfr** [Cacti/plugin_thold#50]
Currently, the thold plugins can degrade the performance of the poller process.
A solution is to reduce the number of UPDATE to the Database.

We can the replace the **UPDATE** in the thold_poller_output in the foreach loop by a **INSERT / ON DUPLICATE KEY UPDATE**.

You can found a patch in attachment.

[0001-Update-thold-poller-to-reduce-poller-time-to-update-.txt](https://github.com/Cacti/plugin_thold/files/789677/0001-Update-thold-poller-to-reduce-poller-time-to-update-.txt)

**Comment by cigamit** [comment]
Great idea.  We will have to give it a close look.

**Comment by cigamit** [comment]
Resolved.  Please test and comment.  Will close, but comments are still accepted.  Thanks for contributing.
