### ISSUE TITLE
Re-warning cycle when alert is reached

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#500]
We are using warnings and alerts as a two-tier system . Warning email notification is for technicians and alert is for superiors. 
The technician must solve the problem, superiors is usually supervision only. 

Problem - superiors are re-alerted always. Technicians only when alert isn't reached. 

Sometimes we have situation when conditions change quickly from normal to alert and technicians do not receive emails. 
Other situation - warning is reached and technician got one email but he waiting for next progression. Later alert is triggered and  the technician will no longer receive any emails.

Checkbox  "send warning email when alert is reached" in thold definition would solve it.

**Comment by xmacan** [comment]
I can prepare a PR, but first I want to ask if it makes sense or how to solve this differently

**Comment by TheWitness** [comment]
@xmacan, please prepare a pull request.  Thanks!

**Comment by TheWitness** [comment]
@xmacan ,Thinking on the more, we have to make a more fundamental change. So, hold off for the moment.

**Comment by xmacan** [comment]
@TheWitness  I'm waiting for your suggestions :-)

**Comment by TheWitness** [comment]
@xmacan So, I read this, as if the Notification List is difference for Warning and Alert, then notify both for all Transitions?  Can you confirm?

**Comment by TheWitness** [comment]
I'll only due this for notification lists...

**Comment by TheWitness** [comment]
Okay, this is resolved.  There is a new option under 'Notification Preferences'.
