### ISSUE TITLE
Latest source - Cacti & Thold - MAILER ERROR Backtrace

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_thold#504]
Hi, if you go to change the following parameters for device, the alert via thold / mail no longer works and the error is shown below: 

![image](https://user-images.githubusercontent.com/1744639/114690242-cd0db100-9d16-11eb-8f50-a63ba5da64d8.png)

2021-04-14 11:40:35 - CMDPHP MAILER ERROR Backtrace: (/poller.php[837]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[193]:thold_poller_bottom(), /plugins/thold/includes/polling.php[46]:thold_update_host_status(), /plugins/thold/includes/polling.php[739]:thold_mail(), /plugins/thold/thold_functions.php[5482]:mailer(), /lib/functions.php[3989]:record_mailer_error(), /lib/functions.php[4190]:cacti_debug_backtrace())
2021-04-14 11:40:35 - CMDPHP MAILER ERROR:

thanks a lot.

**Comment by xmacan** [comment]
I tried to reproduce this without success. What thold version are you using?

**Comment by netniV** [comment]
Yeah, so this is slightly behind where we are in the code now as it's from April.  If you can reproduce and provide an updated stack trace, please post one and we can re-open this.

**Comment by jcmschoot** [comment]
I updated Cacti from 1.2.16 to 1.2.19 today, I also updated all the plugins. Now I get the following error on the thold mailer:

27/01/2022 13:55:15 - CMDPHP MAILER ERROR Backtrace: (/poller.php[830]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[434]:thold_check_threshold(), /plugins/thold/thold_functions.php[2544]:thold_mail(), /plugins/thold/thold_functions.php[5487]:mailer(), /lib/functions.php[4407]:record_mailer_error(), /lib/functions.php[4608]:cacti_debug_backtrace())

27/01/2022 13:55:15 - CMDPHP MAILER ERROR:

Any clue on this error?

**Comment by bmfmancini** [comment]
What version of thold are you using?

**Comment by jcmschoot** [comment]
I am using thold 1.6, via a git pull

**Comment by jcmschoot** [comment]
It seems that saving the notification list again solved the problem.

**Comment by Nadh2413** [comment]
How did you fix that error? I use: Thold 1.0.6 on PHP Version 8.2.15

**Comment by xmacan** [comment]
I suggest update thold to 1.8 (actual develop branch). Version 1.5 and 1.6 are very old. There could be problems with new PHP versions 8.x.

I'm using thold 1.8 few months without any issues.

**Comment by Nadh2413** [comment]
![image](https://github.com/Cacti/plugin_thold/assets/117442476/b949466f-8119-4e33-9bf0-d71adc2fa9e6)
![image](https://github.com/Cacti/plugin_thold/assets/117442476/e181d4c1-3da2-4c89-a6f9-332237b6ca14)

I sent it to test but it still doesn't work

**Comment by Nadh2413** [comment]
![image](https://github.com/Cacti/plugin_thold/assets/117442476/f7c37672-498f-46bb-81d4-d7aab22677d0)

![image](https://github.com/Cacti/plugin_thold/assets/117442476/76ab3ef8-b9b6-424b-bc1c-8944ec9d1796)
