### ISSUE TITLE
When RPN expression is used, defined MAX value is multiplied by 8

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#505]
I am using the following RPN formula to calculate interface % usage: |ds:traffic_in|,|query_ifHighSpeed|,/,0.0008,*
In thold template "Alert - High" defined as 85 (which would be 85%..)

template screenshot below:
![image](https://user-images.githubusercontent.com/11211789/114756907-3c8c9c00-9d29-11eb-9494-d5381d02ad09.png)

But in thold Interface high shows as 680 when it should be 85.. 85x8=680 (thold high should not be multiplied x8).
Perhaps it is potentially easy problem to solve since both calculation and thold "max" value is being multiplied x8 when it shouldn't..

![image](https://user-images.githubusercontent.com/11211789/114757086-6b0a7700-9d29-11eb-8b21-0efbb86be3c4.png)

Please help to resolve it Cacti team

**Comment by cigamit** [comment]
Does your graph have a CDEF applied to it?

**Comment by ikorzha** [comment]
Hi Jimmy Conner, for some reason I do not see your response here, but I did get notification via email with your question ..
Does your graph have a CDEF applied to it?
YES all of my traffic interface graphs have CDEF applied to it see below:
![image](https://user-images.githubusercontent.com/11211789/114774747-7d42e000-9d3e-11eb-9188-f19fccc2fd0a.png)

And this is an end resulting graph that uses this CDEF
![image](https://user-images.githubusercontent.com/11211789/114774984-c5620280-9d3e-11eb-8370-88330d415763.png)

I have to say until recently I have used thold v1.0.6 with the same graphs and this functionality was fully functional in thold 1.0.6 and % and max value was calculating and reporting correctly

**Comment by onyy2000** [comment]
ikorzha, can you show me your graph template. 
I need to know how you can draw the traffic utilization as shown in your screenshot. 
What should I  do to create graph like yours. 
That contains utilization and traffic Errors.
Thanks

**Comment by netniV** [comment]
If I remember rightly, this comes around because of how the source data is stored which is can be bits vs bytes depending on the graph.

**Comment by TheWitness** [comment]
@xmacan, di you fix from a few months ago fix this one?
