### ISSUE TITLE
A non-numeric value encountered in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 4036

### ISSUE THREAD

**Issue by kszwaba** [Cacti/plugin_thold#507]
CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold_graph.php[56]:tholds(), /plugins/thold/thold_graph.php[563]:thold_modify_values_by_cdef(), /plugins/thold/thold_functions.php[3724]:thold_build_cdef(), /plugins/thold/thold_functions.php[4036]:CactiErrorHandler()) 

Generic Log Level: DEVEL

Problem does'n exist when all treshold are disabled.

line 4036 thold_funtions.php:
$cdef['value'] += get_current_value($local_data_id, $dsn['data_source_name']);

Cacti Version 1.2.16
Thold Version 1.5.3 / develop
PHP 7.1.33
OS: Linux PLD TH-2019

**Comment by TheWitness** [comment]
Are you still experiencing this?  Can you update to develop?

**Comment by TheWitness** [comment]
No feedback.
