### ISSUE TITLE
Different values for "waring/alert" and "normal"

### ISSUE THREAD

**Issue by holm-informatik** [Cacti/plugin_thold#508]
**Is your feature request related to a problem? Please describe.**
We have several thresholds were the measured value sometimes oscillates around the threshold value. When this happens we get A TON of "warning/alert"- and "normal"-emails. I may have missed something but I have not found a way to avoid this flood of over/under threshold e-mails.

**Describe the solution you'd like**
It would be great to be able to set one threshold for the "warning/alert" and a different one for "normal". The idea is that You get a "warning/alert" when that threshold is triggerd but don't get any more until the value has gone below the "normal" threshold, even if the values oscillates around the "warning/alert" threshold. In other words, a possibility to configure the threshold as triggerd until the value has gone below the"normal" value.

**Describe alternatives you've considered**
I may have missed something but I have not found a way to accompish this.

Regards,
Åke

**Comment by TheWitness** [comment]
I'm really confused here.  Sorry, I have not been looking at Thold for a while.  Writers block.  Can you please upload a picture or something?

**Comment by TheWitness** [comment]
I suggest maybe using one of the new baseline alerts.
