### ISSUE TITLE
Syslog option not logging "Dead Hosts Notifications or up" on Thold (1.5.2 )

### ISSUE THREAD

**Issue by onyy2000** [Cacti/plugin_thold#512]
Hello,

I've enabled "Syslogging" and "Dead Hosts Notifications or up" on Thold ( 1.5.2 ) with cacti version  1.2.16 . Only Thresholds notifications are sent to my syslog (and mail). Is there any way to notify syslog about dead (up/down) hosts with Thold? It works only with email notification. Monitor plugin does not have this option too.

Thanks

**Comment by onyy2000** [comment]
Thanks to check

**Comment by cigamit** [comment]
As I already stated in https://github.com/Cacti/cacti/issues/4286 .  Thold doesn't do dead host notifications, that process was moved to the Monitor plugin.  The Monitor plugin doesn't support logging to syslog (and really we should remove it from Thold too, as you can instead slurp everything from the Cacti log into syslog).

**Comment by onyy2000** [comment]
Thanks for your feedback, I'm using syslog option to forward alerts from cacti machine to NETCOOL dashboard it works by enabling syslog option to local5 then forwarded to syslog and it works fine with normal thold alert except Host notifications.
Anyway do you have any clue how can I slurp everything from the Cacti log into syslog or to forwarded direct to Netcool. 
Thanks again 🙂

**Comment by jdcoats** [comment]
@onyy2000 you can use the syslog plugin and create syslog alert emails for those events from the cacti log.

**Comment by TheWitness** [comment]
Closing this one.
