### ISSUE TITLE
When saving a thold template, tholds disassociated from their template are re-templated and re-enabled

### ISSUE THREAD

**Issue by kstange** [Cacti/plugin_thold#514]
If you have thresholds that are linked to a template, it is still possible to disable them manually by clicking the disable button from the thold tab, or checking them on the thresholds management page and selecting Disable. This ability to disable individual thresholds based on a template is good and useful to me.

However, if you edit a template, in addition to propagating all the other settings, the "Enabled" setting gets propagated and reactivates any disabled thresholds.

I would suggest removing the "Enabled" option from the template and making sure that it is not overwritten on the individual thresholds when it is updated.  I can't think of a good reason to have a template defined which has "Enabled" set to false as it invalidates all the other options in the template.

If there is a good use case for threshold templates being used for turning off a whole set of thresholds, then my alternate suggestion would be to implement another option in the template called "Propagate Enabled Status."  Then, if this option is disabled, it would not overwrite the Enabled value in the thresholds for any reason.

**Comment by netniV** [comment]
I can concur with this as we had this happen when I upgraded a system recently and then edited a template.  It was almost like something didn't pass the right identifier os it was applied to everything.

**Comment by TheWitness** [comment]
Getting back to this after 2 years.  Sorry about that.  Let me fix this.

**Comment by TheWitness** [comment]
Okay, all I could find is that it was improperly 're-enabling' the template.  I will change the description to this.  As of today, the current develop, the bug is otherwise not reproducible.

**Comment by TheWitness** [comment]
Okay, this is resolved....
