### ISSUE TITLE
notification list page formatting not correct

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#517]
I have to zoom out to see the add/delete/duplicate options for notification lists. You have to zoom out to at least 67% on my display. Confirmed in Chrome, Edge, & Firefox with multiple themes.

![image](https://user-images.githubusercontent.com/42470924/129390681-4371d00e-e122-413f-813f-e8d2544e59ec.png)

**Comment by cigamit** [comment]
Do you happen to have a ton of emails addresses in one of the lists that aren't wrapping?  It's hard to tell anything from your screenshot but from a quick look at mine (which I don't have to zoom on), looks like we need to remove the "nowrap" from that TD.

**Comment by jdcoats** [comment]
yes! that's it and I didn't even think about that.

**Comment by cigamit** [comment]
Might also work a bit better (after fixing the nowrap issue) if you change any long list of emails to ensure there is a space after any commas, so it can properly wrap there instead of the middle of an address.

**Comment by netniV** [comment]
Maybe that's something we can automatically insert @cigamit for our wrapping routines?

Something like:
```php
$a = explode(',', $list)
$list = implode(', ', $list);
```

See any likely problems with that @cigamit ?

**Comment by TheWitness** [comment]
That's reasonable, we there needs to be a wrap CSS on that column too.  I've done this for syslog, though it would be nice to have this as a common class in Cacti.

**Comment by TheWitness** [comment]
This is what is attached to a syslog message that can be upto 1024 bytes per the specification.

![image](https://user-images.githubusercontent.com/1439914/132351117-62a45468-1e29-4fb5-a14c-17c98cb70305.png)

**Comment by TheWitness** [comment]
Okay, things are looking good now.

**Comment by jdcoats** [comment]
works great, Thanks!
