### ISSUE TITLE
CACTI poller type don't change to spine cmd.php only

### ISSUE THREAD

**Issue by MElsaed** [Cacti/plugin_thold#519]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [1.0.6]
 - Source: [cacti in centos 8]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**
 - OS: [Linux centos8]
 - Browser [ chrome]

**Smartphone (please complete the following information):**
 - Device: [laptop]
 - OS: [10]
 - Browser [ browser 
<img width="435" alt="poller" src="https://user-images.githubusercontent.com/88613073/130421859-3c63d017-a197-422a-a699-da7264937929.PNG">
]

**Additional context**

**Comment by netniV** [comment]
This is a configuration issue.  You haven't set the path to spine.
