### ISSUE TITLE
When applying threshold from Devices Page they are not applied.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#520]
Select a device and then select apply thresholds. Generates a mactrack error in the logs for some reason.

![ApplyThresholds](https://user-images.githubusercontent.com/42470924/130625875-ac3d560a-85a8-4275-9f05-1036bc0f0ae9.png)

**Comment by jdcoats** [comment]
also produces error for monitor now after updating to 1.6 thold today
```
2021/08/30 16:55:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php[70]:form_actions(), /host.php[502]:api_plugin_hook_function(), /lib/plugins.php[130]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[237]:monitor_device_action_prepare(), /plugins/monitor/setup.php[296]:CactiErrorHandler())
2021/08/30 16:55:34 - ERROR PHP NOTICE in Plugin 'monitor': Trying to access array offset on value of type null in file: /var/www/localhost/htdocs/cacti/plugins/monitor/setup.php on line: 296
2021/08/30 16:55:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php[70]:form_actions(), /host.php[502]:api_plugin_hook_function(), /lib/plugins.php[130]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[237]:mactrack_device_action_prepare(), /plugins/mactrack/mactrack_actions.php[237]:CactiErrorHandler())
2021/08/30 16:55:34 - ERROR PHP NOTICE in Plugin 'mactrack': Trying to access array offset on value of type null in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_actions.php on line: 237
```

**Comment by bmfmancini** [comment]
1.6 is not ready yet it's in Dev lots of new code there

**Comment by jdcoats** [comment]
@bmfmancini : yeah, it does work though if you fix the database.php typo to get the columns added correctly :) I'm just following along helping with the testing.

**Comment by bmfmancini** [comment]
Ah gotcha lol didn't read all of your comments

I did a pr for the typo

Looks. Like database.php is also missing the units colum need to check that

**Comment by jdcoats** [comment]
I had show_units previously in both thold_template and thold_data so that may be a result of interim upgrades between version bumps that they didn't get added. I find that from time to time and just set the version in INFO way back, disable and enable the plugin, then change the vesion back up to current and enable plugin and apply/run the if statements again to catch up.

**Comment by bmfmancini** [comment]
Yea that's a good hack!

I am finding that a fresh Install using the new code it fails to create the
thold_data table

But if you use the older code and upgrade to the latest it works

**Comment by netniV** [comment]
A fresh install will now work.  The problem was that whilst the column was removed from the table creation code, the key that went with it wasn't.  So, the create table command failed for thold_data on the install, for an upgrade, the column is removed so no issue as that also removes the key.

**Comment by netniV** [comment]
> @bmfmancini : yeah, it does work though if you fix the database.php typo to get the columns added correctly :) I'm just following along helping with the testing.

@jdcoats which fix is that?  I'm wondering if it's already been applied.

**Comment by jdcoats** [comment]
@netniV #523

**Comment by netniV** [comment]
Ah, OK, fixed already 👍

**Comment by netniV** [comment]
So, is this an issue or just an extension of that @jdcoats ?

**Comment by jdcoats** [comment]
Yes this is an issue. I can still reproduce this.

**Comment by netniV** [comment]
If you get the latest version, try and force an upgrade again by changing the thold plugin's version in the database to 1.5.  Then provide a fresh stack trace / error log of the issue so we can work against the current code.

**Comment by jdcoats** [comment]
did this last night but done again just now to be sure. Same thing.. Somehow generates error for other plugin
```
2021/09/01 20:25:49 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php[70]:form_actions(), /host.php[502]:api_plugin_hook_function(), /lib/plugins.php[130]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[237]:mactrack_device_action_prepare(), /plugins/mactrack/mactrack_actions.php[237]:CactiErrorHandler())
2021/09/01 20:25:49 - ERROR PHP NOTICE in Plugin 'mactrack': Trying to access array offset on value of type null in file: /var/www/localhost/htdocs/cacti/plugins/mactrack/mactrack_actions.php on line: 237
```

**Comment by netniV** [comment]
```php
-       if ($save['drp_action'] == 'plugin_mactrack_device') { /* mactrack */
+       if (!empty($save['drp_action']) && $save['drp_action'] == 'plugin_mactrack_device') { /* mactrack */
```
A work around to prevent an issue on mactrack would be the above, but that highlights that whilst going through the `api_plugin_run_plugin_hook_function`, we aren't sure which hook we are applying but fortunately that can be obtained from host.php.  

The strange thing here, device_action_prepare hook is properly supplied with a $save array that does include the drop action element even if the element is empty.  So something is modifying the array before it returns.  

To verify exactly what's happening, can you try the following patch:
```diff
diff --git a/lib/plugins.php b/lib/plugins.php
index 3a8321994..f71f42cc4 100644
--- a/lib/plugins.php
+++ b/lib/plugins.php
@@ -234,7 +234,13 @@ function api_plugin_run_plugin_hook_function($hook, $plugin, $function, $ret) {
                        $ret = $function($ret);
                }
        } else {
+               if ($hook == 'device_action_prepare') {
+                       cacti_log("HOOK[$hook]: Calling $function with " . json_encode($ret));
+               }
                $ret = $function($ret);
+               if ($hook == 'device_action_prepare') {
+                       cacti_log("HOOK[$hook]: $function returned with " . json_encode($ret));
+               }
        }

        return $ret;
```

NOTE: You will want to remove the above if it spams your logs too much and definitely before next release as we wouldn't have that in there. It may be worth considering a hook debug feature similar to device/function debug to provide the above.

**Comment by TheWitness** [comment]
Sounds like a chaining event, the $save passed to the function MUST always be returned from the function as well.  All it takes is one poorly written plugin to break this chaining.

**Comment by netniV** [comment]
Agreed, so the above should highlight where it's lost.

**Comment by TheWitness** [comment]
I'll fix the related MacTrack issue, though slightly differently.  I think we should get the logging into lib/plugins.php for developers to know when they've screwed up too though.  @jdcoats has some plugin installed that is interfering with that hook, and it should be caught.

**Comment by jdcoats** [comment]
@netniV which plugins.php is this patch for? This does not work for me. The line # don't match in 1.2.x. What am I doing wrong?

**Comment by TheWitness** [comment]
@jdcoats, what plugins do you have installed?  Run this SQL command:

```sql
SELECT * FROM plugin_hooks WHERE hook='device_action_prepare';
```

For each of the "function" listed from those plugins, you have to review the function and ensure that there is a $save variable passed into the function, and that that same $save variable is ALWAYS returned at the end of the function.

Let us know what you come up with.

**Comment by TheWitness** [comment]
This manual audit would at least let us know if it's one of our plugins.

**Comment by jdcoats** [comment]
```
MariaDB [cacti]> SELECT * FROM plugin_hooks WHERE hook='device_action_prepare';
+----+----------+-----------------------+----------------------+--------------------------------+--------+
| id | name     | hook                  | file                 | function                       | status |
+----+----------+-----------------------+----------------------+--------------------------------+--------+
| 18 | thold    | device_action_prepare | setup.php            | thold_device_action_prepare    |      1 |
| 75 | mactrack | device_action_prepare | mactrack_actions.php | mactrack_device_action_prepare |      1 |
| 88 | monitor  | device_action_prepare | setup.php            | monitor_device_action_prepare  |      1 |
+----+----------+-----------------------+----------------------+--------------------------------+--------+
```
Monitor crashes often without any error at all. I re-enable it weekly. I did put it in debug mode and still no message when it goes away.

**Comment by TheWitness** [comment]
Okay, I think I found the issue in the thold plugin.  So, going to fix it now.  I added some instrumentation to the lib/plugins.php that made this easy to find.  I'll log a bug for that, and start fixing what I found.

**Comment by TheWitness** [comment]
If you are close to `develop`, you might just want to check out that branch and update.  It should correct the MACTRACK error, but it may not fix the threshold not being created bug.  Let us know.

**Comment by jdcoats** [comment]
This issue is resolved, the thresholds are created as well. Thanks!

**Comment by TheWitness** [comment]
Here is the Cacti ticket for the future warning starting with 1.2.19.

https://github.com/Cacti/cacti/issues/4390

**Comment by TheWitness** [comment]
Thanks @jdcoats.  Closing and then going out to weed the front and back yards....
