### ISSUE TITLE
Associating thresholds to notification list does not work

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#521]
When trying to assign specific tholds to a notification list, the selected items are unselected when choosing associate.

![NotificationList](https://user-images.githubusercontent.com/42470924/130626232-9f2b1d28-3e72-4c27-bfe1-9cc4fcfb6a1b.png)

![AssociateNotificationList](https://user-images.githubusercontent.com/42470924/130626254-4a0dfd25-b003-4d41-8cca-2df16e563bdf.png)

**Comment by jdcoats** [comment]
User error, I didn't have per thold notifications enabled in settings.

**Comment by netniV** [comment]
Good to see quick fixes like this 👍
