### ISSUE TITLE
Cacti-Cannot open after restart the Linux centos 8 server

### ISSUE THREAD

**Issue by MElsaed** [Cacti/plugin_thold#524]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
<img width="379" alt="CACTI-Page" src="https://user-images.githubusercontent.com/88613073/131507818-089c4169-f662-4088-8e4c-9c8deb1eacf1.PNG">

**Comment by cigamit** [comment]
Closing, as this is a configuration issue on your end.  Also as you gave us zero info and you posted this on the Thold plugin page (instead of Cacti's).  If you need help with configuring your server properly, please post in the forums, this Issue tracker is for tracker actual bugs.
