### ISSUE TITLE
When removing a threshold, thold should remove daemon data related to it

### ISSUE THREAD

**Issue by TheWitness** [Cacti/plugin_thold#527]
**Describe the bug**
The thold plugin does not remove daemon data when removing thresholds, which can lead to issues in a production system.

**Expected behavior**
Properly remove daemon data when removing thresholds.

**Comment by netniV** [comment]
You need to be careful that it's not part way through evaluating it or that may cause more issues.  Probably a rare occurrence but still.

**Comment by TheWitness** [comment]
There is still a cleanup handler that will remove these orphans, but doing it inline makes sense too.

**Comment by TheWitness** [comment]
The cleanup handler runs as a part of the main poller loop.
