### ISSUE TITLE
Allow Thold to Use the BCC in addition to the TO line for Notification Lists

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_thold#528]
## Is your feature request related to a problem? Please describe
Cacti now sends mail notifications for users in one mail per user. This generates much work for cacti and mail server.

## Describe the solution you'd like
Cacti should send one mail with all needed user mails in BCC field.

## Additional context ##
For example:
if 40 devices are down and we have in average 10 users to notify for every device there is 400 mails to send instead of 40. Many times on server there are inbound limiters - so in result we get marked as spam in result or the mails are hold in mail spam gateway by policyd service for quarantaine.

**Comment by netniV** [comment]
There is a split here between the core and the monitor/thold plugins.  One way that I've got around this with customers is simply to use a mailing group.  When it comes to customer tholds, they have their own list and I even wrong a tholdlist plugin to allow updating notification lists.

At the end of the day, there has does not need to be a TO recipient for email to be delivered, but some anti-spam software can view that as someone trying to be naughty.  This means, that for the best method, there would still need to be a TO with a bunch of BCC's as well, so using a mailing group just makes that easier.

@TheWitness and @cigamit may want to through their thoughts on this.

**Comment by interduo** [comment]
@netniV if You go problems with that - You can use TO with devnull@ or no-reply@ or simply add this source address to ignore list in spam scoring at local gateway (but not ommit limiting and not generate such amount of mails in: communication cacti<->mail gateway whitch generates most problems.

Moving administration of notification list to mail server (by managing mail list subscriptions) is not perfect solution for all because in some instances there are comercial mail servers like gmail whitch doesn't allow in easy way to do that (no mail group function).

So the perfect solution would be to generate one mail with no-replay@ in "TO:" field and all the other mails in "BCC" in header?

**Comment by netniV** [comment]
I agree, I prefer things that way myself.  And there is a disconnect between Email Admins and Cacti Admins sometimes in larger organisations.

**Comment by cigamit** [comment]
I actually prefer that everyone be in the TO on the same email (or use a mailing list).  That way I can reply to the email and have a chat with all the other people that may be alerted by it.

**Comment by interduo** [comment]
So it could be a setting depending on notification list.

**Comment by TheWitness** [comment]
Distribution lists solve this issue.

**Comment by TheWitness** [comment]
How about a minor update to the notification list to have 'To' Emails and 'BCC' Emails?

**Comment by TheWitness** [comment]
Introducing, but only for notification lists.

**Comment by interduo** [comment]
Nice, thanks. I will test that.

**Comment by TheWitness** [comment]
Develop is under heavy changes.  Test away, but avoid the Notification Queue until I get to releasing the alpha.  Knocked out 36 issues in two days.
