### ISSUE TITLE
500 Internal Server error when trying to setup

### ISSUE THREAD

**Issue by ad1k4h** [Cacti/plugin_thold#532]
2021/10/01 02:57:24 [error] 130898#130898: *166 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function thold_setup_database() in /var/www/html/cacti/plugins/Thold/setup.php:117
Stack trace:
#0 /var/www/html/cacti/lib/plugins.php(675): plugin_thold_install()
#1 /var/www/html/cacti/plugins.php(74): api_plugin_install()
#2 {main}
  thrown in /var/www/html/cacti/plugins/Thold/setup.php on line 117" while reading response header from upstream, client: 192.168.0.254, server: example.com, request: "GET /cacti/plugins.php?mode=install&id=Thold HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "192.168.0.200", referrer: "http://192.168.0.200/cacti/plugins.php"

**Comment by netniV** [comment]
Looking at the path, you have setup the plugin wrong, it should be a lowercase thold.
