### ISSUE TITLE
Dead Host Re-alert not working

### ISSUE THREAD

**Issue by tamanullah** [Cacti/plugin_thold#536]
**Describe the bug**
I have configured dead host notification in Cacti. Once host goes down, I receive notification. But after sometime I want to get a re-alert email. That seems not to be working. Below are the details of my Cacti:

Cacti Version: 1.2.16
THold: 1.5.3
Monitor: 2.5

**Comment by TheWitness** [comment]
Are you using the thold daemon?

**Comment by tamanullah** [comment]
Yes, I am using thold daemon.

**Comment by TheWitness** [comment]
Pull the latest develop and continue watching.  There was a commit today related to PHP 8.1.2 that showed you could miss some samples.  Report back.

**Comment by TheWitness** [comment]
You will likely want to restart the daemon too.

**Comment by tamanullah** [comment]
Sure, I will try and share the results

**Comment by TheWitness** [comment]
Here is the fixing commit.

https://github.com/Cacti/plugin_thold/commit/66ddecf183a84c48b6345a652e7b359e1f85799c
