### ISSUE TITLE
mesurement of traffic_out is triggered and should not be

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_thold#537]
**Describe the bug**
I have some threshold, of traffic_in and out on some interface.
And the traffic_out is giving me the status triggered, and it should not

**To Reproduce**
Create a threshold on a interface with interface traffic -> traffic out
use 50% and 75 % for warning and Alert

**Expected behavior**
Threshold should not ne triggered if it not meet the request:
name                                                              |  id     | Type            | Current   | high               | low |Trigger       |duration | Repeat|trigger | In State
switch - Traffic - PO3 channel to [traffic_out] | 4300 | High / Low | 147.18 M | 50.00 / 75.00 | - / - | 5 Minutes | N/A | Never | Yes | 2d:3h:21m |  

**Plugin (please complete the following information):**
 - Version: 1.6
 - Source: cacti.net

I'm gona say that the data manipulation is not correct!
On the traffic_in th threshold Data Manipulation as Percentage, based on traffic_out
On the traffic_out it display Exact value

Why is that different ?
and Waht is the correct value (since I didn't change before the upgrade)

**Comment by TheWitness** [comment]
Can you re-test with the latest develop?
