### ISSUE TITLE
did not send a Device Statues (Down or recovering )email

### ISSUE THREAD

**Issue by MElsaed** [Cacti/plugin_thold#538]
**Describe the bug**

**To Reproduce**
<img width="415" alt="Cact" src="https://user-images.githubusercontent.com/88613073/143228947-be3295ad-b2fd-4f7c-bab7-1302fec703a0.PNG">

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmfmancini** [comment]
What is the issue you are trying to report?

That messege would indicate you have up/down notifications off in the
device setting page this can be set as a default or per device

**Comment by TheWitness** [comment]
If you are using the thold daemon, there was a recent update in the develop branch that might fix this issue.  Please update and report back.

**Comment by TheWitness** [comment]
This should be resolved in the develop branch now.

**Comment by TheWitness** [comment]
Here is the fixing commit.

https://github.com/Cacti/plugin_thold/commit/66ddecf183a84c48b6345a652e7b359e1f85799c
