### ISSUE TITLE
Can't easily create my tholds

### ISSUE THREAD

**Issue by christh0mas** [Cacti/plugin_thold#54]
It's been a while since I've used thold so I'd like to verify that it should work the way I think it should work.  If I want to create a  threshold for drive space usage, I would go to Threshold under templates and create a new one for the "Host MIB - Hard Drive Space" data template.  After I fill in all the info, I should be able to go to my device list, check all devices and then select "Apply Thresholds" to create a threshold for any device that's using the "Host MIB - Hard Drive Space" template, right?  When I do that, nothing happens.  It just returns me to my devices list.  I'm able to go to "Thresholds" under "Management" and manually add a threshold on a single device.  That creates it fine but I'd rather not have to do that for every device.

I am running Cacti 1.0.3 with thold 1.0.1.  I installed Cacti from BSOD's Windows installer.  If I can provide any additional information, let me know.

Thanks.

**Comment by cigamit** [comment]
Please goto your Device Templates, edit your Device Template and add the Thold Templates there.  Then, save your device and your tholds will be created automatically.  Should be much nicer.  It's just that people don't know about it yet.
