### ISSUE TITLE
Can't delete orphaned Thresholds

### ISSUE THREAD

**Issue by gregnetau** [Cacti/plugin_thold#541]
Hi,

I am runinng cacti v1.2.19 and have about ten thresholds i would like to delete however the interface will not allow me to remove them.

These thresholds are associated with long since deleted data sources, and when i attempt to delete them i get a confirmation request:

"Click 'Delete' to delete the following Threshold(s).

*

"

 - however clicking continue doesn't action anything.

**Comment by TheWitness** [comment]
Moved to thold plugin area.

**Comment by TheWitness** [comment]
You need to provide more information.  First, open the browsers debug window and goto the Console in the Debug window, then try the transaction again.  See if any errors appears on the console window.  Then, second is to goto the Cacti log and look for any backtrace errors.  Post images of both.  In fact, download Screen2Git and upload an animation of the above.

**Comment by gregnetau** [comment]
Hi,

I wish i could provide more information. There is no error logged in the console of Chrome, nor in the cacti.log or cacti_stderr.log on my system with the logging set to DEVEL. I have even set the plugin to use selective debugging.

I can see normal threshold logging in the cacti.log indicating the plugin is working fine, and i get threshold notifications:

2021/12/29 19:17:08 - SYSTEM THOLD STATS: Time:0.0178 Tholds:5 TotalDevices:35 DownDevices:0 NewDownDevices:0

**Comment by TheWitness** [comment]
How about you run this query.

```sql
DELETE FROM thold_data WHERE host_id > 0 AND host_id NOT IN (SELECT id FROM host);
```

That command will blow them all away.  Cacti, assuming the thold plugin is installed and updated correctly will remove the tholds when the devices is also removed.  Your thold is a little data for sure though.  Make sure that the `host_id` column is in thold as we renamed a number of the columns some time ago.  Going to close this, but you can continue to comment.

**Comment by netniV** [comment]
Surely that should be a `NOT IN` ?

**Comment by TheWitness** [comment]
Yes, NOT IN ?
