### ISSUE TITLE
Thold uses hardcoded from adress insted of db one

### ISSUE THREAD

**Issue by Its-egner** [Cacti/plugin_thold#542]
If i changge it in file smtp is working. In file its cacti@cacti.net

**Comment by TheWitness** [comment]
I believe that only happens if the db one is empty.

**Comment by Its-egner** [comment]
There is on in the field under settings thold. So shouldnt be empty.

⁣Freundliche Grüße
Ronny Egner​

**Comment by TheWitness** [comment]
This is fixed now.
