### ISSUE TITLE
Traffic Thresholds with the same ID are duplicated in GUI

### ISSUE THREAD

**Issue by flare2707** [Cacti/plugin_thold#543]
**Describe the bug**
Traffic Thresholds are duplicated in GUI even though they have the same ID .

This issue is similar to what is also reported here:
https://issueexplorer.com/issue/Cacti/plugin_thold/483

**To Reproduce**
1. Go to 'Management'
2. Click on 'Thresholds' --> + --> Not Templated --> Select Device --> Select Graph --> traffic_in
3. Click Create --> Return
4. Entry is created but is duplicated in GUI with **same** ID

**Expected behavior**
GUI (Management --> Thresholds should only show ONE entry per ID

**Screenshots**
![image](https://user-images.githubusercontent.com/97142038/148158125-6b9bd9df-2cb1-42bd-8913-29741bc1aa8d.png)

Confirmed only 1 row for ID exists in DB:
MariaDB [cacti]> select id from thold_data;
+----+
| id |
+----+
|  9 |
+----+
1 row in set (0.00 sec)

**Plugin (please complete the following information):**
 - Version: 1.5.2 (Cacti Version 1.2.19)
 - Source: https://github.com/Cacti/plugin_thold/releases
 - Identifer: https://github.com/Cacti/plugin_thold/archive/refs/tags/v1.5.2.zip

**Desktop (please complete the following information):**
 - Cacti Server OS: 3.10.0-1160.49.1.el7.x86_64
 - Browser Chrome (Version 96.0.4664.110)

**Comment by flare2707** [comment]
Hi,

I should also mention the "duplication" in the GUI only seems to happen for Traffic, appears to be ok for Ping where only one entry is shown.

![image](https://user-images.githubusercontent.com/97142038/148167825-a8e0cf75-0400-44ca-9edc-426719b4a9ca.png)

**Comment by TheWitness** [comment]
On this one, you need to likely provide a database dump.  You can send to `developers@cacti.net`.

**Comment by kubafalta** [comment]
Hi, 

I have the same problem.
It seems it behaves in that way only for some devices.

Jakub

**Comment by TheWitness** [comment]
That's pretty weird.  Likely a join somewhere buggering it up.

**Comment by kubafalta** [comment]
Hi,

I was able to resolve it be deleting the graph (leave data source untouched), add it again and then create new threshold. Now it is there just one.

Jakub

**Comment by TheWitness** [comment]
Glad you were able to work around the problem.

**Comment by TheWitness** [comment]
I still have to fix this problem.  Thold needs some attention.  There is just too much to work on and not enough time or people to pitch in.

**Comment by Rikii16** [comment]
We have the same problem after migrating from cacti Version 0.8.8f to version 1.2.20.
We see multiple thholds with the same ID
We try to delete the graph leaving data source untouched and create a new graph and the thresholds but the issue still
![image](https://user-images.githubusercontent.com/113200412/189400469-8c7211a1-d71e-4658-bd03-c27f36d08828.png)

**Comment by TheWitness** [comment]
Can you dump your database and email to thewitness@cacti.net?

**Comment by Rikii16** [comment]
Hello, unfortunately we cannot share the database dump for security and confidentiality issues.
Actually we had to delete all the devices/graphs/tholds and create them again, this issue just happen with the old devices of the migrated database

Best,

**Comment by Ret21** [comment]
Hi guys , Im also having issues thold , after upgrading all thresholds got duplicated 60 times each one that I got more than 1 million thresholds, tried some workaround but in the end I had to delete all my host and datasources and create new ones after that some hosts were solved but there is like 20 of the new created devices that still persist with this issue.e is like 20 of the new created devices that still persist with this issue
![image](https://user-images.githubusercontent.com/54609338/191852016-5790c47e-538b-41d3-a155-2d56aa4143a8.png)

**Comment by Ret21** [comment]
Im affraid I cant share database dump due to some sensitive information from hosts, is there any other way I can help with troubleshooting?

**Comment by TheWitness** [comment]
Sorry, unless you share the dump, we can not help you.  So, I suggest you experiment with the `get_allows_thresholds()` function in the file `thold_functions.php`.  If you can figure it out, open a pull request with your fixes.  Thanks!
