### ISSUE TITLE
Thold 1.6 breaks on bandwidth utilization

### ISSUE THREAD

**Issue by c0sm1n** [Cacti/plugin_thold#549]
After upgrading the thold plugin to the latest develop branch I'm getting units appended to the Current value read by thold any time the actual bandwidth utilization exceeds 100Mbps. 
There was a similar issue reported (now closed) in the past however that was tied to the interface speed. 

The values are correctly reported while the current bandwidth utilization is under 100Mbps. Once the util (traffic_in or traffic_out) exceeds 100 Mbps, a unit gets appended to the current value and it incorrectly throws up a threshold crossing alert
I'm running cacti 1.2.19 with thold 1.6. Attaching a couple of screen shots for reference
<img width="1035" alt="Screen Shot 2022-02-10 at 9 37 52 AM" src="https://user-images.githubusercontent.com/26253207/153446001-01f20573-26d2-4cb0-87eb-352d1371ad41.png">
<img width="1319" alt="Screen Shot 2022-02-10 at 9 37 30 AM" src="https://user-images.githubusercontent.com/26253207/153446006-aead95d8-ec81-4669-afdc-fdbed959ecc8.png">
<img width="1196" alt="Screen Shot 2022-02-10 at 9 37 03 AM" src="https://user-images.githubusercontent.com/26253207/153446009-834f0d0b-bb8a-44de-a40d-830585a769a3.png">
![Screen Shot 2022-02-10 at 9 27 45 AM](https://user-images.githubusercontent.com/26253207/153446010-29f0b450-bebc-42f8-b557-c105c04b66cc.png)

**Comment by rchen14b** [comment]
It's indeed broken, I have to reverted to latest release.
