### ISSUE TITLE
installing thold makes plugin mgmt page go blank

### ISSUE THREAD

**Issue by dhcox** [Cacti/plugin_thold#55]
After moving thold into the plugin folder, the entire plugin management page goes blank, showing no plugins.

If I remove thold, everything restores to normal operation.

Are there any alternatives for thold?

Cacti version 0.8.8H on Windows 2012 Server (Standard Ed.)

Thanks,

Danny

**Comment by cigamit** [comment]
This plugin is designed for Cacti 1.0.x and above.  Do not attempt to install it on Cacti 0.8.8x
