### ISSUE TITLE
CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'

### ISSUE THREAD

**Issue by nani81** [Cacti/plugin_thold#555]
Hello,
I have:
cactus: v1.29
thold: 1.5.2
The thold info file tells me that it is compatible with  my version of cactus
But I get the following error
And the plugins are not activated on the website.
![thold](https://user-images.githubusercontent.com/51642177/170029137-00305549-ad41-4ebf-ab80-ac12a6e5b6e1.png)
![thold2](https://user-images.githubusercontent.com/51642177/170029308-17c83c32-8e2b-4995-ab5d-4d1335906983.png)
![plugins thold](https://user-images.githubusercontent.com/51642177/170029366-4e475339-4897-457c-82c9-dc9ae46ff261.png)

Thank you

**Comment by TheWitness** [comment]
Okay, this is fixed.

**Comment by nani81** [comment]
Thanks you, has worked.
