### ISSUE TITLE
SMTP connect() failed

### ISSUE THREAD

**Issue by MElsaed** [Cacti/plugin_thold#556]
I configured the mails setting and working normal send emails and all thing normal but last Saturday immediately not receive any mail from cacti  without any change any thing from configuration and get this error " SMTP connect() failed 
<img width="527" alt="Cacti-Error" src="https://user-images.githubusercontent.com/88613073/177512507-9f42274c-a3b5-4478-9c8b-1471c37c43d2.PNG">
"

**Comment by TheWitness** [comment]
This would appear to be a support issue that should be taken up in the forums.  Office may have blacklisted your IP address. But since it appears to be a connectivity issue and not a bug, the forums is the right place to get the answer.
