### ISSUE TITLE
Thold entry displayed moretimes

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#558]
In few cases I see thold displayed more times:
![thold_multiple_1](https://user-images.githubusercontent.com/26485719/196455032-c9938b86-1a28-4224-93c7-b28d467f8cd2.png)

Problem is in function get_allowed_thresholds in sql query. 

If I create users and set default policy to deny and allow only host or graphs, thold plugin will display thold moretimes because of quey:
```
SELECT 
      td.*, dtd.rrd_step, tt.name AS template_name, dtr.data_source_name AS data_source, IF(IFNULL(td.`lastread`,'')='',NULL,    
     (td.`lastread` + 0.0)) AS `flastread`, IF(IFNULL(td.`oldvalue`,'')='',NULL,(td.`oldvalue` + 0.0)) AS `foldvalue`, 
      UNIX_TIMESTAMP() - UNIX_TIMESTAMP(lastchanged) AS `instate`, **uap0.user_id AS user0, 
      uap1.user_id AS user1, uap2.user_id AS user2** 
FROM thold_data AS td INNER JOIN graph_local AS gl ON gl.id=td.local_graph_id 
LEFT JOIN graph_templates AS gt ON gt.id=gl.graph_template_id 
LEFT JOIN host AS h ON h.id=gl.host_id 
LEFT JOIN thold_template AS tt ON tt.id=td.thold_template_id
LEFT JOIN data_template_data AS dtd ON dtd.local_data_id=td.local_data_id 
LEFT JOIN data_template_rrd AS dtr ON dtr.id=td.data_template_rrd_id 
LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1) 
LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3) 
LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4) 
WHERE (td.host_id = 415) HAVING (**user0 IS NULL OR (user1 IS NULL OR user2 IS NULL**)) ORDER BY `name_cache` ASC LIMIT 0,100;
```
Add users causes that in userX columns is more than one id and row will be twice in SQL result.

cacti 1.2.23
thold 1.6

**Comment by anarkia1976** [comment]
Hi @TheWitness  , i have the same issue. unfortunately having thousands of devices this causes a performance problem on the cacti server. I remain available for any info. a thousand thanks.

**Comment by TheWitness** [comment]
That query is the old algo.  I updated it for cacti a while ago.  I'm kind of burned out ATM.  Maybe I can get some cycles on Friday.

**Comment by anarkia1976** [comment]
> Add users causes that in userX columns is more than one id and row will be twice in SQL result.

I have made a test related to this problem:
`Add users causes that in userX columns is more than one id and row will be twice in SQL result.`

for each user with restrictions present, the corresponding multiple of thresholds is created when a thresold template is applied to a device.

thanks a lot guys for support.

**Comment by xmacan** [comment]
@TheWitness after finish rrdcheck I can look on that issue, if you want spend time with another cacti issue

**Comment by TheWitness** [comment]
Go for it Petr!

**Comment by TheWitness** [comment]
Basically boils down to removing the HAVING clause and switching to a WHERE clause.

**Comment by TheWitness** [comment]
And supporting the new permission systems.

**Comment by xmacan** [comment]
@anarkia1976 - please could you test https://github.com/Cacti/plugin_thold/pull/560  ?
Thank you

**Comment by anarkia1976** [comment]
> @anarkia1976 - please could you test #560 ? Thank you

the problem is fixed. thanks a lot @xmacan for your great work.

**Comment by TheWitness** [comment]
@xmacan did you update the ChangeLog?
