### ISSUE TITLE
Incorrect url's 

### ISSUE THREAD

**Issue by obla4ko** [Cacti/plugin_thold#56]
Good day!
after upgrade cacti from 0.8 to 1.0.4 and also upgrade Monitor to 2.0 and thold to 1.0.1 have next problems

First problem
Thold  section does not show images (pic1
![pic01](https://cloud.githubusercontent.com/assets/4190324/23577729/362846e4-00d8-11e7-9f7e-110f604d7bc7.png)
)
Second Problem
Incorrect link for actions
https://myserver/plugins/thold/plugins/thold/thold_graph.php?action=log&threshold_id=5&status=-1

**Comment by cigamit** [comment]
Sounds like the URL path is not set.  This would not be a bug.
