### ISSUE TITLE
Thold shows big numbers for bandwidth percentage CDEF (or RPN)

### ISSUE THREAD

**Issue by iethankim** [Cacti/plugin_thold#562]
## Environment
> Cacti 1.2.22
> Thold develop version (@2022-12-02)

## Issue
- Thold value indicates big numbers for bandwidth percentage CDEF (or RPN) when traffic graph has rrd maximum value

## CDEF
- cdef=CURRENT_DATA_SOURCE,|query_ifHighSpeed|,/,0.0008,*

## Problem
- function thold_get_currentval of thold_functions.php returns raw rrd value for counter value

## Code
- https://github.com/Cacti/plugin_thold/blob/877d6044eeb8be9b8e557362dc7bcb433e3dba1b/thold_functions.php#L796
Above code compares $currentval which is not divided by $step to rrd_maximum value.
If there's much traffic, it could easily exceed rrd_maximum value since it's not divided by $step

Below code may prevent this behavior.
if ($thold_data['rrd_maximum'] > 0 && ($currentval / $step) > $thold_data['rrd_maximum']) {

**Comment by TheWitness** [comment]
The pull request is reasonable I think.  Can you please update the changelog.md also?

**Comment by iethankim** [comment]
Sure, please check pull request, https://github.com/Cacti/plugin_thold/pull/563
