### ISSUE TITLE
Template propagation does not update notification list. 

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_thold#564]
**Describe the bug**
Template propagation does not update notification list. 

**To Reproduce**
1. Go to Templates/Threshold
2. Click on a threshold (In my case Interface - Status)
3. Change the Notification list for the threshold.
4. Go to Management/Thresholds
5. Filter for "Interface - Status"
6. Select the thold you want to update and choose propagate template
7. The notification list does not change even though template propagation is enabled on the thold.

**Expected behavior**
Notification list should change to match template after propagation.

**Comment by netniV** [comment]
I thought your understanding of this is slightly wrong.  I believed that the threshold can have it's own notification list separate to the template.  This allows you have client-based notification list against thresholds and operation lists against the template.  Not so sure now

**Comment by jdcoats** [comment]
otherwise how would you be able to bulk update notifications for specific tholds :) It would be a nice enhancement to have the option to select a bunch of tholds and update notification but as for now the only way I see is to do it with template propagation.

**Comment by TheWitness** [comment]
I would leverage Notification Lists and their Bulk Change capabilities vs. a Templates.

**Comment by TheWitness** [comment]
There may be ambiguity there though, which I discussed with @netniV this afternoon.

**Comment by jdcoats** [comment]
Thanks for reminding me of the other way to bulk update notification list for tholds. It had slipped my mind that I could do it from the Notification List itself instead.
