### ISSUE TITLE
Manually refresh thold 

### ISSUE THREAD

**Issue by bonj1987** [Cacti/plugin_thold#565]
Cacti 1.2.22
THold 1.6
Is there any way add in a function to manually refresh a threshold, or maybe reset it's stats?
Here's why I ask... I am monitoring "SOMETHING".. doesnt matter what.. but it meets the threshold for either a warning or an alert and i get an email about it.
i look into the situation, fix the issue before the next 2 polling cycles, but I want cacti to know its fixed and send out an all clear (without waiting 2 polling cycles or 10 minutes). It would be nice to have a control on the thold mgmt screen or on the thold tab screen to refresh (re poll) that thold. Based on that refresh, it refects the current data. From what I can see, you cant set a thold less than 5 minutes, so if it sees it breached in 5 minutes, alert.. if it sees it up, it has to wait 2 cycles, or 10 minutes to tell you its up.

**Comment by TheWitness** [comment]
You can learn to use the Cacti database api, and then make those modifications in your own plugin or in a cron.
