### ISSUE TITLE
Device Notification Options: Subject editing with tags (<NOTES>) not showing

### ISSUE THREAD

**Issue by jk2808** [Cacti/plugin_thold#566]
**Describe the bug**
Hi all,
I am not sure is this a bug. I got some issues with the tags (<NOTES>) when using on Email subject. 
I try to use the tag:<NOTES> for showing the site information of the devices. However, the tag works on the Message body not for the Subject. (Please refer to the setting & the captured)

I would like to showing the Site on Email Subject. Right now I just using the NOTES tag for showing the information on Email Subject and Message.

**To Reproduce**
Use tags (<NOTES>) on Device Notification Options: Subject and Message
Setting on CACTI:
   (Adding the tag <NOTES> on the Email / Alert Subject)
Down Subject: (Editing Subject with adding the tag <NOTES>)
   Device Error: Site- <NOTES> - <DESCRIPTION> (<HOSTNAME>) is DOWN

Down Message: (Editing Message with adding the tag <NOTES>)
   System Error: Site- <NOTES> - <DESCRIPTION> (<HOSTNAME>) is <DOWN/UP><br>Reason: <MESSAGE><br><br>Average system response: <AVG_TIME> ms<br>System availability: <AVAILABILITY><br>Total Checks Since Clear: <TOT_POLL><br>Total Failed Checks: <FAIL_POLL><br>Last Date Checked DOWN : <LAST_FAIL><br>Device Previously UP for: <DOWNTIME>

**Expected behavior**
   The tag works on the Message body not for the Subject. (Please refer to the setting & the logs captured)

**Screenshots**
   The tag works on the Message body not for the Subject. (Please refer to the setting & the logs captured)

**Plugin (please complete the following information):**
 - Version: [Thold 1.6]
 - Source: [Github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**
 - OS: [WIN10]
 - Browser [firefox]
 - Version [firefox 108.0.1 (64-bit)]

**Smartphone (please complete the following information):**
N/A

**Additional context**
Captured of the setting and the logs on CACTI
![logs_CACTI](https://user-images.githubusercontent.com/92887994/210454090-befca251-c4a7-4cea-a4a5-a9a10c2a9a8e.jpg)
![setting_subject_message_CACTI](https://user-images.githubusercontent.com/92887994/210454097-885ec01b-cae8-4374-bcae-39d2404ac31d.jpg)
![Tech_Support_summary_CACTI](https://user-images.githubusercontent.com/92887994/210454752-8c4877c2-6d15-4cd1-b87c-786623141523.jpg)

**Comment by TheWitness** [comment]
Fixed.

**Comment by jk2808** [comment]
Hi TheWitness,
Does it need to cover under both Down Subject & Recovering Subject? 
(I saw you added one query on Recovering Subject)
Thanks.

**Comment by TheWitness** [comment]
Fixed that ;)

**Comment by jk2808** [comment]
> Fixed that ;)

Thanks TheWitness. 
If I got an question about customs setting on the alerts subject (I mean backend coding / tables / ...etc.). Where should I ask a question is better.
