### ISSUE TITLE
Update copyright for 2023 to file INFO break all cacti plugin 

### ISSUE THREAD

**Issue by sdcxp** [Cacti/plugin_thold#567]
issue , it affects all plugins.
I only open here to be informed about the problem.
Solution: is to delete the copyright added above [info] and the plugin will appear and can be installed

**Comment by netniV** [comment]
This should now have been corrected, thanks for bringing it to our attention.  The wrong prefix was used as in files use a semi-colon not a hash like most other configuration files these days.

**Comment by TheWitness** [comment]
Ditto.

**Comment by sdcxp** [comment]
ok , ty for quick response. have a nice year .
