### ISSUE TITLE
insert ping graph in up\down alert email

### ISSUE THREAD

**Issue by bonj1987** [Cacti/plugin_thold#568]
question.. with a thold, i can have it insert the graph for that thold, up or down..
can we do this with alerting.. i also have the ping history plugin installed and was wondering if there was a way to tie some of that together?

**Comment by bonj1987** [comment]
meaning can we have the up\down alert insert a ping graph into the alert email?

**Comment by TheWitness** [comment]
We can create a hook in thold.  Let me create it now.  You can write a simple plugin to inject HTML or test into the notification.

**Comment by TheWitness** [comment]
It's already there.  You simply need a little plugin to handle this hook and inject the correct text.

![image](https://github.com/Cacti/plugin_thold/assets/1439914/abee858b-aedd-402f-b54b-5b71e7858c66)

**Comment by TheWitness** [comment]
So, consider this fixed.
