### ISSUE TITLE
Provide enough data in environment of command to get Graph Information about Thold

### ISSUE THREAD

**Issue by gpahlevanzadeh** [Cacti/plugin_thold#569]
When I want to run external script  , i have to pass name of switch/vlanid/port  and some of another information to my script and my script send sms them to admin.
I don't know their name variable, How provide their name from where? Do you have a doc to introduce them?

**Comment by TheWitness** [comment]
It's a good feature request.

**Comment by TheWitness** [comment]
So, I added the thold_id, local_graph_id, and data_template_id to the `putenv()` part of the notification.  Should this be enough?  If you script is written in PHP, you could easily get the graph information using the Cacti database API...
