### ISSUE TITLE
Thresholds for Host MIB - Hard Drive Space corrupts the RRDtools for Windows Partions. Unix works fine though

### ISSUE THREAD

**Issue by air8orne** [Cacti/plugin_thold#57]
Hello!

I have a little Problem with the RRD Graphs and the THOLD Plugin:

I've created a Template from "Host MIB - Hard Drive Space" for Disk Space surveillance. Data Field is "hdd_used", Data Type is "Percentage" and Percent Data Source is "hdd_total". Warning and Alert Thresholds High set to 80 and 90.

If i go now to the Disk Graphs of a Unix System and create a Threshold for the "/" Disk from the Template, everything works well. When i go to the Disk Graphs of Windows System and create Threshold from the same Template, the RRD Graph gets broken: "The RRD File does not exist".

************

**Turning on the Graph Debug Mode on a Windows Systems brings the following message:**

LINE1:th0ahi#FF2400:'Alert Hi for test01.abc.loc - Used Space - C: Label:  Serial Number 5e2832c0 [hdd_used] (90.00 %)' \

LINE1:th1whi#FFF200:'Warning Hi for test01.abc.loc - Used Space - C: Label:  Serial Number 5e2832c0 [hdd_used] (80.00 %)' \

RRDTool Says:

ERROR: Unused Arguments " Label:  Serial Number 5e2832c0 [hdd_used] (90.00 %)" in command : LINE1:th0ahi#FF2400:Alert Hi for test01.jvu.loc - Used Space - C: Label:  Serial Number 5e2832c0 [hdd_used] (90.00 %)
************

**Turning on the Graph Debug Mode on a UNIX Systems brings the following message:**

LINE1:th0ahi#FF2400:'Alert Hi for unix01.abc.loc - Used Space - / [hdd_used] (90.00 %)' \

LINE1:th1whi#FFF200:'Warning Hi for unix01.abc.loc - Used Space - / [hdd_used] (80.00 %)' \

RRDTool Says:

OK
************

The RRD File of the broken RRD Graph gets refresfed every 5 Minutes and if i delete the Threshold for that Disk the RRD Graph will show up again.
The Threshold in THOLD is working fine. It collects the current Data of the Disk and sends warnings and alerts.

Versions:
- Cacti 1.0.5
- Thold 1.0.1

**Comment by cigamit** [comment]
Resolved, please test and report if this corrects the problem.

**Comment by cigamit** [comment]
I just tested the fix.  It seems wrong.  What RRDtool version are you using?

**Comment by cigamit** [comment]
Resolved, thanks!

**Comment by air8orne** [comment]
Sorry for the late answer! I just updated Cacti to 1.06 and THOLD and tested it: It works now! THX!
