### ISSUE TITLE
Wrong href after click Auto-create Thresholds

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#574]
Create -> new graphs (or management -> devices -> choose one -> Create graphs for this device 
In top right corner are links for Edit device, create new and auto-create thresholds. Edit and create are correct (https://myserver/host.php?..) After click auto-create thresholds Edit and create became wrong (https://myserver/plugins/thold/host.php?..).

Actual develop branch and 1.2.23

**Comment by TheWitness** [comment]
Duplicate of #585
