### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/plugin_thold#579]
Hi,

Here are the errors I receive sometimes:
Cacti version 1.2.23 running on CentOS 7 (waiting for version 1.2.24 to be released on CentOS repository)
PHP 8.1.18 / 
Thold plugin version 1.7

I suppose that ERROR will be corrected within 1.2.24 but here it's regarding THOLD, this makes it impossible to add new alerts on THOLD:

2023/05/02  20:39:20 - CMDPHP PHP ERROR Backtrace:   (/poller.php[825]:api_plugin_hook(),  /lib/plugins.php[83]:api_plugin_run_plugin_hook(),  /lib/plugins.php[225]:thold_poller_bottom(),  /plugins/thold/includes/polling.php[48]:thold_update_host_status(),  /plugins/thold/includes/polling.php[614]:str_replace(),  CactiErrorHandler())

2023/05/02 20:39:20 - ERROR PHP DEPRECATED in  Plugin 'thold':  str_replace(): Passing null to parameter #2 ($replace) of type  array\|string is deprecated in file:  /usr/share/cacti/plugins/thold/includes/polling.php  on line: 614

2023/05/02 20:39:20 - CMDPHP PHP ERROR Backtrace:   (/poller.php[825]:api_plugin_hook(),  /lib/plugins.php[83]:api_plugin_run_plugin_hook(),  /lib/plugins.php[225]:thold_poller_bottom(),  /plugins/thold/includes/polling.php[48]:thold_update_host_status(),  /plugins/thold/includes/polling.php[599]:str_replace(),  CactiErrorHandler())

2023/05/02 20:39:20 - ERROR PHP DEPRECATED in  Plugin 'thold':  str_replace(): Passing null to parameter #2 ($replace) of type  array\|string is deprecated in file:  /usr/share/cacti/plugins/thold/includes/polling.php  on line: 599

Thanks

**Comment by TheWitness** [comment]
Should be fixed in develop.

**Comment by jackouille-ch** [comment]
Yup, confirmed, thanks....
