### ISSUE TITLE
The return Web page is wrong after clicking the "return" button in the "edit threshold"

### ISSUE THREAD

**Issue by weiguoyan** [Cacti/plugin_thold#585]
**Describe the bug**
The return Web page is wrong after clicking the "return" button in the "edit threshold".

**To Reproduce**
1. Go to "Thold" on the top;
2. Click "edit Threshold" button of one threshold;
3. Click "return" button;
4. The wrong web gui is displayed: There is no "action" column now. It should be the page "Console -> Management -> Thresholds".

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by weiguoyan** [comment]
The screenshots:

Before clicking 'edit' button:
<img width="1131" alt="image" src="https://github.com/Cacti/plugin_thold/assets/140081132/9048ea07-47fb-4bcc-9085-cdd186e00154">

After clicking "return" button:
<img width="985" alt="image" src="https://github.com/Cacti/plugin_thold/assets/140081132/588ceaa9-4a32-4897-ae13-d274473966dc">

**Comment by TheWitness** [comment]
Hey @weiguoyan to you work with the master @ddb4github ?

**Comment by TheWitness** [comment]
Should be fixed now.
