### ISSUE TITLE
Export Threshold Template

### ISSUE THREAD

**Issue by atleticoDC** [Cacti/plugin_thold#60]
Good morning team,

we've noticed that we aren't able to export Threshold Templates, after choosing "GO" in the low-right side of the page, Cacti shows a blank page.

In attach you can find the releated screenshots.

Could you please verify?

Thanks in advance.

![export](https://cloud.githubusercontent.com/assets/26479938/24040850/42bcea8a-0b0b-11e7-9d00-3a6e1cafcdf9.JPG)
![result](https://cloud.githubusercontent.com/assets/26479938/24040854/46e56740-0b0b-11e7-83ca-b966af665a11.jpg)

**Comment by cigamit** [comment]
Confirmed.

**Comment by cigamit** [comment]
Resolved.  Sorry for the delay.
