### ISSUE TITLE
"Current" Traffic Value

### ISSUE THREAD

**Issue by atleticoDC** [Cacti/plugin_thold#62]
Dear team,

we've noticed an issue with Data Manipulation in Threshold Template creation.

Choosing "Exact value" in Data Type field, the "Current" traffic value shows in Threshold status isn't populated correctly.

E.g. The real interface traffic is 5Mb, but "Current" value shows 500Kb.

To fix this behaviour we've create an appropriate CDEF preset in order to multiply this value by 10.

In attach you can find the related screenshots.

Could you please verify?

Tks.

![error](https://cloud.githubusercontent.com/assets/26479938/24098136/497457a4-0d69-11e7-8a60-dd27e3853014.jpg)
![ok](https://cloud.githubusercontent.com/assets/26479938/24098139/4e12e384-0d69-11e7-9243-d05ccc7fe80d.jpg)

**Comment by cigamit** [comment]
This is an artifact of the scaling that goes into the new number_format function.  It is currently not aware of the base units.  So, if the base units are octets (in the case of network traffic), and you want bits, you have to multiply by 8 (not 10).  There is an option to pass in the base to number_format_i18n, but thold has not taken advantage of it yet.
