### ISSUE TITLE
Create thold from Management -> Data Sources produces a lot of php wanings

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#624]
Management -> Data Sources -> click to Template name can show a lot of php warnings.
If thold exists, everything works fine

if there isn't any thold, a lot of warnings willbe show:
Warning: Undefined array key "graph_timespan" in /usr/local/share/cacti/plugins/thold/thold.php on line 1181

Warning: Undefined array key "units_suffix" in /usr/local/share/cacti/plugins/thold/thold.php on line 1392

Warning: Undefined array key "decimals" in /usr/local/share/cacti/plugins/thold/thold.php on line 1393
Warning: Undefined array key "thold_hi" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "thold_low" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "time_hi" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "time_low" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "thold_warning_hi" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "thold_warning_low" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "time_warning_hi" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "time_warning_low" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "bl_pct_down" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Warning: Undefined array key "bl_pct_up" in /usr/local/share/cacti/plugins/thold/thold.php on line 1517

Actual develop  branch

**Comment by TheWitness** [comment]
Set your version back to an earlier version in the plugin_config table and then go to the Thold Top tab and see if things get repaired.

**Comment by TheWitness** [comment]
Okay, just confirmed this.

**Comment by xmacan** [comment]
Working well now, thank you
