### ISSUE TITLE
Enable thold doesn't work correctly

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#625]
I cannot enable some threshold. I can disable any thold without issue. Problem is enable it again. Not all, only some. 

In edit "Enabled at Threshold Level" is still enabled, cannot change 

I have to disable "Template propagation enable". Then it is possible to enable. I don't know where the information "No [template] comes from.

**Comment by xmacan** [comment]
hmm, I can't figure out where information No[Template] comes from. For windows disk and memory is used the same template. Template isn't disabled. I disabled "virtual memory" before version 1.8 but I see  No[Template] on all virtual memory thresholds. Maybe any issue with upgrade?


Workaround - disable template propagation enabled, and enable it again. Than it is possible to enable/disable thold directly in thold.php. Disable in edit via Enabled at Threshold Level is not possible

**Comment by TheWitness** [comment]
Note, you may need to save each one of your templates to fix this.

**Comment by xmacan** [comment]
Great, working well now
