### ISSUE TITLE
Threshold enabled setting issues, templated and non templated

### ISSUE THREAD

**Issue by unka65** [Cacti/plugin_thold#627]
I am not sure how threshold and template level Enabled statuses are intended to be set.  I documented this before issue #625 and fixes, but after updating I still have problems.  I use Firefox browser on Windows 10.  The plugin version is as of 10/05/2023.

From the thold.php thresholds list, after the action to disable a selected threshold, it shows disabled in the list but it still gets processed (lasttime, thold_enabled is on).  Column thold_per_enabled is empty.

When editing a templated threshold with propagation and template level enabled, the threshold level Enabled prompt allows to change (is not blocked).  However, in attempting to disable the threshold at the threshold level, the disable setting is not saved.  The three enabled table columns are not changed.  The threshold is still processed.  This seems similar to #625 but for me the fix did not resolve it.  I must be missing something.  It would seem ideal to have the option to disable a single templated threshold via the edit page.

When adding or editing a non-templated threshold, it includes the prompt "Enabled at Template Level".  Since it is not from a template, the template level enabled prompt does not seem relevant (is unexpected).  As with templated thresholds in attempting to set Enabled at Threshold Level to off, the setting does not save.  After clicking Save, it shows enabled and the table columns do not change.  The threshold is still processed.

**Comment by TheWitness** [comment]
Screen shots please.

**Comment by TheWitness** [comment]
Best thing to do is use screen2gif if you are on Windows.

**Comment by TheWitness** [comment]
I think I figured it out.

**Comment by TheWitness** [comment]
Even when disabled the lastread and lasttime will continue to update.

**Comment by unka65** [comment]
Ah, I did not think to check when the data was updated.

I refreshed the plugin but still cannot disable it.  In the threshold edit, I set the threshold level to disabled.
![image](https://github.com/Cacti/plugin_thold/assets/61275958/8b80b638-6009-4c08-84ff-74f1f1a327ef)

After saving, it shows enabled.
![image](https://github.com/Cacti/plugin_thold/assets/61275958/891e127d-be57-443d-986e-2b321c004179)

```
    thold_enabled: on
thold_per_enabled: on
 template_enabled: off
```
The same occurs for a templated threshold.  Which settings should be used to disable a threshold?

Another is currently disabled.
```
    thold_enabled: off
thold_per_enabled:
 template_enabled: off
```
However, the edit page shows the threshold level enabled.
![image](https://github.com/Cacti/plugin_thold/assets/61275958/679b478d-fa2d-4fbe-80b4-1195829f72e6)

**Comment by TheWitness** [comment]
Oh, got it, inside the form.  Give me a few.

**Comment by TheWitness** [comment]
Okay, try again.

**Comment by unka65** [comment]
I checked both templated and non templated but both still cannot be disabled via the edit page.  I will try again later.
