### ISSUE TITLE
Cacti 1.0.6 and Thshold plugin 1.0.1, problem with PHP MAIL()

### ISSUE THREAD

**Issue by Nellox1** [Cacti/plugin_thold#63]
Hi to all,
with cacti 1.0.6 and theshold plugin 1.0.1 no email alert notification is sent.

I tried with Sendmail and PHPMail but no request arrives to sendmail's mail.log.

Another problem is that when I try to change the Alert  value   High Threshold I am not able to set the new value.

Is there a new plugin compatible with cacti 1.0.6?

Thank you
Ste Nellox

**Comment by cigamit** [comment]
The sendmail issue is more than likely an issue on your side.  It works fine.  Relative to the second issue, you should check your Cacti log file for errors if you are unable to support or provide screen shot's of the errors you are receiving.  If either of these issues were real, there would be lot's of people complaining.
