### ISSUE TITLE
Upgrade from 1.5.3 traffic high values requires change from bytes to bits

### ISSUE THREAD

**Issue by unka65** [Cacti/plugin_thold#630]
I remember mention in the past about the traffic threshold values with a traffic graph of bits but the query data is bytes.  I do not know what should be used for such.  I just try until something works.  I wanted to mention this in case it is determined that this might also affect others and in case it would help others by adding a "breaking change" (term used in a different project/repository) or similar note in the change log/release notes.  It would be great if the upgrade could auto convert such but probably is not feasible.

Previously with 1.5.3 for thresholds on traffic graphs that are bits per second, the threshold high value was set as bytes (desired value divided by 8) and the data type was Exact Value to show as expected on the bits per second graph and to notify accordingly.  After upgrading to the latest, the threshold lines on the traffic graph where much lower (/8) than intended but the notifications did not occur at those unexpected low values (probably did not have an event at the expected value).  To get the threshold lines on the graph where expected, I changed the type from Exact Value to Use CDEF, bytes to bits, and set the high value as bits (previous value multiplied by 8), matching the graph units (a nice improvement, thank you!).

**Comment by TheWitness** [comment]
You might, in a test environment, update to the 1.8 `beta`.  I believe that this issue has been resolved for some time now and provide feedback.  There is one outstanding bug relative to HRULES for Data Sources that use a CDEF and Percentage Thresholds though.  Similar, yet different.

Here is the other issue: https://github.com/Cacti/plugin_thold/issues/580

There are very large change in 1.8 `beta`.  Was supposed to be `2.0`, but I'm having some issues finishing it up.

**Comment by unka65** [comment]
Thank you for responding.  I noted it with the develop version from around September 2023 (I did not think to mention it as I have been working with it for some pull requests).  I confirmed that the notification still works with type Exact Value and byte values and so no concern about function.  Only the values in the list and the graph changed.  Since it is already noted, I will close this one.
