### ISSUE TITLE
Thold_template warning info show from page

### ISSUE THREAD

**Issue by JazzChueh** [Cacti/plugin_thold#632]
# Describe the bug

I'm want from Template "Threshold" add some object, and get warning on the template's page, log get some error info..

## To Reproduce

1. Go to 'Console'

2. Click on 'Templates' > 'Threshold' and add any templates

3. See error code from the page and log get more error info, 'Operator Notessend' function are not work, but alert function is normal.

## Expected behavior

how can i fix the error?and funtion normal to work?

## Screenshots

![image](https://github.com/Cacti/cacti/assets/100668082/dd25250d-793b-4057-acbd-9b35f588157f)
![image](https://github.com/Cacti/cacti/assets/100668082/6f029b0b-69f9-4d44-abed-cf86319e35bb)

## Desktop (please complete the following information)

- OS: [Win-Server 2022]

- Browser [Chrome]

- Version [Cacti:1.2.25 / Thold:1.5.2 and 1.8 same problem]

**Comment by TheWitness** [comment]
Okay, I confirmed this.  It's due to you continuing to use Legacy Nofications.  I'll be fixing shortly.  Thanks for reporting!
