### ISSUE TITLE
QA: Problem with non-templated tholds

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#635]
Thold 1.8 - it seems that non-templated tholds doesn't work. These tholds should be restored:
![thold_tri2](https://github.com/Cacti/plugin_thold/assets/26485719/01344624-0b86-4ce2-ba95-761bddface16)

From normal -> triggered-> breached is the same problem:
![thold2](https://github.com/Cacti/plugin_thold/assets/26485719/248bec41-adf4-4bc0-a638-e11ff162f30a)

Templated  tholds works fine.

**Comment by xmacan** [comment]
without thold daemon

**Comment by TheWitness** [comment]
Can you describe the problem?

**Comment by TheWitness** [comment]
I did not see your sentence about the non-templated not clearing their state.  Any errors in the log?

**Comment by TheWitness** [comment]
You will have to re-upgrade your database.  I've added another column to the notification_queue table and ran a sql query to fix the non-templated tholds.

**Comment by xmacan** [comment]
Still not working

**Comment by xmacan** [comment]
It seems that problem is in include/polling.php in thold_check_all_thresholds() function. My problematic thold:

select thold_enabled, thold_per_enabled, template_enabled,tcheck, thold_template_id from thold_data where id=11886;
+---------------+-------------------+------------------+--------+-------------------+-----------------------+
| thold_enabled | thold_per_enabled | template_enabled | tcheck | thold_template_id |
+---------------+-------------------+------------------+--------+-------------------+-----------------------+
| on                   | on                           | off                          |        0   |                     2      |
+---------------+-------------------+------------------+--------+-------------------+-----------------------+

ID 11886 will never been processed because SQL condition for tholds is:
WHERE td.thold_enabled = 'on'
AND td.thold_per_enabled = 'on'
AND ((thold_template_id > 0 AND **td.template_enabled = 'on'**) OR thold_template_id = 0)
AND td.tcheck = 1
AND h.status = 3

My non-templated thold are created from templated, only disable Template Propagation Enabled and change hi/lo values.

I don't know how right sql for non-templated thold looks like. @TheWitness Could you help me?

**Comment by xmacan** [comment]
works great.
