### ISSUE TITLE
Request:  High/Low Threshold allow for decimal value?

### ISSUE THREAD

**Issue by SilverSquirrl** [Cacti/plugin_thold#64]
Currently the High/Low Threshold doesn't allow for a decimal number.   I use a custom CDEF to provide a % in which I compare the high/low value for.   In the past I used a decimal down to the .01 place to compare and alert against.

Here is the Error when trying to use .05:  (same if I use 95.5)

```
Validation error for variable thold_warning_low, with value of ".05". See backtrace below for more details.
(/plugins/thold/thold_templates.php: 60 template_save_edit)(/plugins/thold/thold_templates.php: 385 get_filter_request_var)(/lib/html_utility.php: 430 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)
```

Currently I am able to bypass the validation by editing the value in the database directly and the alerts trigger normally.   Is it possible to allow a decimal by default? or atleast provide an warning/override option to use a decimal value?   It worked just fine for me in a really old version (I forget what version I was using), I just jumped to 1.0.1 with the new cacti build and now it blocks it.

Thank you,

**Comment by cigamit** [comment]
Yea, that sounds like a bug in the validation logic.  Thanks for reporting.

**Comment by cigamit** [comment]
Resolved, thanks again.
