### ISSUE TITLE
creating thold threshold fails and seem to open in a target of itself.

### ISSUE THREAD

**Issue by dallenk** [Cacti/plugin_thold#641]
# Describe the bug
[ 1.3.0 - Dev 404dfd58 @ 2023-11-17 15:27 ]
When creating a new thold template, the page redirects to itself in what looks like a target iframe.  The template is created tho.

## To Reproduce

1. Go to 'Console/Templates/Threshold'
2. Create new template
3. See error

## Expected behavior

threshold created, and returns to /plugins/thold/thold_templates.php
## Screenshots

![image](https://github.com/Cacti/cacti/assets/2725066/7ffed9a4-c3dc-46c9-a924-2fa2d97272a2)

**Comment by dallenk** [comment]
Sorry, this is likely a thold plugin issue, but I can't move it myself.

**Comment by TheWitness** [comment]
I'm pretty sure this was fixed in the last week.  I can not currently reproduce.

**Comment by dallenk** [comment]
i just reproduced this with a fresh installation, the last one (https://github.com/Cacti/plugin_thold/issues/638)  was deleting or disabling the threshold, this happens when creating a new one.
screen record after fresh install with most current git pulls of cacti and thold
https://watch.screencastify.com/v/Ag0lsez1bhZQfde4GxXN

and after enabling the plugin (forgot that on the first record)
https://watch.screencastify.com/v/E3ZqydgosIVmUaMKoWMD

**Comment by TheWitness** [comment]
Can you do it as a screen2gif?

**Comment by TheWitness** [comment]
Okay, I must have missed a commit somewhere.

**Comment by TheWitness** [comment]
It was a Thold Template.  Fixing now.

**Comment by dallenk** [comment]
works great now!   the amount of work you put into this is nothing short of amazing.  Thank you.

and apologies for posting so many things lol
