### ISSUE TITLE
All thresholds selected by default when viewing threshold management

### ISSUE THREAD

**Issue by dallenk** [Cacti/plugin_thold#644]
**Describe the bug**
viewing "threshold management"  All thresholds are selected by default.  I think nothing should be selected by default?

**Comment by TheWitness** [comment]
Can you upload a screen shot.  I'm a little confused here.

**Comment by TheWitness** [comment]
No feedback.

**Comment by dallenk** [comment]
Sorry @TheWitness , this issue still does show for me.
I've created many thresholds for a device, navigating to "Managment / Thresholds"  All threshholds are selected by default, but the header checkbox is not.
![image](https://github.com/Cacti/plugin_thold/assets/2725066/3a9aa59a-3d12-487a-8878-69e7cba326c8)

**Comment by TheWitness** [comment]
@sgvfr, can you upload a screen2gif of how your do the navigation?  Also, list out the other plugins that you have installed.

**Comment by dallenk** [comment]
No problem, I'll get that for you today

**Comment by dallenk** [comment]
![Animation](https://github.com/Cacti/plugin_thold/assets/2725066/2b7a911c-e548-4a15-a51c-8d399f269062)

**Comment by TheWitness** [comment]
What's that snver plugin?

**Comment by dallenk** [comment]
It's for tracking serial numbers of devices..  doesn't work all that well so goingbto remove it.

**Comment by TheWitness** [comment]
It could be quicktree or that plugin.  Play around disabling them, clear you cache, or use incognito.
