### ISSUE TITLE
thold_functions.php calls get_timespan() from lib/time.php, but it is not included

### ISSUE THREAD

**Issue by eriksejr** [Cacti/plugin_thold#649]
The thold_daemon seems to be crashing out constantly trying to send notifications. The logged error is below:

```
2023/12/12 08:59:05 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2023/12/12 08:59:05 - ERROR PHP ERROR in  Plugin 'thold': Uncaught  Error: Call to undefined function get_timespan() in  /usr/local/share/cacti/plugins/thold/thold_functions.php:6252 Stack  trace: #0  /usr/local/share/cacti/plugins/thold/thold_functions.php(2280):  thold_mail() #1  /usr/local/share/cacti/plugins/thold/thold_process.php(233):  thold_check_threshold() #2 {main} thrown in file:  /usr/local/share/cacti/plugins/thold/thold_functions.php on line: 6252
```

Some quick research discovered that this is not a built-in php function, rather it is in lib/time.php, but that is not included in thold_functions.php and it appears it needs to be so I added an include for that to thold_functions.php:

```
chdir('../../');
include_once($config['base_path'] . '/lib/time.php');
```

and that appears to have sorted it out.

**Comment by TheWitness** [comment]
Pull request?

**Comment by eriksejr** [comment]
No problem, I just can't get to it today. I am still having quite a bit of trouble with the thold plugin, daemon or no daemon but the other issues remain unsolved at the moment.

**Comment by eriksejr** [comment]
Here is my copy of thold_functions.php as requested (renamed with a .txt extension so github would take it). The include in question is commented out on the top. I think it's just a few commits back from the one on here...

[thold_functions.txt](https://github.com/Cacti/plugin_thold/files/14089547/thold_functions.txt)

**Comment by TheWitness** [comment]
Okay, going to close, but please still upload.
