### ISSUE TITLE
ERROR PHP WARNING in plugin 'thold'

### ISSUE THREAD

**Issue by svenbosmans** [Cacti/plugin_thold#662]
Hello

These error logs are reported in the cacti log

<html>
<body>

2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2545]:get_email_subject(), /plugins/thold/thold_functions.php[3496]:CactiErrorHandler())
--
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "decimals" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 3496
2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2545]:get_email_subject(), /plugins/thold/thold_functions.php[3496]:CactiErrorHandler())
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "decimals" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 3496
2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2545]:get_email_subject(), /plugins/thold/thold_functions.php[3495]:CactiErrorHandler())
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "units_suffix" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 3495
2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2545]:get_email_subject(), /plugins/thold/thold_functions.php[3494]:CactiErrorHandler())
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "show_units" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 3494
2024/02/19 10:54:43 - THOLD: Threshold HI / Low check is normal HI:80 LOW: VALUE:0
2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2195]:CactiErrorHandler())
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "decimals" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 2195
2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2195]:CactiErrorHandler())
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "decimals" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 2195
2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2194]:CactiErrorHandler())
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "units_suffix" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 2194
2024/02/19 10:54:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/poller_thold.php[99]:perform_thold_processes(), /plugins/thold/poller_thold.php[154]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[332]:thold_check_threshold(), /plugins/thold/thold_functions.php[2193]:CactiErrorHandler())
2024/02/19 10:54:43 - ERROR PHP WARNING in Plugin 'thold': Undefined array key "show_units" in file: /usr/share/cacti/plugins/thold/thold_functions.php on line: 2193

</body>
</html>

Cacti version 1.2.25
Thold: latest deployment version
PHP version: 8.2.16
OS: Alma linux

I have no idea where these errors are comming from

**Comment by xmacan** [comment]
have you column decimals in thold_template and thold_data tables?

**Comment by svenbosmans** [comment]
> have you column decimals in thold_template and thold_data tables?

these colums where missing.
I thought that the upgrade script should create these? or am I wrong?

**Comment by xmacan** [comment]
Did you disable and enable thold in configuration->plugins? after replacing files?

**Comment by svenbosmans** [comment]
> Did you disable and enable thold in configuration->plugins? after replacing files?

No I didn't ...
also didn't know that it was needed.

Is there some manual for the install/upgrade procedure

**Comment by xmacan** [comment]
or maybe you upgraded from older 1.8 (develop branch) again? 
Try:
update  plugin_config set version=1.7 where directory='thold';
then disable and enable thold plugin again. Your db will be updatet

**Comment by xmacan** [comment]
> > Did you disable and enable thold in configuration->plugins? after replacing files?
> 
> No I didn't ... also didn't know that it was needed.
> 
> Is there some manual for the install/upgrade procedure

For all plugins:
1) disable plugin
2) replace files
3) enable plugin

**Comment by svenbosmans** [comment]
> > > Did you disable and enable thold in configuration->plugins? after replacing files?
> > 
> > 
> > No I didn't ... also didn't know that it was needed.
> > Is there some manual for the install/upgrade procedure
> 
> For all plugins:
> 
> 1. disable plugin
> 2. replace files
> 3. enable plugin

OK Top thanks for this information!

Case Closed!

**Comment by TheWitness** [comment]
Maybe we should do a column check as this could happen for a brief time during upgrades.

**Comment by xmacan** [comment]
... and add info howto upgrade thold correctly :-)

**Comment by TheWitness** [comment]
Yea, thold upgrade comes from the stone-age where you have to go to a specific page to upgrade.
