### ISSUE TITLE
Inconsistent counts in thold tab and management -> thresholds

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#664]
1) Go to thold tab and set filter to triggered or breached 
2) go to management -> thresholds and set filter to triggered or breached

Thold_graph.php adds to SQL condition h.status = 3. If you have any disabled device, you can view here different counts.  

From my perspective - number of triggered/breached shlould be equal. So I suggest add status = 3 to thold.php

thold 1.8

@TheWitness What do you think? It is small fix, I can prepare it.

**Comment by TheWitness** [comment]
Please, also add a new drop-down 'Triggered or Breached'.  Thanks!

**Comment by TheWitness** [comment]
Okay fixed now!
