### ISSUE TITLE
Incorrect "raise message" behavior when thold save fails

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#667]
When user try save incorrect threshold (set low and high thold the same value), after save blank page is displayed. 
Only after click to any page user get message: 
Sorry, we could not process your last action.

Impossible thresholds: 'High Threshold' smaller than or equal to 'Low Threshold'
RECORD NOT UPDATED!

Actual develop branch

**Comment by TheWitness** [comment]
I have just done two new features to handle this more precisely.  Please test.  Also, look for JavaScript errors if you still receive failures.

**Comment by xmacan** [comment]
fixed, works fine now
