### ISSUE TITLE
Email notification should contain about duration in normal/triggered state

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_thold#668]
Alert, warning and restoral emails contains a lot of variables:

A Threshold has returned to normal status. <br><br><strong>Device</strong>: <DESCRIPTION> (<HOSTNAME>)<br><strong>URL</strong>: <URL><br><strong>Message</strong>: <SUBJECT><br><br><GRAPH>

I would like to have there information like:
Breached state duration : 2 hours
or 
Normal state duration: 1 years and 5 weeks....

**Comment by TheWitness** [comment]
I'm assuming we should be getting this data fresh instead of from the `host` table too:

![image](https://github.com/user-attachments/assets/c8134aea-7bf1-45c0-b9ae-25207f95bdd6)

I think that there is a bug for that somewhere either monitor or thold.

**Comment by xmacan** [comment]
@TheWitness agree!

**Comment by xmacan** [comment]
I've revised it and we can close it. All these snmp variables are already there:
<UPTIME>
<SNMP_HOSTNAME>
<SNMP_LOCATION>
<SNMP_CONTACT>
<SNMP_SYSTEM>
