### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by simonwibberley** [Cacti/plugin_thold#67]
Hi there,

I'm running cacti version 1.0.4 since that's what my package manager provides (centos 6.8). I understand the bleeding edge thold is not compatible with that version. I had to infer which commit might be by release date.

Would it be possible to tag commits with version numbers that correspond to compatibility?

Thanks!

**Comment by MorningxGlory95** [comment]
It doesn't work for 0.8.8h either.

**Comment by cigamit** [comment]
Nothing in the Cacti GitHub repo works with anything less than version 1.1.1 at the moment.  This will not change.  Before you move to 1.x.x, you should aways test.
