### ISSUE TITLE
Update settings.php missing 'description' key for 'thold_notification_delay' field

### ISSUE THREAD

**Issue by MSS970** [Cacti/plugin_thold#682]
CACTI [1.3.0 Dev]

Update settings.php missing 'description' key for 'thold_notification_delay' field

**Comment by MSS970** [comment]
Solution:
add description key:


		'thold_notification_delay' => array(
			'friendly_name' => __('Device Notification Delay Options', 'thold'),
			'description' => __('Device Notification Delay Options', 'thold'),
 			'method' => 'hidden',
			//'method' => 'spacer',
		),

**Comment by TheWitness** [comment]
Good catch!
