### ISSUE TITLE
Cannot creeate THOLD template with Baseline thresholds enabled

### ISSUE THREAD

**Issue by coolerl** [Cacti/plugin_thold#684]
Whenever I try to creeate a new template or change an existing template from High/Low to Baseline Deviation, I get the error "Action Failed. Sorry, we could not process your last action. With baseline thresholds enabled."

**To Reproduce**
1. Go to Templates
2. Click on Threshold
3. Click on + to creeate a new template 
4. Select Baseline Deviation 
5. Click Save

**Expected behavior**
Template be saved correctly and act according to specified settings.

**Screenshots**
![image](https://github.com/Cacti/plugin_thold/assets/18700988/1b6435f3-89a6-448c-9b26-4e219284a52f)

**Plugin (please complete the following information):**
 - Version: [1.8.1]
 - Source: [github]
 - Identifier: [(https://github.com/Cacti/plugin_thold/)]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Version 122.0.6261.69 (Official Build) (64-bit)]

**Additional context**
Cacti Version 1.2.27 
running on CentOS Linux release 7.9.2009 (Core)

PHP 7.0.32 (cli) (built: Sep 13 2018 16:50:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.0, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.0.32, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

**Comment by dieselsnowmobile** [comment]
Bump - I'm having a similar issue.

**Comment by bmfmancini** [comment]
Are there any errors in the cacti log?

**Comment by nevillecodes** [comment]
Bump - I too am having a similar issue.  There are no errors in the Cacti log.

**Comment by nevillecodes** [comment]
The issue is on line 5878 in ```thold_functions.php```:

```
5871         } elseif ($save['thold_type'] == 1) {
5872                 /**
5873                  * Baseline Deviation Checks
5874                  *
5875                  * The initial template creation is always hi/low.  So, we
5876                  * do not require an isset in this section.
5877                  */
5878                 $banner .= ($banner != '' ? '<br>':'') . __('With baseline thresholds enabled.', 'thold');
5879
5880                 if (empty($save['bl_ref_time_range']) || $save['bl_ref_time_range'] <= 0) {
5881                         $banner .= ($banner != '' ? '<br>':'') . __('Time reference in the past must be set to positive integer value!', 'thold');
5882
5883                         $_SESSION['sess_error_fields']['bl_ref_time_range'] = 'bl_ref_time_range';
5884                 }
5885
5886                 if (empty($save['bl_pct_down']) && empty($save['bl_pct_up'])) {
5887                         $banner .= ($banner != '' ? '<br>':'') . __('You must specify either \'Baseline Deviation UP\' or \'Baseline Deviation DOWN\' or both!', 'thold');
5888
5889                         $_SESSION['sess_error_fields']['bl_pct_up']   = 'bl_pct_up';
5890                         $_SESSION['sess_error_fields']['bl_pct_down'] = 'bl_pct_down';
5891                 }
```
```$banner``` is being populated regardless of whether an error is detected or not.  The subsequent code on lines 5965-5969 raises an error if ```$banner``` is not empty.

Comment out/remove line 5878 to fix the issue.
