### ISSUE TITLE
Is it possible (would be nice) to compare current reading with historical data?

### ISSUE THREAD

**Issue by redguy666** [Cacti/plugin_thold#69]
Consider web server usage pattern: it is time based, has peak in the middle of the day, and lower readings on weekends. Baseline tries to compare it to some flat average (with weekend exemptions possibly). It woyuld be better to compare it day-to-day on a week basis (like if we have monday, compare current readings with similar time range from previous monday, on tuesday - compare with tuesday week ago, etc. Weekends also can be treated same way). If current readings are higher/lower than those from weeke ago by specified factor - raise alert.

You could compare averages on time period from midnight to current time with same period on a day week ago, last hour with same hour on day week ago, custom range, etc...

**Comment by cigamit** [comment]
This could get overly complicated in a real hurry.  I don't believe we will see this in the current version of the plugin, but I will add it to the list of possibilities for the complete rewrite that is planned in the future.

**Comment by TheWitness** [comment]
@redguy666, this can be done if you are still interested.  It's fairly strait forward, but maybe not exceptionally scalable.  Chime in if you are.

**Comment by TheWitness** [comment]
I marked this resolved as the new baseline features do just that, but not exactly as you articulated.  If you want it, or are even still using cacti, we can entertain it.
