### ISSUE TITLE
Thold 1.8.1没有找到可以设置邮件列表的地方

### ISSUE THREAD

**Issue by chengjiangghr** [Cacti/plugin_thold#692]
**Describe the bug**
我将cacti部署到最新版本1.2.27，各种插件也安装是最新版本，但是在设备管理中，邮件通知全局列表，没有找到该列表在哪里可以创建，如下：
![image](https://github.com/user-attachments/assets/e5314834-ba5a-44f7-8649-1f05357198b5)
![image](https://github.com/user-attachments/assets/3d7c7327-bda0-4102-93ed-e7b4c1c64da1)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifier: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheWitness** [comment]
Console > Configuration > Settings > Alerting/Thold

![image](https://github.com/user-attachments/assets/a8f33a60-79fc-4dc6-b2a8-ec566558354c)
