### ISSUE TITLE
repeatarray not functioning 

### ISSUE THREAD

**Issue by dsclassen** [Cacti/plugin_thold#72]
I have several thresholds for datasources with a 300 sec step. I set the repeat notification to 1 hour or 2 hour and instead of the text value being inserted into the table in the thold tab I see the numeric value.

i.e. instead of "Every Hour" or "Every 2 Hours" I'm seeing 12 or 24.

I inspected includes/arrays.php andI see the proepr values there, but his file doesn't appear to be getting parsed as the thold page loads.

**Comment by cigamit** [comment]
I'll likely be looking at this over the weekend.

**Comment by cigamit** [comment]
Can you confirm this is still a problem.  I'm spending some time on thold, and want to get the issue level reduced.  Also, provide a screen shot.

**Comment by cigamit** [comment]
Seems to me that this was fixed already.  Is this the case?

**Comment by cigamit** [comment]
No feedback.
