### ISSUE TITLE
Thold don't apply to graph with several DS (in separate RRD)

### ISSUE THREAD

**Issue by qw3r1984** [Cacti/plugin_thold#74]
I have an issue with applying thold on graph with 2 different DS in separate RRD.

In creation wizard you can select required graph and data source:
![thold creation wizard](https://cloud.githubusercontent.com/assets/27761137/25168433/f9009660-24fc-11e7-888a-bc50a231d630.png)

But after creation in Data source description you see the other data source, not those was selected during creation:
![thold created](https://cloud.githubusercontent.com/assets/27761137/25168442/fecc7a96-24fc-11e7-94b8-9f8990abcd1c.png)

And therefore it don't return required value (Last:0 on screenshot)
![thold values](https://cloud.githubusercontent.com/assets/27761137/25168892/9008c964-24fe-11e7-9e8d-152a39504d52.png)
Though lower on the screenshot there is a string: `Data Source Item [mem_used] - Current value: [131072]` - actually it's total mem value.

I've discovered, that it take first DS described in graph template.
When you put required DS on the first place in grap template - thold works correctly.
Also when you create thold on graph with several DS from single RRD - thold works correctly.

Found this issue on Cacti 1.1.2 + plugin_thold 1.0.2.

Cacti 0.8.8b + plugin_thold 0.5 works fine in the same situation.

**Comment by cigamit** [comment]
I'll likely be looking at this over the weekend.

**Comment by JorisFRST** [comment]
Confirming the sme issue on cacti 1.1.7 with the latest thold from Github. (Latest commit 257d1e8 7 days ago)

**Comment by JorisFRST** [comment]
Still not working with latest commit (20/9/17) and cacti 1.1.24

**Comment by cigamit** [comment]
Sorry all, but busy on other projects at the moment.

**Comment by JorisFRST** [comment]
Hi,
did you already find some time to work on this issue ?

Thanks.

**Comment by JorisFRST** [comment]
Just updating that issue is still present in version 1.1.36

**Comment by chrispin2** [comment]
Any update on this? Am using 1.1.36.

**Comment by chrispin2** [comment]
Hi timeline to fix this issue?

**Comment by netniV** [comment]
So, the steps to reproduce this are to create a multiple source graph, then select the second or third or nth item and it would still try and use the first one?

**Comment by chrispin2** [comment]
Hi @netniV ,

Yes, 

Steps to reproduce, create a multiple source graph, then select the second datasource to create a threshold. It will use the first datasource for the referencing

**Comment by netniV** [comment]
I believe that this has been resolved recently.  Until 1.2.2 is release though, you won't be able to use the development version of thold unless your running the dev version of the core.
