### ISSUE TITLE
Allow and correctly handle unit suffix in the context of values

### ISSUE THREAD

**Issue by click0** [Cacti/plugin_thold#79]
Allow and correctly handle unit prefix in the context of values.
For example, unit prefixes - k (kilo), M (mega), G (giga), T (tera).

![capture_05062017_193254](https://cloud.githubusercontent.com/assets/396824/25774165/1d4c0ca4-3293-11e7-832f-355eb65ea6ac.jpg)

And after clicking the Save button, I get:

Validation error for variable thold_warning_hi, with value of "65M". See backtrace below for more details.
(/plugins/thold/thold.php: 64 save_thold)(/plugins/thold/thold_functions.php: 2980 get_filter_request_var)(/lib/html_utility.php: 423 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

**Comment by TheWitness** [comment]
Just looking at this.  It's interesting for sure.

**Comment by TheWitness** [comment]
This issue is addressed now and will be included in Thold 2.0.
