### ISSUE TITLE
plugin_monitor

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#8]
Running latest dev commits for Cacti and all of your plugins (syslog, thold, monitor).

Since I also have plugin monitor loaded, I now have this issue when trying to load any page on thold:

From apache2/error.log

[Thu Jun 30 16:55:35.216064 2016] [:error] [pid 15825] [client 192.168.11.140:50203] PHP Fatal error:  Cannot redeclare get_timeinstate() (previously declared in /var/www/html/cacti/plugins/thold/thold_graph.php:682) in /var/www/html/cacti/lib/functions.php on line 3916, referer: http://192.168.11.15/cacti/plugins/monitor/monitor.php

**Comment by cigamit** [comment]
Fixed in https://github.com/Cacti/plugin_thold/issues/8

**Comment by cigamit** [comment]
Make that: https://github.com/Cacti/plugin_thold/commit/8f3ded9b99459c3f42cab48efbbae89bcb964e98

**Comment by smiles1969** [comment]
Thanks..

Fixed the issue with thold, but now having same issue with reports after pulling the new cacti commit:

[Thu Jun 30 19:04:58.650930 2016] [:error] [pid 11400] [client 192.168.11.140:52096] PHP Fatal error:  Cannot redeclare duplicate_reports() (previously declared in /var/www/html/cacti/lib/reports.php:29) in /var/www/html/cacti/lib/reports.php on line 29, referer: http://192.168.11.15/cacti/index.php

**Comment by cigamit** [comment]
pull latest reports_user.php and reports_admin.php and try again.  if it contiues, please try to trace.

**Comment by smiles1969** [comment]
Good to go, thanks ☺
