### ISSUE TITLE
In the settings of a specific Threshold add the ability to change the time presets.

### ISSUE THREAD

**Issue by click0** [Cacti/plugin_thold#80]
In the settings of a specific Threshold add the ability to change the time presets.
By default, 8 hours is a very excessive value.

**Comment by TheWitness** [comment]
Can you please show a screen shot of the default?  Can you also please let me know your poller and cron intervals?

**Comment by netniV** [comment]
@click0 Do you mean when the graph is displayed at the top?

**Comment by click0** [comment]
@TheWitness 
`*/5     *       *       *       *       cacti   /usr/local/bin/php /www/cacti/data/www/cacti.XXXXX.net/poller.php > /dev/null 2>&1
`

**Comment by click0** [comment]
@TheWitness Sorry, I can not find a place where the minimum value was 8 hours :(

**Comment by netniV** [comment]
@click0 that is the core cacti polling call.  Does that have anything to do with this particular issue?

**Comment by netniV** [comment]
So can you explain what you need from this issue or can it be closed?

**Comment by click0** [comment]
Yes, after two years of inattention to her, the problem is not relevant.
