### ISSUE TITLE
is not possible to change the High and Low Threshold in "Alert - High / Low Settings"

### ISSUE THREAD

**Issue by click0** [Cacti/plugin_thold#81]
If the High and Low Threshold values are empty in the "Warning - High / Low Settings", it is not possible to change the High and Low Threshold in "Alert - High / Low Settings".
An error pops up:
![capture_05062017_195722](https://cloud.githubusercontent.com/assets/396824/25774574/cea0b868-329a-11e7-8275-bba23b0dbb6e.jpg)

**Comment by cigamit** [comment]
Oh, that seems like a minor design flaw.  Thanks for catching this.

**Comment by cigamit** [comment]
Resolved.  Thanks.
