### ISSUE TITLE
Thold plugin execute a script each time device state changes?

### ISSUE THREAD

**Issue by navennn** [Cacti/plugin_thold#82]
Hi, 
Up until today I've been using a modified thold that allowed me to use gammu to send SMS notifications. Unfortunately the plugin does not work anymore (see https://github.com/vovan888/cacti-plugin-thold) .

Do you think you can implement a feature to run a script each time a device state is changed? 
Like, device is down -> run /device_down.sh, device is up /device_up.sh.
I tried adapting the script to the new version but it's changed too much, I don't have enough knowledge to do it.
It would make the plugin/cacti much more flexible.

**Comment by cigamit** [comment]
That would be strait forward.  Would you like to volunteer your plugin to the community?

**Comment by navennn** [comment]
Well I don't have it, I've been using the old one https://github.com/vovan888/cacti-plugin-thold

**Comment by TheWitness** [comment]
This is resolved in the development branch now.  Note, Cacti 1.2 will be required to update.

**Comment by navennn** [comment]
@TheWitness Can you also please make script execution possible for up/down hosts, not only for thresholds?

**Comment by cigamit** [comment]
Looks like he missed this part.

**Comment by navennn** [comment]
@cigamit , @TheWitness 
Hi, I think this topic was lost. 
"Can you also please make script execution possible for up/down hosts, not only for thresholds?"
