### ISSUE TITLE
Cant Add Treshold Because Limited Device

### ISSUE THREAD

**Issue by InvokerFury** [Cacti/plugin_thold#83]
Good Morning Sir,

have a nice day, could u help me please, why thold plugin cant list all my device, when i try to add treshold device list didn't show all from my device..
cacti only show a few device.. i need to see all my device to create treshold. thx a lot sir.

![cactithold](https://cloud.githubusercontent.com/assets/24584431/25834518/acf59490-34a2-11e7-8b34-98514999b18c.png)

**Comment by cigamit** [comment]
You must start typing into the dropdown to see all the devices.  It's an auto-complete form that only shows the top 20 matching items.
