### ISSUE TITLE
Link Generation Conflict with Nectar/Reports

### ISSUE THREAD

**Issue by SilverSquirrl** [Cacti/plugin_thold#84]
Nectar/Reports and Thold both have email functions that allow you to click on the graph in the email and it will link back to the site.  The 2 systems gather the url differently and it makes it so that for one to work, it breaks the other.  Since Nectar/Reports has been rolled into official, I'm submitting the issue under the Thold Plugin.

Nectar/Reports url handling:

> 	if ($report['graph_linked'] == 'on' ) {
> 		$out = "<a href='" . htmlspecialchars(read_config_option('base_url') . $config['url_path'] . 'graph.php?action=view&local_graph_id='.$item['local_graph_id']."&rra_id=0") . "'>" . $out . '</a>';
> 	}
> 

Thold url handling:

> $httpurl               = read_config_option('base_url');
> $url = $httpurl . '/graph.php?local_graph_id=' . $thold_data['local_graph_id'] . '&rra_id=all';

The difference is that Nectar/Reports pulls both the base_url + url_path while thold only pulls base_url. 
Base_url setting is set in cacti console -> settings -> dns -> url linking
url_path is set in the /cacti/include/config.php file

If base_url = http://www.myserver.test/cacti
Reports generates:  http://www.myserver.test/cacti/cacti/graph.php
Thold generates: http://www.myserver.test/cacti/graph.php

If base_url = http://www.myserver.test/
Reports generates:  http://www.myserver.test/cacti/graph.php
Thold generates: http://www.myserver.test/graph.php

I experimented with removing /cacti/ from the config.php file, and that just totally broke cacti in general, so that is not a viable fix.

I see 7 hits on httpurl in the thold_functions.php
3 separate functions defining it,  First function has 2 references to generate a link, the other 2 functions only has 1 each.

It appears to me that the fix would be to add the url_path to thold_functions.php to match the standard set by Nectar/Reports.
Unfortunately,  this "fix" may break people's current setups.  If they have base_url set to http://www.myserver.test/cacti and you add in url_path like what reports does, then people will have to change their base_url to http://www.myserver.test/ in the settings.   
Alternatively, If the fix is to adjust Nectar/Reports, then anyone having their base_url set to http://www.myserver.test/ will have to change it to http://www.myserver.test/cacti.

I have been using thold for a long time and didn't start using nectar/reports until it was integrated into main.  So I had mine setup as http://www.myserver.test/cacti which allowed thold to work, but then I realized Reports wasn't.

I hope this is enough information and I'm not missing anything.
Thank you

**Comment by cigamit** [comment]
This was a reports issue and has been resolved.  Thanks for pointing this out.
