### ISSUE TITLE
Undefined variable: snmp_event_description---[Thold-1.0.3][Cacti-1.1.7]

### ISSUE THREAD

**Issue by kaf3773** [Cacti/plugin_thold#86]
I get the below errors while testing thold-1.0.3 snmptraps out of Cacti-1.1.7

`PHP Notice: Undefined variable: snmp_event_description in /var/www/html/new_cacti/plugins/thold/thold_functions.php on line 3849`
`PHP Notice: Undefined variable: thold_snmp_data in /var/www/html/new_cacti/plugins/thold/thold_functions.php on line 3849`

`2017-05-19 17:25:04 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 716 api_plugin_hook)(/lib/plugins.php: 68 api_plugin_run_plugin_hook)(/lib/plugins.php: 161 thold_poller_bottom)(/plugins/thold/includes/polling.php: 35 thold_check_all_thresholds)(/plugins/thold/includes/polling.php: 251 thold_check_threshold)(/plugins/thold/thold_functions.php: 1689 thold_snmptrap)(/plugins/thold/thold_functions.php: 3849 CactiErrorHandler)(/lib/functions.php: 4339 cacti_debug_backtrace)`
`2017-05-19 17:25:04 - ERROR PHP NOTICE in Plugin 'thold': Undefined variable: snmp_event_description in file: /var/www/html/new_cacti/plugins/thold/thold_functions.php on line: 3849`
`2017-05-19 17:25:04 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 716 api_plugin_hook)(/lib/plugins.php: 68 api_plugin_run_plugin_hook)(/lib/plugins.php: 161 thold_poller_bottom)(/plugins/thold/includes/polling.php: 35 thold_check_all_thresholds)(/plugins/thold/includes/polling.php: 251 thold_check_threshold)(/plugins/thold/thold_functions.php: 1689 thold_snmptrap)(/plugins/thold/thold_functions.php: 3849 CactiErrorHandler)(/lib/functions.php: 4339 cacti_debug_backtrace)`
`2017-05-19 17:25:04 - ERROR PHP NOTICE in Plugin 'thold': Undefined variable: thold_snmp_data in file: /var/www/html/new_cacti/plugins/thold/thold_functions.php on line: 3849`

i think as a result of this thold is unable to send  snmp trap although it is triggered. because i do not see any snmptrap logs.

**Comment by cigamit** [comment]
Resolved.  Though that should have not blocked the trap.
