### ISSUE TITLE
Thold plugin not Enabling on CACTI 1.1.2

### ISSUE THREAD

**Issue by slimeminem13** [Cacti/plugin_thold#87]
i have installed thold plugin (clone method from github) 
1) first it was showing that plugin is incompatible, resolved by editing INFO file 
2) plugin got installed
3) plugin not getting enabled , even after clicking enable button hundred times :/

and i cant find any solution on forum or internet
please help asap!

**Comment by cigamit** [comment]
Upgrade Cacti.  Thold GitHub currently requires 1.1.4+
