### ISSUE TITLE
Cisco DOM SNMP script

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#9]
Using SNMP script to poll optical transceiver levels, the values returned are sometimes negative, which fails thold validation code in thold_functions.php when setting appropriate warn and alarm levels.  There have been patches created for older versions of the thold plugin, but it seems your latest code has been through major changes. 

http://forums.cacti.net/viewtopic.php?f=19&t=23089

Any possibility you could review this thread and take this into consideration?

Thanks.

**Comment by cigamit** [comment]
Resolved here. https://github.com/Cacti/plugin_thold/commit/67fc0ef3fc81411aa26ef3127858370312ef2be7

**Comment by cigamit** [comment]
Please post update on forums.
