### ISSUE TITLE
Thold doesn't in cacti.log account for devices polled by remote poller

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#90]
My Test setup: 
Main poller 306 devices:
Test Poller 3 devices:
![setup](https://user-images.githubusercontent.com/11211789/26948069-1054caec-4c63-11e7-9cc7-9285ac37727e.jpg)
All aspects of device up/down, thold alarms functions properly.
What I noticed is on the main poller log, device count is incorrect:
![count](https://user-images.githubusercontent.com/11211789/26948141-4addbbc4-4c63-11e7-8181-d57b30629bdc.jpg)
Thold doesn't account for 3 devices that being polled by remote poller, additionally it doesn't account in the log only for any THOLDs configured on devices polled by remote poller.

**Comment by cigamit** [comment]
This will have to wait for 1.2 we have mail queuing to do since we can not expect the remote data collectors to have sendmail facilities since in some cases they will be behind firewalls.  We are working on this.  We had to 1.1.x stable enough to move to 1.2.

**Comment by cigamit** [comment]
Please test the 1.0.4 version of thold and see if this is working to your expectation.  Please note that notifications (emails) will be sent or attempted to be sent by the remote data collector.  If this will not work, you need to let us know.  It'll be a core cacti change at that point if only the main data collector can notify.

**Comment by ikorzha** [comment]
This was fixed in 1.0.4
