### ISSUE TITLE
Thold search doesnt work under Console->Thresholds->Threshold Management

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#91]
Thold search doesnt work under Console->Thresholds->Threshold Management.
String can't be filtered. Go button returns all results.

![tholds-filter-problem](https://user-images.githubusercontent.com/11211789/27285255-1830fd84-54ca-11e7-81a0-25cde55f5a06.jpeg)

**Comment by cigamit** [comment]
Resolved, thanks!
