### ISSUE TITLE
Thold doesn't automatically create thresholds with several DS in same RRD present

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#92]
Thold doesn't automatically create thresholds with several DS in same RRD present.
I have defined 6 thold templates for "Interface Traffic" see below image:

![tholds-templates](https://user-images.githubusercontent.com/11211789/27285726-a07ef078-54cb-11e7-85f8-aec3e6357a2f.jpeg)

P.S Please also notice in graph above a visual defect search introduced, it should say 1 to 6 not 1 to 30 of 38  (minor issue, outside of the scope of this problem).

These are same data sources in sample RRD:
DEF:a='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'traffic_in':AVERAGE \
DEF:b='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'traffic_out':AVERAGE \
DEF:c='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'traffic_in':MAX \
DEF:d='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'traffic_out':MAX \
DEF:e='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'errors_in':AVERAGE \
DEF:f='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'discards_in':AVERAGE \
DEF:g='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'errors_out':AVERAGE \
DEF:h='/var/www/html/rra/jc_14_north_4506e_discards_in_578.rrd':'discards_out':AVERAGE \

When I go under Console ->Devices-> Select a Device with checkmark->From pull down menu select -> Apply Thresholds:

I do get thresholds created for graphs that are present but only for "traffic_out", I do not get tholds created automatically for same charts with traffic_in, errors_in, errors_out, discards_in, discards_out.

I do however can go and manually create these thresholds by going to: Console ->Device-> Select a device-> Graph List -> Checkmark required graphs -> and from pull down menu select ->Apply Threshold from Template. (I would have to repeat last procedure 5 time to get all of the tholds created.)

Please address this issue it is a major deficiency.

**Comment by JorisFRST** [comment]
Hi,
is this the same issue or related to issue 74 ?
https://github.com/Cacti/plugin_thold/issues/74

**Comment by ikorzha** [comment]
Based on your description in#74 i believe the issue i reported to be different.

**Comment by cigamit** [comment]
I'm back onto plugins.  Hopefully will have this resolved this week along with Issue #74.

**Comment by ikorzha** [comment]
Cigamit, this a critical issue in my install, I will be looking forward to test a fix as soon as you apply it.

**Comment by ikorzha** [comment]
Please apply changes from attached thold_functions.php file, it resolves issues #92 and 93. I have personally tested the patch and certify that issue reported in 92 and 93 are resolved.

Patch applicable to current revision 272
[thold_functions.txt](https://github.com/Cacti/plugin_thold/files/1134220/thold_functions.txt)
![revision](https://user-images.githubusercontent.com/11211789/27999440-1fcca77e-64eb-11e7-9169-703cbae12623.gif)

**Comment by cigamit** [comment]
ikorzha,  please re-patch based upon todays thold_functions.php, or provide a pull request.

**Comment by ikorzha** [comment]
Problem has been fixed by patch applied earlier. Thank you
