### ISSUE TITLE
Thold IDs when auto created are NOT in sequential order.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#93]
When testing new THOLD from github I have discovered If I auto create tholds for a device, there large gaps in sequence numbers assigned to Tholds.
Please see attached image. All thold were created at once for this device and demonstrate a large gap in sequence numbering.. I suspect that when there are multiple thold templates associated with a single  RRD file, it fails to create thold for all but 1 ds that appears in rrd file.   This issue has strong correlation to issue #92 
When tholds are created manually there are no gaps in sequences.

![thold-sequance-numbers](https://user-images.githubusercontent.com/11211789/27302010-460a3a3e-5503-11e7-8c68-ee9b7fca1036.jpeg)

I have a small test Cacti 1.1.10 install with Thold and with 320 actual Tholds configured, by sequance number are up to 15755, this is very abnormal by the time I roll this into prod environment, the sequencing will be in 10s of millions, please address this inconsistency.

![thold-sequance](https://user-images.githubusercontent.com/11211789/27302119-b63354ee-5503-11e7-88f4-e3d82da5b8db.jpeg)

**Comment by ikorzha** [comment]
Please apply changes from attached thold_functions.php file, it resolves issues #92 and 93 
Patch applicable to current revision 272
[thold_functions.txt](https://github.com/Cacti/plugin_thold/files/1134220/thold_functions.txt)
![revision](https://user-images.githubusercontent.com/11211789/27999440-1fcca77e-64eb-11e7-9169-703cbae12623.gif)

**Comment by cigamit** [comment]
Please create a pull request.

**Comment by ikorzha** [comment]
Cigamit, this is the point where I have to acknowledge my limitations as non developer.

[a.patch.txt](https://github.com/Cacti/plugin_thold/files/1271877/a.patch.txt)

Attach is the diff patch I have come up with, if you can help to re-consile with current thold branch, I would be very appreciative.

**Comment by cigamit** [comment]
Resolved.
