### ISSUE TITLE
Thold Alert Message 

### ISSUE THREAD

**Issue by jagmeetbhinder** [Cacti/plugin_thold#94]
Thold alert email is contain lot of '=' signs. Additionally, device previously UP is reported wrong in the email body. It is correct in GUI though under devices. 

 System Error : XXXX is DOWN
Reason: Device did no= t respond to SNMP

Average system response: 20.71 ms
System availa= bility: 99.99 %
Total Checks Since Clear: 125974
Total Failed Checks:= 13
Last Date Checked DOWN : 2017-06-19 15:24:00
Device Previously UP= for: 736896d 14h 26m 9s

**Comment by cigamit** [comment]
This would appear to be some possibly some encoding problem or an issue in your settings table.  There would appear to be an issue with the Device Previously UP as that simply means it was set to 0.  I suggest you goto the settings page under thold and verify the values you have stored there.  I'll be fixing the other issue with 'Device Previously UP for' issue shortly.

**Comment by cigamit** [comment]
Closing the issue.

**Comment by jagmeetbhinder** [comment]
I don't see problem in formatting, below is the text under setting thold, I will dig more into this 

System Error : <DESCRIPTION> (<HOSTNAME>) is <DOWN/UP><br>Reason: <MESSAGE><br><br>Average system response: <AVG_TIME> ms<br>System availability: <AVAILABILITY><br>Total Checks Since Clear: <TOT_POLL><br>Total Failed Checks: <FAIL_POLL><br>Last Date Checked DOWN : <LAST_FAIL><br>Device Previously UP for: <DOWNTIME><br>NOTE: <NOTES>


<br>System <DESCRIPTION> (<HOSTNAME>) status: <DOWN/UP><br><br>Current ping response: <CUR_TIME> ms<br>Average system response: <AVG_TIME> ms<br>System availability: <AVAILABILITY><br>Total Checks Since Clear: <TOT_POLL><br>Total Failed Checks: <FAIL_POLL><br>Last Date Checked UP: <LAST_FAIL><br>Device Previously DOWN for: <DOWNTIME><br><br>Snmp Info:<br>Name - <SNMP_HOSTNAME><br>Location - <SNMP_LOCATION><br>Uptime - <UPTIMETEXT> (<UPTIME> ms)<br>System - <SNMP_SYSTEM><br><br>NOTE: <NOTES>
