### ISSUE TITLE
Enhancement:  Display duration count in days:hr:min:sec for triggered thold alarms and warnings

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#95]
I would like to propose a minor enhancement in Thold alarms/warnings/ views that bring huge value in NOC setup.
You guys already collecting necessary data in table row: "thold_fail_count" and "thold_warning_fail_count"
All I'm asking is to display the data under "Duration" where currently has N/A which brings 0 value in this case.

I had some minor work done on a side in Thold 5.x to introduce this feature in NOC view. Please see sample below:  look under column "duration" for enhancement:

![noc](https://user-images.githubusercontent.com/11211789/27593082-401435ea-5b24-11e7-854f-b47b0d6649b6.jpeg)

**Comment by cigamit** [comment]
Duration is specifically used for for BaseLine Deviations.  Its only N/A because you are not using Base Lines.  If this was to be added, it would be a completely new column.

**Comment by ikorzha** [comment]
Cigamit, I do understand your point, and I am aware that it is used in baseline.. Amount of fields displayed per alarm is large as is.  I was only hoping to reuse "duration" field in non baseline alarm type. 
From NOC and end user stand point it is irrelevant whether it is a separate column or same column. If it is in a same column it would provide consistency for end user, and reduce clogging of the thold interface.

Please consider such points from end user/administrator.

**Comment by cigamit** [comment]
I am an end user / administrator too, so I always consider that case.  We can't just reuse columns though, you have consider the use case of others who do use Base Lines.  We just need to add a new column for the field you would like, and then modify the entire table to allow us to select which columns to display.

**Comment by ikorzha** [comment]
I'm sorry for my original ignorance, I do acknowledge my short comings in this matter. I do love your approach you outlined below:  

### "We just need to add a new column for the field you would like, and then modify the entire table to allow us to select which columns to display."

I hope you would have a chance to implement it as an enhancement.

**Comment by cigamit** [comment]
I think it's better to add a column for the trigger date.  Otherwise, calculating this will be complicated at best.  Adding a column will make things much easier.

**Comment by netniV** [comment]
I would agree with that.  It should be next to the Triggered column to.

**Comment by TheWitness** [comment]
This issue is resolved now.

**Comment by TheWitness** [comment]
Closing.
