### ISSUE TITLE
Undefined variable: item_rows in file: /var/www/html/plugins/thold/thold.php on line: 508 

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#96]
Latest GitHub  Thold, error in Cacti log below: 

2017/06/27 10:41:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 126 list_tholds)(/plugins/thold/thold.php: 508 CactiErrorHandler)(/lib/functions.php: 4368 cacti_debug_backtrace)
2017/06/27 10:41:54 - ERROR PHP NOTICE in Plugin 'thold': Undefined variable: item_rows in file: /var/www/html/plugins/thold/thold.php on line: 508

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting!
